package uk.gov.hmcts.reform.iacaseapi.domain.entities.ccd;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.Arrays;
import java.util.List;
import java.util.stream.Stream;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

class EventTest {

    @ParameterizedTest
    @MethodSource("eventMapping")
    void has_correct_values(String expected, String actual) {
        assertEquals(expected, actual);
    }

    @Test
    void if_this_test_fails_it_is_because_eventMapping_needs_updating_with_your_changes() {
        List<String> eventMappingStrings = eventMapping().map(arg -> arg.get()[1])
            .map(String.class::cast)
            .toList();
        List<Event> missingEvents = Arrays.stream(Event.values())
            .filter(event -> !eventMappingStrings.contains(event.toString())).toList();
        assertTrue(missingEvents.isEmpty(), "The following events are missing from the eventMapping method: " + missingEvents);
    }

    static Stream<Arguments> eventMapping() {
        return Stream.of(
            Arguments.of("startAppeal", Event.START_APPEAL.toString()),
            Arguments.of("editAppeal", Event.EDIT_APPEAL.toString()),
            Arguments.of("submitAppeal", Event.SUBMIT_APPEAL.toString()),
            Arguments.of("sendDirection", Event.SEND_DIRECTION.toString()),
            Arguments.of("requestRespondentEvidence", Event.REQUEST_RESPONDENT_EVIDENCE.toString()),
            Arguments.of("uploadRespondentEvidence", Event.UPLOAD_RESPONDENT_EVIDENCE.toString()),
            Arguments.of("uploadHomeOfficeBundle", Event.UPLOAD_HOME_OFFICE_BUNDLE.toString()),
            Arguments.of("buildCase", Event.BUILD_CASE.toString()),
            Arguments.of("submitCase", Event.SUBMIT_CASE.toString()),
            Arguments.of("requestCaseEdit", Event.REQUEST_CASE_EDIT.toString()),
            Arguments.of("requestRespondentReview", Event.REQUEST_RESPONDENT_REVIEW.toString()),
            Arguments.of("addAppealResponse", Event.ADD_APPEAL_RESPONSE.toString()),
            Arguments.of("uploadHomeOfficeAppealResponse", Event.UPLOAD_HOME_OFFICE_APPEAL_RESPONSE.toString()),
            Arguments.of("requestHearingRequirements", Event.REQUEST_HEARING_REQUIREMENTS.toString()),
            Arguments.of("requestHearingRequirementsFeature", Event.REQUEST_HEARING_REQUIREMENTS_FEATURE.toString()),
            Arguments.of("reviewHearingRequirements", Event.REVIEW_HEARING_REQUIREMENTS.toString()),
            Arguments.of("draftHearingRequirements", Event.DRAFT_HEARING_REQUIREMENTS.toString()),
            Arguments.of("updateHearingRequirements", Event.UPDATE_HEARING_REQUIREMENTS.toString()),
            Arguments.of("updateHearingAdjustments", Event.UPDATE_HEARING_ADJUSTMENTS.toString()),
            Arguments.of("changeDirectionDueDate", Event.CHANGE_DIRECTION_DUE_DATE.toString()),
            Arguments.of("uploadAdditionalEvidence", Event.UPLOAD_ADDITIONAL_EVIDENCE.toString()),
            Arguments.of("uploadAddendumEvidence", Event.UPLOAD_ADDENDUM_EVIDENCE.toString()),
            Arguments.of("listCase", Event.LIST_CASE.toString()),
            Arguments.of("listCaseWithoutHearingRequirements", Event.LIST_CASE_WITHOUT_HEARING_REQUIREMENTS.toString()),
            Arguments.of("createCaseSummary", Event.CREATE_CASE_SUMMARY.toString()),
            Arguments.of("revertStateToAwaitingRespondentEvidence", Event.REVERT_STATE_TO_AWAITING_RESPONDENT_EVIDENCE.toString()),
            Arguments.of("generateHearingBundle", Event.GENERATE_HEARING_BUNDLE.toString()),
            Arguments.of("customiseHearingBundle", Event.CUSTOMISE_HEARING_BUNDLE.toString()),
            Arguments.of("generateUpdatedHearingBundle", Event.GENERATE_UPDATED_HEARING_BUNDLE.toString()),
            Arguments.of("asyncStitchingComplete", Event.ASYNC_STITCHING_COMPLETE.toString()),
            Arguments.of("decisionAndReasonsStarted", Event.DECISION_AND_REASONS_STARTED.toString()),
            Arguments.of("generateDecisionAndReasons", Event.GENERATE_DECISION_AND_REASONS.toString()),
            Arguments.of("sendDecisionAndReasons", Event.SEND_DECISION_AND_REASONS.toString()),
            Arguments.of("addCaseNote", Event.ADD_CASE_NOTE.toString()),
            Arguments.of("addStatutoryTimeframe24Weeks", Event.ADD_STATUTORY_TIMEFRAME_24_WEEKS.toString()),
            Arguments.of("removeStatutoryTimeframe24Weeks", Event.REMOVE_STATUTORY_TIMEFRAME_24_WEEKS.toString()),
            Arguments.of("editCaseListing", Event.EDIT_CASE_LISTING.toString()),
            Arguments.of("recordApplication", Event.RECORD_APPLICATION.toString()),
            Arguments.of("recordAttendeesAndDuration", Event.RECORD_ATTENDEES_AND_DURATION.toString()),
            Arguments.of("uploadHearingRecording", Event.UPLOAD_HEARING_RECORDING.toString()),
            Arguments.of("endAppeal", Event.END_APPEAL.toString()),
            Arguments.of("requestCaseBuilding", Event.REQUEST_CASE_BUILDING.toString()),
            Arguments.of("forceRequestCaseBuilding", Event.FORCE_REQUEST_CASE_BUILDING.toString()),
            Arguments.of("uploadAdditionalEvidenceHomeOffice", Event.UPLOAD_ADDITIONAL_EVIDENCE_HOME_OFFICE.toString()),
            Arguments.of("requestResponseReview", Event.REQUEST_RESPONSE_REVIEW.toString()),
            Arguments.of("requestResponseAmend", Event.REQUEST_RESPONSE_AMEND.toString()),
            Arguments.of("uploadAddendumEvidenceLegalRep", Event.UPLOAD_ADDENDUM_EVIDENCE_LEGAL_REP.toString()),
            Arguments.of("uploadAddendumEvidenceHomeOffice", Event.UPLOAD_ADDENDUM_EVIDENCE_HOME_OFFICE.toString()),
            Arguments.of("uploadAddendumEvidenceAdminOfficer", Event.UPLOAD_ADDENDUM_EVIDENCE_ADMIN_OFFICER.toString()),
            Arguments.of("submitHearingRequirements", Event.SUBMIT_HEARING_REQUIREMENTS.toString()),
            Arguments.of("removeAppealFromOnline", Event.REMOVE_APPEAL_FROM_ONLINE.toString()),
            Arguments.of("shareACase", Event.SHARE_A_CASE.toString()),
            Arguments.of("requestReasonsForAppeal", Event.REQUEST_REASONS_FOR_APPEAL.toString()),
            Arguments.of("editReasonsForAppeal", Event.EDIT_REASONS_FOR_APPEAL.toString()),
            Arguments.of("submitReasonsForAppeal", Event.SUBMIT_REASONS_FOR_APPEAL.toString()),
            Arguments.of("requestClarifyingAnswers", Event.REQUEST_CLARIFYING_ANSWERS.toString()),
            Arguments.of("submitClarifyingQuestionAnswers", Event.SUBMIT_CLARIFYING_QUESTION_ANSWERS.toString()),
            Arguments.of("completeClarifyQuestions", Event.COMPLETE_CLARIFY_QUESTIONS.toString()),
            Arguments.of("editDocuments", Event.EDIT_DOCUMENTS.toString()),
            Arguments.of("sendToPreHearing", Event.SEND_TO_PREHEARING.toString()),
            Arguments.of("changeHearingCentre", Event.CHANGE_HEARING_CENTRE.toString()),
            Arguments.of("applyForFTPAAppellant", Event.APPLY_FOR_FTPA_APPELLANT.toString()),
            Arguments.of("applyForFTPARespondent", Event.APPLY_FOR_FTPA_RESPONDENT.toString()),
            Arguments.of("leadershipJudgeFtpaDecision", Event.LEADERSHIP_JUDGE_FTPA_DECISION.toString()),
            Arguments.of("residentJudgeFtpaDecision", Event.RESIDENT_JUDGE_FTPA_DECISION.toString()),
            Arguments.of("decideFtpaApplication", Event.DECIDE_FTPA_APPLICATION.toString()),
            Arguments.of("recordAllocatedJudge", Event.RECORD_ALLOCATED_JUDGE.toString()),
            Arguments.of("editTimeExtension", Event.EDIT_TIME_EXTENSION.toString()),
            Arguments.of("submitTimeExtension", Event.SUBMIT_TIME_EXTENSION.toString()),
            Arguments.of("reviewTimeExtension", Event.REVIEW_TIME_EXTENSION.toString()),
            Arguments.of("sendDirectionWithQuestions", Event.SEND_DIRECTION_WITH_QUESTIONS.toString()),
            Arguments.of("flagCase", Event.FLAG_CASE.toString()),
            Arguments.of("createFlag", Event.CREATE_FLAG.toString()),
            Arguments.of("removeFlag", Event.REMOVE_FLAG.toString()),
            Arguments.of("requestCmaRequirements", Event.REQUEST_CMA_REQUIREMENTS.toString()),
            Arguments.of("editCmaRequirements", Event.EDIT_CMA_REQUIREMENTS.toString()),
            Arguments.of("submitCmaRequirements", Event.SUBMIT_CMA_REQUIREMENTS.toString()),
            Arguments.of("reviewCmaRequirements", Event.REVIEW_CMA_REQUIREMENTS.toString()),
            Arguments.of("forceCaseToCaseUnderReview", Event.FORCE_CASE_TO_CASE_UNDER_REVIEW.toString()),
            Arguments.of("forceCaseToPrepareForHearing", Event.FORCE_CASE_TO_PREPARE_FOR_HEARING.toString()),
            Arguments.of("updateDetailsAfterCma", Event.UPDATE_DETAILS_AFTER_CMA.toString()),
            Arguments.of("forceCaseToSubmitHearingRequirements", Event.FORCE_CASE_TO_SUBMIT_HEARING_REQUIREMENTS.toString()),
            Arguments.of("updateLegalRepDetails", Event.UPDATE_LEGAL_REPRESENTATIVES_DETAILS.toString()),
            Arguments.of("adjournHearingWithoutDate", Event.ADJOURN_HEARING_WITHOUT_DATE.toString()),
            Arguments.of("restoreStateFromAdjourn", Event.RESTORE_STATE_FROM_ADJOURN.toString()),
            Arguments.of("decisionWithoutHearing", Event.DECISION_WITHOUT_HEARING.toString()),
            Arguments.of("listCma", Event.LIST_CMA.toString()),
            Arguments.of("editAppealAfterSubmit", Event.EDIT_APPEAL_AFTER_SUBMIT.toString()),
            Arguments.of("linkAppeal", Event.LINK_APPEAL.toString()),
            Arguments.of("unlinkAppeal", Event.UNLINK_APPEAL.toString()),
            Arguments.of("paymentAppeal", Event.PAYMENT_APPEAL.toString()),
            Arguments.of("moveToPaymentPending", Event.MOVE_TO_PAYMENT_PENDING.toString()),
            Arguments.of("rollbackPayment", Event.ROLLBACK_PAYMENT.toString()),
            Arguments.of("rollbackPaymentTimeout", Event.ROLLBACK_PAYMENT_TIMEOUT.toString()),
            Arguments.of("rollbackPaymentTimeoutToPaymentPending", Event.ROLLBACK_PAYMENT_TIMEOUT_TO_PAYMENT_PENDING.toString()),
            Arguments.of("uploadSensitiveDocuments", Event.UPLOAD_SENSITIVE_DOCUMENTS.toString()),
            Arguments.of("markAppealPaid", Event.MARK_APPEAL_PAID.toString()),
            Arguments.of("requestHomeOfficeData", Event.REQUEST_HOME_OFFICE_DATA.toString()),
            Arguments.of("makeAnApplication", Event.MAKE_AN_APPLICATION.toString()),
            Arguments.of("reinstateAppeal", Event.REINSTATE_APPEAL.toString()),
            Arguments.of("decideAnApplication", Event.DECIDE_AN_APPLICATION.toString()),
            Arguments.of("requestNewHearingRequirements", Event.REQUEST_NEW_HEARING_REQUIREMENTS.toString()),
            Arguments.of("allocateTheCase", Event.ALLOCATE_THE_CASE.toString()),
            Arguments.of("recordRemissionDecision", Event.RECORD_REMISSION_DECISION.toString()),
            Arguments.of("manageFeeUpdate", Event.MANAGE_FEE_UPDATE.toString()),
            Arguments.of("nocRequest", Event.NOC_REQUEST.toString()),
            Arguments.of("removeRepresentation", Event.REMOVE_REPRESENTATION.toString()),
            Arguments.of("removeLegalRepresentative", Event.REMOVE_LEGAL_REPRESENTATIVE.toString()),
            Arguments.of("revokeCaseAccess", Event.REVOKE_CASE_ACCESS.toString()),
            Arguments.of("requestFeeRemission", Event.REQUEST_FEE_REMISSION.toString()),
            Arguments.of("recordOutOfTimeDecision", Event.RECORD_OUT_OF_TIME_DECISION.toString()),
            Arguments.of("generateUpperTribunalBundle", Event.GENERATE_UPPER_TRIBUNAL_BUNDLE.toString()),
            Arguments.of("markEvidenceAsReviewed", Event.MARK_EVIDENCE_AS_REVIEWED.toString()),
            Arguments.of("updatePaymentStatus", Event.UPDATE_PAYMENT_STATUS.toString()),
            Arguments.of("reTriggerWaBulkTasks", Event.RE_TRIGGER_WA_BULK_TASKS.toString()),
            Arguments.of("reTriggerWaTasks", Event.RE_TRIGGER_WA_TASKS.toString()),
            Arguments.of("removeCaseManagerBulk", Event.REMOVE_CASE_MANAGER_BULK.toString()),
            Arguments.of("markAddendumEvidenceAsReviewed", Event.MARK_ADDENDUM_EVIDENCE_AS_REVIEWED.toString()),
            Arguments.of("markPaymentRequestSent", Event.MARK_PAYMENT_REQUEST_SENT.toString()),
            Arguments.of("endAppealAutomatically", Event.END_APPEAL_AUTOMATICALLY.toString()),
            Arguments.of("generateServiceRequest", Event.GENERATE_SERVICE_REQUEST.toString()),
            Arguments.of("transferOutOfAda", Event.TRANSFER_OUT_OF_ADA.toString()),
            Arguments.of("markAppealAsAda", Event.MARK_APPEAL_AS_ADA.toString()),
            Arguments.of("createCaseLink", Event.CREATE_CASE_LINK.toString()),
            Arguments.of("maintainCaseLinks", Event.MAINTAIN_CASE_LINKS.toString()),
            Arguments.of("pipActivation", Event.PIP_ACTIVATION.toString()),
            Arguments.of("updateS94bStatus", Event.UPDATE_S94B_STATUS.toString()),
            Arguments.of("adaSuitabilityReview", Event.ADA_SUITABILITY_REVIEW.toString()),
            Arguments.of("removeDetainedStatus", Event.REMOVE_DETAINED_STATUS.toString()),
            Arguments.of("markAppealAsDetained", Event.MARK_APPEAL_AS_DETAINED.toString()),
            Arguments.of("markAsReadyForUtTransfer", Event.MARK_AS_READY_FOR_UT_TRANSFER.toString()),
            Arguments.of("updateDetentionLocation", Event.UPDATE_DETENTION_LOCATION.toString()),
            Arguments.of("applyForCosts", Event.APPLY_FOR_COSTS.toString()),
            Arguments.of("turnOnNotifications", Event.TURN_ON_NOTIFICATIONS.toString()),
            Arguments.of("respondToCosts", Event.RESPOND_TO_COSTS.toString()),
            Arguments.of("addEvidenceForCosts", Event.ADD_EVIDENCE_FOR_COSTS.toString()),
            Arguments.of("decideCostsApplication", Event.DECIDE_COSTS_APPLICATION.toString()),
            Arguments.of("considerMakingCostsOrder", Event.CONSIDER_MAKING_COSTS_ORDER.toString()),
            Arguments.of("updateTribunalDecision", Event.UPDATE_TRIBUNAL_DECISION.toString()),
            Arguments.of("recordRemissionReminder", Event.RECORD_REMISSION_REMINDER.toString()),
            Arguments.of("markAppealAsRemitted", Event.MARK_APPEAL_AS_REMITTED.toString()),
            Arguments.of("sendPaymentReminderNotification", Event.SEND_PAYMENT_REMINDER_NOTIFICATION.toString()),
            Arguments.of("ariaCreateCase", Event.ARIA_CREATE_CASE.toString()),
            Arguments.of("progressMigratedCase", Event.PROGRESS_MIGRATED_CASE.toString()),
            Arguments.of("refundConfirmation", Event.REFUND_CONFIRMATION.toString()),
            Arguments.of("hearingCancelled", Event.HEARING_CANCELLED.toString()),
            Arguments.of("updateInterpreterBookingStatus", Event.UPDATE_INTERPRETER_BOOKING_STATUS.toString()),
            Arguments.of("updateInterpreterDetails", Event.UPDATE_INTERPRETER_DETAILS.toString()),
            Arguments.of("updateHearingRequest", Event.UPDATE_HEARING_REQUEST.toString()),
            Arguments.of("handleHearingException", Event.HANDLE_HEARING_EXCEPTION.toString()),
            Arguments.of("cmrReListing", Event.CMR_RE_LISTING.toString()),
            Arguments.of("recordAdjournmentDetails", Event.RECORD_ADJOURNMENT_DETAILS.toString()),
            Arguments.of("listAssistIntegration", Event.LIST_ASSIST_INTEGRATION.toString()),
            Arguments.of("cmrListing", Event.CMR_LISTING.toString()),
            Arguments.of("decisionWithoutHearingListed", Event.DECISION_WITHOUT_HEARING_LISTED.toString()),
            Arguments.of("saveNotificationsToData", Event.SAVE_NOTIFICATIONS_TO_DATA.toString()),
            Arguments.of("UpdateNextHearingInfo", Event.UPDATE_NEXT_HEARING_INFO.toString()),
            Arguments.of("appellantInPersonManual", Event.APPELLANT_IN_PERSON_MANUAL.toString()),
            Arguments.of("generateListCmrTask", Event.GENERATE_LIST_CMR_TASK.toString()),
            Arguments.of("turnOnNotificationsWATasks", Event.TURN_ON_NOTIFICATIONS_WA_TASKS.toString()),
            Arguments.of("forceDecidedState", Event.FORCE_DECIDED_STATE.toString()),
            Arguments.of("forceFtpaDecidedState", Event.FORCE_FTPA_DECIDED_STATE.toString()),
            Arguments.of("rollbackMigration", Event.ROLLBACK_MIGRATION.toString()),
            Arguments.of("revokeCitizenAccess", Event.REVOKE_CITIZEN_ACCESS.toString()),
            Arguments.of("completeCaseReview", Event.COMPLETE_CASE_REVIEW.toString()),
            Arguments.of("unknown", Event.UNKNOWN.toString())
        );
    }
}
