package uk.gov.hmcts.reform.iacaseapi.domain.entities.ccd;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

class NationalityTest {

    @Test
    void has_correct_values() {
        assertEquals("Afghan", Nationality.AF.toString());
        assertEquals("Albanian", Nationality.AL.toString());
        assertEquals("Algerian", Nationality.DZ.toString());
        assertEquals("American", Nationality.US.toString());
        assertEquals("Andorran", Nationality.AD.toString());
        assertEquals("Angolan", Nationality.AO.toString());
        assertEquals("Anguillan", Nationality.AI.toString());
        assertEquals("Citizen of Antigua and Barbuda", Nationality.AG.toString());
        assertEquals("Argentine", Nationality.AR.toString());
        assertEquals("Armenian", Nationality.AM.toString());
        assertEquals("Australian", Nationality.AU.toString());
        assertEquals("Austrian", Nationality.AT.toString());
        assertEquals("Azerbaijani", Nationality.AZ.toString());
        assertEquals("Bahamian", Nationality.BS.toString());
        assertEquals("Bahraini", Nationality.BH.toString());
        assertEquals("Bangladeshi", Nationality.BD.toString());
        assertEquals("Barbadian", Nationality.BB.toString());
        assertEquals("Belarusian", Nationality.BY.toString());
        assertEquals("Belgian", Nationality.BE.toString());
        assertEquals("Belizean", Nationality.BZ.toString());
        assertEquals("Beninese", Nationality.BJ.toString());
        assertEquals("Bermudian", Nationality.BM.toString());
        assertEquals("Bhutanese", Nationality.BT.toString());
        assertEquals("Bolivian", Nationality.BO.toString());
        assertEquals("Citizen of Bosnia and Herzegovina", Nationality.BA.toString());
        assertEquals("Botswanan", Nationality.BW.toString());
        assertEquals("Brazilian", Nationality.BR.toString());
        assertEquals("British", Nationality.GB.toString());
        assertEquals("British Virgin Islander", Nationality.VG.toString());
        assertEquals("Bruneian", Nationality.BN.toString());
        assertEquals("Bulgarian", Nationality.BG.toString());
        assertEquals("Burkinan", Nationality.BF.toString());
        assertEquals("Burmese", Nationality.MM.toString());
        assertEquals("Burundian", Nationality.BI.toString());
        assertEquals("Cambodian", Nationality.KH.toString());
        assertEquals("Cameroonian", Nationality.CM.toString());
        assertEquals("Canadian", Nationality.CA.toString());
        assertEquals("Cape Verdean", Nationality.CV.toString());
        assertEquals("Cayman Islander", Nationality.KY.toString());
        assertEquals("Central African", Nationality.CF.toString());
        assertEquals("Chadian", Nationality.TD.toString());
        assertEquals("Chilean", Nationality.CL.toString());
        assertEquals("Chinese", Nationality.CN.toString());
        assertEquals("Colombian", Nationality.CO.toString());
        assertEquals("Comoran", Nationality.KM.toString());
        assertEquals("Congolese (Congo)", Nationality.CG.toString());
        assertEquals("Congolese (DRC)", Nationality.CD.toString());
        assertEquals("Cook Islander", Nationality.CK.toString());
        assertEquals("Costa Rican", Nationality.CR.toString());
        assertEquals("Croatian", Nationality.HR.toString());
        assertEquals("Cuban", Nationality.CU.toString());
        assertEquals("Cymraes", Nationality.CYMRAES.toString());
        assertEquals("Cymro", Nationality.CYMRO.toString());
        assertEquals("Cypriot", Nationality.CY.toString());
        assertEquals("Czech", Nationality.CZ.toString());
        assertEquals("Danish", Nationality.DK.toString());
        assertEquals("Djiboutian", Nationality.DJ.toString());
        assertEquals("Dominican", Nationality.DM.toString());
        assertEquals("Citizen of the Dominican Republic", Nationality.DO.toString());
        assertEquals("Dutch", Nationality.NL.toString());
        assertEquals("East Timorese", Nationality.TL.toString());
        assertEquals("Ecuadorean", Nationality.EC.toString());
        assertEquals("Egyptian", Nationality.EG.toString());
        assertEquals("Emirati", Nationality.AE.toString());
        assertEquals("English", Nationality.GB_ENG.toString());
        assertEquals("Equatorial Guinean", Nationality.GQ.toString());
        assertEquals("Eritrean", Nationality.ER.toString());
        assertEquals("Estonian", Nationality.EE.toString());
        assertEquals("Ethiopian", Nationality.ET.toString());
        assertEquals("Faroese", Nationality.FO.toString());
        assertEquals("Fijian", Nationality.FJ.toString());
        assertEquals("Filipino", Nationality.PH.toString());
        assertEquals("Finnish", Nationality.FI.toString());
        assertEquals("French", Nationality.FR.toString());
        assertEquals("Gabonese", Nationality.GA.toString());
        assertEquals("Gambian", Nationality.GM.toString());
        assertEquals("Georgian", Nationality.GE.toString());
        assertEquals("German", Nationality.DE.toString());
        assertEquals("Ghanaian", Nationality.GH.toString());
        assertEquals("Gibraltarian", Nationality.GI.toString());
        assertEquals("Greek", Nationality.GR.toString());
        assertEquals("Greenlandic", Nationality.GL.toString());
        assertEquals("Grenadian", Nationality.GD.toString());
        assertEquals("Guamanian", Nationality.GU.toString());
        assertEquals("Guatemalan", Nationality.GT.toString());
        assertEquals("Citizen of Guinea-Bissau", Nationality.GW.toString());
        assertEquals("Guinean", Nationality.GN.toString());
        assertEquals("Guyanese", Nationality.GY.toString());
        assertEquals("Haitian", Nationality.HT.toString());
        assertEquals("Honduran", Nationality.HN.toString());
        assertEquals("Hong Konger", Nationality.HK.toString());
        assertEquals("Hungarian", Nationality.HU.toString());
        assertEquals("Icelandic", Nationality.IS.toString());
        assertEquals("Indian", Nationality.IN.toString());
        assertEquals("Indonesian", Nationality.ID.toString());
        assertEquals("Iranian", Nationality.IR.toString());
        assertEquals("Iraqi", Nationality.IQ.toString());
        assertEquals("Irish", Nationality.IE.toString());
        assertEquals("Israeli", Nationality.IL.toString());
        assertEquals("Italian", Nationality.IT.toString());
        assertEquals("Ivorian", Nationality.CI.toString());
        assertEquals("Jamaican", Nationality.JM.toString());
        assertEquals("Japanese", Nationality.JP.toString());
        assertEquals("Jordanian", Nationality.JO.toString());
        assertEquals("Kazakh", Nationality.KZ.toString());
        assertEquals("Kenyan", Nationality.KE.toString());
        assertEquals("Kittitian", Nationality.KN.toString());
        assertEquals("Citizen of Kiribati", Nationality.KI.toString());
        assertEquals("Kosovan", Nationality.XK.toString());
        assertEquals("Kuwaiti", Nationality.KW.toString());
        assertEquals("Kyrgyz", Nationality.KG.toString());
        assertEquals("Lao", Nationality.LA.toString());
        assertEquals("Latvian", Nationality.LV.toString());
        assertEquals("Lebanese", Nationality.LB.toString());
        assertEquals("Liberian", Nationality.LR.toString());
        assertEquals("Libyan", Nationality.LY.toString());
        assertEquals("Liechtenstein citizen", Nationality.LI.toString());
        assertEquals("Lithuanian", Nationality.LT.toString());
        assertEquals("Luxembourger", Nationality.LU.toString());
        assertEquals("Macanese", Nationality.MO.toString());
        assertEquals("Macedonian", Nationality.MK.toString());
        assertEquals("Malagasy", Nationality.MG.toString());
        assertEquals("Malawian", Nationality.MW.toString());
        assertEquals("Malaysian", Nationality.MY.toString());
        assertEquals("Maldivian", Nationality.MV.toString());
        assertEquals("Malian", Nationality.ML.toString());
        assertEquals("Maltese", Nationality.MT.toString());
        assertEquals("Marshallese", Nationality.MH.toString());
        assertEquals("Martiniquais", Nationality.MQ.toString());
        assertEquals("Mauritanian", Nationality.MR.toString());
        assertEquals("Mauritian", Nationality.MU.toString());
        assertEquals("Mexican", Nationality.MX.toString());
        assertEquals("Micronesian", Nationality.FM.toString());
        assertEquals("Moldovan", Nationality.MD.toString());
        assertEquals("Monegasque", Nationality.MC.toString());
        assertEquals("Mongolian", Nationality.MN.toString());
        assertEquals("Montenegrin", Nationality.ME.toString());
        assertEquals("Montserratian", Nationality.MS.toString());
        assertEquals("Moroccan", Nationality.MA.toString());
        assertEquals("Mosotho", Nationality.LS.toString());
        assertEquals("Mozambican", Nationality.MZ.toString());
        assertEquals("Namibian", Nationality.NA.toString());
        assertEquals("Nauruan", Nationality.NR.toString());
        assertEquals("Nepalese", Nationality.NP.toString());
        assertEquals("New Zealander", Nationality.NZ.toString());
        assertEquals("Nicaraguan", Nationality.NI.toString());
        assertEquals("Nigerian", Nationality.NG.toString());
        assertEquals("Nigerien", Nationality.NE.toString());
        assertEquals("Niuean", Nationality.NU.toString());
        assertEquals("North Korean", Nationality.KP.toString());
        assertEquals("Northern Irish", Nationality.GB_NIR.toString());
        assertEquals("Norwegian", Nationality.NO.toString());
        assertEquals("Omani", Nationality.OM.toString());
        assertEquals("Pakistani", Nationality.PK.toString());
        assertEquals("Palauan", Nationality.PW.toString());
        assertEquals("Palestinian", Nationality.PS.toString());
        assertEquals("Panamanian", Nationality.PA.toString());
        assertEquals("Papua New Guinean", Nationality.PG.toString());
        assertEquals("Paraguayan", Nationality.PY.toString());
        assertEquals("Peruvian", Nationality.PE.toString());
        assertEquals("Pitcairn Islander", Nationality.PN.toString());
        assertEquals("Polish", Nationality.PL.toString());
        assertEquals("Portuguese", Nationality.PT.toString());
        assertEquals("Prydeinig", Nationality.PRYDEINIG.toString());
        assertEquals("Puerto Rican", Nationality.PR.toString());
        assertEquals("Qatari", Nationality.QA.toString());
        assertEquals("Romanian", Nationality.RO.toString());
        assertEquals("Russian", Nationality.RU.toString());
        assertEquals("Rwandan", Nationality.RW.toString());
        assertEquals("Salvadorean", Nationality.SV.toString());
        assertEquals("Sammarinese", Nationality.SM.toString());
        assertEquals("Samoan", Nationality.WS.toString());
        assertEquals("Sao Tomean", Nationality.ST.toString());
        assertEquals("Saudi Arabian", Nationality.SA.toString());
        assertEquals("Scottish", Nationality.GB_SCT.toString());
        assertEquals("Senegalese", Nationality.SN.toString());
        assertEquals("Serbian", Nationality.RS.toString());
        assertEquals("Citizen of Seychelles", Nationality.SC.toString());
        assertEquals("Sierra Leonean", Nationality.SL.toString());
        assertEquals("Singaporean", Nationality.SG.toString());
        assertEquals("Slovak", Nationality.SK.toString());
        assertEquals("Slovenian", Nationality.SI.toString());
        assertEquals("Solomon Islander", Nationality.SB.toString());
        assertEquals("Somali", Nationality.SO.toString());
        assertEquals("South African", Nationality.ZA.toString());
        assertEquals("South Korean", Nationality.KR.toString());
        assertEquals("South Sudanese", Nationality.SS.toString());
        assertEquals("Spanish", Nationality.ES.toString());
        assertEquals("Sri Lankan", Nationality.LK.toString());
        assertEquals("St Helenian", Nationality.SH.toString());
        assertEquals("St Lucian", Nationality.LC.toString());
        assertEquals("Sudanese", Nationality.SD.toString());
        assertEquals("Surinamese", Nationality.SR.toString());
        assertEquals("Swazi", Nationality.SZ.toString());
        assertEquals("Swedish", Nationality.SE.toString());
        assertEquals("Swiss", Nationality.CH.toString());
        assertEquals("Syrian", Nationality.SY.toString());
        assertEquals("Taiwanese", Nationality.TW.toString());
        assertEquals("Tajik", Nationality.TJ.toString());
        assertEquals("Tanzanian", Nationality.TZ.toString());
        assertEquals("Thai", Nationality.TH.toString());
        assertEquals("Togolese", Nationality.TG.toString());
        assertEquals("Tongan", Nationality.TO.toString());
        assertEquals("Trinidadian", Nationality.TT.toString());
        assertEquals("Tristanian", Nationality.SH_TA.toString());
        assertEquals("Tunisian", Nationality.TN.toString());
        assertEquals("Turkish", Nationality.TR.toString());
        assertEquals("Turkmen", Nationality.TM.toString());
        assertEquals("Turks and Caicos Islander", Nationality.TC.toString());
        assertEquals("Tuvaluan", Nationality.TV.toString());
        assertEquals("Ugandan", Nationality.UG.toString());
        assertEquals("Ukrainian", Nationality.UA.toString());
        assertEquals("Uruguayan", Nationality.UY.toString());
        assertEquals("Uzbek", Nationality.UZ.toString());
        assertEquals("Vatican citizen", Nationality.VA.toString());
        assertEquals("Citizen of Vanuatu", Nationality.VU.toString());
        assertEquals("Venezuelan", Nationality.VE.toString());
        assertEquals("Vietnamese", Nationality.VN.toString());
        assertEquals("Vincentian", Nationality.VC.toString());
        assertEquals("Wallisian", Nationality.WF.toString());
        assertEquals("Welsh", Nationality.GB_WLS.toString());
        assertEquals("Yemeni", Nationality.YE.toString());
        assertEquals("Zambian", Nationality.ZM.toString());
        assertEquals("Zimbabwean", Nationality.ZW.toString());
    }

    @Test
    void if_this_test_fails_it_is_because_it_needs_updating_with_your_changes() {
        assertEquals(226, Nationality.values().length);
    }
}
