package uk.gov.hmcts.reform.iacaseapi.domain.entities.ccd;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

class NationalityTest {

    @Test
    void has_correct_values() {
        assertEquals("Afghan", Nationality.AFGHAN.toString());
        assertEquals("Albanian", Nationality.ALBANIAN.toString());
        assertEquals("Algerian", Nationality.ALGERIAN.toString());
        assertEquals("American", Nationality.AMERICAN.toString());
        assertEquals("Andorran", Nationality.ANDORRAN.toString());
        assertEquals("Angolan", Nationality.ANGOLAN.toString());
        assertEquals("Anguillan", Nationality.ANGUILLAN.toString());
        assertEquals("Citizen of Antigua and Barbuda", Nationality.CITIZEN_OF_ANTIGUA_AND_BARBUDA.toString());
        assertEquals("Argentine", Nationality.ARGENTINE.toString());
        assertEquals("Armenian", Nationality.ARMENIAN.toString());
        assertEquals("Australian", Nationality.AUSTRALIAN.toString());
        assertEquals("Austrian", Nationality.AUSTRIAN.toString());
        assertEquals("Azerbaijani", Nationality.AZERBAIJANI.toString());
        assertEquals("Bahamian", Nationality.BAHAMIAN.toString());
        assertEquals("Bahraini", Nationality.BAHRAINI.toString());
        assertEquals("Bangladeshi", Nationality.BANGLADESHI.toString());
        assertEquals("Barbadian", Nationality.BARBADIAN.toString());
        assertEquals("Belarusian", Nationality.BELARUSIAN.toString());
        assertEquals("Belgian", Nationality.BELGIAN.toString());
        assertEquals("Belizean", Nationality.BELIZEAN.toString());
        assertEquals("Beninese", Nationality.BENINESE.toString());
        assertEquals("Bermudian", Nationality.BERMUDIAN.toString());
        assertEquals("Bhutanese", Nationality.BHUTANESE.toString());
        assertEquals("Bolivian", Nationality.BOLIVIAN.toString());
        assertEquals("Citizen of Bosnia and Herzegovina", Nationality.CITIZEN_OF_BOSNIA_AND_HERZEGOVINA.toString());
        assertEquals("Botswanan", Nationality.BOTSWANAN.toString());
        assertEquals("Brazilian", Nationality.BRAZILIAN.toString());
        assertEquals("British", Nationality.BRITISH.toString());
        assertEquals("British Virgin Islander", Nationality.BRITISH_VIRGIN_ISLANDER.toString());
        assertEquals("Bruneian", Nationality.BRUNEIAN.toString());
        assertEquals("Bulgarian", Nationality.BULGARIAN.toString());
        assertEquals("Burkinan", Nationality.BURKINAN.toString());
        assertEquals("Burmese", Nationality.BURMESE.toString());
        assertEquals("Burundian", Nationality.BURUNDIAN.toString());
        assertEquals("Cambodian", Nationality.CAMBODIAN.toString());
        assertEquals("Cameroonian", Nationality.CAMEROONIAN.toString());
        assertEquals("Canadian", Nationality.CANADIAN.toString());
        assertEquals("Cape Verdean", Nationality.CAPE_VERDEAN.toString());
        assertEquals("Cayman Islander", Nationality.CAYMAN_ISLANDER.toString());
        assertEquals("Central African", Nationality.CENTRAL_AFRICAN.toString());
        assertEquals("Chadian", Nationality.CHADIAN.toString());
        assertEquals("Chilean", Nationality.CHILEAN.toString());
        assertEquals("Chinese", Nationality.CHINESE.toString());
        assertEquals("Colombian", Nationality.COLOMBIAN.toString());
        assertEquals("Comoran", Nationality.COMORAN.toString());
        assertEquals("Congolese (Congo)", Nationality.CONGOLESE_CONGO.toString());
        assertEquals("Congolese (DRC)", Nationality.CONGOLESE_DRC.toString());
        assertEquals("Cook Islander", Nationality.COOK_ISLANDER.toString());
        assertEquals("Costa Rican", Nationality.COSTA_RICAN.toString());
        assertEquals("Croatian", Nationality.CROATIAN.toString());
        assertEquals("Cuban", Nationality.CUBAN.toString());
        assertEquals("Cymraes", Nationality.CYMRAES.toString());
        assertEquals("Cymro", Nationality.CYMRO.toString());
        assertEquals("Cypriot", Nationality.CYPRIOT.toString());
        assertEquals("Czech", Nationality.CZECH.toString());
        assertEquals("Danish", Nationality.DANISH.toString());
        assertEquals("Djiboutian", Nationality.DJIBOUTIAN.toString());
        assertEquals("Dominican", Nationality.DOMINICAN.toString());
        assertEquals("Citizen of the Dominican Republic", Nationality.CITIZEN_OF_THE_DOMINICAN_REPUBLIC.toString());
        assertEquals("Dutch", Nationality.DUTCH.toString());
        assertEquals("East Timorese", Nationality.EAST_TIMORESE.toString());
        assertEquals("Ecuadorean", Nationality.ECUADOREAN.toString());
        assertEquals("Egyptian", Nationality.EGYPTIAN.toString());
        assertEquals("Emirati", Nationality.EMIRATI.toString());
        assertEquals("English", Nationality.ENGLISH.toString());
        assertEquals("Equatorial Guinean", Nationality.EQUATORIAL_GUINEAN.toString());
        assertEquals("Eritrean", Nationality.ERITREAN.toString());
        assertEquals("Estonian", Nationality.ESTONIAN.toString());
        assertEquals("Ethiopian", Nationality.ETHIOPIAN.toString());
        assertEquals("Faroese", Nationality.FAROESE.toString());
        assertEquals("Fijian", Nationality.FIJIAN.toString());
        assertEquals("Filipino", Nationality.FILIPINO.toString());
        assertEquals("Finnish", Nationality.FINNISH.toString());
        assertEquals("French", Nationality.FRENCH.toString());
        assertEquals("Gabonese", Nationality.GABONESE.toString());
        assertEquals("Gambian", Nationality.GAMBIAN.toString());
        assertEquals("Georgian", Nationality.GEORGIAN.toString());
        assertEquals("German", Nationality.GERMAN.toString());
        assertEquals("Ghanaian", Nationality.GHANAIAN.toString());
        assertEquals("Gibraltarian", Nationality.GIBRALTARIAN.toString());
        assertEquals("Greek", Nationality.GREEK.toString());
        assertEquals("Greenlandic", Nationality.GREENLANDIC.toString());
        assertEquals("Grenadian", Nationality.GRENADIAN.toString());
        assertEquals("Guamanian", Nationality.GUAMANIAN.toString());
        assertEquals("Guatemalan", Nationality.GUATEMALAN.toString());
        assertEquals("Citizen of Guinea-Bissau", Nationality.CITIZEN_OF_GUINEA_BISSAU.toString());
        assertEquals("Guinean", Nationality.GUINEAN.toString());
        assertEquals("Guyanese", Nationality.GUYANESE.toString());
        assertEquals("Haitian", Nationality.HAITIAN.toString());
        assertEquals("Honduran", Nationality.HONDURAN.toString());
        assertEquals("Hong Konger", Nationality.HONG_KONGER.toString());
        assertEquals("Hungarian", Nationality.HUNGARIAN.toString());
        assertEquals("Icelandic", Nationality.ICELANDIC.toString());
        assertEquals("Indian", Nationality.INDIAN.toString());
        assertEquals("Indonesian", Nationality.INDONESIAN.toString());
        assertEquals("Iranian", Nationality.IRANIAN.toString());
        assertEquals("Iraqi", Nationality.IRAQI.toString());
        assertEquals("Irish", Nationality.IRISH.toString());
        assertEquals("Israeli", Nationality.ISRAELI.toString());
        assertEquals("Italian", Nationality.ITALIAN.toString());
        assertEquals("Ivorian", Nationality.IVORIAN.toString());
        assertEquals("Jamaican", Nationality.JAMAICAN.toString());
        assertEquals("Japanese", Nationality.JAPANESE.toString());
        assertEquals("Jordanian", Nationality.JORDANIAN.toString());
        assertEquals("Kazakh", Nationality.KAZAKH.toString());
        assertEquals("Kenyan", Nationality.KENYAN.toString());
        assertEquals("Kittitian", Nationality.KITTITIAN.toString());
        assertEquals("Citizen of Kiribati", Nationality.CITIZEN_OF_KIRIBATI.toString());
        assertEquals("Kosovan", Nationality.KOSOVAN.toString());
        assertEquals("Kuwaiti", Nationality.KUWAITI.toString());
        assertEquals("Kyrgyz", Nationality.KYRGYZ.toString());
        assertEquals("Lao", Nationality.LAO.toString());
        assertEquals("Latvian", Nationality.LATVIAN.toString());
        assertEquals("Lebanese", Nationality.LEBANESE.toString());
        assertEquals("Liberian", Nationality.LIBERIAN.toString());
        assertEquals("Libyan", Nationality.LIBYAN.toString());
        assertEquals("Liechtenstein citizen", Nationality.LIECHTENSTEIN_CITIZEN.toString());
        assertEquals("Lithuanian", Nationality.LITHUANIAN.toString());
        assertEquals("Luxembourger", Nationality.LUXEMBOURGER.toString());
        assertEquals("Macanese", Nationality.MACANESE.toString());
        assertEquals("Macedonian", Nationality.MACEDONIAN.toString());
        assertEquals("Malagasy", Nationality.MALAGASY.toString());
        assertEquals("Malawian", Nationality.MALAWIAN.toString());
        assertEquals("Malaysian", Nationality.MALAYSIAN.toString());
        assertEquals("Maldivian", Nationality.MALDIVIAN.toString());
        assertEquals("Malian", Nationality.MALIAN.toString());
        assertEquals("Maltese", Nationality.MALTESE.toString());
        assertEquals("Marshallese", Nationality.MARSHALLESE.toString());
        assertEquals("Martiniquais", Nationality.MARTINIQUAIS.toString());
        assertEquals("Mauritanian", Nationality.MAURITANIAN.toString());
        assertEquals("Mauritian", Nationality.MAURITIAN.toString());
        assertEquals("Mexican", Nationality.MEXICAN.toString());
        assertEquals("Micronesian", Nationality.MICRONESIAN.toString());
        assertEquals("Moldovan", Nationality.MOLDOVAN.toString());
        assertEquals("Monegasque", Nationality.MONEGASQUE.toString());
        assertEquals("Mongolian", Nationality.MONGOLIAN.toString());
        assertEquals("Montenegrin", Nationality.MONTENEGRIN.toString());
        assertEquals("Montserratian", Nationality.MONTSERRATIAN.toString());
        assertEquals("Moroccan", Nationality.MOROCCAN.toString());
        assertEquals("Mosotho", Nationality.MOSOTHO.toString());
        assertEquals("Mozambican", Nationality.MOZAMBICAN.toString());
        assertEquals("Namibian", Nationality.NAMIBIAN.toString());
        assertEquals("Nauruan", Nationality.NAURUAN.toString());
        assertEquals("Nepalese", Nationality.NEPALESE.toString());
        assertEquals("New Zealander", Nationality.NEW_ZEALANDER.toString());
        assertEquals("Nicaraguan", Nationality.NICARAGUAN.toString());
        assertEquals("Nigerian", Nationality.NIGERIAN.toString());
        assertEquals("Nigerien", Nationality.NIGERIEN.toString());
        assertEquals("Niuean", Nationality.NIUEAN.toString());
        assertEquals("North Korean", Nationality.NORTH_KOREAN.toString());
        assertEquals("Northern Irish", Nationality.NORTHERN_IRISH.toString());
        assertEquals("Norwegian", Nationality.NORWEGIAN.toString());
        assertEquals("Omani", Nationality.OMANI.toString());
        assertEquals("Pakistani", Nationality.PAKISTANI.toString());
        assertEquals("Palauan", Nationality.PALAUAN.toString());
        assertEquals("Palestinian", Nationality.PALESTINIAN.toString());
        assertEquals("Panamanian", Nationality.PANAMANIAN.toString());
        assertEquals("Papua New Guinean", Nationality.PAPUA_NEW_GUINEAN.toString());
        assertEquals("Paraguayan", Nationality.PARAGUAYAN.toString());
        assertEquals("Peruvian", Nationality.PERUVIAN.toString());
        assertEquals("Pitcairn Islander", Nationality.PITCAIRN_ISLANDER.toString());
        assertEquals("Polish", Nationality.POLISH.toString());
        assertEquals("Portuguese", Nationality.PORTUGUESE.toString());
        assertEquals("Prydeinig", Nationality.PRYDEINIG.toString());
        assertEquals("Puerto Rican", Nationality.PUERTO_RICAN.toString());
        assertEquals("Qatari", Nationality.QATARI.toString());
        assertEquals("Romanian", Nationality.ROMANIAN.toString());
        assertEquals("Russian", Nationality.RUSSIAN.toString());
        assertEquals("Rwandan", Nationality.RWANDAN.toString());
        assertEquals("Salvadorean", Nationality.SALVADOREAN.toString());
        assertEquals("Sammarinese", Nationality.SAMMARINESE.toString());
        assertEquals("Samoan", Nationality.SAMOAN.toString());
        assertEquals("Sao Tomean", Nationality.SAO_TOMEAN.toString());
        assertEquals("Saudi Arabian", Nationality.SAUDI_ARABIAN.toString());
        assertEquals("Scottish", Nationality.SCOTTISH.toString());
        assertEquals("Senegalese", Nationality.SENEGALESE.toString());
        assertEquals("Serbian", Nationality.SERBIAN.toString());
        assertEquals("Citizen of Seychelles", Nationality.CITIZEN_OF_SEYCHELLES.toString());
        assertEquals("Sierra Leonean", Nationality.SIERRA_LEONEAN.toString());
        assertEquals("Singaporean", Nationality.SINGAPOREAN.toString());
        assertEquals("Slovak", Nationality.SLOVAK.toString());
        assertEquals("Slovenian", Nationality.SLOVENIAN.toString());
        assertEquals("Solomon Islander", Nationality.SOLOMON_ISLANDER.toString());
        assertEquals("Somali", Nationality.SOMALI.toString());
        assertEquals("South African", Nationality.SOUTH_AFRICAN.toString());
        assertEquals("South Korean", Nationality.SOUTH_KOREAN.toString());
        assertEquals("South Sudanese", Nationality.SOUTH_SUDANESE.toString());
        assertEquals("Spanish", Nationality.SPANISH.toString());
        assertEquals("Sri Lankan", Nationality.SRI_LANKAN.toString());
        assertEquals("St Helenian", Nationality.ST_HELENIAN.toString());
        assertEquals("St Lucian", Nationality.ST_LUCIAN.toString());
        assertEquals("Sudanese", Nationality.SUDANESE.toString());
        assertEquals("Surinamese", Nationality.SURINAMESE.toString());
        assertEquals("Swazi", Nationality.SWAZI.toString());
        assertEquals("Swedish", Nationality.SWEDISH.toString());
        assertEquals("Swiss", Nationality.SWISS.toString());
        assertEquals("Syrian", Nationality.SYRIAN.toString());
        assertEquals("Taiwanese", Nationality.TAIWANESE.toString());
        assertEquals("Tajik", Nationality.TAJIK.toString());
        assertEquals("Tanzanian", Nationality.TANZANIAN.toString());
        assertEquals("Thai", Nationality.THAI.toString());
        assertEquals("Togolese", Nationality.TOGOLESE.toString());
        assertEquals("Tongan", Nationality.TONGAN.toString());
        assertEquals("Trinidadian", Nationality.TRINIDADIAN.toString());
        assertEquals("Tristanian", Nationality.TRISTANIAN.toString());
        assertEquals("Tunisian", Nationality.TUNISIAN.toString());
        assertEquals("Turkish", Nationality.TURKISH.toString());
        assertEquals("Turkmen", Nationality.TURKMEN.toString());
        assertEquals("Turks and Caicos Islander", Nationality.TURKS_AND_CAICOS_ISLANDER.toString());
        assertEquals("Tuvaluan", Nationality.TUVALUAN.toString());
        assertEquals("Ugandan", Nationality.UGANDAN.toString());
        assertEquals("Ukrainian", Nationality.UKRAINIAN.toString());
        assertEquals("Uruguayan", Nationality.URUGUAYAN.toString());
        assertEquals("Uzbek", Nationality.UZBEK.toString());
        assertEquals("Vatican citizen", Nationality.VATICAN_CITIZEN.toString());
        assertEquals("Citizen of Vanuatu", Nationality.CITIZEN_OF_VANUATU.toString());
        assertEquals("Venezuelan", Nationality.VENEZUELAN.toString());
        assertEquals("Vietnamese", Nationality.VIETNAMESE.toString());
        assertEquals("Vincentian", Nationality.VINCENTIAN.toString());
        assertEquals("Wallisian", Nationality.WALLISIAN.toString());
        assertEquals("Welsh", Nationality.WELSH.toString());
        assertEquals("Yemeni", Nationality.YEMENI.toString());
        assertEquals("Zambian", Nationality.ZAMBIAN.toString());
        assertEquals("Zimbabwean", Nationality.ZIMBABWEAN.toString());
    }

    @Test
    void if_this_test_fails_it_is_because_it_needs_updating_with_your_changes() {
        assertEquals(225, Nationality.values().length);
    }
}
