package uk.gov.hmcts.reform.iacaseapi.ccd;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>The work-basket input and result fields for {@code Asylum}.
 */
@Component
public class AsylumWorkBasket implements CCDConfig<CaseData, State, UserRole> {
    /**
     * Configures the work-basket input and result fields for {@code Asylum}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.workBasketInputFields()
            .field("selectedHearingCentreRefData", "Hearing centre")
            .field("appealReferenceNumber", "HMCTS reference")
            .field("appellantNameForDisplay", "Appellant name")
            .field("appellantDateOfBirth", "Date of birth")
            .field("searchPostcode", "Post code")
            .field("legalRepReferenceNumber", "Legal representative reference")
            .field("homeOfficeReferenceNumber", "Home Office reference")
            .field("caseWorkerName", "Caseworker")
            .field("[CASE_REFERENCE]", "Case Id Reference")
            .field("isAriaMigratedFilter", "ARIA migrated")
            .field("appellantInDetention", "Detained")
            .field("stf24wCurrentStatusAutoGenerated", "24W statutory timeframe")
            .field("isAdmin", "Internal creation (ICC)")
            .field("journeyType", "Representation type");
        builder.workBasketResultFields()
            .field("appealReferenceNumber", "HMCTS reference")
            .field("appellantNameForDisplay", "Appellant name")
            .field("[STATE]", "Status")
            .field("listCaseHearingDate", "Hearing date")
            .field("caseWorkerName", "Caseworker")
            .field("appellantsRepresentation", "ICC Appellant in person");
    }
}
