package uk.gov.hmcts.reform.iacaseapi.ccd;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>The Notice of Change challenge questions for {@code Asylum}.
 */
@Component
public class AsylumNoticeOfChange implements CCDConfig<CaseData, State, UserRole> {
    /**
     * Configures the Notice of Change challenge questions for {@code Asylum}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.noticeOfChange()
            .challenge("NoCChallenge")
                .question("NoCChallengeQ1", "First Name")
                .displayOrder(1)
                .answerFieldType("Text")
                .answer(UserRole.LEGALREPRESENTATIVE)
                    .field("appellantGivenNames")
                .done()
                .question("NoCChallengeQ2", "Last Name")
                .displayOrder(2)
                .answerFieldType("Text")
                .answer(UserRole.LEGALREPRESENTATIVE)
                    .field("appellantFamilyName")
                .done();
    }
}
