package uk.gov.hmcts.reform.iacaseapi.domain.entities.ccd;

import com.fasterxml.jackson.annotation.JsonEnumDefaultValue;
import com.fasterxml.jackson.annotation.JsonValue;

public enum Event {

    START_APPEAL("startAppeal"),
    EDIT_APPEAL("editAppeal"),
    SUBMIT_APPEAL("submitAppeal"),
    SEND_DIRECTION("sendDirection"),
    REQUEST_RESPONDENT_EVIDENCE("requestRespondentEvidence"),
    UPLOAD_RESPONDENT_EVIDENCE("uploadRespondentEvidence"),
    UPLOAD_HOME_OFFICE_BUNDLE("uploadHomeOfficeBundle"),
    BUILD_CASE("buildCase"),
    SUBMIT_CASE("submitCase"),
    REQUEST_CASE_EDIT("requestCaseEdit"),
    REQUEST_RESPONDENT_REVIEW("requestRespondentReview"),
    ADD_APPEAL_RESPONSE("addAppealResponse"),
    UPLOAD_HOME_OFFICE_APPEAL_RESPONSE("uploadHomeOfficeAppealResponse"),
    REQUEST_HEARING_REQUIREMENTS("requestHearingRequirements"),
    REQUEST_HEARING_REQUIREMENTS_FEATURE("requestHearingRequirementsFeature"),
    REVIEW_HEARING_REQUIREMENTS("reviewHearingRequirements"),
    DRAFT_HEARING_REQUIREMENTS("draftHearingRequirements"),
    UPDATE_HEARING_REQUIREMENTS("updateHearingRequirements"),
    UPDATE_HEARING_ADJUSTMENTS("updateHearingAdjustments"),
    CHANGE_DIRECTION_DUE_DATE("changeDirectionDueDate"),
    UPLOAD_ADDITIONAL_EVIDENCE("uploadAdditionalEvidence"),
    UPLOAD_ADDENDUM_EVIDENCE("uploadAddendumEvidence"),
    LIST_CASE("listCase"),
    LIST_CASE_WITHOUT_HEARING_REQUIREMENTS("listCaseWithoutHearingRequirements"),
    CREATE_CASE_SUMMARY("createCaseSummary"),
    REVERT_STATE_TO_AWAITING_RESPONDENT_EVIDENCE("revertStateToAwaitingRespondentEvidence"),
    GENERATE_HEARING_BUNDLE("generateHearingBundle"),
    CUSTOMISE_HEARING_BUNDLE("customiseHearingBundle"),
    GENERATE_UPDATED_HEARING_BUNDLE("generateUpdatedHearingBundle"),
    ASYNC_STITCHING_COMPLETE("asyncStitchingComplete"),
    DECISION_AND_REASONS_STARTED("decisionAndReasonsStarted"),
    GENERATE_DECISION_AND_REASONS("generateDecisionAndReasons"),
    SEND_DECISION_AND_REASONS("sendDecisionAndReasons"),
    ADD_CASE_NOTE("addCaseNote"),
    EDIT_CASE_LISTING("editCaseListing"),
    RECORD_APPLICATION("recordApplication"),
    RECORD_ATTENDEES_AND_DURATION("recordAttendeesAndDuration"),
    UPLOAD_HEARING_RECORDING("uploadHearingRecording"),
    END_APPEAL("endAppeal"),
    REQUEST_CASE_BUILDING("requestCaseBuilding"),
    FORCE_REQUEST_CASE_BUILDING("forceRequestCaseBuilding"),
    UPLOAD_ADDITIONAL_EVIDENCE_HOME_OFFICE("uploadAdditionalEvidenceHomeOffice"),
    REQUEST_RESPONSE_REVIEW("requestResponseReview"),
    REQUEST_RESPONSE_AMEND("requestResponseAmend"),
    UPLOAD_ADDENDUM_EVIDENCE_LEGAL_REP("uploadAddendumEvidenceLegalRep"),
    UPLOAD_ADDENDUM_EVIDENCE_HOME_OFFICE("uploadAddendumEvidenceHomeOffice"),
    UPLOAD_ADDENDUM_EVIDENCE_ADMIN_OFFICER("uploadAddendumEvidenceAdminOfficer"),
    SUBMIT_HEARING_REQUIREMENTS("submitHearingRequirements"),
    REMOVE_APPEAL_FROM_ONLINE("removeAppealFromOnline"),
    SHARE_A_CASE("shareACase"),
    REQUEST_REASONS_FOR_APPEAL("requestReasonsForAppeal"),
    EDIT_REASONS_FOR_APPEAL("editReasonsForAppeal"),
    SUBMIT_REASONS_FOR_APPEAL("submitReasonsForAppeal"),
    REQUEST_CLARIFYING_ANSWERS("requestClarifyingAnswers"),
    SUBMIT_CLARIFYING_QUESTION_ANSWERS("submitClarifyingQuestionAnswers"),
    COMPLETE_CLARIFY_QUESTIONS("completeClarifyQuestions"),
    EDIT_DOCUMENTS("editDocuments"),
    SEND_TO_PREHEARING("sendToPreHearing"),
    CHANGE_HEARING_CENTRE("changeHearingCentre"),
    APPLY_FOR_FTPA_APPELLANT("applyForFTPAAppellant"),
    APPLY_FOR_FTPA_RESPONDENT("applyForFTPARespondent"),
    LEADERSHIP_JUDGE_FTPA_DECISION("leadershipJudgeFtpaDecision"),
    RESIDENT_JUDGE_FTPA_DECISION("residentJudgeFtpaDecision"),
    DECIDE_FTPA_APPLICATION("decideFtpaApplication"),
    RECORD_ALLOCATED_JUDGE("recordAllocatedJudge"),
    EDIT_TIME_EXTENSION("editTimeExtension"),
    SUBMIT_TIME_EXTENSION("submitTimeExtension"),
    REVIEW_TIME_EXTENSION("reviewTimeExtension"),
    SEND_DIRECTION_WITH_QUESTIONS("sendDirectionWithQuestions"),
    FLAG_CASE("flagCase"), // tactical flag
    CREATE_FLAG("createFlag"), // strategic flag
    REMOVE_FLAG("removeFlag"),
    REQUEST_CMA_REQUIREMENTS("requestCmaRequirements"),
    EDIT_CMA_REQUIREMENTS("editCmaRequirements"),
    SUBMIT_CMA_REQUIREMENTS("submitCmaRequirements"),
    REVIEW_CMA_REQUIREMENTS("reviewCmaRequirements"),
    FORCE_CASE_TO_CASE_UNDER_REVIEW("forceCaseToCaseUnderReview"),
    UPDATE_DETAILS_AFTER_CMA("updateDetailsAfterCma"),
    FORCE_CASE_TO_SUBMIT_HEARING_REQUIREMENTS("forceCaseToSubmitHearingRequirements"),
    UPDATE_LEGAL_REPRESENTATIVES_DETAILS("updateLegalRepDetails"),
    ADJOURN_HEARING_WITHOUT_DATE("adjournHearingWithoutDate"),
    RESTORE_STATE_FROM_ADJOURN("restoreStateFromAdjourn"),
    DECISION_WITHOUT_HEARING("decisionWithoutHearing"),
    LIST_CMA("listCma"),
    EDIT_APPEAL_AFTER_SUBMIT("editAppealAfterSubmit"),
    LINK_APPEAL("linkAppeal"),
    UNLINK_APPEAL("unlinkAppeal"),
    PAYMENT_APPEAL("paymentAppeal"),
    MOVE_TO_PAYMENT_PENDING("moveToPaymentPending"),
    ROLLBACK_PAYMENT("rollbackPayment"),
    ROLLBACK_PAYMENT_TIMEOUT("rollbackPaymentTimeout"),
    ROLLBACK_PAYMENT_TIMEOUT_TO_PAYMENT_PENDING("rollbackPaymentTimeoutToPaymentPending"),
    UPLOAD_SENSITIVE_DOCUMENTS("uploadSensitiveDocuments"),
    MARK_APPEAL_PAID("markAppealPaid"),
    REQUEST_HOME_OFFICE_DATA("requestHomeOfficeData"),
    MAKE_AN_APPLICATION("makeAnApplication"),
    REINSTATE_APPEAL("reinstateAppeal"),
    DECIDE_AN_APPLICATION("decideAnApplication"),
    REQUEST_NEW_HEARING_REQUIREMENTS("requestNewHearingRequirements"),
    ALLOCATE_THE_CASE("allocateTheCase"),
    RECORD_REMISSION_DECISION("recordRemissionDecision"),
    MANAGE_FEE_UPDATE("manageFeeUpdate"),
    NOC_REQUEST("nocRequest"),
    REMOVE_REPRESENTATION("removeRepresentation"),
    REMOVE_LEGAL_REPRESENTATIVE("removeLegalRepresentative"),
    REQUEST_FEE_REMISSION("requestFeeRemission"),
    RECORD_OUT_OF_TIME_DECISION("recordOutOfTimeDecision"),
    GENERATE_UPPER_TRIBUNAL_BUNDLE("generateUpperTribunalBundle"),
    MARK_EVIDENCE_AS_REVIEWED("markEvidenceAsReviewed"),
    UPDATE_PAYMENT_STATUS("updatePaymentStatus"),
    RE_TRIGGER_WA_BULK_TASKS("reTriggerWaBulkTasks"),
    RE_TRIGGER_WA_TASKS("reTriggerWaTasks"),
    MARK_ADDENDUM_EVIDENCE_AS_REVIEWED("markAddendumEvidenceAsReviewed"),
    MARK_PAYMENT_REQUEST_SENT("markPaymentRequestSent"),
    END_APPEAL_AUTOMATICALLY("endAppealAutomatically"),
    GENERATE_SERVICE_REQUEST("generateServiceRequest"),
    TRANSFER_OUT_OF_ADA("transferOutOfAda"),
    MARK_APPEAL_AS_ADA("markAppealAsAda"),
    CREATE_CASE_LINK("createCaseLink"),
    MAINTAIN_CASE_LINKS("maintainCaseLinks"),
    PIP_ACTIVATION("pipActivation"),
    UPDATE_S94B_STATUS("updateS94bStatus"),
    ADA_SUITABILITY_REVIEW("adaSuitabilityReview"),
    REMOVE_DETAINED_STATUS("removeDetainedStatus"),
    MARK_APPEAL_AS_DETAINED("markAppealAsDetained"),
    MARK_AS_READY_FOR_UT_TRANSFER("markAsReadyForUtTransfer"),
    UPDATE_DETENTION_LOCATION("updateDetentionLocation"),
    APPLY_FOR_COSTS("applyForCosts"),
    TURN_ON_NOTIFICATIONS("turnOnNotifications"),
    RESPOND_TO_COSTS("respondToCosts"),
    ADD_EVIDENCE_FOR_COSTS("addEvidenceForCosts"),
    DECIDE_COSTS_APPLICATION("decideCostsApplication"),
    CONSIDER_MAKING_COSTS_ORDER("considerMakingCostsOrder"),
    UPDATE_TRIBUNAL_DECISION("updateTribunalDecision"),
    RECORD_REMISSION_REMINDER("recordRemissionReminder"),
    MARK_APPEAL_AS_REMITTED("markAppealAsRemitted"),
    REFUND_CONFIRMATION("refundConfirmation"),

    UPDATE_INTERPRETER_BOOKING_STATUS("updateInterpreterBookingStatus"),
    UPDATE_INTERPRETER_DETAILS("updateInterpreterDetails"),
    UPDATE_HEARING_REQUEST("updateHearingRequest"),
    HANDLE_HEARING_EXCEPTION("handleHearingException"),
    TRIGGER_CMR_UPDATED("triggerCmrUpdated"),
    RECORD_ADJOURNMENT_DETAILS("recordAdjournmentDetails"),
    LIST_ASSIST_INTEGRATION("listAssistIntegration"),
    TRIGGER_CMR_LISTED("triggerCmrListed"),
    DECISION_WITHOUT_HEARING_LISTED("decisionWithoutHearingListed"),

    @JsonEnumDefaultValue
    UNKNOWN("unknown");

    @JsonValue
    private final String id;

    Event(String id) {
        this.id = id;
    }

    @Override
    public String toString() {
        return id;
    }
}
