package uk.gov.hmcts.reform.iacaseapi.domain.entities.ccd;

import com.fasterxml.jackson.annotation.JsonEnumDefaultValue;
import com.fasterxml.jackson.annotation.JsonValue;

public enum Nationality {
    AF("Afghan"),
    AL("Albanian"),
    DZ("Algerian"),
    US("American"),
    AD("Andorran"),
    AO("Angolan"),
    AI("Anguillan"),
    AG("Citizen of Antigua and Barbuda"),
    AR("Argentine"),
    AM("Armenian"),
    AU("Australian"),
    AT("Austrian"),
    AZ("Azerbaijani"),
    BS("Bahamian"),
    BH("Bahraini"),
    BD("Bangladeshi"),
    BB("Barbadian"),
    BY("Belarusian"),
    BE("Belgian"),
    BZ("Belizean"),
    BJ("Beninese"),
    BM("Bermudian"),
    BT("Bhutanese"),
    BO("Bolivian"),
    BA("Citizen of Bosnia and Herzegovina"),
    BW("Botswanan"),
    BR("Brazilian"),
    GB("British"),
    VG("British Virgin Islander"),
    BN("Bruneian"),
    BG("Bulgarian"),
    BF("Burkinan"),
    MM("Burmese"),
    BI("Burundian"),
    KH("Cambodian"),
    CM("Cameroonian"),
    CA("Canadian"),
    CV("Cape Verdean"),
    KY("Cayman Islander"),
    CF("Central African"),
    TD("Chadian"),
    CL("Chilean"),
    CN("Chinese"),
    CO("Colombian"),
    KM("Comoran"),
    CG("Congolese (Congo)"),
    CD("Congolese (DRC)"),
    CK("Cook Islander"),
    CR("Costa Rican"),
    HR("Croatian"),
    CU("Cuban"),
    CYMRAES("Cymraes"),
    CYMRO("Cymro"),
    CY("Cypriot"),
    CZ("Czech"),
    DK("Danish"),
    DJ("Djiboutian"),
    DM("Dominican"),
    DO("Citizen of the Dominican Republic"),
    NL("Dutch"),
    TL("East Timorese"),
    EC("Ecuadorean"),
    EG("Egyptian"),
    AE("Emirati"),
    GB_ENG("English"),
    GQ("Equatorial Guinean"),
    ER("Eritrean"),
    EE("Estonian"),
    ET("Ethiopian"),
    FO("Faroese"),
    FJ("Fijian"),
    PH("Filipino"),
    FI("Finnish"),
    FR("French"),
    GA("Gabonese"),
    GM("Gambian"),
    GE("Georgian"),
    DE("German"),
    GH("Ghanaian"),
    GI("Gibraltarian"),
    GR("Greek"),
    GL("Greenlandic"),
    GD("Grenadian"),
    GU("Guamanian"),
    GT("Guatemalan"),
    GW("Citizen of Guinea-Bissau"),
    GN("Guinean"),
    GY("Guyanese"),
    HT("Haitian"),
    HN("Honduran"),
    HK("Hong Konger"),
    HU("Hungarian"),
    IS("Icelandic"),
    IN("Indian"),
    ID("Indonesian"),
    IR("Iranian"),
    IQ("Iraqi"),
    IE("Irish"),
    IL("Israeli"),
    IT("Italian"),
    CI("Ivorian"),
    JM("Jamaican"),
    JP("Japanese"),
    JO("Jordanian"),
    KZ("Kazakh"),
    KE("Kenyan"),
    KN("Kittitian"),
    KI("Citizen of Kiribati"),
    XK("Kosovan"),
    KW("Kuwaiti"),
    KG("Kyrgyz"),
    LA("Lao"),
    LV("Latvian"),
    LB("Lebanese"),
    LR("Liberian"),
    LY("Libyan"),
    LI("Liechtenstein citizen"),
    LT("Lithuanian"),
    LU("Luxembourger"),
    MO("Macanese"),
    MK("Macedonian"),
    MG("Malagasy"),
    MW("Malawian"),
    MY("Malaysian"),
    MV("Maldivian"),
    ML("Malian"),
    MT("Maltese"),
    MH("Marshallese"),
    MQ("Martiniquais"),
    MR("Mauritanian"),
    MU("Mauritian"),
    MX("Mexican"),
    FM("Micronesian"),
    MD("Moldovan"),
    MC("Monegasque"),
    MN("Mongolian"),
    ME("Montenegrin"),
    MS("Montserratian"),
    MA("Moroccan"),
    LS("Mosotho"),
    MZ("Mozambican"),
    NA("Namibian"),
    NR("Nauruan"),
    NP("Nepalese"),
    NZ("New Zealander"),
    NI("Nicaraguan"),
    NG("Nigerian"),
    NE("Nigerien"),
    NU("Niuean"),
    KP("North Korean"),
    GB_NIR("Northern Irish"),
    NO("Norwegian"),
    OM("Omani"),
    PK("Pakistani"),
    PW("Palauan"),
    PS("Palestinian"),
    PA("Panamanian"),
    PG("Papua New Guinean"),
    PY("Paraguayan"),
    PE("Peruvian"),
    PN("Pitcairn Islander"),
    PL("Polish"),
    PT("Portuguese"),
    PRYDEINIG("Prydeinig"),
    PR("Puerto Rican"),
    QA("Qatari"),
    RO("Romanian"),
    RU("Russian"),
    RW("Rwandan"),
    SV("Salvadorean"),
    SM("Sammarinese"),
    WS("Samoan"),
    ST("Sao Tomean"),
    SA("Saudi Arabian"),
    GB_SCT("Scottish"),
    SN("Senegalese"),
    RS("Serbian"),
    SC("Citizen of Seychelles"),
    SL("Sierra Leonean"),
    SG("Singaporean"),
    SK("Slovak"),
    SI("Slovenian"),
    SB("Solomon Islander"),
    SO("Somali"),
    ZA("South African"),
    KR("South Korean"),
    SS("South Sudanese"),
    ES("Spanish"),
    LK("Sri Lankan"),
    SH("St Helenian"),
    LC("St Lucian"),
    ZZ("Stateless"),
    SD("Sudanese"),
    SR("Surinamese"),
    SZ("Swazi"),
    SE("Swedish"),
    CH("Swiss"),
    SY("Syrian"),
    TW("Taiwanese"),
    TJ("Tajik"),
    TZ("Tanzanian"),
    TH("Thai"),
    TG("Togolese"),
    TO("Tongan"),
    TT("Trinidadian"),
    SH_TA("Tristanian"),
    TN("Tunisian"),
    TR("Turkish"),
    TM("Turkmen"),
    TC("Turks and Caicos Islander"),
    TV("Tuvaluan"),
    UG("Ugandan"),
    UA("Ukrainian"),
    UY("Uruguayan"),
    UZ("Uzbek"),
    VA("Vatican citizen"),
    VU("Citizen of Vanuatu"),
    VE("Venezuelan"),
    VN("Vietnamese"),
    VC("Vincentian"),
    WF("Wallisian"),
    GB_WLS("Welsh"),
    YE("Yemeni"),
    ZM("Zambian"),
    ZW("Zimbabwean"),

    @JsonEnumDefaultValue
    UNKNOWN("unknown");

    @JsonValue
    private final String id;

    Nationality(String id) {
        this.id = id;
    }

    @Override
    public String toString() {
        return id;
    }

}



