package uk.gov.hmcts.reform.iacaseapi.domain.entities.ccd;

import com.fasterxml.jackson.annotation.JsonEnumDefaultValue;
import com.fasterxml.jackson.annotation.JsonValue;

public enum Nationality {
    AFGHAN("Afghan"),
    ALBANIAN("Albanian"),
    ALGERIAN("Algerian"),
    AMERICAN("American"),
    ANDORRAN("Andorran"),
    ANGOLAN("Angolan"),
    ANGUILLAN("Anguillan"),
    CITIZEN_OF_ANTIGUA_AND_BARBUDA("Citizen of Antigua and Barbuda"),
    ARGENTINE("Argentine"),
    ARMENIAN("Armenian"),
    AUSTRALIAN("Australian"),
    AUSTRIAN("Austrian"),
    AZERBAIJANI("Azerbaijani"),
    BAHAMIAN("Bahamian"),
    BAHRAINI("Bahraini"),
    BANGLADESHI("Bangladeshi"),
    BARBADIAN("Barbadian"),
    BELARUSIAN("Belarusian"),
    BELGIAN("Belgian"),
    BELIZEAN("Belizean"),
    BENINESE("Beninese"),
    BERMUDIAN("Bermudian"),
    BHUTANESE("Bhutanese"),
    BOLIVIAN("Bolivian"),
    CITIZEN_OF_BOSNIA_AND_HERZEGOVINA("Citizen of Bosnia and Herzegovina"),
    BOTSWANAN("Botswanan"),
    BRAZILIAN("Brazilian"),
    BRITISH("British"),
    BRITISH_VIRGIN_ISLANDER("British Virgin Islander"),
    BRUNEIAN("Bruneian"),
    BULGARIAN("Bulgarian"),
    BURKINAN("Burkinan"),
    BURMESE("Burmese"),
    BURUNDIAN("Burundian"),
    CAMBODIAN("Cambodian"),
    CAMEROONIAN("Cameroonian"),
    CANADIAN("Canadian"),
    CAPE_VERDEAN("Cape Verdean"),
    CAYMAN_ISLANDER("Cayman Islander"),
    CENTRAL_AFRICAN("Central African"),
    CHADIAN("Chadian"),
    CHILEAN("Chilean"),
    CHINESE("Chinese"),
    COLOMBIAN("Colombian"),
    COMORAN("Comoran"),
    CONGOLESE_CONGO("Congolese (Congo)"),
    CONGOLESE_DRC("Congolese (DRC)"),
    COOK_ISLANDER("Cook Islander"),
    COSTA_RICAN("Costa Rican"),
    CROATIAN("Croatian"),
    CUBAN("Cuban"),
    CYMRAES("Cymraes"),
    CYMRO("Cymro"),
    CYPRIOT("Cypriot"),
    CZECH("Czech"),
    DANISH("Danish"),
    DJIBOUTIAN("Djiboutian"),
    DOMINICAN("Dominican"),
    CITIZEN_OF_THE_DOMINICAN_REPUBLIC("Citizen of the Dominican Republic"),
    DUTCH("Dutch"),
    EAST_TIMORESE("East Timorese"),
    ECUADOREAN("Ecuadorean"),
    EGYPTIAN("Egyptian"),
    EMIRATI("Emirati"),
    ENGLISH("English"),
    EQUATORIAL_GUINEAN("Equatorial Guinean"),
    ERITREAN("Eritrean"),
    ESTONIAN("Estonian"),
    ETHIOPIAN("Ethiopian"),
    FAROESE("Faroese"),
    FIJIAN("Fijian"),
    FILIPINO("Filipino"),
    FINNISH("Finnish"),
    FRENCH("French"),
    GABONESE("Gabonese"),
    GAMBIAN("Gambian"),
    GEORGIAN("Georgian"),
    GERMAN("German"),
    GHANAIAN("Ghanaian"),
    GIBRALTARIAN("Gibraltarian"),
    GREEK("Greek"),
    GREENLANDIC("Greenlandic"),
    GRENADIAN("Grenadian"),
    GUAMANIAN("Guamanian"),
    GUATEMALAN("Guatemalan"),
    CITIZEN_OF_GUINEA_BISSAU("Citizen of Guinea-Bissau"),
    GUINEAN("Guinean"),
    GUYANESE("Guyanese"),
    HAITIAN("Haitian"),
    HONDURAN("Honduran"),
    HONG_KONGER("Hong Konger"),
    HUNGARIAN("Hungarian"),
    ICELANDIC("Icelandic"),
    INDIAN("Indian"),
    INDONESIAN("Indonesian"),
    IRANIAN("Iranian"),
    IRAQI("Iraqi"),
    IRISH("Irish"),
    ISRAELI("Israeli"),
    ITALIAN("Italian"),
    IVORIAN("Ivorian"),
    JAMAICAN("Jamaican"),
    JAPANESE("Japanese"),
    JORDANIAN("Jordanian"),
    KAZAKH("Kazakh"),
    KENYAN("Kenyan"),
    KITTITIAN("Kittitian"),
    CITIZEN_OF_KIRIBATI("Citizen of Kiribati"),
    KOSOVAN("Kosovan"),
    KUWAITI("Kuwaiti"),
    KYRGYZ("Kyrgyz"),
    LAO("Lao"),
    LATVIAN("Latvian"),
    LEBANESE("Lebanese"),
    LIBERIAN("Liberian"),
    LIBYAN("Libyan"),
    LIECHTENSTEIN_CITIZEN("Liechtenstein citizen"),
    LITHUANIAN("Lithuanian"),
    LUXEMBOURGER("Luxembourger"),
    MACANESE("Macanese"),
    MACEDONIAN("Macedonian"),
    MALAGASY("Malagasy"),
    MALAWIAN("Malawian"),
    MALAYSIAN("Malaysian"),
    MALDIVIAN("Maldivian"),
    MALIAN("Malian"),
    MALTESE("Maltese"),
    MARSHALLESE("Marshallese"),
    MARTINIQUAIS("Martiniquais"),
    MAURITANIAN("Mauritanian"),
    MAURITIAN("Mauritian"),
    MEXICAN("Mexican"),
    MICRONESIAN("Micronesian"),
    MOLDOVAN("Moldovan"),
    MONEGASQUE("Monegasque"),
    MONGOLIAN("Mongolian"),
    MONTENEGRIN("Montenegrin"),
    MONTSERRATIAN("Montserratian"),
    MOROCCAN("Moroccan"),
    MOSOTHO("Mosotho"),
    MOZAMBICAN("Mozambican"),
    NAMIBIAN("Namibian"),
    NAURUAN("Nauruan"),
    NEPALESE("Nepalese"),
    NEW_ZEALANDER("New Zealander"),
    NICARAGUAN("Nicaraguan"),
    NIGERIAN("Nigerian"),
    NIGERIEN("Nigerien"),
    NIUEAN("Niuean"),
    NORTH_KOREAN("North Korean"),
    NORTHERN_IRISH("Northern Irish"),
    NORWEGIAN("Norwegian"),
    OMANI("Omani"),
    PAKISTANI("Pakistani"),
    PALAUAN("Palauan"),
    PALESTINIAN("Palestinian"),
    PANAMANIAN("Panamanian"),
    PAPUA_NEW_GUINEAN("Papua New Guinean"),
    PARAGUAYAN("Paraguayan"),
    PERUVIAN("Peruvian"),
    PITCAIRN_ISLANDER("Pitcairn Islander"),
    POLISH("Polish"),
    PORTUGUESE("Portuguese"),
    PRYDEINIG("Prydeinig"),
    PUERTO_RICAN("Puerto Rican"),
    QATARI("Qatari"),
    ROMANIAN("Romanian"),
    RUSSIAN("Russian"),
    RWANDAN("Rwandan"),
    SALVADOREAN("Salvadorean"),
    SAMMARINESE("Sammarinese"),
    SAMOAN("Samoan"),
    SAO_TOMEAN("Sao Tomean"),
    SAUDI_ARABIAN("Saudi Arabian"),
    SCOTTISH("Scottish"),
    SENEGALESE("Senegalese"),
    SERBIAN("Serbian"),
    CITIZEN_OF_SEYCHELLES("Citizen of Seychelles"),
    SIERRA_LEONEAN("Sierra Leonean"),
    SINGAPOREAN("Singaporean"),
    SLOVAK("Slovak"),
    SLOVENIAN("Slovenian"),
    SOLOMON_ISLANDER("Solomon Islander"),
    SOMALI("Somali"),
    SOUTH_AFRICAN("South African"),
    SOUTH_KOREAN("South Korean"),
    SOUTH_SUDANESE("South Sudanese"),
    SPANISH("Spanish"),
    SRI_LANKAN("Sri Lankan"),
    ST_HELENIAN("St Helenian"),
    ST_LUCIAN("St Lucian"),
    SUDANESE("Sudanese"),
    SURINAMESE("Surinamese"),
    SWAZI("Swazi"),
    SWEDISH("Swedish"),
    SWISS("Swiss"),
    SYRIAN("Syrian"),
    TAIWANESE("Taiwanese"),
    TAJIK("Tajik"),
    TANZANIAN("Tanzanian"),
    THAI("Thai"),
    TOGOLESE("Togolese"),
    TONGAN("Tongan"),
    TRINIDADIAN("Trinidadian"),
    TRISTANIAN("Tristanian"),
    TUNISIAN("Tunisian"),
    TURKISH("Turkish"),
    TURKMEN("Turkmen"),
    TURKS_AND_CAICOS_ISLANDER("Turks and Caicos Islander"),
    TUVALUAN("Tuvaluan"),
    UGANDAN("Ugandan"),
    UKRAINIAN("Ukrainian"),
    URUGUAYAN("Uruguayan"),
    UZBEK("Uzbek"),
    VATICAN_CITIZEN("Vatican citizen"),
    CITIZEN_OF_VANUATU("Citizen of Vanuatu"),
    VENEZUELAN("Venezuelan"),
    VIETNAMESE("Vietnamese"),
    VINCENTIAN("Vincentian"),
    WALLISIAN("Wallisian"),
    WELSH("Welsh"),
    YEMENI("Yemeni"),
    ZAMBIAN("Zambian"),
    ZIMBABWEAN("Zimbabwean"),

    @JsonEnumDefaultValue
    UNKNOWN("unknown");

    @JsonValue
    private final String id;

    Nationality(String id) {
        this.id = id;
    }

    @Override
    public String toString() {
        return id;
    }

}



