apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "ia-case-api"
  annotations:
    # This must match folder-name/job-name in Jenkins.
    jenkins.io/job-full-name: cft:HMCTS_d_to_i/ia-case-api
    github.com/project-slug: hmcts/ia-case-api
  tags:
    - java
  links:
    - url: https://hmcts-reform.slack.com/app_redirect?channel=ia-tech
      title: "#ia-tech on Slack"
      icon: chat
spec:
  type: service
  lifecycle: production
  owner: dcd_ia
