detention-facilities:
  addresses:
    Brookhouse:
      building: "Brook House IRC"
      lines:
        - "Perimeter Road South"
        - "London Gatwick Airport"
      townCity: "Gatwick"
      postcode: "RH6 0PQ"
    Addiewell:
      building: "HMP Addiewell"
      lines:
        - "9 Station Road"
      townCity: "Addiewell"
      county: "West Lothian"
      postcode: "EH55 8QA"
    Albany:
      building: "HMP Isle of Wight"
      lines:
        - "Albany House"
      townCity: "Newport"
      postcode: "PO30 5RS"
    Altcourse:
      building: "HMP Altcourse"
      lines:
        - "Brookfield Dr"
        - "Fazakerley"
      townCity: "Liverpool"
      postcode: "L9 7LH"
#  - name: Ashfield
#    address: HMP Ashfield, Shortwood Road, Pucklechurch, Bristol BS16 9QJ
#    note: ''
#  - name: Askham Grange
#    address: HMP/YOI Askham Grange, Askham, Richard, YO23 3FT
#    note: ''
#  - name: Aylesbury
#    address: HMP Aylesbury, Bierton Road, Aylesbury HP20 1EH
#    note: ''
#  - name: Barlinnie
#    address: HMP Barlinnie, 81 Lee Avenue, Riddrie, Glasgow, G33 2QX
#    note: ''
#  - name: Bedford
#    address: HMP Bedford, St Loyes St, Bedford MK40 1HG
#    note: ''
#  - name: Bella Centre
#    address: Bella Centre, 81 Ann Street, Dundee, DD3 7TF
#    note: Community Custody Units (CCU)
#  - name: Belmarsh
#    address: HMP Belmarsh, Western Way, Thamesmead, London, SE28 0EB
#    note: ''
#  - name: Berwyn
#    address: HMP Berwyn, Bridge Road, Wrexham Industrial Estate, Wrexham, North
#      Wales, LL13 9QE
#    note: ''
#  - name: Birmingham
#    address: HMP Birmingham, Winson Green Road, Birmingham, B18 4AS
#    note: ''
#  - name: Brinsford
#    address: HMP Brinsford, New Road, Featherstone, Wolverhampton WV10 7PY
#    note: ''
#  - name: Bristol
#    address: HMP Bristol, 19 Cambridge Road, Bishopston, Bristol, BS7 8PS
#    note: ''
#  - name: Brixton
#    address: HMP Brixton, Jebb Ave, Brixton Hill, London, SW2 5XF
#    note: ''
#  - name: Bronzefield
#    address: HMP Bronzefield, Woodthorpe Road, Ashford, Middlesex, TW15 3JZ
#    note: ''
#  - name: Buckley Hall
#    address: HMP Buckley Hall, Buckley Farm Lane, Rochdale OL12 9DW
#    note: ''
#  - name: Bullingdon
#    address: HMP Bullingdon, Patrick Haugh Road, Bicester OX25 1PZ
#    note: ''
#  - name: Bure
#    address: HMP Bure, Jaguar Drive, Badersfield, Norwich NR10 5GB
#    note: ''
#  - name: Cardiff
#    address: HMP Cardiff, Knox Road, Cardiff CF24 0UG
#    note: ''
#  - name: Castle Huntly
#    address: HMP Castle Huntly, Longforgan, Nr Dundee, DD2 5HL
#    note: ''
#  - name: Channings Wood
#    address: HMP Channings Wood, Denbury, Newton Abbot, Devon,TQ12 6DW
#    note: ''
#  - name: Chelmsford
#    address: HMP/YOI Chelmsford, 200 Springfield Road, Chelmsford, Essex, CM2
#      6LQ
#    note: ''
#  - name: Coldingley
#    address: HMP Coldingley, Shaftesbury Road, Bisley, Woking, Surrey, GU24 9EX
#    note: ''
#  - name: Cookham Wood
#    address: HMP Cookham Wood, Sir Evelyn Road, Rochester, Kent, ME1 3LU
#    note: ''
#  - name: Dartmoor
#    address: HMP Dartmoor, Tavistock Rd, Princetown, Yelverton PL20 6RR
#    note: ''
#  - name: Deerbolt
#    address: HMP/YOI Deerbolt, Bowes Road, Barnard Castle, County Durham, DL12
#      9BG
#    note: ''
#  - name: Doncaster
#    address: HMP & YOI Doncaster, Marsh Gate, Doncaster DN5 8UX
#    note: ''
#  - name: Dovegate
#    address: HMP Dovegate, Uttoxeter, Staffordshire, ST14 8XR
#    note: ''
#  - name: Downview
#    address: HMP/YOI Downview, Sutton Lane, Sutton, Surrey, SM2 5PD
#    note: ''
#  - name: Drake Hall
#    address: HMP/YOI Drake Hall, Eccleshall, Staffordshire, ST21 6LQ
#    note: ''
#  - name: Dumfries
#    address: HMP Dumfries, Terregles Street, Dumfries, DG2 9AX
#    note: ''
#  - name: Durham
#    address: HMP Durham, Old Elvet, Durham, DH1 3HU
#    note: ''
#  - name: East Sutton Park
#    address: HMP/YOI East Sutton Park, Sutton Valence, Maidstone, Kent, ME17
#      3DF
#    note: ''
#  - name: Eastwood Park
#    address: HMP/YOI Eastwood Park, Falfield, Wotton-under-Edge, Gloucestershire,
#      GL12 8DB
#    note: ''
#  - name: Edinburgh
#    address: HMP Edinburgh, 33 Stenhouse Road, Edinburgh, EH11 3LN
#    note: ''
#  - name: Elmley
#    address: HMP/YOI Elmley, Church Road, Eastchurch, Sheerness, Kent, ME12 4DZ
#    note: ''
#  - name: Erlestoke
#    address: HMP Erlestoke, Erlestoke, Devizes, Wiltshire, SN10 5TU
#    note: ''
#  - name: Exeter
#    address: HMP Exeter, 30 New North Road, Exeter, EX4 4EX
#    note: ''
#  - name: Featherstone
#    address: HMP Featherstone, New Road, Featherstone, Wolverhampton, WV10 7PU
#    note: ''
#  - name: Feltham
#    address: HMP/YOI Feltham, Bedfont Road, Feltham, Middlesex, TW13 4ND
#    note: ''
#  - name: Five Wells
#    address: HMP Five Wells Prison,  Doddington Rd, Wellingborough, NN8 2NG
#    note: ''
#  - name: Ford
#    address: HMP Ford, Arundel, West Sussex, BN18 0BX
#    note: ''
#  - name: Forest Bank
#    address: HMP Forest Bank, Agecroft Road, Pendlebury, Manchester M27 8FB
#    note: ''
#  - name: Fosse Way
#    address: HMP Fosse Way, 1 Tigers Road, Glen Parva, Wigston, LE18 4WS
#    note: ''
#  - name: Foston Hall
#    address: HMP/YOI Foston Hall, Foston, Derby, Derbyshire, DE65 5DN
#    note: ''
#  - name: Frankland
#    address: HMP Frankland, Business Hub,  Brasside,Durham, DH1 5YD
#    note: ''
#  - name: Full Sutton
#    address: HMP Full Sutton, Moor Lane, Full Sutton, York, YO41 1PS
#    note: ''
#  - name: Garth
#    address: HMP Garth, Ulnes Walton, Leyland, Preston, PR26 8NE
#    note: ''
#  - name: Gartree
#    address: HMP Gartree, Gallow Field Road, Market Harborough, Leicestershire,
#      LE16 7RP
#    note: ''
#  - name: Glenochil
#    address: HMP Glenochil, King O Muir Road, Tullibody, Clackmannanshire, FK10
#      3AD
#    note: ''
#  - name: Grampian
#    address: HMP & YOI Grampian, South Road, Peterhead, AB42 2YY
#    note: ''
#  - name: Greenock
#    address: HMP Greenock, Old Inverkip Road, Greenock, PA16 9AJ
#    note: ''
#  - name: Grendon/Spring Hill
#    address: HMP Grendon, Grendon Underwood, Buckinghamshire, HP18 0TL
#    note: ''
#  - name: Guys Marsh
#    address: HMP Guys Marsh, Shaftesbury, Dorset, SP7 0AH
#    note: ''
#  - name: Hatfield (Main site)
#    address: HMP/YOI Hatfield (Main site), Thorne Road, Hatfield, Doncaster,
#      South Yorkshire, DN7 6EL
#    note: ''
#  - name: Hatfield (Lakes site)
#    address: HMP/YOI Hatfield (Lakes site), Lancaster Drive, Lindholme, Doncaster,
#      South Yorkshire, DN7 6FA
#    note: ''
#  - name: Haverigg
#    address: HMP Haverigg, North Lane, Millom, LA18 4NA
#    note: ''
#  - name: Hewell Prison
#    address: HMP Hewell, Hewell Lane, Redditch, Worcestershire, B97 6QS
#    note: ''
#  - name: High Down
#    address: HMP/YOI High Down, High Down Lane, Sutton, Surrey, SM2 5PJ
#    note: ''
#  - name: Highpoint
#    address: HMP Highpoint, Stradishall, Newmarket, Suffolk, CB8 9YG
#    note: ''
#  - name: Hindley
#    address: HMP/YOI Hindley, Barracks Road, Bickershaw, Wigan, WN2 5TH
#    note: ''
#  - name: Hollesley Bay
#    address: HMP/YOI Hollesley Bay, Rectory Road, Woodbridge, Suffolk, IP12 3JW
#    note: ''
#  - name: Holme House
#    address: HMP Holme House, Holme House Road, Stockton on Tees, TS18 2QU
#    note: ''
#  - name: Hull
#    address: HMP Hull, Hedon Road, Hull, HU9 5LS
#    note: ''
#  - name: Humber
#    address: HMP Humber, Sands Lane, Brough, East Yorkshire, HU15 2JZ
#    note: ''
#  - name: Huntercombe
#    address: HMP Huntercombe, Nuffield, Henley-on-Thames, Oxfordshire, RG9 5SB
#    note: ''
#  - name: Hydebank Wood
#    address: Hydebank Wood College, Hydebank Wood, Belfast, BT8 8NA
#    note: ''
#  - name: Inverness
#    address: HM Prison Inverness, Duffy Drive, Inverness, IV2 3HH
#    note: ''
#  - name: Isis
#    address: HMP/YOI Isis, Western Way, Thamesmead, SE28 0NZ
#    note: ''
#  - name: Isle of Wight
#    address: HMP Isle of Wight, Albany House, Newport, Isle of Wight, PO30 5RS
#    note: ''
#  - name: Kilmarnock
#    address: HMP Kilmarnock, Mauchline Road, Kilmarnock, KA1 5AA
#    note: ''
#  - name: Kirkham
#    address: HMP Kirkham, Freckleton Road, Kirkham, Preston, Lancashire, PR4
#      2RN
#    note: ''
#  - name: Kirklevington Grange
#    address: HMP Kirklevington Grange, Yarm, Cleveland, TS15 9PA
#    note: ''
#  - name: Lancaster Farms
#    address: HMP Lancaster Farms, Stone Row Head, Off Quernmore Road, Lancaster,
#      LA1 3QZ
#    note: ''
#  - name: Leeds
#    address: HMP Leeds, 2 Gloucester Terrace, Stanningley Road, Leeds, West Yorkshire,
#      LS12 2TJ
#    note: ''
#  - name: Leicester
#    address: HMP Leicester, 116 Welford Road, Leicester, LE2 7AJ
#    note: ''
#  - name: Lewes
#    address: HMP/YOI Lewes, 1 Brighton Road, Lewes, East Sussex, BN7 1EA
#    note: ''
#  - name: Leyhill
#    address: HMP Leyhill, Wotton-under-Edge, Gloucester, GL12 8BT
#    note: ''
#  - name: Lilias Centre
#    address: Lilias Centre, 41 Shawpark Street, Maryhill, Glasgow, G20 9DR
#    note: Community Custody Units (CCU)
#  - name: Lincoln
#    address: HMP/YOI Lincoln, Greetwell Road, Lincoln, LN2 4BD
#    note: ''
#  - name: Lindholme
#    address: HMP Lindholme, Bawtry Road, Hatfield, Doncaster, DN7 6EE
#    note: ''
#  - name: Littlehey
#    address: HMP Littlehey, Perry, Huntingdon, Cambridgeshire, PE28 0SR
#    note: ''
#  - name: Liverpool
#    address: HMP Liverpool, 68 Hornby Road, Liverpool, L9 3DF
#    note: ''
#  - name: Long Lartin
#    address: HMP Long Lartin, South Littleton, Evesham, Worcestershire, WR11
#      8TZ
#    note: ''
#  - name: Low Moss
#    address: HMP Low Moss, Crosshill Road, Bishopbriggs, Glasgow, G64 2QB
#    note: ''
#  - name: Low Newton
#    address: HMP/YOI Low Newton, Brasside, Durham, DH1 5YA
#    note: ''
#  - name: Lowdham Grange
#    address: HMP Lowdham Grange, Old Epperstone Road, Lowdham, Nottingham, NG14
#      7DA
#    note: ''
#  - name: Magilligan
#    address: HMP Magilligan, Point Road, Londonderry, Limavady BT49 0LR
#    note: ''
#  - name: Maghaberry
#    address: HMP Maghaberry, Old Road, Ballinderry Upper, Lisburn, BT28 2PT
#    note: ''
#  - name: Maidstone
#    address: HMP Maidstone, 36 County Road, Maidstone, Kent, ME14 1UZ
#    note: ''
#  - name: Manchester
#    address: HMP Manchester, 1 Southall Street, Manchester, M60 9AH
#    note: ''
#  - name: Moorland
#    address: HMP/YOI Moorland, Bawtry Road, Hatfield Woodhouse, Doncaster, South
#      Yorkshire, DN7 6BW
#    note: ''
#  - name: Morton Hall
#    address: HMP Morton Hall, Swinderby, Lincoln, LN6 9PT
#    note: ''
#  - name: New Hall
#    address: HMP/YOI New Hall, Dial Wood, Flockton, Wakefield, West Yorkshire,
#      WF4 4XX
#    note: ''
#  - name: North Sea Camp
#    address: HMP North Sea Camp, Croppers Lane, Freiston, Boston, Lincolnshire,
#      PE22 0QX
#    note: ''
#  - name: Northumberland
#    address: HMP Northumberland, Wansbeck Rd, Morpeth NE65 9XG
#    note: ''
#  - name: Norwich
#    address: HMP/YOI Norwich, Knox Road, Norwich, Norfolk, NR1 4LU
#    note: ''
#  - name: Nottingham
#    address: HMP Nottingham, Perry Road, Sherwood, Nottingham, NG5 3AG
#    note: ''
#  - name: Oakwood
#    address: HMP Oakwood, Oaks Drive, Featherstone, West Midlands, WV10 7QD
#    note: ''
#  - name: Onley
#    address: HMP Onley, Rugby, Warwickshire, CV23 8AP
#    note: ''
#  - name: Parc
#    address: HMP/YOI Parc, Heol Hopcyn John, Coety, Pen-y-bont ar Ogwr, Bridgend,
#      CF35 6AP
#    note: ''
#  - name: Pentonville
#    address: HMP/YOI Pentonville, Caledonian Road, London, N7 8TT
#    note: ''
#  - name: Perth
#    address: HMP Peth, 3 Edinburgh Road, Perth, PH2 8AT
#    note: ''
#  - name: Peterborough
#    address: HMP Peterborough, Saville Road, Peterborough, PE3 7PD
#    note: ''
#  - name: Polmont
#    address: HMP Polmont, Redding Road, Brightons, Falkirk, FK2 0AB
#    note: ''
#  - name: Portland
#    address: HMP/YOI Portland, 104 The Grove, Easton, Portland, Dorset, DT5 1DL
#    note: ''
#  - name: Prescoed
#    address: HMP Prescoed, Coed-y-Paen, Pontypool, Monmouthshire, NP4 0TB
#    note: ''
#  - name: Preston
#    address: HMP Preston, 2 Ribbleton Lane, Preston, Lancashire, PR1 5AB
#    note: ''
#  - name: Ranby
#    address: HMP Ranby, Retford, Nottingham, DN22 8EU
#    note: ''
#  - name: Risley
#    address: HMP Risley, Warrington Road, Risley, Warrington, Cheshire, WA3 6BP
#    note: ''
#  - name: Rochester
#    address: HMP/YOI Rochester, 1 Fort Road, Rochester, Kent, ME1 3QS
#    note: ''
#  - name: Rye Hill
#    address: HMP Rye Hill, Willoughby, Rugby, CV23 8SZ
#    note: ''
#  - name: Send
#    address: HMP Send, Ripley Road, Woking, Surrey, GU23 7LJ
#    note: ''
#  - name: Shotts
#    address: HMP Shotts, Canthill Road, Shotts, ML7 4LE
#    note: ''
#  - name: Spring Hill / Grendon
#    address: HMP Spring Hill, Grendon Underwood, Buckinghamshire, HP18 0TL
#    note: ''
#  - name: Stafford
#    address: HMP Stafford, 54 Gaol Road, Stafford, Staffordshire, ST16 3AW
#    note: ''
#  - name: Standford Hill
#    address: HMP Standford Hill, Church Road, Eastchurch, Sheerness, Kent, ME12
#      4AA
#    note: ''
#  - name: Stirling
#    address: HMP YOI Stirling, Stirling, FK9 5NU
#    note: ''
#  - name: Stocken
#    address: HMP Stocken, Stocken Hall Road, Stretton, Nr Oakham, Rutland, LE15
#      7RD
#    note: ''
#  - name: Stoke Heath
#    address: HMP/YOI Stoke Heath, Market Drayton, Shropshire, TF9 2JL
#    note: ''
#  - name: Styal
#    address: HMP/YOI Styal, Wilmslow, Cheshire, SK9 4HR
#    note: ''
#  - name: Sudbury
#    address: HMP Sudbury, Nr Ashbourne, Derbyshire, DE6 5HW
#    note: ''
#  - name: Swaleside
#    address: HMP Swaleside, Brabazon Road, Eastchurch, Isle of Sheppey, Kent,
#      ME12 4AX
#    note: ''
#  - name: Swansea
#    address: HMP Swansea, 200 Oystermouth Road, Swansea, SA1 3SR
#    note: ''
#  - name: Swinfen Hall
#    address: HMP/YOI Swinfen Hall, Swinfen Hall, Lichfield, Staffordshire, WS14
#      9QS
#    note: ''
#  - name: Thameside
#    address: HMP Thameside, Griffin Manorway, London, SE28 0FJ
#    note: ''
#  - name: The Mount
#    address: HMP The Mount, Molyneaux Avenue, Bovingdon, Hemel Hempstead, Hertfordshire,
#      HP3 0NZ
#    note: ''
#  - name: The Verne
#    address: HMP The Verne, Verne Common Road, Portland, Dorset, DT5 1EQ
#    note: ''
#  - name: Thorn Cross
#    address: HMP/YOI Thorn Cross, Arley Road, Appleton Thorn, Warrington, Cheshire,
#      WA4 4RL
#    note: ''
#  - name: Usk
#    address: HMP Usk, 47 Maryport Street, Usk, Monmouthshire, NP15 1XP
#    note: ''
#  - name: Wakefield
#    address: HMP Wakefield, 5 Love Lane, Wakefield, West Yorkshire, WF2 9AG
#    note: ''
#  - name: Wandsworth
#    address: HMP Wandsworth, PO Box 757, Heathfield Road, Wandsworth, London,
#      SW18 3HS
#    note: ''
#  - name: Warren Hill
#    address: HMP Warren Hill, Grove Road, Hollesley, Woodbridge, Suffolk, IP12
#      3BF
#    note: ''
#  - name: Wayland
#    address: HMP Wayland, Griston, Thetford, Norfolk, IP25 6RL
#    note: ''
#  - name: Wealstun
#    address: HMP Wealstun, Church Causeway, Thorp Arch, Wetherby, Yorkshire,
#      LS23 7AZ
#    note: ''
#  - name: Werrington
#    address: HMYOI Werrington, Ash Bank Road, Werrington, Stoke-On-Trent, ST9
#      0DX
#    note: ''
#  - name: Wetherby
#    address: HMYOI Wetherby, York Road, Wetherby, West Yorkshire, LS22 5ED
#    note: ''
#  - name: Whatton
#    address: HMP Whatton, New Lane, Whatton, Nottingham, NG13 9FQ
#    note: ''
#  - name: Whitemoor
#    address: HMP Whitemoor, Longhill Road, March, Cambridgeshire, PE15 0PR
#    note: ''
#  - name: Winchester
#    address: HMP/YOI Winchester, Romsey Road, Winchester, SO22 5DF
#    note: ''
#  - name: Woodhill
#    address: HMP/YOI Woodhill, Tattenhoe Street, Milton Keynes, Buckinghamshire,
#      MK4 4DA
#    note: ''
#  - name: Wormwood Scrubs
#    address: HMP Wormwood Scrubs, PO Box 757, Du Cane Road, London, W12 0AE
#    note: ''
#  - name: Wymott
#    address: HMP Wymott, Ulnes Walton Lane, Leyland, Preston, Lancashire, PR26
#      8LW
#    note: ''
#
