package uk.gov.hmcts.reform.iacaseapi.ccd.access;

import com.google.common.collect.HashMultimap;
import com.google.common.collect.SetMultimap;
import uk.gov.hmcts.ccd.sdk.api.HasAccessControl;
import uk.gov.hmcts.ccd.sdk.api.HasRole;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter from AuthorisationCaseField — do not edit by hand.
 */
public class IaAdmofficerRPlus12RolesJhrvliAccess implements HasAccessControl {
    @Override
    public SetMultimap<HasRole, Permission> getGrants() {
        SetMultimap<HasRole, Permission> grants = HashMultimap.create();
        grants.put(UserRole.CASEWORKER_IA_ADMOFFICER, Permission.R);
        grants.put(UserRole.CASEWORKER_IA_CASEOFFICER, Permission.R);
        grants.put(UserRole.CASEWORKER_IA_HOMEOFFICEAPC, Permission.R);
        grants.put(UserRole.CASEWORKER_IA_HOMEOFFICELART, Permission.R);
        grants.put(UserRole.CASEWORKER_IA_HOMEOFFICEPOU, Permission.R);
        grants.put(UserRole.CASEWORKER_IA_IACJUDGE, Permission.R);
        grants.put(UserRole.CASEWORKER_IA_LEGALREP_SOLICITOR, Permission.R);
        grants.put(UserRole.CASEWORKER_IA_RESPONDENTOFFICER, Permission.R);
        grants.put(UserRole.CASEWORKER_IA_SYSTEM, Permission.C);
        grants.put(UserRole.CASEWORKER_IA_SYSTEM, Permission.R);
        grants.put(UserRole.CASEWORKER_IA_SYSTEM, Permission.U);
        grants.put(UserRole.CASEWORKER_IA_SYSTEM, Permission.D);
        grants.put(UserRole.CASEWORKER_WA_TASK_CONFIGURATION, Permission.C);
        grants.put(UserRole.CASEWORKER_WA_TASK_CONFIGURATION, Permission.R);
        grants.put(UserRole.CASEWORKER_WA_TASK_CONFIGURATION, Permission.U);
        grants.put(UserRole.CASEWORKER_WA_TASK_CONFIGURATION, Permission.D);
        grants.put(UserRole.CITIZEN, Permission.R);
        grants.put(UserRole.IA_SPECIFIC_ACCESS_JUDGE_PROFILE, Permission.R);
        grants.put(UserRole.IA_SPECIFIC_ACCESS_LEGAL_OPS_PROFILE, Permission.R);
        return grants;
    }
}
