package uk.gov.hmcts.reform.iacaseapi.ccd.access;

import com.google.common.collect.HashMultimap;
import com.google.common.collect.SetMultimap;
import uk.gov.hmcts.ccd.sdk.api.HasAccessControl;
import uk.gov.hmcts.ccd.sdk.api.HasRole;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter from AuthorisationCaseField — do not edit by hand.
 */
public class IaSpecificAccessAdminProfileCrudPlus2RolesPehjvmAccess implements HasAccessControl {
    @Override
    public SetMultimap<HasRole, Permission> getGrants() {
        SetMultimap<HasRole, Permission> grants = HashMultimap.create();
        grants.put(UserRole.IA_SPECIFIC_ACCESS_ADMIN_PROFILE, Permission.C);
        grants.put(UserRole.IA_SPECIFIC_ACCESS_ADMIN_PROFILE, Permission.R);
        grants.put(UserRole.IA_SPECIFIC_ACCESS_ADMIN_PROFILE, Permission.U);
        grants.put(UserRole.IA_SPECIFIC_ACCESS_ADMIN_PROFILE, Permission.D);
        grants.put(UserRole.IA_SPECIFIC_ACCESS_CTSC_PROFILE, Permission.C);
        grants.put(UserRole.IA_SPECIFIC_ACCESS_CTSC_PROFILE, Permission.U);
        grants.put(UserRole.IA_SPECIFIC_ACCESS_CTSC_PROFILE, Permission.D);
        grants.put(UserRole.IA_SPECIFIC_ACCESS_LEGAL_OPS_PROFILE, Permission.C);
        grants.put(UserRole.IA_SPECIFIC_ACCESS_LEGAL_OPS_PROFILE, Permission.R);
        grants.put(UserRole.IA_SPECIFIC_ACCESS_LEGAL_OPS_PROFILE, Permission.U);
        grants.put(UserRole.IA_SPECIFIC_ACCESS_LEGAL_OPS_PROFILE, Permission.D);
        return grants;
    }
}
