package uk.gov.hmcts.reform.iacaseapi.domain.entities.homeoffice;

import lombok.Getter;

import java.util.Arrays;

@Getter
public enum HomeOfficeLanguage {
    // These values are given by the Home Office so contact them if any are found to be missing in future
    AFG("AFG", "Afghan"),
    AFR("AFR", "Afrikaans"),
    AKA("AKA", "Akan"),
    AKI("AKI", "Akim"),
    AKP("AKP", "Akpafu"),
    AKU("AKU", "Akuapem"),
    ALB("ALB", "Albanian"),
    AMH("AMH", "Amharic"),
    ARAB("ARAB", "Arabic"),
    ARAAL("ARAAL", "Algerian"),
    ARABE("ARABE", "Arabic - Egyptian"),
    ARABG("ARABG", "Arabic - Middle Eastern"),
    ARABL("ARABL", "Arabic - Levantine"),
    ARABM("ARABM", "Arabic - Maghrebi"),
    ARANA("ARANA", "Arabic - North African"),
    ARABSU("ARABSU", "Arabic - Sudanese"),
    ARABS("ARABS", "Arabic - Syrian"),
    ARM("ARM", "Armenian"),
    ASH("ASH", "Ashanti"),
    ASSAM("ASSAM", "Assamese (ISC)"),
    ASS("ASS", "Assyrian"),
    AZE("AZE", "Azeri - North"),
    BADN("BADN", "Badnani"),
    BALU("BALU", "Balochi"),
    BAM("BAM", "Bambara"),
    BASA("BASA", "Basa"),
    BEL("BEL", "Belarusian"),
    BEMBA("BEMBA", "Bemba"),
    BENG("BENG", "Bengali"),
    BERB("BERB", "Berber"),
    BYN("BYN", "Bilen"),
    BISL("BISL", "Bislama"),
    BRAV("BRAV", "Bravanese"),
    BRO("BRO", "Brong"),
    BUEM("BUEM", "Buem"),
    BUG("BUG", "Bugandan (UGA)"),
    BUL("BUL", "Bulgarian"),
    BRM("BRM", "Burmese"),
    CAN("CAN", "Cantonese"),
    CHA("CHA", "Chagga"),
    CHE("CHE", "Chewa"),
    CHIC("CHIC", "Chichewa"),
    CHN("CHN", "Chinese"),
    CHIN("CHIN", "Chinyanja"),
    CHOW("CHOW", "Chaozhou"),
    CRE("CRE", "Creole"),
    CZ("CZ", "Czech"),
    DAG("DAG", "Dagbani"),
    DAN("DAN", "Danish"),
    DAR("DAR", "Dari"),
    DHI("DHI", "Dhivehi"),
    DYU("DYU", "Dioula"),
    DU("DU", "Dutch"),
    EBO("EBO", "Ebo"),
    EDB("EDB", "Edbado"),
    EDO("EDO", "Edo"),
    ENG("ENG", "English"),
    ERI("ERI", "Eritrean"),
    ISH("ISH", "Esan"),
    ESP("ESP", "Esperanto"),
    EST("EST", "Estonian"),
    EWE("EWE", "Ewe (ANLO)"),
    FAN("FAN", "Fanti (GHA)"),
    FAR("FAR", "Farsi"),
    FELLI("FELLI", "Felli"),
    FIN("FIN", "Finnish"),
    FR("FR", "French"),
    FRE_NA("FRE- NA", "French North African"),
    FRE_OTHER("FRE- OTHER", "French Other"),
    FUCH("FUCH", "Fuchow"),
    FUKI("FUKI", "Fukienese"),
    FULA("FULA", "Fula (SLE)"),
    FULANI("FULANI", "Fulani"),
    FULLA("FULLA", "Fulla"),
    GA("GA", "Ga (GHA)"),
    GAM("GAM", "Gambian"),
    GEORG("GEORG", "Georgian"),
    GER("GER", "German"),
    GHE("GHE", "Gheg"),
    GOR("GOR", "Gorani"),
    GR("GR", "Greek"),
    GUJ("GUJ", "Gujarati"),
    HAK("HAK", "Hakka"),
    HAU("HAU", "Hausa"),
    HEB("HEB", "Hebrew"),
    HINDI("HINDI", "Hindi"),
    HINDKU("HINDKU", "Hindko"),
    HOKIAN("HOKIAN", "Hokian"),
    HOK("HOK", "Hokkien"),
    HUN("HUN", "Hungarian"),
    IBO("IBO", "Ibo"),
    ICE("ICE", "Icelandic"),
    IGBO("IGBO", "Igbo"),
    IJE("IJE", "Ijebu"),
    ILO("ILO", "Ilocano"),
    IDO("IDO", "Indonesian"),
    IRI("IRI", "Irish"),
    IT("IT", "Italian"),
    JAP("JAP", "Japanese"),
    KHA("KHA", "Kalanga"),
    KHM("KHM", "Khmer"),
    KIBA("KIBA", "Kibajuni"),
    KIB("KIB", "Kibosho"),
    KIK("KIK", "Kikongo (ANG)"),
    KIKU("KIKU", "Kikuyu"),
    KIL("KIL", "Kilema"),
    KIN("KIN", "Kinyarwanda"),
    KIRM("KIRM", "Kirmanji"),
    KIR("KIR", "Kirundi"),
    KIS("KIS", "Kiswahili"),
    KISO("KISO", "Kisonge"),
    KON("KON", "Konkani"),
    KOR("KOR", "Korean"),
    KPE("KPE", "Kpelle"),
    KRIO("KRIO", "Krio"),
    KUR("KUR", "Kurdish"),
    KURTK("KURTK", "Kurdish - Kurmanji (TUR)"),
    KURBA("KURBA", "Kurdish - Bahdini"),
    KURDKI("KURDKI", "Kurdish - Kurmanji"),
    KURDSO("KURDSO", "Kurdish - Sorani"),
    KUT("KUT", "Kutchi (ISC)"),
    LAN("LAN", "Lango"),
    LAO("LAO", "Laotian"),
    LAT("LAT", "Latin"),
    LAV("LAV", "Latvian"),
    LIN("LIN", "Lingala (ZAI)"),
    LITH("LITH", "Lithuanian"),
    LOL("LOL", "Lolobi"),
    LUBA("LUBA", "Luba"),
    LUF("LUF", "Lufumbria"),
    LUG("LUG", "Lugandan (UGA)"),
    LUGI("LUGI", "Lugika"),
    LUH("LUH", "Luhya"),
    LUN("LUN", "Lunywatwanda"),
    LUO("LUO", "Luo (UGA)"),
    LUS("LUS", "Lusoga"),
    LWO("LWO", "Lwo"),
    MAC("MAC", "Macedonian"),
    MACH("MACH", "Machame"),
    MAK("MAK", "Makinke"),
    MYA("MYA", "Malay"),
    MLM("MLM", "Malayalam (ISC)"),
    MTA("MTA", "Maltese"),
    MAN("MAN", "Mandarin"),
    MAND("MAND", "Mandinka"),
    MANO("MANO", "Mandingo"),
    MARA("MARA", "Marangu"),
    MAR("MAR", "Marathi (ISC)"),
    MEN("MEN", "Mende"),
    MER("MER", "Mercan"),
    MERI("MERI", "Meru"),
    MON("MON", "Mongolian"),
    NDE("NDE", "Ndebele"),
    NEP("NEP", "Nepali"),
    NGALA("NGALA", "Ngala (ANG)"),
    NOR("NOR", "Norwegian"),
    NS("NS", "Not Specified"),
    NYA("NYA", "Nyanja"),
    OROMO("OROMO", "Oromo"),
    OUA("OUA", "Ouolof"),
    PAH("PAH", "Pahari"),
    PAM("PAM", "Pampango"),
    PAN("PAN", "Pangasinan"),
    PID_LIB("PID - LIB", "Pidgin English - Liberian"),
    PID_YOR("PID - YOR", "Pidgin English - West African"),
    POL("POL", "Polish"),
    PA("PA", "Portuguese Angolan"),
    POR("POR", "Portuguese European"),
    PTM("PTM", "Portuguese - Mozambique Guinea Bissau"),
    PTB("PTB", "Portuguese - South American"),
    POT("POT", "Potwari"),
    PUN("PUN", "Punjabi - Indian"),
    PUS("PUS", "Pashto"),
    REM("REM", "Remo"),
    ROM("ROM", "Romanian"),
    ROMANY("ROMANY", "Romany"),
    RUK("RUK", "Rukiga"),
    RUN("RUN", "Runyankole"),
    RUNYO("RUNYO", "Runyoro"),
    RUSS("RUSS", "Russian"),
    RUT("RUT", "Rutooro"),
    SEN("SEN", "Senegalese"),
    SER("SER", "Serahula"),
    SERB("SERB", "Serbo-Croat"),
    SES("SES", "Sesotho"),
    SHA("SHA", "Shanghainese"),
    SHO("SHO", "Shona"),
    SIGN("SIGN", "Sign Language - British"),
    SIND("SIND", "Sindhi"),
    SINH("SINH", "Sinhala"),
    SINL("SINL", "Sinhalese"),
    SLO("SLO", "Slovak"),
    SLOV("SLOV", "Slovene"),
    SOM("SOM", "Somali"),
    SOR("SOR", "Sorani"),
    SOT("SOT", "Sotho"),
    SP("SP", "Spanish"),
    SPL("SPL", "Spanish - Latin America"),
    SUS("SUS", "Susu"),
    SWA("SWA", "Swahili"),
    SWD("SWD", "Swedish"),
    TAG("TAG", "Tagalog"),
    TAM("TAM", "Tamil"),
    TEMME("TEMME", "Teme"),
    TEMNE("TEMNE", "Temne"),
    TEO("TEO", "Teochew"),
    THAI("THAI", "Thai"),
    TBT("TBT", "Tibetan"),
    TIG("TIG", "Tigre"),
    TIGR("TIGR", "Tigrean (SOM)"),
    TIGN("TIGN", "Tigrinian (SOM)"),
    TON("TON", "Tongan"),
    TOS("TOS", "Tosk"),
    TK("TK", "Turkish"),
    TURKM("TURKM", "Turkmen"),
    TWI("TWI", "Twi"),
    UKR("UKR", "Ukrainian"),
    UKW("UKW", "Ukwuani"),
    ICWUNKNOWN("ICWUNKNOWN", "Unknown"),
    URDU("URDU", "Urdu"),
    URH("URH", "Urhobo"),
    UZBEK("UZBEK", "Uzbek"),
    VIET("VIET", "Vietnamese"),
    WAL("WAL", "Walof"),
    WOL("WOL", "Wolof"),
    XHO("XHO", "Xhosa"),
    YIDD("YIDD", "Yiddish"),
    YOR("YOR", "Yoruba"),
    ZU("ZU", "Zulu"),
    ACH("ACH", "Acholi"),
    ANY("ANY", "Anyuak"),
    BEMBE("BEMBE", "Bembe"),
    CHALNA("CHALNA", "Chaldean - Neo Aramaic"),
    DINKNE("DINKNE", "Dinka - North Eastern"),
    DINKSE("DINKSE", "Dinka - South Eastern"),
    FULI("FULI", "Fuliiru Kifulero"),
    HAROE("HAROE", "Harar (Oromo Eastern)"),
    HEMA("HEMA", "Hema"),
    KINY("KINY", "Kinyabuisha"),
    LEGAM("LEGAM", "Lega - Mwenga"),
    LINGALA("LINGALA", "Lingala"),
    MASHI("MASHI", "Mashi"),
    NUER("NUER", "Nuer"),
    OROMBA("OROMBA", "Oromo Borana-arsi-guji"),
    OROMWC("OROMWC", "Oromo W Central"),
    TIGRIN("TIGRIN", "Tigrinya"),
    BANGLA("BANGLA", "Bangla"),
    CRIOFULLA("CRIOFULLA", "Crio - Fulla"),
    CHECHEN("CHECHEN", "Chechen"),
    KARAMAJONG("KARAMAJONG", "Karamajong"),
    PASHAI("PASHAI", "Pashai"),
    MORO("MORO", "Moro"),
    AFAR("AFAR", "Afar"),
    ARMEAST("ARMEAST", "Armenian - Eastern"),
    ARMWEST("ARMWEST", "Armenian - Western"),
    AYM("AYM", "Aymara"),
    AZES("AZES", "Azeri - South"),
    BENAD("BENAD", "Benadiri"),
    BOSN("BOSN", "Bosnian"),
    CHNTAI("CHNTAI", "Chinese - Taiwanese"),
    CEBU("CEBU", "Cebuano"),
    CREMAU("CREMAU", "Creole - Mauritian"),
    CRESIE("CRESIE", "Creole - Sierra Leone"),
    CROA("CROA", "Croatian"),
    DAVA("DAVA", "Davaweno"),
    DEAFBL("DEAFBL", "Deafblind"),
    DOG("DOG", "Dogri"),
    FILI("FILI", "Filipino"),
    FLEM("FLEM", "Flemish"),
    FUJI("FUJI", "Fujian"),
    GUAR("GUAR", "Guarani"),
    HAZA("HAZA", "Hazaragi"),
    KASH("KASH", "Kashmiri"),
    KAZA("KAZA", "Kazakh"),
    KIKLAADI("KIKLAADI", "Kikongo - LaadiI"),
    KINYKINYAM("KINYKINYAM", "Kinyarwanda - Kinyamulenge"),
    KIRG("KIRG", "Kirgiz"),
    KISSI("KISSI", "Kissi"),
    KIYO("KIYO", "Kiyombe"),
    KURFEIL("KURFEIL", "Kurdish - Feili"),
    KURGOR("KURGOR", "Kurdish - Gorani"),
    KURHAW("KURHAW", "Kurdish - Hawrami"),
    KURSYR("KURSYR", "Kurdish - Kurmanji (SYR)"),
    KITU("KITU", "Kituba"),
    KYERE("KYERE", "Kyerepong"),
    LARI("LARI", "Lari"),
    MAIT("MAIT", "Maithili"),
    MALIN("MALIN", "Malinke"),
    MIRP("MIRP", "Mirpuri"),
    MOLD("MOLD", "Moldovan"),
    MONTEN("MONTEN", "Montenegroian"),
    NDALI("NDALI", "Ndali"),
    NYAK("NYAK", "Nyakyusa"),
    NYI("NYI", "Nyiha"),
    PATWI("PATWI", "Patois - West Indies"),
    PIDENG("PIDENG", "Pidgin English"),
    PUNPAK("PUNPAK", "Punjabi - Pakistani"),
    QUE("QUE", "Quechua"),
    ROMMOLD("ROMMOLD", "Romanian - Moldovan"),
    SAHO("SAHO", "Saho"),
    SIGNINT("SIGNINT", "Sign Language - International"),
    SIGNFARSI("SIGNFARSI", "Sign Language - Farsi"),
    SOMRHAM("SOMRHAM", "Somali - Reer Hamar"),
    SOMRMARK("SOMRMARK", "Somali - Reer Marka"),
    SWADRC("SWADRC", "Swahili - DRC"),
    SWAKIB("SWAKIB", "Swahili - Kibajuni"),
    SYLH("SYLH", "Sylheti"),
    TAIW("TAIW", "Taiwanese"),
    TAJI("TAJI", "Tajik"),
    TSHIL("TSHIL", "Tshiluba"),
    UIG("UIG", "Uighur"),
    UIGUYG("UIGUYG", "Uighur - Uyghur"),
    YORNGA("YORNGA", "Yoruba - Nigerian"),
    ZAGH("ZAGH", "Zaghawa"),
    TURKIC("TURKIC", "Turkic"),
    ALBANIAN_KOSOVO("ALBANIAN_KOSOVO", "Albanian (Kosovo Only)"),
    SERBO_CROAT_NONPRACT_MUSLIM("SERBO_CROAT_NONPRACT_MUSLIM", "Serbo-Croat (Non-Practising Muslim)"),
    SERBO_CROAT_SERBIAN("SERBO_CROAT_SERBIAN", "Serbo-Croat (Serbian Only)"),
    PUSHTU_DARI_AFGHAN("PUSHTU_DARI_AFGHAN", "Pushtu/Dari (Afghan Only)"),
    SERBO_CROAT_BOSNIA("SERBO_CROAT_BOSNIA", "Serbo-Croat (Bosnia Only)"),
    SERBO_CROAT_NON_SERBIAN("SERBO_CROAT_NON_SERBIAN", "Serbo-Croat (not Serbian)"),
    CHECH("CHECH", "Chechan"),
    LAO1("LAO1", "Lao"),
    SERBIAN("SERBIAN", "Serbian"),
    CHIMINI("CHIMINI", "Chimini"),
    TETUM("TETUM", "Tetum"),
    OTJIHERERO("OTJIHERERO", "Otjiherero");

    private final String code;
    private final String language;

    HomeOfficeLanguage(String code, String language) {
        this.code = code;
        this.language = language;
    }

    @Override
    public String toString() {
        return language;
    }

    public static String getLanguageFromCode(String code) {
        return Arrays.stream(HomeOfficeLanguage.values())
            .filter(lan -> lan.code.equalsIgnoreCase(code))
            .findFirst().map(HomeOfficeLanguage::getLanguage).orElse(code);
    }
}
