package uk.gov.hmcts.reform.iacaseapi.domain.handlers.presubmit.statutorytimeframe24weeks;

import lombok.extern.slf4j.Slf4j;
import org.jetbrains.annotations.NotNull;
import org.springframework.stereotype.Service;
import uk.gov.hmcts.reform.iacaseapi.domain.entities.AsylumCase;
import uk.gov.hmcts.reform.iacaseapi.domain.entities.StatutoryTimeframe24Weeks;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Optional;

import static java.time.LocalDate.parse;
import static java.time.format.DateTimeFormatter.ofPattern;
import static org.apache.commons.lang3.StringUtils.EMPTY;
import static org.apache.commons.lang3.StringUtils.SPACE;
import static uk.gov.hmcts.reform.iacaseapi.domain.entities.AsylumCaseFieldDefinition.APPEAL_SUBMISSION_DATE;
import static uk.gov.hmcts.reform.iacaseapi.domain.entities.AsylumCaseFieldDefinition.XUI_BANNER_TEXT;
import static uk.gov.hmcts.reform.iacaseapi.domain.entities.ccd.field.YesOrNo.YES;

@Slf4j
@Service
public class BannerTextService {
    private static final String DD_MMM_YYYY = "dd MMM yyyy";
    private static final String PRE_24W_BANNER_TEXT = "24 Week STF: case deadline ";
    private static final int INT_24 = 24;

    public void updateBannerText(AsylumCase asylumCase, StatutoryTimeframe24Weeks updatedStatutoryTimeframe24Weeks) {

        final String stf24wBannerText = populateSTF24wBannerText(asylumCase);
        Optional<String> existingCaseBannerText = getExistingCaseBannerText(asylumCase);
        if (updatedStatutoryTimeframe24Weeks.getCurrentStatusAutoGenerated().equals(YES)) {
            if (existingCaseBannerText.isEmpty()) {
                add24wBannerText(asylumCase, stf24wBannerText);
            } else {
                append24wBannerTextToExistingBannerText(asylumCase, existingCaseBannerText, stf24wBannerText);
            }
        } else {
            remove24wBannerText(asylumCase, existingCaseBannerText, stf24wBannerText);
        }
    }

    @NotNull
    private String populateSTF24wBannerText(AsylumCase asylumCase) {
        Optional<String> appealSubmissionDate = asylumCase.read(APPEAL_SUBMISSION_DATE);
        String added24WeeksToAppealDate = add24WeeksToAppealDate(appealSubmissionDate);
        return PRE_24W_BANNER_TEXT + added24WeeksToAppealDate;
    }

    private Optional<String> getExistingCaseBannerText(AsylumCase asylumCase) {
        return asylumCase.read(XUI_BANNER_TEXT);
    }


    private void remove24wBannerText(AsylumCase asylumCase, Optional<String> bannerTex, String stf24wBannerText) {
        String existingBannerText = bannerTex.orElse(EMPTY);
        if (is24wBannerTextAlreadyExist(existingBannerText, stf24wBannerText)) {
            existingBannerText = existingBannerText.replace(stf24wBannerText, EMPTY);
            add24wBannerText(asylumCase, existingBannerText.trim());
        }
    }

    private void append24wBannerTextToExistingBannerText(AsylumCase asylumCase, Optional<String> bannerTex, String stf24wBannerText) {
        String existingBannerText = bannerTex.orElse(EMPTY);
        if (!is24wBannerTextAlreadyExist(existingBannerText, stf24wBannerText)) {
            if (!existingBannerText.isEmpty()) {
                existingBannerText = existingBannerText + SPACE + stf24wBannerText;
            } else {
                existingBannerText = stf24wBannerText;
            }
            add24wBannerText(asylumCase, existingBannerText);
        }
    }

    private boolean is24wBannerTextAlreadyExist(String existingText, String stf24wBannerText) {
        return existingText.contains(stf24wBannerText);
    }

    public String add24WeeksToAppealDate(Optional<String> appealSubmittedDate) {
        LocalDate appealDate = parse(appealSubmittedDate.orElse(EMPTY));
        LocalDate stf24WeeksDate = appealDate.plusWeeks(INT_24);
        DateTimeFormatter dateFormatter = ofPattern(DD_MMM_YYYY);
        return stf24WeeksDate.format(dateFormatter);
    }

    private void add24wBannerText(AsylumCase asylumCase, String stf24wBannerText) {
        asylumCase.write(XUI_BANNER_TEXT, stf24wBannerText);
    }
}
