package uk.gov.hmcts.reform.iacaseapi.domain.handlers.presubmit.statutorytimeframe24weeks;

import org.springframework.stereotype.Service;
import uk.gov.hmcts.reform.iacaseapi.domain.entities.AsylumCase;
import uk.gov.hmcts.reform.iacaseapi.domain.entities.StatutoryTimeframe24Weeks;
import uk.gov.hmcts.reform.iacaseapi.domain.service.BannerTextService;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Optional;

import static java.time.LocalDate.parse;
import static java.time.format.DateTimeFormatter.ofPattern;
import static org.apache.commons.lang3.StringUtils.EMPTY;
import static org.apache.commons.lang3.StringUtils.isEmpty;
import static uk.gov.hmcts.reform.iacaseapi.domain.entities.AsylumCaseFieldDefinition.APPEAL_SUBMISSION_DATE;
import static uk.gov.hmcts.reform.iacaseapi.domain.entities.AsylumCaseFieldDefinition.TRIBUNAL_RECEIVED_DATE;
import static uk.gov.hmcts.reform.iacaseapi.domain.entities.ccd.field.YesOrNo.YES;

@Service
public class STF24WeeksBannerTextService {
    private static final String DD_MMM_YYYY = "dd MMM yyyy";
    private static final String PRE_24W_BANNER_TEXT = "24 Week STF: case deadline ";
    private static final int INT_24 = 24;
    private final BannerTextService service;

    public STF24WeeksBannerTextService(BannerTextService service) {
        this.service = service;
    }

    public void updateBannerText(AsylumCase asylumCase, StatutoryTimeframe24Weeks updatedStatutoryTimeframe24Weeks) {

        final String stf24wBannerText = populateSTF24wBannerText(asylumCase);

        if (updatedStatutoryTimeframe24Weeks.getCurrentStatusAutoGenerated().equals(YES)) {
            service.addToBannerText(asylumCase, stf24wBannerText);
        } else {
            service.removeFromBannerText(asylumCase, stf24wBannerText);
        }
    }


    private String populateSTF24wBannerText(AsylumCase asylumCase) {
        String tribunalReceivedDate = getTribunalReceivedDate(asylumCase);
        String stf24WeeksAddedToDate;
        if (isEmpty(tribunalReceivedDate)) {
            String appealSubmissionDate = getAppealSubmissionDate(asylumCase);
            stf24WeeksAddedToDate = add24WeeksToDate(appealSubmissionDate);
        } else {
            stf24WeeksAddedToDate = add24WeeksToDate(tribunalReceivedDate);
        }
        return PRE_24W_BANNER_TEXT + stf24WeeksAddedToDate;
    }

    private String getAppealSubmissionDate(AsylumCase asylumCase) {
        Optional<String> appealDate = asylumCase.read(APPEAL_SUBMISSION_DATE);
        return appealDate.orElse(EMPTY);
    }

    private String getTribunalReceivedDate(AsylumCase asylumCase) {
        Optional<String> tribunalReceivedDate = asylumCase.read(TRIBUNAL_RECEIVED_DATE);
        return tribunalReceivedDate.orElse(EMPTY);
    }

    public String add24WeeksToDate(String date) {
        LocalDate appealDate = parse(date);
        LocalDate stf24WeeksDate = appealDate.plusWeeks(INT_24);
        DateTimeFormatter dateFormatter = ofPattern(DD_MMM_YYYY);
        return stf24WeeksDate.format(dateFormatter);
    }
}
