package uk.gov.hmcts.reform.iacaseapi.domain.handlers.presubmit.statutorytimeframe24weeks;

import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import uk.gov.hmcts.reform.iacaseapi.domain.DateProvider;
import uk.gov.hmcts.reform.iacaseapi.domain.entities.AsylumCase;
import uk.gov.hmcts.reform.iacaseapi.domain.entities.CaseNote;
import uk.gov.hmcts.reform.iacaseapi.domain.entities.HomeOfficeStatutoryTimeframeDto;
import uk.gov.hmcts.reform.iacaseapi.domain.entities.HomeOfficeStatutoryTimeframeDto.Stf24WeekCohort;
import uk.gov.hmcts.reform.iacaseapi.domain.entities.StatutoryTimeframe24Weeks;
import uk.gov.hmcts.reform.iacaseapi.domain.entities.StatutoryTimeframe24WeeksHistory;
import uk.gov.hmcts.reform.iacaseapi.domain.entities.UserDetails;
import uk.gov.hmcts.reform.iacaseapi.domain.entities.ccd.field.IdValue;
import uk.gov.hmcts.reform.iacaseapi.domain.entities.ccd.field.YesOrNo;
import uk.gov.hmcts.reform.iacaseapi.domain.service.Appender;

import java.time.LocalDate;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

import static java.util.Collections.emptyList;
import static uk.gov.hmcts.reform.iacaseapi.domain.entities.AsylumCaseFieldDefinition.CASE_NOTES;
import static uk.gov.hmcts.reform.iacaseapi.domain.entities.AsylumCaseFieldDefinition.STATUTORY_TIMEFRAME_24_WEEKS;
import static uk.gov.hmcts.reform.iacaseapi.domain.entities.AsylumCaseFieldDefinition.STF_24W_CURRENT_REASON_AUTO_GENERATED;
import static uk.gov.hmcts.reform.iacaseapi.domain.entities.AsylumCaseFieldDefinition.STF_24W_CURRENT_STATUS_AUTO_GENERATED;
import static uk.gov.hmcts.reform.iacaseapi.domain.entities.AsylumCaseFieldDefinition.STF_24W_HOME_OFFICE_COHORT;
import static uk.gov.hmcts.reform.iacaseapi.domain.entities.AsylumCaseFieldDefinition.STF_24W_PREVIOUS_STATUS_WAS_YES_AUTO_GENERATED;

@Slf4j
@Service
public class UpdateStatutoryTimeframe24WeeksService {

    private final Appender<StatutoryTimeframe24WeeksHistory> statutoryTimeframe24WeeksHistoryAppender;
    private final Appender<CaseNote> caseNoteAppender;
    private final DateProvider dateProvider;
    private final UserDetails userDetails;
    private final STF24WeeksBannerTextService stf24WeeksBannerTextService;

    public UpdateStatutoryTimeframe24WeeksService(
        Appender<StatutoryTimeframe24WeeksHistory> statutoryTimeframe24WeeksHistoryAppender,
        Appender<CaseNote> caseNoteAppender,
        DateProvider dateProvider,
        UserDetails userDetails,
        STF24WeeksBannerTextService stf24WeeksBannerTextService
    ) {
        this.statutoryTimeframe24WeeksHistoryAppender = statutoryTimeframe24WeeksHistoryAppender;
        this.caseNoteAppender = caseNoteAppender;
        this.dateProvider = dateProvider;
        this.userDetails = userDetails;
        this.stf24WeeksBannerTextService = stf24WeeksBannerTextService;
    }

    public AsylumCase updateAsylumCase(AsylumCase asylumCase, YesOrNo stf24wStatus) {
        // Read existing fields
        String stf24wReason = asylumCase
            .read(STF_24W_CURRENT_REASON_AUTO_GENERATED, String.class)
            .orElseThrow(() -> new IllegalStateException("stf24wCurrentReasonAutoGenerated is not present"));
        Optional<YesOrNo> stf24wCurrentStatus = asylumCase
                .read(STF_24W_CURRENT_STATUS_AUTO_GENERATED, YesOrNo.class);
        log.debug("currentStatus: {}", stf24wCurrentStatus);
        boolean isStatusPresent = stf24wCurrentStatus.isPresent();
        boolean statusHasChanged = isStatusPresent && !stf24wCurrentStatus.get().equals(stf24wStatus);
        log.debug("statusHasChanged: {}", statusHasChanged);
        // Check that status has actually changed before updating the case record
        if (!isStatusPresent || statusHasChanged) {
            // Update auto-generated fields
            asylumCase.write(STF_24W_CURRENT_STATUS_AUTO_GENERATED, stf24wStatus);
            Optional<YesOrNo> previousStatusWasYes = asylumCase.read(STF_24W_PREVIOUS_STATUS_WAS_YES_AUTO_GENERATED, YesOrNo.class);
            if (previousStatusWasYes.isEmpty() || !previousStatusWasYes.get().equals(YesOrNo.YES)) {
                asylumCase.write(STF_24W_PREVIOUS_STATUS_WAS_YES_AUTO_GENERATED, stf24wStatus);
            }
            // Update STF 24-week object containing history and original Home Office response information
            String userDetails = buildFullName();
            Optional<StatutoryTimeframe24Weeks> existingStf24wObj = asylumCase.read(STATUTORY_TIMEFRAME_24_WEEKS, StatutoryTimeframe24Weeks.class);
            StatutoryTimeframe24Weeks updatedStf24wObj =
                    buildNewStatutoryTimeframe24Weeks(stf24wStatus, stf24wReason, userDetails, existingStf24wObj);
            asylumCase.write(STATUTORY_TIMEFRAME_24_WEEKS, updatedStf24wObj);
            // Update case notes
            Optional<List<IdValue<CaseNote>>> existingCaseNotes = asylumCase.read(CASE_NOTES);
            List<IdValue<CaseNote>> allCaseNotes = caseNoteAppender.append(buildNewCaseNote(stf24wStatus, stf24wReason, userDetails), existingCaseNotes.orElse(Collections.emptyList()));
            asylumCase.write(CASE_NOTES, allCaseNotes);
        } else {
            log.warn("The current 24-week status is already set to {}.  No changes have been made to the case record.", stf24wStatus);
        }
        // Always ensure that the banner text is up to date
        stf24WeeksBannerTextService.updateBannerText(asylumCase);
        // Ugly hack to work around a CCD bug where event data properties with collection values are not being written to the case record
        // If the CCD bug is ever fixed (yeah, I know), delete the following line (and corresponding function) and also see if the
        //  STF_24W_HOME_OFFICE_COHORT  definition can also be removed from AsylumCaseFieldDefinition.java,
        // then make the corresponding change in ia-home-office-integration-api
        fixHomeOfficeResponseAndCohortTextOnFirstPass(asylumCase);
        log.info("Leaving updateAsylumCase ...");
        return asylumCase;
    }

    private void fixHomeOfficeResponseAndCohortTextOnFirstPass(AsylumCase asylumCase) {
        // The first time we come through here, we need to adjust a couple of case values to work around a CCD bug
        String stf24wHomeOfficeCohortText = asylumCase.read(STF_24W_HOME_OFFICE_COHORT, String.class).orElse("");
        if (stf24wHomeOfficeCohortText.contains("=")) {
            log.info("Updating Home Office response and resetting cohort text on first pass through the code.");
            log.info("  - before: {}", stf24wHomeOfficeCohortText);
            // Get Home Office response object
            Optional<StatutoryTimeframe24Weeks> stf24w = asylumCase.read(STATUTORY_TIMEFRAME_24_WEEKS, StatutoryTimeframe24Weeks.class);
            if (stf24w.isPresent()) {
                HomeOfficeStatutoryTimeframeDto homeOfficeResponse = stf24w.get().getHomeOfficeResponse();
                List<Stf24WeekCohort> cohorts = homeOfficeResponse.getStf24weekCohorts();
                if (cohorts.size() == 0) {
                    // Recreate the original Home Office response from the (modified) cohort text passed in
                    cohorts = Arrays.stream(stf24wHomeOfficeCohortText.split(","))
                             .map(cohortText -> new Stf24WeekCohort(cohortText.substring(0, cohortText.indexOf("=")), cohortText.endsWith("=true"))).toList();
                    // Update case record
                    homeOfficeResponse.setStf24weekCohorts(cohorts);
                    log.info("cohorts just before writing to the case: {}", cohorts);
                    log.info("homeOfficeResponse just before writing to the case: {}", homeOfficeResponse);
                    asylumCase.write(STATUTORY_TIMEFRAME_24_WEEKS, stf24w);
                    log.info("cohorts just after writing to the case: {}", cohorts);
                    log.info("homeOfficeResponse just after writing to the case: {}", homeOfficeResponse);
                }
            }
            // Finally, restore the cohort text to a comma-separated list of present cohorts so that it can be used by XUI
            stf24wHomeOfficeCohortText = Arrays.stream(stf24wHomeOfficeCohortText.split(","))
                                        .filter(cohortText -> cohortText.endsWith("=true"))
                                        .map(cohortText -> cohortText.replace("=true", ""))
                                        .collect(Collectors.joining(","));
            log.info("  - after: {}", stf24wHomeOfficeCohortText);
            // Update case record
            asylumCase.write(STF_24W_HOME_OFFICE_COHORT, stf24wHomeOfficeCohortText);
        }
    }

    private String buildFullName() {
        return userDetails.getForename()
            + " "
            + userDetails.getSurname();
    }

    private StatutoryTimeframe24Weeks buildNewStatutoryTimeframe24Weeks(YesOrNo status, String reason, String user, Optional<StatutoryTimeframe24Weeks> existingStf24wObj) {
        List<IdValue<StatutoryTimeframe24WeeksHistory>> existingHistory = emptyList();
        HomeOfficeStatutoryTimeframeDto homeOfficeResponse = null;

        if (existingStf24wObj.isPresent()) {
            StatutoryTimeframe24Weeks stf24wObj = existingStf24wObj.get();
            homeOfficeResponse = stf24wObj.getHomeOfficeResponse();
            existingHistory = stf24wObj.getHistory();
        }

        StatutoryTimeframe24WeeksHistory newHistoryItem = new StatutoryTimeframe24WeeksHistory(
            status,
            reason,
            user,
            dateProvider.nowWithTime().toString()
        );
        return new StatutoryTimeframe24Weeks(
                statutoryTimeframe24WeeksHistoryAppender.append(newHistoryItem, existingHistory),
                homeOfficeResponse
        );
    }

    private CaseNote buildNewCaseNote(YesOrNo status, String reason, String user) {
        return new CaseNote(
            "Setting statutory timeframe 24 weeks to - " + status,
            reason,
            user,
            LocalDate.now().toString()
        );
    }
}
