package uk.gov.hmcts.reform.iacaseapi.domain.handlers.presubmit.statutorytimeframe24weeks;

import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import uk.gov.hmcts.reform.iacaseapi.domain.DateProvider;
import uk.gov.hmcts.reform.iacaseapi.domain.entities.AsylumCase;
import uk.gov.hmcts.reform.iacaseapi.domain.entities.CaseNote;
import uk.gov.hmcts.reform.iacaseapi.domain.entities.StatutoryTimeframe24Weeks;
import uk.gov.hmcts.reform.iacaseapi.domain.entities.StatutoryTimeframe24WeeksHistory;
import uk.gov.hmcts.reform.iacaseapi.domain.entities.UserDetails;
import uk.gov.hmcts.reform.iacaseapi.domain.entities.ccd.field.IdValue;
import uk.gov.hmcts.reform.iacaseapi.domain.entities.ccd.field.YesOrNo;
import uk.gov.hmcts.reform.iacaseapi.domain.service.Appender;

import java.time.LocalDate;
import java.util.Collections;
import java.util.List;
import java.util.Optional;

import static java.util.Collections.emptyList;
import static uk.gov.hmcts.reform.iacaseapi.domain.entities.AsylumCaseFieldDefinition.CASE_NOTES;
import static uk.gov.hmcts.reform.iacaseapi.domain.entities.AsylumCaseFieldDefinition.STATUTORY_TIMEFRAME_24_WEEKS;
import static uk.gov.hmcts.reform.iacaseapi.domain.entities.AsylumCaseFieldDefinition.STATUTORY_TIMEFRAME_24_WEEKS_REASON;

@Slf4j
@Service
public class UpdateStatutoryTimeframe24WeeksService {

    public static final String HOME_OFFICE_INITIAL_DETERMINATION = "Home Office initial determination";

    private final Appender<StatutoryTimeframe24WeeksHistory> statutoryTimeframe24WeeksHistoryAppender;
    private final Appender<CaseNote> caseNoteAppender;
    private final DateProvider dateProvider;
    private final UserDetails userDetails;

    public UpdateStatutoryTimeframe24WeeksService(
        Appender<StatutoryTimeframe24WeeksHistory> statutoryTimeframe24WeeksHistoryAppender,
        Appender<CaseNote> caseNoteAppender,
        DateProvider dateProvider,
        UserDetails userDetails
    ) {
        this.statutoryTimeframe24WeeksHistoryAppender = statutoryTimeframe24WeeksHistoryAppender;
        this.caseNoteAppender = caseNoteAppender;
        this.dateProvider = dateProvider;
        this.userDetails = userDetails;
    }

    public AsylumCase updateAsylumCase(AsylumCase asylumCase, YesOrNo statutoryTimeframe24WeeksStatus) {
        String statutoryTimeframe24WeeksReason = asylumCase
            .read(STATUTORY_TIMEFRAME_24_WEEKS_REASON, String.class)
            .orElseThrow(() -> new IllegalStateException("statutoryTimeframe24WeeksReason is not present"));

        Optional<StatutoryTimeframe24Weeks> maybeExistingStatutoryTimeframe24Weeks =
            asylumCase.read(STATUTORY_TIMEFRAME_24_WEEKS);

        if (maybeExistingStatutoryTimeframe24Weeks.isPresent() && maybeExistingStatutoryTimeframe24Weeks.get().getCurrentStatusAutoGenerated() == statutoryTimeframe24WeeksStatus) {
            throw new IllegalStateException("The current status is already set to " + statutoryTimeframe24WeeksStatus);
        }

        String userDetails = buildFullName();

        StatutoryTimeframe24Weeks updatedStatutoryTimeframe24Weeks =
            buildNewStatutoryTimeframe24Weeks(statutoryTimeframe24WeeksStatus, statutoryTimeframe24WeeksReason, userDetails, maybeExistingStatutoryTimeframe24Weeks);

        if (!statutoryTimeframe24WeeksReason.contains(HOME_OFFICE_INITIAL_DETERMINATION)) {
            log.info("Writing STATUTORY_TIMEFRAME_24_WEEKS with status: {}", statutoryTimeframe24WeeksStatus);
            asylumCase.write(STATUTORY_TIMEFRAME_24_WEEKS, updatedStatutoryTimeframe24Weeks);
            asylumCase.clear(STATUTORY_TIMEFRAME_24_WEEKS_REASON);
        } else {
            log.info("Skipping write of STATUTORY_TIMEFRAME_24_WEEKS for '{}'", HOME_OFFICE_INITIAL_DETERMINATION);
        }

        Optional<List<IdValue<CaseNote>>> maybeExistingCaseNotes = asylumCase.read(CASE_NOTES);
        List<IdValue<CaseNote>> allCaseNotes = caseNoteAppender.append(
            buildNewCaseNote(statutoryTimeframe24WeeksStatus, statutoryTimeframe24WeeksReason, userDetails), maybeExistingCaseNotes.orElse(Collections.emptyList()));

        asylumCase.write(CASE_NOTES, allCaseNotes);

        return asylumCase;
    }

    private String buildFullName() {
        return userDetails.getForename()
            + " "
            + userDetails.getSurname();
    }

    private StatutoryTimeframe24Weeks buildNewStatutoryTimeframe24Weeks(YesOrNo status, String reason, String user, Optional<StatutoryTimeframe24Weeks> maybeExistingStatutoryTimeframe24Weeks) {
        List<IdValue<StatutoryTimeframe24WeeksHistory>> existingHistory = emptyList();

        if (maybeExistingStatutoryTimeframe24Weeks.isPresent()) {
            StatutoryTimeframe24Weeks statutoryTimeframe24Weeks = maybeExistingStatutoryTimeframe24Weeks.get();

            existingHistory = statutoryTimeframe24Weeks.getHistory();
        }
        StatutoryTimeframe24WeeksHistory latestStatutoryTimeframe24WeeksHistory = new StatutoryTimeframe24WeeksHistory(
            status,
            reason,
            user,
            dateProvider.nowWithTime().toString()
        );
        return new StatutoryTimeframe24Weeks(
            status,
            statutoryTimeframe24WeeksHistoryAppender.append(latestStatutoryTimeframe24WeeksHistory, existingHistory)
        );
    }

    private CaseNote buildNewCaseNote(YesOrNo status, String reason, String user) {
        return new CaseNote(
            "Setting statutory timeframe 24 weeks to " + status,
            reason,
            user,
            LocalDate.now().toString()
        );
    }
}
