java:
  # Don't modify below here unless you know what you are doing
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    # Set HOME_OFFICE_VALIDATION_ENABLED: "true" if you want to run the validation against the mock HO validation API in AAT; otherwise leave at "false".
    # The mock HO validation API lives at http://ia-home-office-mock-api-aat.service.core-compute-aat.internal/ichallenge/applications/v1/1111-2222-3333-4444
    # (you can use any valid UAN at the end; but in the application you must enter the expected UAN, name and DOB in order to proceed past validation)
    HOME_OFFICE_VALIDATION_ENABLED: "false" # Do not remove this environment variable!
