xui-webapp:
  enabled: true
  nodejs:
    imagePullPolicy: Always
    releaseNameOverride: ${SERVICE_NAME}-xui-webapp
    image: hmctsprod.azurecr.io/xui/webapp:latest
    ingressHost: xui-${SERVICE_FQDN}
    memoryRequests: 2Gi
    cpuRequests: 2000m
    memoryLimits: 4Gi
    cpuLimits: 3500m
    devmemoryRequests: 6Gi
    devcpuRequests: 2000m
    devmemoryLimits: 8Gi
    devcpuLimits: 4500m
    environment:
      HEALTH_CCD_COMPONENT_API: http://gateway-${SERVICE_FQDN}/health
      HEALTH_CCD_DATA_API: https://ccd-data-store-api-${SERVICE_FQDN}/health
      HEALTH_TERMS_AND_CONDITIONS_API: https://xui-terms-and-conditions-${SERVICE_FQDN}/health
      SERVICES_EM_ANNO_API: http://{{ .Release.Name }}-ccd-api-gw
      SERVICES_CCD_COMPONENT_API: http://{{ .Release.Name }}-ccd-api-gw
      SERVICES_CCD_DATA_STORE_API: https://ccd-data-store-api-ia-case-api-pr-${CHANGE_ID}.preview.platform.hmcts.net
      SERVICES_TERMS_AND_CONDITIONS: https://xui-terms-and-conditions-${SERVICE_FQDN}
      SERVICES_IDAM_API_URL: https://idam-api.aat.platform.hmcts.net
      SERVICES_S2S: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
      SERVICES_PRD_LOCATION_API: http://rd-location-ref-api-aat.service.core-compute-aat.internal
      SERVICES_PRD_JUDICIAL_API: http://rd-judicial-api-aat.service.core-compute-aat.internal
      SERVICES_PRD_COMMONDATA_API: http://rd-commondata-api-aat.service.core-compute-aat.internal
      SERVICES_PRD_API: http://rd-professional-api-aat.service.core-compute-aat.internal
      SERVICES_CCD_CASE_ASSIGNMENT_API: https://aac-${SERVICE_FQDN}
      SERVICES_DOCUMENTS_API_V2: http://${SERVICE_NAME}-ccd-case-document-am-api
      SERVICES_WORK_ALLOCATION_TASK_API: https://wa-task-management-api-ia-case-api-pr-${CHANGE_ID}.preview.platform.hmcts.net
      SERVICES_WA_WORKFLOW_API_URL: https://wa-task-monitor-ia-case-api-pr-${CHANGE_ID}.preview.platform.hmcts.net
      SERVICES_IDAM_ISS_URL: https://forgerock-am.service.core-compute-idam-aat2.internal:8443/openam/oauth2/realms/root/realms/hmcts
      SERVICES_ROLE_ASSIGNMENT_API: https://am-role-assignment-ia-case-api-pr-${CHANGE_ID}.preview.platform.hmcts.net
      SERVICES_ROLE_ASSIGNMENT_MAPPING_API: https://am-org-role-mapping-service-${SERVICE_FQDN}
      JURISDICTIONS: IA
      GLOBAL_SEARCH_SERVICES: IA
      LAUNCH_DARKLY_CLIENT_ID: 5de6610b23ce5408280f2268
      FEATURE_REDIS_ENABLED: false
      FEATURE_APP_INSIGHTS_ENABLED: false
      FEATURE_SECURE_COOKIE_ENABLED: false
      FEATURE_PROXY_ENABLED: false
      FEATURE_TERMS_AND_CONDITIONS_ENABLED: false
      FEATURE_HELMET_ENABLED: false
      FEATURE_OIDC_ENABLED: false
      FEATURE_WORKALLOCATION_ENABLED: true
      FEATURE_ACCESS_MANAGEMENT_ENABLED: true
      FEATURE_SUBSTANTIVE_ROLE_ENABLED: true
      FEATURE_JRD_E_LINKS_V2_ENABLED: true
      NOW: false
      REDISCLOUD_URL: http://dummyrediscloudurl
      UV_THREADPOOL_SIZE: 128
      PROTOCOL: http
      WA_SUPPORTED_JURISDICTIONS: IA
      PREVIEW_DEPLOYMENT_ID: "ia-${CHANGE_ID}"
      ENABLE_HEARING_DATA_SOURCE_HEADERS: "true"
      SERVICES_HEARINGS_COMPONENT_API_IAC: https://ia-case-api-pr-${CHANGE_ID}-hearings-api.preview.platform.hmcts.net
    keyVaults:
      rpx:
        resourceGroup: rpx
        secrets:
          - name: mc-s2s-client-secret
            alias: mc-s2s-client-secret
          - name: mc-idam-client-secret
            alias: mc-idam-client-secret
          - name: mc-session-secret
            alias: mc-session-secret
          - name: system-user-name
            alias: system-user-name
          - name: system-user-password
            alias: system-user-password
          - name: mc-session-secret
            alias: mc-session-secret