java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  keyVaults:
    ia:
      resourceGroup: ia
      secrets:
        - name: ia-gov-notify-key
          alias: IA_GOV_NOTIFY_KEY
        - name: ia-bail-gov-notify-key
          alias: IA_BAIL_GOV_NOTIFY_KEY