# https://github.com/hmcts/wa-chart/blob/master/wa/values.yaml
# 1.0.4
wa:
  enabled: true
  taskManagement:
    enabled: true
  taskMonitor:
    enabled: true
  eventHandler:
    enabled: true
  workflow:
    enabled: true
  taskBatchCron:
    enabled: true
  messageCron:
    enabled: true
  camunda:
    enabled: true
  postgresql:
    enabled: true
  reconfigurationBatchCron:
    enabled: true
  terminationBatchCron:
    enabled: true
  global:
    postgresUsername: hmcts
    postgresSecret: postgres
    postgresHost: ia-preview.postgres.database.azure.com
    databaseNamePrefix: "pr-${CHANGE_ID}-"
  wa-initiation-batch:
    job:
      releaseNameOverride: "{{ .Release.Name }}-wa-task-batch"
  wa-reconfiguration-batch:
    job:
      releaseNameOverride: "{{ .Release.Name }}-reconfiguration"
  wa-termination-batch:
    job:
      releaseNameOverride: "{{ .Release.Name }}-termination-batch"
  wa-message-cron-service:
    job:
      releaseNameOverride: "{{ .Release.Name }}-wa-message-cron"

  camunda-bpm:
    java:
      devcpuRequests: 500m
      devmemoryRequests: 1Gi
      devcpuLimits: 2
      devmemoryLimits: 4Gi
      environment:
        CAMUNDA_DB_CONN_OPTIONS: "?stringtype=unspecified&reWriteBatchedInserts=true&sslmode=require"

  wa-task-management-api:
    java:
      ingressHost: wa-task-management-api-${SERVICE_FQDN}
      devcpuRequests: 500m
      devmemoryRequests: 1Gi
      devcpuLimits: 2
      devmemoryLimits: 4Gi
      environment:
        IDAM_SECURITY_ALLOWED_ISSUERS_0: https://forgerock-am.service.core-compute-idam-aat2.internal:8443/openam/oauth2/realms/root/realms/hmcts
        IDAM_SECURITY_ALLOWED_ISSUERS_1: https://hmcts-access.aat.platform.hmcts.net/o
        IDAM_SECURITY_ALLOWED_ISSUERS_2: https://idam-web-public.aat.platform.hmcts.net/o
        CAMUNDA_URL: "http://{{ .Release.Name }}-camunda/engine-rest"
        IDAM_URL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net"
        S2S_URL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        OPEN_ID_IDAM_URL: "https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net"
        ROLE_ASSIGNMENT_URL: https://am-role-assignment-${SERVICE_FQDN}
        ALLOWED_JURISDICTIONS: ia
        ALLOWED_CASE_TYPES: asylum

  wa-case-event-handler:
    java:
      ingressHost: wa-case-event-handler-${SERVICE_FQDN}
      releaseNameOverride: ${SERVICE_NAME}-wa-case-event-handler
      secrets:
        AZURE_SERVICE_BUS_CONNECTION_STRING:
          secretRef: ia-sb-preview
          key: connectionString
      devcpuRequests: 500m
      devmemoryRequests: 1Gi
      devcpuLimits: 2
      devmemoryLimits: 4Gi
      environment:
        CAMUNDA_URL: "http://{{ .Release.Name }}-camunda/engine-rest"
        CCD_URL: "http://{{ .Release.Name }}-ccd-data-store-api"
        CCD_SEARCH_URL: "http://{{ .Release.Name }}-ccd-data-store-api"
        ROLE_ASSIGNMENT_URL: https://am-role-assignment-${SERVICE_FQDN}
        WA_WORKFLOW_API_URL: "http://{{ .Release.Name }}-wa-workflow-api"
        WA_TASK_MANAGEMENT_API_URL: "http://{{ .Release.Name }}-wa-task-management-api"
        AZURE_SERVICE_BUS_TOPIC_NAME: ${SERVICE_NAME}-ccd-case-events
        AZURE_SERVICE_BUS_SUBSCRIPTION_NAME: ${SERVICE_NAME}-ccd-case-events
        AZURE_SERVICE_BUS_CCD_CASE_EVENTS_SUBSCRIPTION_NAME: ${SERVICE_NAME}-ccd-case-events
  wa-task-monitor:
    java:
      ingressHost: wa-task-monitor-${SERVICE_FQDN}
      environment:
        WA_TASK_MANAGEMENT_API_URL: http://{{ .Release.Name }}-wa-task-management-api
  wa-workflow-api:
    java:
      devcpuRequests: 500m
      devmemoryRequests: 1Gi
      devcpuLimits: 2
      devmemoryLimits: 4Gi
      environment:
        DB_READER_USERNAME: "hmcts"
  wa:
    postgresql:
      enabled: false

postgresql:
  enabled: true
  flexibleserver: ia-preview
  setup:
    databases:
      - name: "pr-${CHANGE_ID}-data-store"
      - name: "pr-${CHANGE_ID}-definition-store"
      - name: "pr-${CHANGE_ID}-user-profile"
      - name: "pr-${CHANGE_ID}-role_assignment"
      - name: "pr-${CHANGE_ID}-ia-case-api"
      - name: "pr-${CHANGE_ID}-emstitch"
      - name: "pr-${CHANGE_ID}-wa-case-event-handler"
      - name: "pr-${CHANGE_ID}-wa_workflow_api"
      - name: "pr-${CHANGE_ID}-camunda"
      - name: "pr-${CHANGE_ID}-cft_task_db"
      - name: "pr-${CHANGE_ID}-cft_task_db_replica"
      - name: "pr-${CHANGE_ID}-org_role_mapping"
      - name: "pr-${CHANGE_ID}-ia_timed_event_service"
      - name: "pr-${CHANGE_ID}-hmc-cft-hearing-service"

xui-webapp:
  nodejs:
    environment:
      WA_SUPPORTED_JURISDICTIONS: IA
      SERVICES_WORK_ALLOCATION_TASK_API: https://wa-task-management-api-ia-case-api-pr-${CHANGE_ID}.preview.platform.hmcts.net
      SERVICES_WA_WORKFLOW_API_URL: https://wa-task-monitor-ia-case-api-pr-${CHANGE_ID}.preview.platform.hmcts.net