package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.Document;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from ComplexTypes — do not edit by hand.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "additionalEvidenceDocument",
        generate = true
)
public class AdditionalEvidenceDocument {
    @CCD(
            label = "Document",
            searchable = false
    )
    private Document document;

    @CCD(
            label = "Explain why you are submitting this evidence after the appeal skeleton argument.",
            searchable = false,
            typeOverride = FieldType.TextArea
    )
    private String description;
}
