package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from FixedLists — do not edit by hand.
 */
@ComplexType(
        name = "appealGroundsProtection",
        generate = true
)
@Getter
@AllArgsConstructor
public enum AppealGroundsProtectionList implements HasLabel {
    PROTECTION_HUMANITARIAN_PROTECTION("Removing the appellant from the UK would breach the UK's obligation in relation to persons eligible for a grant of humanitarian protection", "protectionHumanitarianProtection"),

    PROTECTION_REFUGEE_CONVENTION("Removing the appellant from the UK would breach the UK's obligation under the Refugee Convention", "protectionRefugeeConvention");

    private final String label;

    @JsonValue
    private final String code;
}
