package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from FixedLists — do not edit by hand.
 */
@ComplexType(
        name = "appealType",
        generate = true
)
@Getter
@AllArgsConstructor
public enum AppealType implements HasLabel {
    REFUSAL_OF_HUMAN_RIGHTS("Refusal of a human rights claim", "refusalOfHumanRights"),

    REFUSAL_OF_EU("Refusal of application under the EEA regulations", "refusalOfEu"),

    DEPRIVATION("Deprivation of citizenship", "deprivation"),

    PROTECTION("Refusal of protection claim", "protection"),

    REVOCATION_OF_PROTECTION("Revocation of a protection status", "revocationOfProtection"),

    EU_SETTLEMENT_SCHEME("Refusal of application under the EU Settlement Scheme", "euSettlementScheme");

    private final String label;

    @JsonValue
    private final String code;
}
