package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from FixedLists — do not edit by hand.
 */
@ComplexType(
        name = "appealGroundsDeprivation",
        generate = true
)
@Getter
@AllArgsConstructor
public enum AppealGroundsDeprivationList implements HasLabel {
    DISPROPORTIONATE_DEPRIVATION("Deprivation would have a disproportionate effect", "disproportionateDeprivation"),

    UNLAWFUL_DEPRIVATION("The decision is unlawful because discretion should have been exercised differently", "unlawfulDeprivation");

    private final String label;

    @JsonValue
    private final String code;
}
