package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from FixedLists — do not edit by hand.
 */
@ComplexType(
        name = "appealGroundsRevocation",
        generate = true
)
@Getter
@AllArgsConstructor
public enum AppealGroundsRevocationList implements HasLabel {
    REVOCATION_HUMANITARIAN_PROTECTION("Revocation of the appellant's protection status breaches the United Kingdom's obligations in relation to persons eligible for humanitarian protection", "revocationHumanitarianProtection"),

    REVOCATION_REFUGEE_CONVENTION("Revocation of the appellant's protection status breaches the United Kingdom's obligations under the Refugee Convention", "revocationRefugeeConvention");

    private final String label;

    @JsonValue
    private final String code;
}
