package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from FixedLists — do not edit by hand.
 */
@ComplexType(
        name = "appealGroundsDecisionHumanRightsRefusal",
        generate = true
)
@Getter
@AllArgsConstructor
public enum AppealGroundsDecisionHumanRightsRefusalList implements HasLabel {
    HUMAN_RIGHTS_REFUSAL("The decision is unlawful under section 6 of the Human Rights Act 1998", "humanRightsRefusal");

    private final String label;

    @JsonValue
    private final String code;
}
