package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from FixedLists — do not edit by hand.
 */
@ComplexType(
        name = "applicationType",
        generate = true
)
@Getter
@AllArgsConstructor
public enum ApplicationType implements HasLabel {
    TIME_EXTENSION("Time extension", "Time extension"),

    ADJOURN("Adjourn", "Adjourn"),

    EXPEDITE("Expedite", "Expedite"),

    TRANSFER("Transfer", "Transfer"),

    WITHDRAW("Withdraw", "Withdraw"),

    UPDATE_HEARING_REQUIREMENTS("Update hearing requirements", "Update hearing requirements"),

    CHANGE_HEARING_CENTRE("Change hearing centre", "Change hearing centre"),

    UPDATE_APPEAL_DETAILS("Update appeal details", "Update appeal details");

    private final String label;

    @JsonValue
    private final String code;
}
