package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import java.time.LocalDate;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.Document;
import uk.gov.hmcts.ccd.sdk.type.FieldType;
import uk.gov.hmcts.ccd.sdk.type.ListValue;

/**
 * Generated by ccd-definition-converter from ComplexTypes — do not edit by hand.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "application",
        generate = true
)
public class Application {
    @CCD(
            label = "Application email"
    )
    private List<ListValue<Document>> applicationDocuments;

    @CCD(
            label = "Application from"
    )
    private String applicationSupplier;

    @CCD(
            label = "Type of application"
    )
    private String applicationType;

    @CCD(
            label = "Reason of application",
            typeOverride = FieldType.TextArea
    )
    private String applicationReason;

    @CCD(
            label = "Date application was made"
    )
    private LocalDate applicationDate;

    @CCD(
            label = "Decision"
    )
    private String applicationDecision;

    @CCD(
            label = "Reason of decision",
            typeOverride = FieldType.TextArea
    )
    private String applicationDecisionReason;

    @CCD(
            label = "Date of decision"
    )
    private LocalDate applicationDateOfDecision;

    @CCD(
            label = "Status"
    )
    private String applicationStatus;
}
