package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.Document;

/**
 * Generated by ccd-definition-converter from ComplexTypes — do not edit by hand.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "BundleDocument",
        generate = true
)
public class BundleDocument {
    @CCD(
            label = "Document Name",
            searchable = false
    )
    private String name;

    @CCD(
            label = "Sort Index",
            searchable = false
    )
    private Integer sortIndex;

    @CCD(
            label = "Description",
            searchable = false
    )
    private String description;

    @CCD(
            label = "Source Document",
            searchable = false
    )
    private Document sourceDocument;
}
