package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from ComplexTypes — do not edit by hand.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "caseManagementLocation",
        generate = true
)
public class CaseManagementLocation {
    @CCD(
            label = "region",
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "region"
    )
    private Region region;

    @CCD(
            label = "baseLocation",
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "baseLocation"
    )
    private BaseLocation baseLocation;
}
