package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import java.util.Set;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;

/**
 * Generated by ccd-definition-converter from ComplexTypes — do not edit by hand.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "checklistOutOfCountry",
        generate = true
)
public class ChecklistOutOfCountry {
    @CCD(
            label = " ",
            searchable = false
    )
    private Set<Checklist2> checklist2;

    @CCD(
            label = " ",
            searchable = false
    )
    private Set<Checklist7> checklist7;
}
