package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import java.util.Set;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;

/**
 * Generated by ccd-definition-converter from ComplexTypes — do not edit by hand.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "checklist",
        generate = true
)
public class Checklist {
    @CCD(
            label = " ",
            showCondition = "checklist1=\"DUMMY_VALUE_TO_HIDE_FIELD\"",
            searchable = false
    )
    private Set<Checklist5> checklist5;

    @CCD(
            label = " ",
            showCondition = "checklist1=\"DUMMY_VALUE_TO_HIDE_FIELD\"",
            searchable = false
    )
    private Set<Checklist1> checklist1;

    @CCD(
            label = " ",
            searchable = false
    )
    private Set<Checklist2> checklist2;

    @CCD(
            label = " ",
            showCondition = "checklist7=\"DUMMY_VALUE_TO_HIDE_FIELD\"",
            searchable = false
    )
    private Set<Checklist7> checklist7;

    @CCD(
            label = " ",
            showCondition = "checklist4=\"DUMMY_VALUE_TO_HIDE_FIELD\"",
            searchable = false
    )
    private Set<Checklist3> checklist3;

    @CCD(
            label = " ",
            showCondition = "checklist4=\"DUMMY_VALUE_TO_HIDE_FIELD\"",
            searchable = false
    )
    private Set<Checklist4> checklist4;

    @CCD(
            label = " ",
            showCondition = "checklist6=\"DUMMY_VALUE_TO_HIDE_FIELD\"",
            searchable = false
    )
    private Set<Checklist6> checklist6;
}
