package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from FixedLists — do not edit by hand.
 */
@ComplexType(
        name = "checklist6",
        generate = true
)
@Getter
@AllArgsConstructor
public enum Checklist6 implements HasLabel {
    IS_NOT_STATELESS("My client is not stateless", "isNotStateless");

    private final String label;

    @JsonValue
    private final String code;
}
