package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from FixedLists — do not edit by hand.
 */
@ComplexType(
        name = "checklist3",
        generate = true
)
@Getter
@AllArgsConstructor
public enum Checklist3 implements HasLabel {
    IS_NOT_FAMILY_APPEAL("My client is not appealing with anyone else as part of a linked or grouped appeal", "isNotFamilyAppeal");

    private final String label;

    @JsonValue
    private final String code;
}
