package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from FixedLists — do not edit by hand.
 */
@ComplexType(
        name = "countryGuidance",
        generate = true
)
@Getter
@AllArgsConstructor
public enum CountryGuidance implements HasLabel {
    COUNTRY_GUIDANCE("It's clear at this stage that the issue is likely to be used for giving country guidance", "countryGuidance");

    private final String label;

    @JsonValue
    private final String code;
}
