package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import java.time.LocalDate;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from ComplexTypes — do not edit by hand.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "datesToAvoid",
        generate = true
)
public class DatesToAvoid {
    @CCD(
            label = "Date",
            searchable = false
    )
    private LocalDate dateToAvoid;

    @CCD(
            label = "Reason",
            searchable = false,
            typeOverride = FieldType.TextArea
    )
    private String dateToAvoidReason;
}
