package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import java.time.LocalDate;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.Document;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from ComplexTypes — do not edit by hand.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "decisionAndReasons",
        generate = true
)
public class DecisionAndReasons {
    @CCD(
            label = "Date uploaded"
    )
    private LocalDate updatedDecisionDate;

    @CCD(
            label = "Date uploaded"
    )
    private LocalDate dateCoverLetterDocumentUploaded;

    @CCD(
            label = "Document"
    )
    private Document coverLetterDocument;

    @CCD(
            label = "Date uploaded"
    )
    private LocalDate dateDocumentAndReasonsDocumentUploaded;

    @CCD(
            label = "Document"
    )
    private Document documentAndReasonsDocument;

    @CCD(
            label = "What has been corrected",
            typeOverride = FieldType.TextArea
    )
    private String summariseChanges;
}
