package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from ComplexTypes — do not edit by hand.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "DocumentImage",
        generate = true
)
public class DocumentImage {
    @CCD(
            label = "How would you like to have the image rendered?",
            searchable = false,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "imageRendering"
    )
    private ImageRendering imageRendering;

    @CCD(
            label = "Where would you like to embed the image in stitched document?",
            searchable = false,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "imageRenderingLocation"
    )
    private ImageRenderingLocation imageRenderingLocation;

    @CCD(
            label = "The filename of the Image you wish to embed",
            searchable = false
    )
    private String docmosisAssetId;

    @CCD(
            label = "X position of the image",
            searchable = false
    )
    private Integer coordinateX;

    @CCD(
            label = "Y position of the image",
            searchable = false
    )
    private Integer coordinateY;
}
