package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from FixedLists — do not edit by hand.
 */
@ComplexType(
        name = "endAppealOutcome",
        generate = true
)
@Getter
@AllArgsConstructor
public enum EndAppealOutcome implements HasLabel {
    WITHDRAWN("Withdrawn", "Withdrawn"),

    STRUCK_OUT("Struck out", "Struck out"),

    NO_VALID_APPEAL("No valid appeal", "No valid appeal"),

    ABANDONED("Abandoned", "Abandoned");

    private final String label;

    @JsonValue
    private final String code;
}
