package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from FixedLists — do not edit by hand.
 */
@ComplexType(
        name = "feeUpdateTribunalActions",
        generate = true
)
@Getter
@AllArgsConstructor
public enum FeeUpdateTribunalActions implements HasLabel {
    REFUND("The appellant should receive a refund", "refund"),

    ADDITIONAL_PAYMENT("The appellant needs to make an additional payment", "additionalPayment"),

    NO_ACTION("No action required - fee update made for information only", "noAction");

    private final String label;

    @JsonValue
    private final String code;
}
