package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import java.time.LocalDate;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.Document;
import uk.gov.hmcts.ccd.sdk.type.FieldType;
import uk.gov.hmcts.ccd.sdk.type.ListValue;
import uk.gov.hmcts.ccd.sdk.type.YesOrNo;

/**
 * Generated by ccd-definition-converter from ComplexTypes — do not edit by hand.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "ftpaApplications",
        generate = true
)
public class FtpaApplications {
    @CCD(
            label = "Applicant",
            searchable = false
    )
    private FtpaApplicantType ftpaApplicant;

    @CCD(
            label = "FTPA Decision and Reasons document",
            searchable = false
    )
    private Document ftpaNewDecisionDocument;

    @CCD(
            label = "FTPA Decision and Reasons document",
            searchable = false
    )
    private List<ListValue<DocumentWithDescription>> ftpaLegacyDecisionDocument;

    @CCD(
            label = "Rule 35 notice",
            searchable = false
    )
    private Document ftpaR35Document;

    @CCD(
            label = "What is the First-tier Tribunal's decision on this case following the FTPA?",
            searchable = false
    )
    private IsDecisionAllowed ftpaDecisionRemadeRule32;

    @CCD(
            label = "Explain why the application should be disposed",
            searchable = false,
            typeOverride = FieldType.TextArea
    )
    private String ftpaDecisionRemadeRule32Text;

    @CCD(
            label = "Before this decision, did you send a Notice of Decision set aside and to be reheard in the First-tier under rule 35?",
            searchable = false
    )
    private YesOrNo isFtpaNoticeOfDecisionSetAside;

    @CCD(
            label = "Objections to set aside",
            searchable = false,
            typeOverride = FieldType.TextArea
    )
    private String ftpaDecisionObjections;

    @CCD(
            label = "Notice communication",
            searchable = false
    )
    private List<ListValue<DocumentWithDescription>> ftpaNoticeDocument;

    @CCD(
            label = "Listing instructions",
            searchable = false,
            typeOverride = FieldType.TextArea
    )
    private String ftpaDecisionLstIns;

    @CCD(
            label = "Decision date",
            searchable = false
    )
    private LocalDate ftpaDecisionDate;

    @CCD(
            label = "Reasons why the application is late",
            searchable = false,
            typeOverride = FieldType.TextArea
    )
    private String ftpaOutOfTimeExplanation;

    @CCD(
            label = "Documents supporting late application",
            searchable = false
    )
    private List<ListValue<DocumentWithDescription>> ftpaOutOfTimeDocuments;

    @CCD(
            label = "Grounds of the application",
            searchable = false,
            typeOverride = FieldType.TextArea
    )
    private String ftpaAppellantGroundsText;

    @CCD(
            label = "Grounds of the application",
            searchable = false
    )
    private List<ListValue<DocumentWithDescription>> ftpaGroundsDocuments;

    @CCD(
            label = "Supporting evidence",
            searchable = false
    )
    private List<ListValue<DocumentWithDescription>> ftpaEvidenceDocuments;

    @CCD(
            label = "Application date",
            searchable = false
    )
    private LocalDate ftpaApplicationDate;

    @CCD(
            label = "Tick any applicable points",
            searchable = false
    )
    private FtpaDecisionCheckList ftpaDecisionNotesPoints;

    @CCD(
            label = "Provide any information that may be helpful to the Upper Tribunal judge",
            searchable = false,
            typeOverride = FieldType.TextArea
    )
    private String ftpaDecisionNotesDescription;

    @CCD(
            label = "The outcome of the application",
            searchable = false
    )
    private FtpaResidentJudgeDecisionOutcomeType ftpaDecisionOutcomeType;

    @CCD(
            label = "The outcome of the application",
            searchable = false
    )
    private String ftpaDecisionOutcomeTypeR35;
}
