package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from FixedLists — do not edit by hand.
 */
@ComplexType(
        name = "govUkNationalities",
        generate = true
)
@Getter
@AllArgsConstructor
public enum GovUkNationalities implements HasLabel {
    AF("Afghan", "AF"),

    AX("Aland Islands", "AX"),

    AL("Albanian", "AL"),

    DZ("Algerian", "DZ"),

    US("American", "US"),

    AS("American Samoa", "AS"),

    AD("Andorran", "AD"),

    AO("Angolan", "AO"),

    AI("Anguillan", "AI"),

    AQ("Antarctica", "AQ"),

    AR("Argentine", "AR"),

    AM("Armenian", "AM"),

    AW("Aruba", "AW"),

    AU("Australian", "AU"),

    AT("Austrian", "AT"),

    AZ("Azerbaijani", "AZ"),

    BS("Bahamian", "BS"),

    BH("Bahraini", "BH"),

    BD("Bangladeshi", "BD"),

    BB("Barbadian", "BB"),

    BY("Belarusian", "BY"),

    BE("Belgian", "BE"),

    BZ("Belizean", "BZ"),

    BJ("Beninese", "BJ"),

    BM("Bermudian", "BM"),

    BT("Bhutanese", "BT"),

    BO("Bolivian", "BO"),

    BQ("Bonaire, Sint Eustatius and Saba", "BQ"),

    BW("Botswanan", "BW"),

    BV("Bouvet Island", "BV"),

    BR("Brazilian", "BR"),

    GB("British", "GB"),

    IO("British Indian Ocean Territory", "IO"),

    BC("British Overseas Citizen", "BC"),

    VG("British Virgin Islander", "VG"),

    BN("Bruneian", "BN"),

    BG("Bulgarian", "BG"),

    BF("Burkinan", "BF"),

    MM("Burmese", "MM"),

    BI("Burundian", "BI"),

    KH("Cambodian", "KH"),

    CM("Cameroonian", "CM"),

    CA("Canadian", "CA"),

    CV("Cape Verdean", "CV"),

    KY("Cayman Islander", "KY"),

    CF("Central African", "CF"),

    TD("Chadian", "TD"),

    CL("Chilean", "CL"),

    CN("Chinese", "CN"),

    CX("Christmas Island", "CX"),

    AG("Citizen of Antigua and Barbuda", "AG"),

    BA("Citizen of Bosnia and Herzegovina", "BA"),

    GW("Citizen of Guinea-Bissau", "GW"),

    KI("Citizen of Kiribati", "KI"),

    SC("Citizen of Seychelles", "SC"),

    DO_("Citizen of the Dominican Republic", "DO"),

    VU("Citizen of Vanuatu", "VU"),

    CC("Cocos (Keeling) Island", "CC"),

    CO("Colombian", "CO"),

    KM("Comoran", "KM"),

    CG("Congolese (Congo)", "CG"),

    CD("Congolese (DRC)", "CD"),

    CK("Cook Islander", "CK"),

    CR("Costa Rican", "CR"),

    HR("Croatian", "HR"),

    CU("Cuban", "CU"),

    CW("Curaçao", "CW"),

    CE("Cymraes", "CE"),

    CC_2("Cymro", "CC"),

    CY("Cypriot", "CY"),

    CZ("Czech", "CZ"),

    DK("Danish", "DK"),

    DJ("Djiboutian", "DJ"),

    DM("Dominican", "DM"),

    NL("Dutch", "NL"),

    TL("East Timorese", "TL"),

    EC("Ecuadorean", "EC"),

    EG("Egyptian", "EG"),

    AE("Emirati", "AE"),

    EN("English", "EN"),

    GQ("Equatorial Guinean", "GQ"),

    ER("Eritrean", "ER"),

    EE("Estonian", "EE"),

    ET("Ethiopian", "ET"),

    FK("Falkland Islands (Malvinas)", "FK"),

    FO("Faroese", "FO"),

    FJ("Fijian", "FJ"),

    PH("Filipino", "PH"),

    FI("Finnish", "FI"),

    FR("French", "FR"),

    GF("French Guiana", "GF"),

    PF("French Polynesia", "PF"),

    TF("French Southern Territories", "TF"),

    GA("Gabonese", "GA"),

    GM("Gambian", "GM"),

    GE("Georgian", "GE"),

    DE("German", "DE"),

    GH("Ghanaian", "GH"),

    GI("Gibraltarian", "GI"),

    GR("Greek", "GR"),

    GL("Greenlandic", "GL"),

    GD("Grenadian", "GD"),

    GP("Guadeloupe", "GP"),

    GU("Guamanian", "GU"),

    GT("Guatemalan", "GT"),

    GG("Guernsey", "GG"),

    GN("Guinean", "GN"),

    GY("Guyanese", "GY"),

    HT("Haitian", "HT"),

    HM("Heard Island and Mcdonald Islands", "HM"),

    HN("Honduran", "HN"),

    HK("Hong Konger", "HK"),

    HU("Hungarian", "HU"),

    IS("Icelandic", "IS"),

    IN("Indian", "IN"),

    ID("Indonesian", "ID"),

    IR("Iranian", "IR"),

    IQ("Iraqi", "IQ"),

    IE("Irish", "IE"),

    IM("Isle of Man", "IM"),

    IL("Israeli", "IL"),

    IT("Italian", "IT"),

    CI("Ivorian", "CI"),

    JM("Jamaican", "JM"),

    JP("Japanese", "JP"),

    JE("Jersey", "JE"),

    JO("Jordanian", "JO"),

    KZ("Kazakh", "KZ"),

    KE("Kenyan", "KE"),

    KN("Kittitian", "KN"),

    KO("Kosovan", "KO"),

    KW("Kuwaiti", "KW"),

    KG("Kyrgyz", "KG"),

    LA("Lao", "LA"),

    LV("Latvian", "LV"),

    LB("Lebanese", "LB"),

    LR("Liberian", "LR"),

    LY("Libyan", "LY"),

    LI("Liechtenstein citizen", "LI"),

    LT("Lithuanian", "LT"),

    LU("Luxembourger", "LU"),

    MO("Macanese", "MO"),

    MK("Macedonian", "MK"),

    MG("Malagasy", "MG"),

    MW("Malawian", "MW"),

    MY("Malaysian", "MY"),

    MV("Maldivian", "MV"),

    ML("Malian", "ML"),

    MT("Maltese", "MT"),

    MH("Marshallese", "MH"),

    MQ("Martiniquais", "MQ"),

    MR("Mauritanian", "MR"),

    MU("Mauritian", "MU"),

    YT("Mayotte", "YT"),

    MX("Mexican", "MX"),

    FM("Micronesian", "FM"),

    MD("Moldovan", "MD"),

    MC("Monagasque", "MC"),

    MN("Mongolian", "MN"),

    ME("Montenegrin", "ME"),

    MS("Montserratian", "MS"),

    MA("Moroccan", "MA"),

    MZ("Mozambican", "MZ"),

    LS("Mpsotho", "LS"),

    NA("Namibian", "NA"),

    NR("Nauruan", "NR"),

    NP("Nepalese", "NP"),

    AN("Netherlands Antilles", "AN"),

    NC("New Caledonia", "NC"),

    NZ("New Zealander", "NZ"),

    NI("Nicaraguan", "NI"),

    NG("Nigerian", "NG"),

    NE("Nigerien", "NE"),

    NU("Niuean", "NU"),

    NF("Norfolk Island", "NF"),

    KP("North Korean", "KP"),

    XN("Northern Irish", "XN"),

    MP("Northern Mariana Islands", "MP"),

    NO("Norwegian", "NO"),

    OM("Omani", "OM"),

    PK("Pakistani", "PK"),

    PW("Palauan", "PW"),

    PS("Palestinian", "PS"),

    PA("Panamanian", "PA"),

    PG("Papua New Guinean", "PG"),

    PY("Paraguayan", "PY"),

    PE("Peruvian", "PE"),

    PN("Pitcairn islander", "PN"),

    PL("Polish", "PL"),

    PT("Portuguese", "PT"),

    PD("Prydeinig", "PD"),

    PR("Puerto Rican", "PR"),

    QA("Qatari", "QA"),

    RO("Romanian", "RO"),

    RU("Russian", "RU"),

    RW("Rwandan", "RW"),

    RE("Réunion", "RE"),

    PM("Saint Pierre and Miquelon", "PM"),

    BL("Saint-Barthélemy", "BL"),

    MF("Saint-Martin (French part)", "MF"),

    SV("Salvadorean", "SV"),

    SM("Sammarinese", "SM"),

    WS("Samoan", "WS"),

    ST("Sao Tomean", "ST"),

    SA("Saudi Arabian", "SA"),

    XS("Scottish", "XS"),

    SN("Senegalese", "SN"),

    RS("Serbian", "RS"),

    SL("Sierra Leonean", "SL"),

    SG("Singaporean", "SG"),

    SX("Sint Maarten (Dutch part)", "SX"),

    SK("Slovak", "SK"),

    SI("Slovenian", "SI"),

    SB("Solomon Islander", "SB"),

    SO("Somali", "SO"),

    ZA("South African", "ZA"),

    GS("South Georgia and the South Sandwich Islands", "GS"),

    KR("South Korean", "KR"),

    SS("South Sudanese", "SS"),

    ES("Spanish", "ES"),

    LK("Sri Lankan", "LK"),

    SH("St Helenian", "SH"),

    LC("St Lucian", "LC"),

    ZZ("Stateless", "ZZ"),

    SD("Sudanese", "SD"),

    SR("Surinamese", "SR"),

    SJ("Svalbard and Jan Mayen Islands", "SJ"),

    SZ("Swazi", "SZ"),

    SE("Swedish", "SE"),

    CH("Swiss", "CH"),

    SY("Syrian", "SY"),

    TW("Taiwanese", "TW"),

    TJ("Tajik", "TJ"),

    TZ("Tanzanian", "TZ"),

    TH("Thai", "TH"),

    TG("Togolese", "TG"),

    TK("Tokelau", "TK"),

    TO("Tongan", "TO"),

    TT("Trinidadian", "TT"),

    TI("Tristanian", "TI"),

    TN("Tunisian", "TN"),

    TR("Turkish", "TR"),

    TM("Turkmen", "TM"),

    TC("Turks and Caicos Islander", "TC"),

    TV("Tuvaluan", "TV"),

    UG("Ugandan", "UG"),

    UA("Ukrainian", "UA"),

    UM("United States Minor Outlying Islands", "UM"),

    UY("Uruguayan", "UY"),

    UZ("Uzbek", "UZ"),

    VA("Vatican citizen", "VA"),

    VE("Venezuelan", "VE"),

    VN("Vietnamese", "VN"),

    VC("Vincentian", "VC"),

    VI("Virgin Islands, US", "VI"),

    WF("Wallisian", "WF"),

    WL("Welsh", "WL"),

    EH("Western Sahara", "EH"),

    YE("Yemeni", "YE"),

    ZM("Zambian", "ZM"),

    ZW("Zimbabwean", "ZW");

    private final String label;

    @JsonValue
    private final String code;
}
