package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from FixedLists — do not edit by hand.
 */
@ComplexType(
        name = "hearingConductionOptions",
        generate = true
)
@Getter
@AllArgsConstructor
public enum HearingConductionOptions implements HasLabel {
    DECISION_WITHOU_HEARING("Decision without a hearing", "decisionWithouHearing"),

    VIDEO_WITH_NO_PARTICIPANTS("Video with no participants at a hearing centre", "videoWithNoParticipants"),

    VIDEO_WITH_AT_LEAST_ONE("Video with at least one participant at a hearing centre", "videoWithAtLeastOne"),

    AUDIO_WITH_NO_PARTICIPANTS("Audio with no participants at a hearing centre", "audioWithNoParticipants"),

    AUDIO_WITH_AT_LEAST_ONE("Audio with at least one participant at a hearing centre", "audioWithAtLeastOne"),

    ALL_PARTICIPANTS("All participants at the hearing centre", "allParticipants");

    private final String label;

    @JsonValue
    private final String code;
}
