package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;

/**
 * Generated by ccd-definition-converter from ComplexTypes — do not edit by hand.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "hearingSchedule",
        generate = true
)
public class HearingSchedule {
    @CCD(
            label = " "
    )
    private String hearingID;

    @CCD(
            label = " "
    )
    private LocalDateTime hearingDateTime;
}
