package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from FixedLists — do not edit by hand.
 */
@ComplexType(
        name = "hearingCentre",
        generate = true
)
@Getter
@AllArgsConstructor
public enum HearingCentre implements HasLabel {
    TAYLOR_HOUSE("Taylor House", "taylorHouse"),

    NEWPORT("Newport", "newport"),

    NEWCASTLE("Newcastle Civil & Family Courts and Tribunals Centre", "newcastle"),

    MANCHESTER("Manchester", "manchester"),

    HATTON_CROSS("Hatton Cross", "hattonCross"),

    GLASGOW("Glasgow", "glasgow"),

    BRADFORD("Bradford", "bradford"),

    BIRMINGHAM("Birmingham", "birmingham"),

    ARNHEM_HOUSE("Arnhem House", "arnhemHouse"),

    CROWN_HOUSE("Crown House", "crownHouse"),

    HARMONDSWORTH("Harmondsworth", "harmondsworth"),

    YARLS_WOOD("Yarl's Wood", "yarlsWood"),

    IAC_NATIONAL_VIRTUAL("IAC National (Virtual)", "iacNationalVirtual"),

    REMOTE_HEARING("Remote hearing", "remoteHearing"),

    DECISION_WITHOUT_HEARING("Decision without a hearing", "decisionWithoutHearing");

    private final String label;

    @JsonValue
    private final String code;
}
