package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from FixedLists — do not edit by hand.
 */
@ComplexType(
        name = "hearingVenue",
        generate = true
)
@Getter
@AllArgsConstructor
public enum HearingVenue implements HasLabel {
    TAYLOR_HOUSE("Taylor House", "taylorHouse"),

    NOTTINGHAM("Nottingham Justice Centre", "nottingham"),

    NEWPORT("Newport", "newport"),

    NEWCASTLE("Newcastle Civil & Family Courts and Tribunals Centre", "newcastle"),

    MANCHESTER("Manchester", "manchester"),

    HATTON_CROSS("Hatton Cross", "hattonCross"),

    GLASGOW_TRIBUNALS_CENTRE("Glasgow", "glasgowTribunalsCentre"),

    COVENTRY("Coventry Magistrates Court", "coventry"),

    BELFAST("Belfast", "belfast"),

    BRADFORD("Bradford", "bradford"),

    BIRMINGHAM("Birmingham", "birmingham"),

    HARMONDSWORTH("Harmondsworth", "harmondsworth"),

    HENDON("Hendon", "hendon"),

    YARLS_WOOD("Yarl's Wood", "yarlsWood"),

    BRADFORD_KEIGHLEY("Bradford & Keighley", "bradfordKeighley"),

    MCC_MINSHULL("MCC Minshull st", "mccMinshull"),

    MCC_CROWN_SQUARE("MCC Crown Square", "mccCrownSquare"),

    MANCHESTER_MAGS("Manchester Mags", "manchesterMags"),

    NTH_TYNE_MAGS("NTH Tyne Mags", "nthTyneMags"),

    LEEDS_MAGS("Leeds Mags", "leedsMags"),

    ALLOA_SHERRIF("Alloa Sherrif Court", "alloaSherrif"),

    IAC_NATIONAL_VIRTUAL("IAC National (Virtual)", "iacNationalVirtual"),

    REMOTE_HEARING("Remote hearing", "remoteHearing"),

    DECISION_WITHOUT_HEARING("Decision Without Hearing", "decisionWithoutHearing");

    private final String label;

    @JsonValue
    private final String code;
}
