package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from FixedLists — do not edit by hand.
 */
@ComplexType(
        name = "hearingTypes",
        generate = true
)
@Getter
@AllArgsConstructor
public enum HearingTypes implements HasLabel {
    HEARING("Hearing", "hearing"),

    APPOINTMENT("Appointment", "appointment");

    private final String label;

    @JsonValue
    private final String code;
}
