package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;

/**
 * Generated by ccd-definition-converter from ComplexTypes — do not edit by hand.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "hoDecisionComm",
        generate = true
)
public class HoDecisionComm {
    @CCD(
            label = "HO decision description",
            searchable = false
    )
    private String description;

    @CCD(
            label = "HO decision dispatch date",
            searchable = false
    )
    private String dispatchDate;

    @CCD(
            label = "HO decision sent date",
            searchable = false
    )
    private String sentDate;

    @CCD(
            label = "HO decision type",
            searchable = false
    )
    private String type;
}
