package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;

/**
 * Generated by ccd-definition-converter from ComplexTypes — do not edit by hand.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "hoMetadata",
        generate = true
)
public class HoMetadata {
    @CCD(
            label = "HO metadata code",
            searchable = false
    )
    private String code;

    @CCD(
            label = "HO metadata value boolean",
            searchable = false
    )
    private String valueBoolean;

    @CCD(
            label = "HO metadata value date",
            searchable = false
    )
    private String valueDateTime;

    @CCD(
            label = "HO metadata value string",
            searchable = false
    )
    private String valueString;
}
