package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;

/**
 * Generated by ccd-definition-converter from ComplexTypes — do not edit by hand.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "hoPerson",
        generate = true
)
public class HoPerson {
    @CCD(
            label = "HO given name",
            searchable = false
    )
    private String givenName;

    @CCD(
            label = "HO family name",
            searchable = false
    )
    private String familyName;

    @CCD(
            label = "HO full name",
            searchable = false
    )
    private String fullName;

    @CCD(
            label = "HO day of birth",
            searchable = false
    )
    private Integer dayOfBirth;

    @CCD(
            label = "HO month of birth",
            searchable = false
    )
    private Integer monthOfBirth;

    @CCD(
            label = "HO year of birth",
            searchable = false
    )
    private Integer yearOfBirth;

    @CCD(
            label = "HO gender",
            searchable = false
    )
    private HoCodeValue gender;

    @CCD(
            label = "HO nationality",
            searchable = false
    )
    private HoCodeValue nationality;
}
