package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from ComplexTypes — do not edit by hand.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "interpreterLanguage",
        generate = true
)
public class InterpreterLanguage {
    @CCD(
            label = "Language",
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "isoLanguages"
    )
    private IsoLanguages language;

    @CCD(
            label = "Dialect",
            hint = "Enter N/A if no dialect required"
    )
    private String languageDialect;
}
