package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from FixedLists — do not edit by hand.
 */
@ComplexType(
        name = "isDecisionAllowed",
        generate = true
)
@Getter
@AllArgsConstructor
public enum IsDecisionAllowed implements HasLabel {
    ALLOWED("Allowed", "allowed"),

    DISMISSED("Dismissed on all grounds", "dismissed");

    private final String label;

    @JsonValue
    private final String code;
}
