package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from FixedLists — do not edit by hand.
 */
@ComplexType(
        name = "isoCountriesGovUk",
        generate = true
)
@Getter
@AllArgsConstructor
public enum IsoCountriesGovUk implements HasLabel {
    AF("Afghanistan", "AF"),

    AX("Aland Islands", "AX"),

    AL("Albania", "AL"),

    DZ("Algeria", "DZ"),

    AD("Andorra", "AD"),

    AO("Angola", "AO"),

    AI("Anguilla", "AI"),

    AG("Antigua / Barbuda", "AG"),

    AR("Argentina", "AR"),

    AM("Armenia", "AM"),

    AW("Aruba", "AW"),

    AC("Ascension Island", "AC"),

    AU("Australia", "AU"),

    AT("Austria", "AT"),

    AZ("Azerbaijan", "AZ"),

    BS("Bahamas", "BS"),

    BH("Bahrain", "BH"),

    BD("Bangladesh", "BD"),

    BB("Barbados", "BB"),

    BY("Belarus", "BY"),

    BE("Belgium", "BE"),

    BZ("Belize", "BZ"),

    BJ("Benin", "BJ"),

    BM("Bermuda", "BM"),

    BT("Bhutan", "BT"),

    BO("Bolivia", "BO"),

    BQ("Bonaire", "BQ"),

    BA("Bosnia & Herzegovina", "BA"),

    BW("Botswana", "BW"),

    BR("Brazil", "BR"),

    IO("British Indian Ocean Territory", "IO"),

    VG("British Virgin Islands", "VG"),

    BN("Brunei", "BN"),

    BG("Bulgaria", "BG"),

    BF("Burkina Faso", "BF"),

    BI("Burundi", "BI"),

    KH("Cambodia", "KH"),

    CM("Cameroon", "CM"),

    CA("Canada", "CA"),

    IC("Canary Islands", "IC"),

    CV("Cape Verde", "CV"),

    KY("Cayman Islands", "KY"),

    CF("Central African Republic", "CF"),

    EA("Ceuta", "EA"),

    TD("Chad", "TD"),

    CL("Chile", "CL"),

    CN("China (People's Republic of)", "CN"),

    CX("Christmas Island", "CX"),

    CO("Colombia", "CO"),

    KM("Comoros", "KM"),

    CD("Congo", "CD"),

    CG("Congo (Brazzaville)", "CG"),

    CK("Cook Islands", "CK"),

    CR("Costa Rica", "CR"),

    HR("Croatia", "HR"),

    CU("Cuba", "CU"),

    CW("Curacao", "CW"),

    CY("Cyprus", "CY"),

    CZ("Czech Republic", "CZ"),

    DK("Denmark", "DK"),

    DJ("Djibouti", "DJ"),

    DM("Dominica", "DM"),

    DO_("Dominican Republic", "DO"),

    EC("Ecuador", "EC"),

    EG("Egypt", "EG"),

    SV("El Salvador", "SV"),

    GQ("Equatorial Guinea", "GQ"),

    ER("Eritrea", "ER"),

    EE("Estonia", "EE"),

    ET("Ethiopia", "ET"),

    FK("Falkland Islands", "FK"),

    FO("Faroe Islands", "FO"),

    FJ("Fiji", "FJ"),

    FI("Finland", "FI"),

    FR("France", "FR"),

    GF("French Guiana", "GF"),

    PF("French Polynesia", "PF"),

    TF("French Southern Territories", "TF"),

    GA("Gabon", "GA"),

    GM("Gambia", "GM"),

    GE("Georgia", "GE"),

    DE("Germany", "DE"),

    GH("Ghana", "GH"),

    GI("Gibraltar", "GI"),

    GR("Greece", "GR"),

    GL("Greenland", "GL"),

    GD("Grenada", "GD"),

    GP("Guadeloupe", "GP"),

    GT("Guatemala", "GT"),

    GN("Guinea", "GN"),

    GW("Guinea-Bissau", "GW"),

    GY("Guyana", "GY"),

    HT("Haiti", "HT"),

    HN("Honduras", "HN"),

    HK("Hong Kong", "HK"),

    HU("Hungary", "HU"),

    IS("Iceland", "IS"),

    IN("India", "IN"),

    ID("Indonesia", "ID"),

    IR("Iran (Islamic Republic of)", "IR"),

    IQ("Iraq", "IQ"),

    IE("Ireland", "IE"),

    IL("Israel", "IL"),

    IT("Italy", "IT"),

    CI("Ivory Coast (Cote D'Ivoire)", "CI"),

    JM("Jamaica", "JM"),

    JP("Japan", "JP"),

    JO("Jordan", "JO"),

    KZ("Kazakhstan", "KZ"),

    KE("Kenya", "KE"),

    KO("Kosovo", "KO"),

    KI("Kiribati", "KI"),

    KW("Kuwait", "KW"),

    KG("Kyrgyzstan", "KG"),

    LA("Laos (People's Democratic Republic of)", "LA"),

    LV("Latvia", "LV"),

    LB("Lebanon", "LB"),

    LS("Lesotho", "LS"),

    LR("Liberia", "LR"),

    LY("Libya", "LY"),

    LI("Liechtenstein", "LI"),

    LT("Lithuania", "LT"),

    LU("Luxembourg", "LU"),

    MO("Macao", "MO"),

    MK("Macedonia", "MK"),

    MG("Madagascar", "MG"),

    YT("Mahore (also known as Mayotte)", "YT"),

    MW("Malawi", "MW"),

    MY("Malaysia", "MY"),

    MV("Maldives", "MV"),

    ML("Mali", "ML"),

    MT("Malta", "MT"),

    MQ("Martinique", "MQ"),

    MR("Mauritania", "MR"),

    MU("Mauritius", "MU"),

    MX("Mexico", "MX"),

    MD("Moldova", "MD"),

    MC("Monaco", "MC"),

    MN("Mongolia", "MN"),

    ME("Montenegro", "ME"),

    MS("Montserrat", "MS"),

    MA("Morocco", "MA"),

    MZ("Mozambique", "MZ"),

    MM("Myanmar", "MM"),

    NA("Namibia", "NA"),

    NR("Nauru Islands", "NR"),

    NP("Nepal", "NP"),

    NL("Netherlands", "NL"),

    NC("New Caledonia", "NC"),

    NZ("New Zealand", "NZ"),

    NI("Nicaragua", "NI"),

    NE("Niger Republic", "NE"),

    NG("Nigeria", "NG"),

    NU("Niue Islands", "NU"),

    KP("North Korea (People's Democratic Republic of)", "KP"),

    NO("Norway", "NO"),

    OM("Oman", "OM"),

    PK("Pakistan", "PK"),

    PW("Palau (known also as Belau)", "PW"),

    PS("Palestine", "PS"),

    PA("Panama", "PA"),

    PG("Papua New Guinea", "PG"),

    PY("Paraguay", "PY"),

    PE("Peru", "PE"),

    PH("Philippines", "PH"),

    PN("Pitcairn Islands", "PN"),

    PL("Poland", "PL"),

    PT("Portugal", "PT"),

    PR("Puerto Rico", "PR"),

    QA("Qatar", "QA"),

    RE("Reunion Islands", "RE"),

    RO("Romania", "RO"),

    RU("Russian Federation", "RU"),

    RW("Rwanda", "RW"),

    SM("San Marino", "SM"),

    ST("Sao Tome & Principe", "ST"),

    SA("Saudi Arabia", "SA"),

    SN("Senegal", "SN"),

    RS("Serbia", "RS"),

    SC("Seychelles", "SC"),

    SL("Sierra Leone", "SL"),

    SG("Singapore", "SG"),

    SK("Slovak Republic", "SK"),

    SI("Slovenia", "SI"),

    SB("Solomon Islands", "SB"),

    SO("Somalia", "SO"),

    ZA("South Africa (Republic of)", "ZA"),

    KR("South Korea (Republic of)", "KR"),

    SS("South Sudan", "SS"),

    ES("Spain", "ES"),

    LK("Sri Lanka", "LK"),

    BQ_2("St Eustatius", "BQ"),

    SH("St Helena", "SH"),

    KN("St Kitts & Nevis", "KN"),

    LC("St Lucia", "LC"),

    MF("St Marteen", "MF"),

    VC("St Vincent & The Grenadines", "VC"),

    SD("Sudan", "SD"),

    SR("Suriname", "SR"),

    SZ("Swaziland", "SZ"),

    SE("Sweden", "SE"),

    CH("Switzerland", "CH"),

    SY("Syria", "SY"),

    TW("Taiwan", "TW"),

    TJ("Tajikistan", "TJ"),

    TZ("Tanzania", "TZ"),

    TH("Thailand", "TH"),

    TL("Timor-Leste", "TL"),

    TG("Togo", "TG"),

    TK("Tokelau Islands", "TK"),

    TO("Tonga", "TO"),

    TT("Trinidad & Tobago", "TT"),

    TN("Tunisia", "TN"),

    TR("Turkey", "TR"),

    TM("Turkmenistan", "TM"),

    TC("Turks & Caicos Islands", "TC"),

    TV("Tuvalu", "TV"),

    UG("Uganda", "UG"),

    UA("Ukraine", "UA"),

    AE("United Arab Emirates", "AE"),

    GB("United Kingdom", "GB"),

    UY("Uruguay", "UY"),

    US("USA", "US"),

    UZ("Uzbekistan", "UZ"),

    VU("Vanuatu", "VU"),

    VA("Vatican City State", "VA"),

    VE("Venezuela", "VE"),

    VN("Vietnam", "VN"),

    WF("Wallis & Futuna Islands", "WF"),

    EH("Western Sahara", "EH"),

    WS("Western Samoa", "WS"),

    YE("Yemen, Republic of", "YE"),

    ZM("Zambia", "ZM"),

    ZW("Zimbabwe", "ZW");

    private final String label;

    @JsonValue
    private final String code;
}
