package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from FixedLists — do not edit by hand.
 */
@ComplexType(
        name = "lateRemissionTypes",
        generate = true
)
@Getter
@AllArgsConstructor
public enum LateRemissionTypes implements HasLabel {
    HO_WAIVER_REMISSION("My client has a remission, e.g. Asylum support, Legal Aid, Home Office waiver, Section 17/20", "hoWaiverRemission"),

    HELP_WITH_FEES("My client has a Help with Fees reference number", "helpWithFees"),

    EXCEPTIONAL_CIRCUMSTANCES_REMISSION("My client wants to apply for an Exceptional Circumstances Remission", "exceptionalCircumstancesRemission");

    private final String label;

    @JsonValue
    private final String code;
}
