package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from FixedLists — do not edit by hand.
 */
@ComplexType(
        name = "listOfStates",
        generate = true
)
@Getter
@AllArgsConstructor
public enum ListOfStates implements HasLabel {
    PENDING_PAYMENT("Payment pending", "pendingPayment"),

    APPEAL_SUBMITTED("Appeal submitted", "appealSubmitted"),

    AWAITING_RESPONDENT_EVIDENCE("Awaiting respondent evidence", "awaitingRespondentEvidence"),

    CASE_UNDER_REVIEW("Case under review", "caseUnderReview"),

    LISTING("Listing", "listing"),

    PREPARE_FOR_HEARING("Prepare For Hearing", "prepareForHearing"),

    DECISION("Decision", "decision"),

    DECIDED("Decided", "decided"),

    FTPA_SUBMITTED("FTPA Submitted", "ftpaSubmitted"),

    FTPA_DECIDED("FTPA Decided", "ftpaDecided"),

    REMITTED("Remitted", "remitted"),

    ENDED("Ended", "ended"),

    REASONS_FOR_APPEAL_SUBMITTED("Reasons for appeal submitted", "reasonsForAppealSubmitted");

    private final String label;

    @JsonValue
    private final String code;
}
