package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.AddressUK;
import uk.gov.hmcts.ccd.sdk.type.FieldType;
import uk.gov.hmcts.ccd.sdk.type.YesOrNo;

/**
 * Generated by ccd-definition-converter from ComplexTypes — do not edit by hand.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "nlrDetails",
        generate = true
)
public class NlrDetails {
    @CCD(
            label = "Given names"
    )
    private String givenNames;

    @CCD(
            label = "Family name"
    )
    private String familyName;

    @CCD(
            label = "Email Address",
            typeOverride = FieldType.Email
    )
    private String emailAddress;

    @CCD(
            label = "Phone number"
    )
    private String phoneNumber;

    @CCD(
            label = "Is same as sponsor",
            showCondition = "emailAddress=\"DUMMY_VALUE_TO_HIDE_FIELD\""
    )
    private YesOrNo sameAsSponsor;

    @CCD(
            label = "Address",
            showCondition = "sameAsSponsor=\"Yes\""
    )
    private AddressUK addressUk;

    @CCD(
            label = "Address",
            showCondition = "sameAsSponsor!=\"Yes\"",
            typeOverride = FieldType.TextArea
    )
    private String address;

    @CCD(
            label = "Idam ID",
            showCondition = "emailAddress=\"DUMMY_VALUE_TO_HIDE_FIELD\""
    )
    private String idamId;
}
