package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;

/**
 * Generated by ccd-definition-converter from ComplexTypes — do not edit by hand.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "otherDetentionFacilityComplexType",
        generate = true
)
public class OtherDetentionFacilityComplexType {
    @CCD(
            label = "Enter the name of the detention facility"
    )
    private String other;
}
