package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.Document;

/**
 * Generated by ccd-definition-converter from ComplexTypes — do not edit by hand.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "outOfTimeDecisionDetails",
        generate = true
)
public class OutOfTimeDecisionDetails {
    @CCD(
            label = "Out of time decision",
            searchable = false
    )
    private String decisionType;

    @CCD(
            label = "Decision maker",
            searchable = false
    )
    private String decisionMaker;

    @CCD(
            label = "Decision notice",
            searchable = false
    )
    private Document decisionDocument;
}
