package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from FixedLists — do not edit by hand.
 */
@ComplexType(
        name = "pageNumberFormat",
        generate = true
)
@Getter
@AllArgsConstructor
public enum PageNumberFormat implements HasLabel {
    PAGE_RANGE("Page Range", "pageRange"),

    NUMBER_OF_PAGES("Number Of Pages", "numberOfPages");

    private final String label;

    @JsonValue
    private final String code;
}
