package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from FixedLists — do not edit by hand.
 */
@ComplexType(
        name = "paginationStyle",
        generate = true
)
@Getter
@AllArgsConstructor
public enum PaginationStyle implements HasLabel {
    OFF("Off", "off"),

    TOP_LEFT("Top Left", "topLeft"),

    TOP_CENTER("Top Center", "topCenter"),

    TOP_RIGHT("Top Right", "topRight"),

    BOTTOM_LEFT("Bottom Left", "bottomLeft"),

    BOTTOM_CENTER("Bottom Center", "bottomCenter"),

    BOTTOM_RIGHT("Bottom Right", "bottomRight");

    private final String label;

    @JsonValue
    private final String code;
}
