package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import java.time.LocalDate;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.AddressUK;

/**
 * Generated by ccd-definition-converter from ComplexTypes — do not edit by hand.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "parties",
        generate = true
)
public class Parties {
    @CCD(
            label = " ",
            searchable = false
    )
    private String appellantTitle;

    @CCD(
            label = " ",
            searchable = false
    )
    private String appellantGivenNames;

    @CCD(
            label = " ",
            searchable = false
    )
    private String appellantFamilyName;

    @CCD(
            label = " ",
            searchable = false
    )
    private AddressUK appellantAddress;

    @CCD(
            label = " ",
            searchable = false
    )
    private String appellantEmailAddress;

    @CCD(
            label = " ",
            searchable = false
    )
    private LocalDate appellantDateOfBirth;
}
