package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import java.time.LocalDate;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.YesOrNo;

/**
 * Generated by ccd-definition-converter from ComplexTypes — do not edit by hand.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "pinInPost",
        generate = true
)
public class PinInPost {
    @CCD(
            label = "Legal representation reference",
            searchable = false
    )
    private String accessCode;

    @CCD(
            label = "Legal representation reference",
            searchable = false
    )
    private LocalDate expiryDate;

    @CCD(
            label = "Legal representation reference",
            searchable = false
    )
    private YesOrNo pinUsed;
}
