package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;

/**
 * Generated by ccd-definition-converter from ComplexTypes — do not edit by hand.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "previousRepresentation",
        generate = true
)
public class PreviousRepresentation {
    @CCD(
            label = "Company Name",
            searchable = false
    )
    private String legalRepCompany;

    @CCD(
            label = "Legal representation reference",
            searchable = false
    )
    private String legalRepReferenceNumber;
}
