package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from FixedLists — do not edit by hand.
 */
@ComplexType(
        name = "prisonNameList",
        generate = true
)
@Getter
@AllArgsConstructor
public enum PrisonNameList implements HasLabel {
    ADDIEWELL("HM Prison Addiewell", "Addiewell"),

    ALBANY("HM Prison Albany", "Albany"),

    ALTCOURSE("HM Prison Altcourse", "Altcourse"),

    ASHFIELD("HM Prison Ashfield", "Ashfield"),

    ASHWELL("HM Prison Ashwell", "Ashwell"),

    ASKHAM_GRANGE("HM Prison Askham Grange", "Askham Grange"),

    AYLESBURY("HM Prison Aylesbury", "Aylesbury"),

    BARLINNIE("HM Prison Barlinnie", "Barlinnie"),

    BEDFORD("HM Prison Bedford", "Bedford"),

    BELLA_CENTRE("Bella Centre", "Bella Centre"),

    BELMARSH("HM Prison Belmarsh", "Belmarsh"),

    BERWYN("HM Prison Berwyn", "Berwyn"),

    BIRMINGHAM("HM Prison Birmingham", "Birmingham"),

    BLAKENHURST("HM Prison Blakenhurst", "Blakenhurst"),

    BLANTYRE_HOUSE("HM Prison Blantyre House", "Blantyre House"),

    BLUNDESTON("HM Prison Blundeston", "Blundeston"),

    BRINSFORD("HM Prison Brinsford", "Brinsford"),

    BRISTOL("HM Prison Bristol", "Bristol"),

    BRIXTON("HM Prison Brixton", "Brixton"),

    BROCKHILL("HM Prison Brockhill", "Brockhill"),

    BRONZEFIELD("HM Prison Bronzefield", "Bronzefield"),

    BUCKLEY_HALL("HM Prison Buckley Hall", "Buckley Hall"),

    BULLINGDON("HM Prison Bullingdon", "Bullingdon"),

    BULLWOOD_HALL("HM Prison Bullwood Hall", "Bullwood Hall"),

    BURE("HM Prison Bure", "Bure"),

    CAMP_HILL("HM Prison Camp Hill", "Camp Hill"),

    CANTERBURY("HM Prison Canterbury", "Canterbury"),

    CARDIFF("HM Prison Cardiff", "Cardiff"),

    CASTINGTON("HM Prison Castington", "Castington"),

    CASTLE_HUNTLY("HM Prison Castle Huntly", "Castle Huntly"),

    CHANNINGS_WOOD("HM Prison Channings Wood", "Channings Wood"),

    CHELMSFORD("HM Prison Chelmsford", "Chelmsford"),

    COLDINGLEY("HM Prison Coldingley", "Coldingley"),

    COOKHAM_WOOD("HM Prison Cookham Wood", "Cookham Wood"),

    CORNTON_VALE("HM Prison Cornton Vale", "Cornton Vale"),

    DARTMOOR("HM Prison Dartmoor", "Dartmoor"),

    DEERBOLT("HM Prison Deerbolt", "Deerbolt"),

    DONCASTER("HM Prison Doncaster", "Doncaster"),

    DORCHESTER("HM Prison Dorchester", "Dorchester"),

    DOVEGATE("HM Prison Dovegate", "Dovegate"),

    DOWNVIEW("HM Prison Downview", "Downview"),

    DRAKE_HALL("HM Prison Drake Hall", "Drake Hall"),

    DUMFRIES("HM Prison Dumfries", "Dumfries"),

    DURHAM("HM Prison Durham", "Durham"),

    EAST_SUTTON_PARK("HM Prison East Sutton Park", "East Sutton Park"),

    EASTWOOD_PARK("HM Prison Eastwood Park", "Eastwood Park"),

    EDINBURGH_SAUGHTON("HM Prison Edinburgh Saughton", "Edinburgh Saughton"),

    EDMUNDS_HILL("HM Prison Edmunds Hill", "Edmunds Hill"),

    ELMLEY("HM Prison Elmley", "Elmley"),

    ERLESTOKE("HM Prison Erlestoke", "Erlestoke"),

    EVERTHORPE("HM Prison Everthorpe", "Everthorpe"),

    EXETER("HM Prison Exeter", "Exeter"),

    FEATHERSTONE("HM Prison Featherstone", "Featherstone"),

    FELTHAM("HM Prison Feltham", "Feltham"),

    FIVE_WELLS("HM Prison Five Wells", "Five Wells"),

    FORD("HM Prison Ford", "Ford"),

    FOREST_BANK("HM Prison Forest Bank", "Forest Bank"),

    FOSTON_HALL("HM Prison Foston Hall", "Foston Hall"),

    FOSSE_WAY("HM Prison Fosse Way", "Fosse Way"),

    FRANKLAND("HM Prison Frankland", "Frankland"),

    FULL_SUTTON("HM Prison Full Sutton", "Full Sutton"),

    GARTH("HM Prison Garth", "Garth"),

    GARTREE("HM Prison Gartree", "Gartree"),

    GLEN_PARVA("HM Prison Glen Parva", "Glen Parva"),

    GLENOCHIL("HM Prison Glenochil", "Glenochil"),

    GLOUCESTER("HM Prison Gloucester", "Gloucester"),

    GRAMPIAN("HM Prison Grampian", "Grampian"),

    GREENOCK("HM Prison Greenock", "Greenock"),

    GRENDON_SPRING_HILL("HM Prison Grendon/Spring Hill", "Grendon/Spring Hill"),

    GUYS_MARSH("HM Prison Guys Marsh", "Guys Marsh"),

    HATFIELD_MAIN_SITE("HMP/YOI Hatfield (Main site)", "Hatfield (Main site)"),

    HATFIELD_LAKES_SITE("HMP/YOI Hatfield (Lakes site)", "Hatfield (Lakes site)"),

    HAVERIGG("HM Prison Haverigg", "Haverigg"),

    HEWELL_GRANGE("HM Prison Hewell", "Hewell Grange"),

    HIGH_DOWN("HM Prison High Down", "High Down"),

    HIGHPOINT("HM Prison Highpoint", "Highpoint"),

    HINDLEY("HM Prison Hindley", "Hindley"),

    HOLLESLEY_BAY("HM Prison Hollesley Bay", "Hollesley Bay"),

    HOLLOWAY("HM Prison Holloway", "Holloway"),

    HOLME_HOUSE("HM Prison Holme House", "Holme House"),

    HULL("HM Prison Hull", "Hull"),

    HUMBER("HM Prison Humber", "Humber"),

    HUNTERCOMBE("HM Prison Huntercombe", "Huntercombe"),

    HYDEBANK_WOOD("HM Prison Hydebank Wood", "Hydebank Wood"),

    INVERNESS("HM Prison Inverness", "Inverness"),

    ISIS("HM Prison Isis", "Isis"),

    ISLE_OF_WIGHT("HM Prison Isle of Wight", "Isle of Wight"),

    KENNET("HM Prison Kennet", "Kennet"),

    KILMARNOCK("HM Prison Kilmarnock", "Kilmarnock"),

    KINGSTON("HM Prison Kingston", "Kingston"),

    KIRKHAM("HM Prison Kirkham", "Kirkham"),

    KIRKLEVINGTON_GRANGE("HM Prison Kirklevington Grange", "Kirklevington Grange"),

    LANCASTER("HM Prison Lancaster", "Lancaster"),

    LANCASTER_FARMS("HM Prison Lancaster Farms", "Lancaster Farms"),

    LATCHMERE_HOUSE("HM Prison Latchmere House", "Latchmere House"),

    LEEDS("HM Prison Leeds", "Leeds"),

    LEICESTER("HM Prison Leicester", "Leicester"),

    LEWES("HM Prison Lewes", "Lewes"),

    LEYHILL("HM Prison Leyhill", "Leyhill"),

    LILIAS_CENTRE("Lilias Centre", "Lilias Centre"),

    LINCOLN("HM Prison Lincoln", "Lincoln"),

    LINDHOLME("HM Prison Lindholme", "Lindholme"),

    LITTLEHEY("HM Prison Littlehey", "Littlehey"),

    LIVERPOOL("HM Prison Liverpool", "Liverpool"),

    LONG_LARTIN("HM Prison Long Lartin", "Long Lartin"),

    LOW_MOSS("HM Prison Low Moss", "Low Moss"),

    LOW_NEWTON("HM Prison Low Newton", "Low Newton"),

    LOWDHAM_GRANGE("HM Prison Lowdham Grange", "Lowdham Grange"),

    MAGILLIGAN("HM Prison Magilligan", "Magilligan"),

    MAGHABERRY("HM Prison Maghaberry", "Maghaberry"),

    MAIDSTONE("HM Prison Maidstone", "Maidstone"),

    MANCHESTER("HM Prison Manchester", "Manchester"),

    MOORLAND("HM Prison Moorland", "Moorland"),

    MORTON_HALL("HM Prison Morton Hall", "Morton Hall"),

    NEW_HALL("HM Prison New Hall", "New Hall"),

    NORTH_SEA_CAMP("HM Prison North Sea Camp", "North Sea Camp"),

    NORTHALLERTON("HM Prison Northallerton", "Northallerton"),

    NORTHUMBERLAND("HM Prison Northumberland", "Northumberland"),

    NORWICH("HM Prison Norwich", "Norwich"),

    NOTTINGHAM("HM Prison Nottingham", "Nottingham"),

    ONLEY("HM Prison Onley", "Onley"),

    OAKWOOD("HM Prison Oakwood ", "Oakwood"),

    PARC("HM Prison Parc", "Parc"),

    PARKHURST("HM Prison Parkhurst", "Parkhurst"),

    PENTONVILLE("HM Prison Pentonville", "Pentonville"),

    PERTH("HM Prison Perth", "Perth"),

    PETERBOROUGH("HM Prison Peterborough", "Peterborough"),

    POLMONT("HM YOI Polmont", "Polmont"),

    PORTLAND("HM Prison Portland", "Portland"),

    PRESCOED("HM Prison Prescoed", "Prescoed"),

    PRESTON("HM Prison Preston", "Preston"),

    RANBY("HM Prison Ranby", "Ranby"),

    READING("HM Prison Reading", "Reading"),

    RISLEY("HM Prison Risley", "Risley"),

    ROCHESTER("HM Prison Rochester", "Rochester"),

    RYE_HILL("HM Prison Rye Hill", "Rye Hill"),

    SEND("HM Prison Send", "Send"),

    SHEPTON_MALLET("HM Prison Shepton Mallet", "Shepton Mallet"),

    SHOTTS("HM Prison Shotts", "Shotts"),

    SHREWSBURY("HM Prison Shrewsbury", "Shrewsbury"),

    SPRING_HILL("HM Prison Spring Hill", "Spring Hill"),

    STAFFORD("HM Prison Stafford", "Stafford"),

    STANDFORD_HILL("HM Prison Standford Hill", "Standford Hill"),

    STOCKEN("HM Prison Stocken", "Stocken"),

    STOKE_HEATH("HM Prison Stoke Heath", "Stoke Heath"),

    STIRLING("HM Prison YOI Stirling", "Stirling"),

    STYAL("HM Prison Styal", "Styal"),

    SUDBURY("HM Prison Sudbury", "Sudbury"),

    SWALESIDE("HM Prison Swaleside", "Swaleside"),

    SWANSEA("HM Prison Swansea", "Swansea"),

    SWINFEN_HALL("HM Prison Swinfen Hall", "Swinfen Hall"),

    THAMESIDE("HM Prison Thameside", "Thameside"),

    THE_MOUNT("HM Prison The Mount", "The Mount"),

    THE_VERNE("HM Prison The Verne", "The Verne"),

    THE_WEARE("HM Prison The Weare", "The Weare"),

    THORN_CROSS("HM Prison Thorn Cross", "Thorn Cross"),

    USK("HM Prison Usk", "Usk"),

    WAKEFIELD("HM Prison Wakefield", "Wakefield"),

    WANDSWORTH("HM Prison Wandsworth", "Wandsworth"),

    WARREN_HILL("HM Prison Warren Hill", "Warren Hill"),

    WAYLAND("HM Prison Wayland", "Wayland"),

    WEALSTUN("HM Prison Wealstun", "Wealstun"),

    WELLINGBOROUGH("HM Prison Wellingborough", "Wellingborough"),

    WERRINGTON("HM Prison Werrington", "Werrington"),

    WETHERBY("HM Prison Wetherby", "Wetherby"),

    WHATTON("HM Prison Whatton", "Whatton"),

    WHITEMOOR("HM Prison Whitemoor", "Whitemoor"),

    WINCHESTER("HM Prison Winchester", "Winchester"),

    WOLDS("HM Prison Wolds", "Wolds"),

    WOODHILL("HM Prison Woodhill", "Woodhill"),

    WORMWOOD_SCRUBS("HM Prison Wormwood Scrubs", "Wormwood Scrubs"),

    WYMOTT("HM Prison Wymott", "Wymott");

    private final String label;

    @JsonValue
    private final String code;
}
