package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from FixedLists — do not edit by hand.
 */
@ComplexType(
        name = "reasonForLinkAppealOptions",
        generate = true
)
@Getter
@AllArgsConstructor
public enum ReasonForLinkAppealOptions implements HasLabel {
    OTHER_APPEAL_DECIDED("Other appeal decided", "Other appeal decided"),

    OTHER_APPEAL_PENDING("Other appeal pending", "Other appeal pending"),

    HOME_OFFICE_REQUEST("Home Office request", "Home Office request"),

    BAIL("Bail", "Bail"),

    GUARDIAN("Guardian", "Guardian"),

    SHARED_EVIDENCE("Shared evidence", "Shared evidence"),

    FAMILIAL("Familial", "Familial");

    private final String label;

    @JsonValue
    private final String code;
}
