package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from FixedLists — do not edit by hand.
 */
@ComplexType(
        name = "remissionTypes",
        generate = true
)
@Getter
@AllArgsConstructor
public enum RemissionTypes implements HasLabel {
    NO_REMISSION("The appellant is not eligible for a fee remission", "noRemission"),

    HO_WAIVER_REMISSION("The appellant has a remission, e.g. Asylum support, Legal Aid, Home Office waiver, Section 17/20", "hoWaiverRemission"),

    HELP_WITH_FEES("The appellant has applied for help with fees", "helpWithFees"),

    EXCEPTIONAL_CIRCUMSTANCES_REMISSION("The appellant wants to apply for an Exceptional Circumstances Remission", "exceptionalCircumstancesRemission");

    private final String label;

    @JsonValue
    private final String code;
}
