package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from FixedLists — do not edit by hand.
 */
@ComplexType(
        name = "remissionDecisionOptions",
        generate = true
)
@Getter
@AllArgsConstructor
public enum RemissionDecisionOptions implements HasLabel {
    APPROVED("Approved", "approved"),

    PARTIALLY_APPROVED("Partially approved", "partiallyApproved"),

    REJECTED("Rejected", "rejected");

    private final String label;

    @JsonValue
    private final String code;
}
