package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.Document;
import uk.gov.hmcts.ccd.sdk.type.FieldType;
import uk.gov.hmcts.ccd.sdk.type.ListValue;

/**
 * Generated by ccd-definition-converter from ComplexTypes — do not edit by hand.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "remissionDetails",
        generate = true
)
public class RemissionDetails {
    @CCD(
            label = "Fee remission type",
            searchable = false
    )
    private String feeRemissionType;

    @CCD(
            label = "Asylum Support reference number",
            searchable = false
    )
    private String asylumSupportReference;

    @CCD(
            label = "Asylum Support confirmation letter",
            searchable = false
    )
    private Document asylumSupportDocument;

    @CCD(
            label = "Legal Aid account number",
            searchable = false
    )
    private String legalAidAccountNumber;

    @CCD(
            label = "Local authority letter",
            searchable = false
    )
    private Document section17Document;

    @CCD(
            label = "Local authority letter",
            searchable = false
    )
    private Document section20Document;

    @CCD(
            label = "Home Office fee waiver letter",
            searchable = false
    )
    private Document homeOfficeWaiverDocument;

    @CCD(
            label = "Help with Fees reference number",
            searchable = false
    )
    private String helpWithFeesReferenceNumber;

    @CCD(
            label = "Explain the exceptional circumstances which justify remission of the fee",
            searchable = false
    )
    private String exceptionalCircumstances;

    @CCD(
            label = "Supporting evidence",
            searchable = false
    )
    private List<ListValue<Document>> remissionEcEvidenceDocuments;

    @CCD(
            label = "Decision",
            searchable = false
    )
    private String remissionDecision;

    @CCD(
            label = "Fee",
            searchable = false,
            typeOverride = FieldType.MoneyGBP
    )
    private String feeAmount;

    @CCD(
            label = "Amount remitted",
            searchable = false,
            typeOverride = FieldType.MoneyGBP
    )
    private String amountRemitted;

    @CCD(
            label = "Amount left to pay",
            searchable = false,
            typeOverride = FieldType.MoneyGBP
    )
    private String amountLeftToPay;

    @CCD(
            label = "Reason for decision",
            searchable = false
    )
    private String remissionDecisionReason;

    @CCD(
            label = "Local authority letters",
            searchable = false
    )
    private List<ListValue<DocumentWithMetadata>> localAuthorityLetters;

    @CCD(
            label = "Help with fees option",
            searchable = false
    )
    private String helpWithFeesOption;
}
