package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from FixedLists — do not edit by hand.
 */
@ComplexType(
        name = "rpDcAppealHearingOptions",
        generate = true
)
@Getter
@AllArgsConstructor
public enum RpDcAppealHearingOptions implements HasLabel {
    DECISION_WITH_HEARING("Decision with a hearing", "decisionWithHearing"),

    DECISION_WITHOUT_HEARING("Decision without a hearing", "decisionWithoutHearing");

    private final String label;

    @JsonValue
    private final String code;
}
