package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from FixedLists — do not edit by hand.
 */
@ComplexType(
        name = "singleSexCourtType",
        generate = true
)
@Getter
@AllArgsConstructor
public enum SingleSexCourtType implements HasLabel {
    ALL_MALE("All male", "All male"),

    ALL_FEMALE("All female", "All female");

    private final String label;

    @JsonValue
    private final String code;
}
