package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.ListValue;

/**
 * Generated by ccd-definition-converter from ComplexTypes — do not edit by hand.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "statutoryTimeframe24Weeks",
        generate = true
)
public class StatutoryTimeframe24Weeks {
    @CCD(
            label = "History",
            searchable = false
    )
    private List<ListValue<StatutoryTimeframe24WeeksHistory>> history;

    @CCD(
            label = "Home Office response",
            searchable = false
    )
    private HomeOfficeStatutoryTimeframeDto homeOfficeResponse;
}
