package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import uk.gov.hmcts.ccd.sdk.api.CCD;

/**
 * Generated by ccd-definition-converter from State — do not edit by hand.
 */
public enum State {
    @CCD(
            label = "Appeal started",
            hint = "# Case record for ${appealReferenceNumber}<br /><font color=\"#1C8242\">${xuiBannerText}</font>"
    )
    appealStarted,

    @CCD(
            label = "Appeal started",
            hint = "# Case record for ${appealReferenceNumber}<br /><font color=\"#1C8242\">${xuiBannerText}</font>"
    )
    appealStartedByAdmin,

    @CCD(
            label = "Appeal submitted",
            hint = "# Case record for ${appealReferenceNumber}<br /><font color=\"#1C8242\">${xuiBannerText}</font>"
    )
    appealSubmitted,

    @CCD(
            label = "Awaiting respondent evidence",
            hint = "# Case record for ${appealReferenceNumber}<br /><font color=\"#1C8242\">${xuiBannerText}</font>"
    )
    awaitingRespondentEvidence,

    @CCD(
            label = "Case building",
            hint = "# Case record for ${appealReferenceNumber}<br /><font color=\"#1C8242\">${xuiBannerText}</font>"
    )
    caseBuilding,

    @CCD(
            label = "Case under review",
            hint = "# Case record for ${appealReferenceNumber}<br /><font color=\"#1C8242\">${xuiBannerText}</font>"
    )
    caseUnderReview,

    @CCD(
            label = "Respondent review",
            hint = "# Case record for ${appealReferenceNumber}<br /><font color=\"#1C8242\">${xuiBannerText}</font>"
    )
    respondentReview,

    @CCD(
            label = "Submit hearing requirements",
            hint = "# Case record for ${appealReferenceNumber}<br /><font color=\"#1C8242\">${xuiBannerText}</font>"
    )
    submitHearingRequirements,

    @CCD(
            label = "Listing",
            hint = "# Case record for ${appealReferenceNumber}<br /><font color=\"#1C8242\">${xuiBannerText}</font>"
    )
    listing,

    @CCD(
            label = "Prepare for hearing",
            hint = "# Case record for ${appealReferenceNumber}<br /><font color=\"#1C8242\">${xuiBannerText}</font>"
    )
    prepareForHearing,

    @CCD(
            label = "Final bundling",
            hint = "# Case record for ${appealReferenceNumber}<br /><font color=\"#1C8242\">${xuiBannerText}</font>"
    )
    finalBundling,

    @CCD(
            label = "Pre hearing",
            hint = "# Case record for ${appealReferenceNumber}<br /><font color=\"#1C8242\">${xuiBannerText}</font>"
    )
    preHearing,

    @CCD(
            label = "Decision",
            hint = "# Case record for ${appealReferenceNumber}<br /><font color=\"#1C8242\">${xuiBannerText}</font>"
    )
    decision,

    @CCD(
            label = "Decided",
            hint = "# Case record for ${appealReferenceNumber}<br /><font color=\"#1C8242\">${xuiBannerText}</font>"
    )
    decided,

    @CCD(
            label = "Ended",
            hint = "# Case record for ${appealReferenceNumber}<br /><font color=\"#1C8242\">${xuiBannerText}</font>"
    )
    ended,

    @CCD(
            label = "Appeal taken offline",
            hint = "# Case record for ${appealReferenceNumber}<br /><font color=\"#1C8242\">${xuiBannerText}</font>"
    )
    appealTakenOffline,

    @CCD(
            label = "Awaiting reasons for appeal",
            hint = "# Case record for ${appealReferenceNumber}<br /><font color=\"#1C8242\">${xuiBannerText}</font>",
            description = "Awaiting the appellant entering reasons for appeal"
    )
    awaitingReasonsForAppeal,

    @CCD(
            label = "Reasons for appeal submitted",
            hint = "# Case record for ${appealReferenceNumber}<br /><font color=\"#1C8242\">${xuiBannerText}</font>",
            description = "The appellant has entered their reasons for appeal"
    )
    reasonsForAppealSubmitted,

    @CCD(
            label = "FTPA submitted",
            hint = "# Case record for ${appealReferenceNumber}<br /><font color=\"#1C8242\">${xuiBannerText}</font>",
            description = "An Upper Tribunal has been submitted by Appellant or Home Office"
    )
    ftpaSubmitted,

    @CCD(
            label = "FTPA decided",
            hint = "# Case record for ${appealReferenceNumber}<br /><font color=\"#1C8242\">${xuiBannerText}</font>",
            description = "A leadership/resident judge record the ftpa decision"
    )
    ftpaDecided,

    @CCD(
            label = "Awaiting clarifying question answers",
            hint = "# Case record for ${appealReferenceNumber}<br /><font color=\"#1C8242\">${xuiBannerText}</font>",
            description = "Clarifying questions have been asked and awaiting the appellants response"
    )
    awaitingClarifyingQuestionsAnswers,

    @CCD(
            label = "Clarifying questions answers submitted",
            hint = "# Case record for ${appealReferenceNumber}<br /><font color=\"#1C8242\">${xuiBannerText}</font>",
            description = "Clarifying questions have been answered by the appellant"
    )
    clarifyingQuestionsAnswersSubmitted,

    @CCD(
            label = "Awaiting CMA requirements",
            hint = "# Case record for ${appealReferenceNumber}<br /><font color=\"#1C8242\">${xuiBannerText}</font>",
            description = "Awaiting CMA requirements from appellant or legal rep"
    )
    awaitingCmaRequirements,

    @CCD(
            label = "Submitted CMA requirements",
            hint = "# Case record for ${appealReferenceNumber}<br /><font color=\"#1C8242\">${xuiBannerText}</font>",
            description = "Submitted CMA requirements from appellant or legal rep"
    )
    cmaRequirementsSubmitted,

    @CCD(
            label = "CMA requirements agreed",
            hint = "# Case record for ${appealReferenceNumber}<br /><font color=\"#1C8242\">${xuiBannerText}</font>",
            description = "CMA requirements reviewed by tcw"
    )
    cmaAdjustmentsAgreed,

    @CCD(
            label = "CMA listed",
            hint = "# Case record for ${appealReferenceNumber}<br /><font color=\"#1C8242\">${xuiBannerText}</font>"
    )
    cmaListed,

    @CCD(
            label = "Adjourned",
            hint = "# Case record for ${appealReferenceNumber}<br /><font color=\"#1C8242\">${xuiBannerText}</font>",
            description = "Appeal adjourned"
    )
    adjourned,

    @CCD(
            label = "Payment pending",
            hint = "# Case record for ${appealReferenceNumber}<br /><font color=\"#1C8242\">${xuiBannerText}</font>"
    )
    pendingPayment,

    @CCD(
            label = "Remitted",
            hint = "# Case record for ${appealReferenceNumber}<br /><font color=\"#1C8242\">${xuiBannerText}</font>"
    )
    remitted,

    @CCD(
            label = "Migrated",
            hint = "# Case record for ${appealReferenceNumber}<br /><font color=\"#1C8242\">${xuiBannerText}</font>"
    )
    migrated
}
