package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from FixedLists — do not edit by hand.
 */
@ComplexType(
        name = "timeExtensionStatus",
        generate = true
)
@Getter
@AllArgsConstructor
public enum TimeExtensionStatus implements HasLabel {
    IN_PROGRESS("In progress", "inProgress"),

    SUBMITTED("Submitted", "submitted"),

    REFUSED("Refused", "refused"),

    GRANTED("Granted", "granted");

    private final String label;

    @JsonValue
    private final String code;
}
