package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.HasRole;

/**
 * Generated by ccd-definition-converter from AuthorisationCaseType/CaseRoles — do not edit by hand.
 */
@Getter
@AllArgsConstructor
public enum UserRole implements HasRole {
    CASEWORKER_IA_CASEOFFICER("caseworker-ia-caseofficer", "CRU"),

    CASEWORKER_WA_TASK_CONFIGURATION("caseworker-wa-task-configuration", "CRU"),

    CITIZEN("citizen", "CRU"),

    CASEWORKER_IA_LEGALREP_SOLICITOR("caseworker-ia-legalrep-solicitor", "CRU"),

    CASEWORKER_IA_SYSTEM("caseworker-ia-system", "CRU"),

    CASEWORKER_IA_SYSTEM_ACCESS("caseworker-ia-system-access", "CRU"),

    CASEWORKER_IA_ADMOFFICER("caseworker-ia-admofficer", "CRU"),

    CASEWORKER_IA_HOMEOFFICEAPC("caseworker-ia-homeofficeapc", "CRU"),

    CASEWORKER_IA_HOMEOFFICELART("caseworker-ia-homeofficelart", "CRU"),

    CASEWORKER_IA_HOMEOFFICEPOU("caseworker-ia-homeofficepou", "CRU"),

    CASEWORKER_IA_RESPONDENTOFFICER("caseworker-ia-respondentofficer", "CRU"),

    CASEWORKER_IA_IACJUDGE("caseworker-ia-iacjudge", "CRU"),

    CASEWORKER_RAS_VALIDATION("caseworker-ras-validation", "R"),

    CASEWORKER_CAA("caseworker-caa", "CRU"),

    CASEWORKER_APPROVER("caseworker-approver", "CRU"),

    IA_SPECIFIC_ACCESS_LEGAL_OPS_PROFILE("ia_specific_access_legal_ops_profile", "R"),

    IA_SPECIFIC_ACCESS_ADMIN_PROFILE("ia_specific_access_admin_profile", "R"),

    IA_SPECIFIC_ACCESS_JUDGE_PROFILE("ia_specific_access_judge_profile", "R"),

    IA_SPECIFIC_ACCESS_CTSC_PROFILE("ia_specific_access_ctsc_profile", "R"),

    GS_PROFILE("GS_profile", "R"),

    CFT_TTL_MANAGER("cft-ttl-manager", "CRU"),

    CASEWORKER_IA_INTERNAL("caseworker-ia-internal", "CRU"),

    CASEWORKER_IA_RPAROBOT("caseworker-ia-rparobot", "CRU"),

    IA_CASELINKS_PROFILE("ia_caselinks_profile", ""),

    IA_CASEFLAGS_PROFILE("ia_caseflags_profile", ""),

    IA_CASEFLAGS_READONLY_PROFILE("ia_caseflags_readonly_profile", ""),

    NEXT_HEARING_DATE_ADMIN("next-hearing-date-admin", ""),

    CASEWORKER_IA_HOMEOFFICEBAIL("caseworker-ia-homeofficebail", ""),

    @CCD(
            label = "Legal Representative",
            hint = "Legal Representative"
    )
    LEGALREPRESENTATIVE("[LEGALREPRESENTATIVE]", ""),

    @CCD(
            label = "Citizen",
            hint = "Citizen"
    )
    CREATOR("[CREATOR]", "");

    private final String role;

    private final String caseTypePermissions;
}
