package uk.gov.hmcts.reform.iacaseapi.ccd.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.YesOrNo;

/**
 * Generated by ccd-definition-converter from ComplexTypes — do not edit by hand.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "witnessDetails",
        generate = true
)
public class WitnessDetails {
    @CCD(
            label = "Given names",
            searchable = false
    )
    private String witnessName;

    @CCD(
            label = "Family name",
            searchable = false
    )
    private String witnessFamilyName;

    @CCD(
            label = " ",
            showCondition = "witnessPartyId=\"DUMMY_VALUE_TO_HIDE_FIELD\"",
            searchable = false
    )
    private String witnessPartyId;

    @CCD(
            label = " ",
            showCondition = "isWitnessDeleted=\"DUMMY_VALUE_TO_HIDE_FIELD\"",
            searchable = false,
            retainHiddenValue = true
    )
    private YesOrNo isWitnessDeleted;
}
