package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code allocateTheCase2} of event {@code allocateTheCase}.
 */
public final class AllocateTheCaseAllocateTheCase2Page {
    private AllocateTheCaseAllocateTheCase2Page() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("allocateTheCase2");
        fields.showCondition("allocateTheCaseTo=\"caseworker\"");
        fields.readonlyNoSummary(CaseData::getCaseWorkerLocationTitle);
        fields.mandatory(CaseData::getCaseWorkerLocationList);
    }
}
