package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code ftpaAppellantSubmissionOutOfTimePage} of event {@code applyForFTPAAppellant}.
 */
public final class ApplyForFTPAAppellantFtpaAppellantSubmissionOutOfTimePagePage {
    private ApplyForFTPAAppellantFtpaAppellantSubmissionOutOfTimePagePage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("ftpaAppellantSubmissionOutOfTimePage");
        fields.pageLabel("Late application");
        fields.showCondition("ftpaAppellantSubmissionOutOfTime=\"Yes\"");
        fields.readonlyNoSummary(CaseData::getFtpaAppellantSubmissionOutOfTime)
                    .fieldShowCondition("ftpaAppellantOutOfTimeText=\"DUMMY_FIELD_TO_HIDE\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getFtpaAppellantOutOfTimeText)
                    .publish(false);
        fields.mandatory(CaseData::getFtpaAppellantOutOfTimeExplanation)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getFtpaAppellantFileUploadAdvice)
                    .publish(false);
        fields.optional(CaseData::getFtpaAppellantOutOfTimeDocuments)
                    .publish(false);
    }
}
