package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.Direction;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code changeDirectionDueDate2} of event {@code changeDirectionDueDate}.
 */
public final class ChangeDirectionDueDateChangeDirectionDueDate2Page {
    private ChangeDirectionDueDateChangeDirectionDueDate2Page() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("changeDirectionDueDate2");
        fields.readonlyNoSummary(CaseData::getChangeDirectionDueDateTitle2)
                    .publish(false);
        fields.readonly(CaseData::getDirectionEditExplanation)
                    .publish(false);
        fields.readonly(CaseData::getDirectionEditParties)
                    .publish(false);
        fields.readonly(CaseData::getDirectionEditDateSent)
                    .publish(false);
        fields.mandatory(CaseData::getDirectionEditDateDue)
                    .publish(false);
        fields.complex(CaseData::getLastModifiedDirection, false)
                    .optional(Direction::getExplanation)
                    .publish(true)
                    .optional(Direction::getParties)
                    .publish(true)
                    .optional(Direction::getDateDue)
                    .publish(true)
                    .optional(Direction::getDateSent)
                    .publish(true)
                    .optional(Direction::getTag)
                    .publish(true)
                    .optional(Direction::getPreviousDates)
                    .publish(true)
                    .optional(Direction::getUniqueId)
                    .publish(true)
                    .optional(Direction::getDirectionType)
                    .publish(true).done()
                    .fieldShowCondition("directionEditDateDue=\"DUMMY_FIELD_TO_HIDE\"");
        fields.mandatoryNoSummary(CaseData::getAppellantInDetention)
                    .fieldShowCondition("changeDirectionDueDateTitle=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
        fields.mandatoryNoSummary(CaseData::getIsNotificationTurnedOff)
                    .fieldShowCondition("changeDirectionDueDateTitle=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
    }
}
