package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code ftpaAppellantDecisionOutcome} of event {@code decideFtpaApplication}.
 */
public final class DecideFtpaApplicationFtpaAppellantDecisionOutcomePage {
    private DecideFtpaApplicationFtpaAppellantDecisionOutcomePage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("ftpaAppellantDecisionOutcome");
        fields.pageLabel("Decision");
        fields.showCondition("ftpaApplicantType=\"appellant\"");
        fields.mandatory(CaseData::getFtpaAppellantRjDecisionOutcomeType);
    }
}
