package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code ftpaApplicantType} of event {@code decideFtpaApplication}.
 */
public final class DecideFtpaApplicationFtpaApplicantTypePage {
    private DecideFtpaApplicationFtpaApplicantTypePage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("ftpaApplicantType");
        fields.pageLabel("Applicant");
        fields.mandatory(CaseData::getFtpaApplicantType);
        fields.mandatoryNoSummary(CaseData::getFtpaAppellantDecisionObjectionsVisible)
                    .fieldShowCondition("ftpaApplicantType=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getFtpaRespondentDecisionObjectionsVisible)
                    .fieldShowCondition("ftpaApplicantType=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getFtpaAppellantDecisionListingVisible)
                    .fieldShowCondition("ftpaApplicantType=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getFtpaRespondentDecisionListingVisible)
                    .fieldShowCondition("ftpaApplicantType=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getFtpaAppellantNoticeOfDecisionSetAsideVisible)
                    .fieldShowCondition("ftpaApplicantType=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getFtpaRespondentNoticeOfDecisionSetAsideVisible)
                    .fieldShowCondition("ftpaApplicantType=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getFtpaAppellantDecisionReasonsNotesVisible)
                    .fieldShowCondition("ftpaApplicantType=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getFtpaRespondentDecisionReasonsNotesVisible)
                    .fieldShowCondition("ftpaApplicantType=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getIsAdmin)
                    .fieldShowCondition("ftpaApplicantType=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
    }
}
