package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code ftpaAppellantFinalR35Notice} of event {@code decideFtpaApplication}.
 */
public final class DecideFtpaApplicationFtpaAppellantFinalR35NoticePage {
    private DecideFtpaApplicationFtpaAppellantFinalR35NoticePage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("ftpaAppellantFinalR35Notice");
        fields.pageLabel("Final rule 35 notice");
        fields.showCondition("ftpaApplicantType=\"appellant\" AND ftpaAppellantRjDecisionOutcomeType=\"reheardRule35\"");
        fields.readonlyNoSummary(CaseData::getFtpaAppellantR35RjDecisionDocumentUploadAdvice)
                    .publish(false);
        fields.mandatory(CaseData::getFtpaR35AppellantDocument)
                    .caseEventFieldLabel("Document")
                    .publish(false);
    }
}
