package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code ftpaRespondentDecisionRemadeRule32} of event {@code decideFtpaApplication}.
 */
public final class DecideFtpaApplicationFtpaRespondentDecisionRemadeRule32Page {
    private DecideFtpaApplicationFtpaRespondentDecisionRemadeRule32Page() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("ftpaRespondentDecisionRemadeRule32");
        fields.pageLabel("Reasoning");
        fields.showCondition("ftpaApplicantType=\"respondent\" AND (ftpaRespondentRjDecisionOutcomeType=\"remadeRule31\" OR ftpaRespondentRjDecisionOutcomeType=\"remadeRule32\")");
        fields.mandatory(CaseData::getFtpaRespondentDecisionRemadeRule32Text)
                    .publish(false);
    }
}
