package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.MakeAnApplication;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code decideAnApplication} of event {@code decideAnApplication}.
 */
public final class DecideAnApplicationDecideAnApplicationPage {
    private DecideAnApplicationDecideAnApplicationPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("decideAnApplication");
        fields.readonlyNoSummary(CaseData::getDecideAnApplicationReviewAdvice)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getDecideAnApplicationHeader)
                    .caseEventFieldLabel("## ${makeAnApplicationsList.value.label}")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getMakeAnApplicationFieldsLabel)
                    .caseEventFieldLabel("${makeAnApplicationFields}")
                    .publish(false);
        fields.mandatory(CaseData::getMakeAnApplicationDecision)
                    .publish(false);
        fields.mandatory(CaseData::getMakeAnApplicationDecisionReason)
                    .publish(false);
        fields.complex(CaseData::getLastModifiedApplication, false)
                    .optional(MakeAnApplication::getApplicant)
                    .optional(MakeAnApplication::getType)
                    .optional(MakeAnApplication::getDetails)
                    .optional(MakeAnApplication::getEvidence)
                    .optional(MakeAnApplication::getDate)
                    .optional(MakeAnApplication::getDecision)
                    .optional(MakeAnApplication::getState)
                    .optional(MakeAnApplication::getApplicantRole)
                    .optional(MakeAnApplication::getDecisionReason)
                    .optional(MakeAnApplication::getDecisionDate)
                    .optional(MakeAnApplication::getDecisionMaker).done()
                    .fieldShowCondition("makeAnApplicationDecision=\"DUMMY_FIELD_TO_HIDE\"");
        fields.mandatoryNoSummary(CaseData::getIsIntegrated)
                    .fieldShowCondition("makeAnApplicationDecision=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
        fields.mandatoryNoSummary(CaseData::getAppellantInDetention)
                    .fieldShowCondition("makeAnApplicationDecision=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
        fields.mandatoryNoSummary(CaseData::getIsNotificationTurnedOff)
                    .fieldShowCondition("makeAnApplicationDecision=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
        fields.readonlyNoSummary(CaseData::getStf24wCurrentStatusAutoGenerated)
                    .fieldShowCondition("makeAnApplicationDecision=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue()
                    .publish(false);
    }
}
