package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code ftpaDecisionLstIns} of event {@code decideFtpaApplication}.
 */
public final class DecideFtpaApplicationFtpaDecisionLstInsPage {
    private DecideFtpaApplicationFtpaDecisionLstInsPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("ftpaDecisionLstIns");
        fields.pageLabel("Listing instructions");
        fields.showCondition("ftpaAppellantDecisionListingVisible=\"Yes\" OR ftpaRespondentDecisionListingVisible=\"Yes\"");
        fields.readonlyNoSummary(CaseData::getFtpaDecisionListingInsAdvice)
                    .publish(false);
        fields.optional(CaseData::getFtpaAppellantDecisionLstIns)
                    .fieldShowCondition("ftpaApplicantType=\"appellant\" AND ftpaAppellantRjDecisionOutcomeType!=\"reheardRule35\"")
                    .publish(false);
        fields.optional(CaseData::getFtpaRespondentDecisionLstIns)
                    .fieldShowCondition("ftpaApplicantType=\"respondent\" AND ftpaRespondentRjDecisionOutcomeType!=\"reheardRule35\"")
                    .publish(false);
        fields.optionalNoSummary(CaseData::getJudgesNamesToExclude)
                    .publish(false);
        fields.optional(CaseData::getFtpaAppellantR35ListingAdditionalIns)
                    .fieldShowCondition("ftpaApplicantType=\"appellant\" AND ftpaAppellantRjDecisionOutcomeType=\"reheardRule35\"")
                    .caseEventFieldLabel("Enter any additional instructions")
                    .publish(false);
        fields.optional(CaseData::getFtpaRespondentR35ListingAdditionalIns)
                    .fieldShowCondition("ftpaApplicantType=\"respondent\" AND ftpaRespondentRjDecisionOutcomeType=\"reheardRule35\"")
                    .caseEventFieldLabel("Enter any additional instructions")
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getAppellantInDetention)
                    .fieldShowCondition("ftpaRespondentDecisionLstIns=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
        fields.mandatoryNoSummary(CaseData::getIsNotificationTurnedOff)
                    .fieldShowCondition("ftpaRespondentDecisionLstIns=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
    }
}
