package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code ftpaRespondentFinalR35Notice} of event {@code decideFtpaApplication}.
 */
public final class DecideFtpaApplicationFtpaRespondentFinalR35NoticePage {
    private DecideFtpaApplicationFtpaRespondentFinalR35NoticePage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("ftpaRespondentFinalR35Notice");
        fields.pageLabel("Final rule 35 notice");
        fields.showCondition("ftpaApplicantType=\"respondent\" AND ftpaRespondentRjDecisionOutcomeType=\"reheardRule35\"");
        fields.readonlyNoSummary(CaseData::getFtpaRespondentR35RjDecisionDocumentUploadAdvice)
                    .publish(false);
        fields.mandatory(CaseData::getFtpaR35RespondentDocument)
                    .caseEventFieldLabel("Document")
                    .publish(false);
    }
}
