package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.InterpreterSignLanguage;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code witness3InterpreterSignLanguage} of event {@code draftHearingRequirements}.
 */
public final class DraftHearingRequirementsWitness3InterpreterSignLanguagePage {
    private DraftHearingRequirementsWitness3InterpreterSignLanguagePage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("witness3InterpreterSignLanguage");
        fields.showCondition("witness3InterpreterLanguageCategoryCONTAINS\"signLanguageInterpreter\" AND isWitnessesAttending=\"Yes\" AND isAnyWitnessInterpreterRequired=\"Yes\"");
        fields.complex(CaseData::getWitness3InterpreterSignLanguage)
                    .mandatory(InterpreterSignLanguage::getLanguageRefData)
                    .optional(InterpreterSignLanguage::getLanguageManualEntry)
                    .mandatory(InterpreterSignLanguage::getLanguageManualEntryDescription).done()
                    .caseEventFieldLabel("Which sign language is needed for ${witness3.witnessName} ${witness3.witnessFamilyName}?");
    }
}
