package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code checklist} of event {@code editAppealAfterSubmit}.
 */
public final class EditAppealAfterSubmitChecklistPage {
    private EditAppealAfterSubmitChecklistPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("checklist");
        fields.showCondition("isAdmin!=\"Yes\" AND appellantInDetention!=\"Yes\"");
        fields.readonlyNoSummary(CaseData::getIsAdmin)
                    .fieldShowCondition("checklistTitle4=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getChecklistTitle4)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getIsOutOfCountryEnabled)
                    .fieldShowCondition("checklistTitle4=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getHomeOfficeReferenceNumberBeforeEdit)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getAppellantInDetention)
                    .fieldShowCondition("checklistTitle4=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getIsNotificationTurnedOff)
                    .fieldShowCondition("checklistTitle4=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .publish(false);
    }
}
