package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code appellantContactPreference} of event {@code editAppeal}.
 */
public final class EditAppealAppellantContactPreferencePage {
    private EditAppealAppellantContactPreferencePage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("appellantContactPreference");
        fields.pageLabel("The appellant's contact preference");
        fields.showCondition("appellantInDetention!=\"Yes\" AND isAdmin!=\"Yes\"");
        fields.readonlyNoSummary(CaseData::getAppellantContactPreferenceTitle);
        fields.mandatory(CaseData::getContactPreference);
        fields.readonlyNoSummary(CaseData::getEmailInfoText)
                    .fieldShowCondition("contactPreference=\"wantsEmail\"");
        fields.mandatory(CaseData::getEmail)
                    .fieldShowCondition("contactPreference=\"wantsEmail\"");
        fields.mandatoryNoSummary(CaseData::getEmailRetype)
                    .fieldShowCondition("contactPreference=\"wantsEmail\"");
        fields.readonlyNoSummary(CaseData::getMobilePhoneNumberInfoText)
                    .fieldShowCondition("contactPreference=\"wantsSms\"");
        fields.mandatory(CaseData::getMobileNumber)
                    .fieldShowCondition("contactPreference=\"wantsSms\"");
        fields.mandatoryNoSummary(CaseData::getMobileNumberRetype)
                    .fieldShowCondition("contactPreference=\"wantsSms\"");
    }
}
