package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.PrisonNOMSComplexType;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code detentionFacility} of event {@code editAppeal}.
 */
public final class EditAppealDetentionFacilityPage {
    private EditAppealDetentionFacilityPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("detentionFacility");
        fields.pageLabel("Where is the appellant detained?");
        fields.showCondition("appellantInDetention=\"Yes\" AND appellantInUk=\"Yes\"");
        fields.mandatory(CaseData::getDetentionFacility)
                    .caseEventFieldLabel("Detention facility");
        fields.complex(CaseData::getPrisonNOMSNumber)
                    .optional(PrisonNOMSComplexType::getPrison)
                    .publish(false).done()
                    .fieldShowCondition("detentionFacility=\"prison\"")
                    .caseEventFieldLabel("Prison");
        fields.mandatory(CaseData::getOtherDetentionFacilityName)
                    .fieldShowCondition("detentionFacility=\"other\"")
                    .caseEventFieldLabel("Other");
        fields.readonlyNoSummary(CaseData::getDetentionBuilding)
                    .fieldShowCondition("checklistTitle2=\"DUMMY_VALUE_TO_HIDE_FIELD\"");
        fields.readonlyNoSummary(CaseData::getDetentionAddressLines)
                    .fieldShowCondition("checklistTitle2=\"DUMMY_VALUE_TO_HIDE_FIELD\"");
        fields.readonlyNoSummary(CaseData::getDetentionPostcode)
                    .fieldShowCondition("checklistTitle2=\"DUMMY_VALUE_TO_HIDE_FIELD\"");
    }
}
