package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code adminJSponsorContactPreference} of event {@code editAppealAfterSubmit}.
 */
public final class EditAppealAfterSubmitAdminJSponsorContactPreferencePage {
    private EditAppealAfterSubmitAdminJSponsorContactPreferencePage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("adminJSponsorContactPreference");
        fields.pageLabel("Sponsor's contact details");
        fields.showCondition("hasSponsor=\"Yes\" AND isAdmin=\"Yes\"");
        fields.readonlyNoSummary(CaseData::getAdminJSponsorContactTitle)
                    .publish(false);
        fields.optional(CaseData::getSponsorMobileNumberAdminJ)
                    .caseEventFieldLabel("Mobile number")
                    .publish(false);
        fields.optional(CaseData::getSponsorEmailAdminJ)
                    .caseEventFieldLabel("Email address")
                    .publish(false);
    }
}
