package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code paymentOptions} of event {@code editAppeal}.
 */
public final class EditAppealPaymentOptionsPage {
    private EditAppealPaymentOptionsPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("paymentOptions");
        fields.pageLabel("How to pay");
        fields.showCondition("isFeePaymentEnabled=\"Yes\" AND appealType!=\"deprivation\" AND appealType!=\"revocationOfProtection\" AND remissionType!=\"hoWaiverRemission\" AND remissionType!=\"helpWithFees\" AND remissionType!=\"exceptionalCircumstancesRemission\" AND appealType!=\"refusalOfEu\" AND appealType!=\"refusalOfHumanRights\" AND appealType!=\"euSettlementScheme\"");
        fields.mandatory(CaseData::getPaAppealTypePaymentOption)
                    .fieldShowCondition("appealType=\"protection\"")
                    .caseEventFieldLabel("Select a payment method");
    }
}
