package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code legalRepresentativeDetails} of event {@code editAppeal}.
 */
public final class EditAppealLegalRepresentativeDetailsPage {
    private EditAppealLegalRepresentativeDetailsPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("legalRepresentativeDetails");
        fields.pageLabel("Legal representative details");
        fields.showCondition("isAdmin!=\"Yes\"");
        fields.readonlyNoSummary(CaseData::getLegalRepDetailsHintAndTitle);
        fields.mandatory(CaseData::getLegalRepCompany);
        fields.mandatory(CaseData::getLegalRepName);
        fields.mandatory(CaseData::getLegalRepFamilyName);
        fields.mandatory(CaseData::getLegalRepMobilePhoneNumber);
        fields.mandatory(CaseData::getLegalRepReferenceNumber)
                    .caseEventFieldLabel("Own reference");
        fields.readonlyNoSummary(CaseData::getPaymentStatus)
                    .fieldShowCondition("legalRepReferenceNumber=\"DUMMY_VALUE_TO_HIDE_FIELD\"");
        fields.readonlyNoSummary(CaseData::getIsFeePaymentEnabled)
                    .fieldShowCondition("legalRepReferenceNumber=\"DUMMY_VALUE_TO_HIDE_FIELD\"");
        fields.readonlyNoSummary(CaseData::getIsRemissionsEnabled)
                    .fieldShowCondition("legalRepReferenceNumber=\"DUMMY_VALUE_TO_HIDE_FIELD\"");
    }
}
