package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code editCaseListingHearing} of event {@code editCaseListing}.
 */
public final class EditCaseListingEditCaseListingHearingPage {
    private EditCaseListingEditCaseListingHearingPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("editCaseListingHearing");
        fields.readonlyNoSummary(CaseData::getEditCaseListingTitle)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getIsIntegrated)
                    .fieldShowCondition("editCaseListingTitle=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getIsCaseUsingLocationRefData)
                    .fieldShowCondition("editCaseListingTitle=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .publish(false);
        fields.readonly(CaseData::getListCaseHearingCentreAddress)
                    .fieldShowCondition("editCaseListingTitle=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .publish(false);
        fields.mandatory(CaseData::getListCaseHearingCentre)
                    .fieldShowCondition("isCaseUsingLocationRefData!=\"Yes\"")
                    .publish(false);
        fields.mandatory(CaseData::getListingLocation)
                    .fieldShowCondition("isCaseUsingLocationRefData=\"Yes\"")
                    .publish(false);
        fields.mandatory(CaseData::getIsRemoteHearing)
                    .fieldShowCondition("isCaseUsingLocationRefData=\"Yes\"")
                    .publish(false);
        fields.mandatory(CaseData::getListCaseHearingLength)
                    .fieldShowCondition("isIntegrated!=\"Yes\"")
                    .publish(false);
        fields.mandatory(CaseData::getListingLength)
                    .fieldShowCondition("isIntegrated=\"Yes\"")
                    .publish(false);
        fields.mandatory(CaseData::getListCaseHearingDate);
    }
}
