package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code submissionOutOfTimePage} of event {@code editAppealAfterSubmit}.
 */
public final class EditAppealAfterSubmitSubmissionOutOfTimePagePage {
    private EditAppealAfterSubmitSubmissionOutOfTimePagePage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("submissionOutOfTimePage");
        fields.showCondition("submissionOutOfTime=\"Yes\" AND isAdmin!=\"Yes\"");
        fields.mandatoryNoSummary(CaseData::getSubmissionOutOfTime)
                    .fieldShowCondition("applicationOutOfTimeText=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getApplicationOutOfTimeText)
                    .caseEventFieldLabel("You've missed the deadline for appealing.\r\n"
                        + "\r\n"
                        + "You can ask for permission to appeal outside of the deadline.\r\n"
                        + "\r\n"
                        + "Explain why you believe your late appeal should be allowed to proceed.")
                    .publish(false);
        fields.optionalNoSummary(CaseData::getApplicationOutOfTimeExplanation)
                    .caseEventFieldLabel("You can upload a document or fill out the box below.")
                    .publish(false);
        fields.optionalNoSummary(CaseData::getApplicationOutOfTimeDocument)
                    .caseEventFieldLabel(" ")
                    .publish(false);
    }
}
