package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code appellantAddress} of event {@code editAppeal}.
 */
public final class EditAppealAppellantAddressPage {
    private EditAppealAppellantAddressPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("appellantAddress");
        fields.pageLabel("Appellant's address");
        fields.showCondition("appellantInUk!=\"No\" AND appellantInDetention!=\"Yes\" OR detentionFacility=\"other\"");
        fields.readonlyNoSummary(CaseData::getAppellantAddressTitle)
                    .fieldShowCondition("appellantInDetention!=\"Yes\"");
        fields.readonlyNoSummary(CaseData::getDetaineeAddressSubTitle)
                    .fieldShowCondition("appellantInDetention=\"Yes\" AND detentionFacility=\"other\"");
        fields.readonly(CaseData::getAppellantAddressLabel)
                    .fieldShowCondition("isAdmin!=\"Yes\" AND detentionFacility!=\"other\"");
        fields.mandatory(CaseData::getAppellantHasFixedAddress)
                    .fieldShowCondition("detentionFacility!=\"other\"");
        fields.readonly(CaseData::getAppellantHasFixedAddressLabel)
                    .fieldShowCondition("appellantHasFixedAddress=\"No\" AND appellantInUk!=\"No\"");
        fields.mandatory(CaseData::getAppellantAddress)
                    .fieldShowCondition("appellantHasFixedAddress=\"Yes\" OR detentionFacility=\"other\"");
    }
}
