package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code sponsor} of event {@code editAppealAfterSubmit}.
 */
public final class EditAppealAfterSubmitSponsorPage {
    private EditAppealAfterSubmitSponsorPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("sponsor");
        fields.pageLabel("Sponsor");
        fields.readonlyNoSummary(CaseData::getAppellantSponsorTitle)
                    .publish(false);
        fields.mandatory(CaseData::getHasSponsor)
                    .caseEventFieldLabel("Does the appellant have a sponsor?")
                    .publish(false);
        fields.mandatory(CaseData::getHasNonLegalRep)
                    .fieldShowCondition("journeyType=\"aip\"")
                    .caseEventFieldLabel("Does the appellant have a non-legal representative?")
                    .publish(false);
        fields.mandatory(CaseData::getIsSponsorSameAsNlr)
                    .fieldShowCondition("journeyType=\"aip\" AND hasSponsor=\"Yes\" AND hasNonLegalRep=\"Yes\"")
                    .caseEventFieldLabel("Are the sponsor and the non-legal representative the same person?")
                    .publish(false);
    }
}
