package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code requestCaseBuilding} of event {@code forceRequestCaseBuilding}.
 */
public final class ForceRequestCaseBuildingRequestCaseBuildingPage {
    private ForceRequestCaseBuildingRequestCaseBuildingPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("requestCaseBuilding");
        fields.readonlyNoSummary(CaseData::getRequestCaseBuildingTitle);
        fields.mandatory(CaseData::getSendDirectionExplanation);
        fields.readonly(CaseData::getSendDirectionParties);
        fields.mandatory(CaseData::getSendDirectionDateDue);
    }
}
