package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code listCaseRequirements} of event {@code listCase}.
 */
public final class ListCaseListCaseRequirementsPage {
    private ListCaseListCaseRequirementsPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("listCaseRequirements");
        fields.showCondition("submitHearingRequirementsAvailable!=\"Yes\"");
        fields.mandatoryNoSummary(CaseData::getSubmitHearingRequirementsAvailable)
                    .fieldShowCondition("listCaseRequirementsTitle=\"DUMMY_FIELD_TO_HIDE\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getListCaseRequirementsTitle)
                    .publish(false);
        fields.optional(CaseData::getListCaseRequirementsVulnerabilities)
                    .publish(false);
        fields.optional(CaseData::getListCaseRequirementsMultimedia)
                    .publish(false);
        fields.optional(CaseData::getListCaseRequirementsSingleSexCourt)
                    .publish(false);
        fields.optional(CaseData::getListCaseRequirementsInCameraCourt)
                    .publish(false);
        fields.optional(CaseData::getListCaseRequirementsOther)
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getAppellantInDetention)
                    .fieldShowCondition("listCaseHearingTitle=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
        fields.mandatoryNoSummary(CaseData::getIsNotificationTurnedOff)
                    .fieldShowCondition("listCaseHearingTitle=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
        fields.mandatoryNoSummary(CaseData::getStf24wCurrentStatusAutoGenerated)
                    .fieldShowCondition("listCaseHearingTitle=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
        fields.mandatoryNoSummary(CaseData::getStf24wPreviousStatusWasYesAutoGenerated)
                    .fieldShowCondition("listCaseHearingTitle=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
    }
}
