package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code listCaseHearing} of event {@code listCase}.
 */
public final class ListCaseListCaseHearingPage {
    private ListCaseListCaseHearingPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("listCaseHearing");
        fields.readonlyNoSummary(CaseData::getListCaseHearingTitle)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getIsIntegrated)
                    .fieldShowCondition("listCaseHearingTitle=\"DUMMY_FIELD_TO_HIDE\"")
                    .publish(false);
        fields.readonly(CaseData::getIsCaseUsingLocationRefData)
                    .fieldShowCondition("listCaseHearingTitle=\"DUMMY_VALUE_TO_HIDE\"")
                    .caseEventFieldLabel(" ")
                    .publish(false);
        fields.mandatory(CaseData::getAriaListingReference)
                    .publish(false);
        fields.readonly(CaseData::getListCaseHearingCentreAddress)
                    .fieldShowCondition("listCaseHearingCentre=\"DUMMY_FIELD_TO_HIDE\"")
                    .caseEventFieldLabel("Location")
                    .publish(false);
        fields.mandatory(CaseData::getListCaseHearingCentre)
                    .fieldShowCondition("isCaseUsingLocationRefData!=\"Yes\"")
                    .caseEventFieldLabel("Location")
                    .publish(false);
        fields.mandatory(CaseData::getListingLocation)
                    .fieldShowCondition("isCaseUsingLocationRefData=\"Yes\"")
                    .caseEventFieldLabel("Listing location")
                    .publish(false);
        fields.mandatory(CaseData::getIsRemoteHearing)
                    .fieldShowCondition("isCaseUsingLocationRefData=\"Yes\"")
                    .publish(false);
        fields.mandatory(CaseData::getListCaseHearingLength)
                    .fieldShowCondition("isIntegrated!=\"Yes\"")
                    .publish(false);
        fields.mandatory(CaseData::getListingLength)
                    .fieldShowCondition("isIntegrated=\"Yes\"")
                    .publish(false);
        fields.mandatory(CaseData::getListCaseHearingDate);
    }
}
