package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code newFeeAmount} of event {@code manageFeeUpdate}.
 */
public final class ManageFeeUpdateNewFeeAmountPage {
    private ManageFeeUpdateNewFeeAmountPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("newFeeAmount");
        fields.pageLabel("New fee amount");
        fields.readonlyNoSummary(CaseData::getFeeAmountGbp)
                    .caseEventFieldLabel("Current appeal fee amount")
                    .publish(false);
        fields.mandatory(CaseData::getNewFeeAmount)
                    .caseEventFieldLabel("Enter new appeal fee amount")
                    .publish(false);
    }
}
