package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code feeUpdateTribunalAction} of event {@code manageFeeUpdate}.
 */
public final class ManageFeeUpdateFeeUpdateTribunalActionPage {
    private ManageFeeUpdateFeeUpdateTribunalActionPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("feeUpdateTribunalAction");
        fields.pageLabel("Tribunal action required");
        fields.mandatory(CaseData::getFeeUpdateTribunalAction);
        fields.mandatory(CaseData::getManageFeeRefundedAmount)
                    .fieldShowCondition("feeUpdateTribunalAction=\"refund\"")
                    .publish(false);
        fields.mandatory(CaseData::getManageFeeRequestedAmount)
                    .fieldShowCondition("feeUpdateTribunalAction=\"additionalPayment\"")
                    .caseEventFieldLabel("Amount to be requested")
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getAppellantInDetention)
                    .fieldShowCondition("feeUpdateTribunalAction=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
        fields.mandatoryNoSummary(CaseData::getIsNotificationTurnedOff)
                    .fieldShowCondition("feeUpdateTribunalAction=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
    }
}
