package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code markAppealAsDetained_prisonName} of event {@code markAppealAsDetained}.
 */
public final class MarkAppealAsDetainedMarkAppealAsDetainedPrisonNamePage {
    private MarkAppealAsDetainedMarkAppealAsDetainedPrisonNamePage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("markAppealAsDetained_prisonName");
        fields.pageLabel("In which prison is the appellant detained?");
        fields.showCondition("detentionFacility=\"prison\" AND prisonNOMSNumber!=\"\"");
        fields.mandatory(CaseData::getPrisonName)
                    .caseEventFieldLabel("Prison name")
                    .publish(false);
    }
}
