package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code markAppealAsDetained_appellantBailApplication} of event {@code markAppealAsDetained}.
 */
public final class MarkAppealAsDetainedMarkAppealAsDetainedAppellantBailApplicationPage {
    private MarkAppealAsDetainedMarkAppealAsDetainedAppellantBailApplicationPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("markAppealAsDetained_appellantBailApplication");
        fields.pageLabel("Bail application");
        fields.showCondition("releaseDateProvided!=\"Yes\"");
        fields.mandatory(CaseData::getHasPendingBailApplications)
                    .caseEventFieldLabel("Does the appellant have a pending bail application?")
                    .publish(false);
        fields.mandatory(CaseData::getBailApplicationNumber)
                    .fieldShowCondition("hasPendingBailApplications=\"Yes\"")
                    .caseEventFieldLabel("What is the appellant's bail application number?")
                    .publish(false);
    }
}
