package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseNoteMigration;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code editDocs} of event {@code progressMigratedCase}.
 */
public final class ProgressMigratedCaseEditDocsPage {
    private ProgressMigratedCaseEditDocsPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("editDocs");
        fields.pageLabel("Upload the desired state documents");
        fields.readonlyNoSummary(CaseData::getMigrationWarningTitle)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getDummyEmptyLabel)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getMigrationMainTextVisible)
                    .fieldShowCondition("dummyEmptyLabel=\"DUMMY_FIELD_TO_HIDE\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getMigrationHmcSecondPartVisible)
                    .fieldShowCondition("dummyEmptyLabel=\"DUMMY_FIELD_TO_HIDE\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getMigrationVhhText)
                    .fieldShowCondition("migrationMainTextVisible=\"VHH\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getMigrationHmcText)
                    .fieldShowCondition("migrationMainTextVisible=\"HMC\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getMigrationMoveItText)
                    .fieldShowCondition("migrationMainTextVisible=\"MoveIT\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getMigrationVhhToCcdText)
                    .fieldShowCondition("migrationMainTextVisible=\"VHHToCCD\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getMigrationDocumentUploadGeneralText)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getMigrationHMCSecondPartTitle)
                    .fieldShowCondition("migrationHmcSecondPartVisible=\"Yes\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getMigrationDocumentsUploadTitle)
                    .publish(false);
        fields.optionalNoSummary(CaseData::getTribunalDocuments)
                    .publish(false);
        fields.optionalNoSummary(CaseData::getAdditionalEvidenceDocuments)
                    .publish(false);
        fields.optionalNoSummary(CaseData::getUploadSensitiveDocs)
                    .publish(false);
        fields.optionalNoSummary(CaseData::getReheardHearingDocuments)
                    .publish(false);
        fields.optionalNoSummary(CaseData::getHearingDocuments)
                    .publish(false);
        fields.optionalNoSummary(CaseData::getHearingRecordingDocuments)
                    .publish(false);
        fields.optionalNoSummary(CaseData::getAddendumEvidenceDocuments)
                    .publish(false);
        fields.optionalNoSummary(CaseData::getLegalRepresentativeDocuments)
                    .publish(false);
        fields.optionalNoSummary(CaseData::getRespondentDocuments)
                    .publish(false);
        fields.optionalNoSummary(CaseData::getDraftReheardDecisionAndReasons)
                    .publish(false);
        fields.optionalNoSummary(CaseData::getFinalDecisionAndReasonsDocuments)
                    .publish(false);
        fields.optionalNoSummary(CaseData::getFtpaAppellantDocuments)
                    .publish(false);
        fields.optionalNoSummary(CaseData::getAllFtpaAppellantDecisionDocs)
                    .publish(false);
        fields.optionalNoSummary(CaseData::getFtpaRespondentDocuments)
                    .publish(false);
        fields.optionalNoSummary(CaseData::getAllFtpaRespondentDecisionDocs)
                    .publish(false);
        fields.optionalNoSummary(CaseData::getRemittalDocuments)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getMigrationCaseNoteTitle)
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getMigrationCaseNote)
                    .publish(false);
        fields.complex(CaseData::getAddCaseNotesMigration, false).done()
                    .fieldShowCondition("migrationCaseNote=\"Yes\"");
        fields.complex(CaseData::getAddCaseNotesMigration, CaseNoteMigration.class)
                    .mandatory(CaseNoteMigration::getCaseNoteSubject)
                    .publish(true)
                    .mandatory(CaseNoteMigration::getCaseNoteDescription)
                    .publish(true)
                    .optional(CaseNoteMigration::getCaseNoteDocument)
                    .publish(true).done();
        fields.mandatoryNoSummary(CaseData::getReviewedHearingRequirements)
                    .fieldShowCondition("dummyEmptyLabel=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
        fields.mandatoryNoSummary(CaseData::getUploadHomeOfficeBundleAvailable)
                    .fieldShowCondition("dummyEmptyLabel=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
        fields.mandatoryNoSummary(CaseData::getAppealType)
                    .fieldShowCondition("dummyEmptyLabel=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
        fields.mandatoryNoSummary(CaseData::getJourneyType)
                    .fieldShowCondition("dummyEmptyLabel=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
        fields.mandatoryNoSummary(CaseData::getRemissionType)
                    .fieldShowCondition("dummyEmptyLabel=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
        fields.mandatoryNoSummary(CaseData::getHelpWithFeesOption)
                    .fieldShowCondition("dummyEmptyLabel=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
        fields.mandatoryNoSummary(CaseData::getRemissionOption)
                    .fieldShowCondition("dummyEmptyLabel=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
        fields.mandatoryNoSummary(CaseData::getRemissionClaim)
                    .fieldShowCondition("dummyEmptyLabel=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
        fields.mandatoryNoSummary(CaseData::getFtpaAppellantRjDecisionOutcomeType)
                    .fieldShowCondition("dummyEmptyLabel=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
        fields.mandatoryNoSummary(CaseData::getFtpaApplicantType)
                    .fieldShowCondition("dummyEmptyLabel=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
        fields.mandatoryNoSummary(CaseData::getFtpaRespondentRjDecisionOutcomeType)
                    .fieldShowCondition("dummyEmptyLabel=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
        fields.mandatoryNoSummary(CaseData::getAppellantInDetention)
                    .fieldShowCondition("dummyEmptyLabel=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
        fields.mandatoryNoSummary(CaseData::getIsNotificationTurnedOff)
                    .fieldShowCondition("dummyEmptyLabel=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
    }
}
