package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code remissionDecisionDetails} of event {@code recordRemissionDecision}.
 */
public final class RecordRemissionDecisionRemissionDecisionDetailsPage {
    private RecordRemissionDecisionRemissionDecisionDetailsPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("remissionDecisionDetails");
        fields.readonlyNoSummary(CaseData::getRemissionApprovedForFeeWithHearingAdvice)
                    .fieldShowCondition("remissionDecision=\"approved\" AND decisionHearingFeeOption=\"decisionWithHearing\"")
                    .caseEventFieldLabel("The full fee of £${feeWithHearing} will be remitted. Click Continue to confirm the amount remitted and the amount left to pay are correct.")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getRemissionApprovedForFeeWithoutHearingAdvice)
                    .fieldShowCondition("remissionDecision=\"approved\" AND decisionHearingFeeOption=\"decisionWithoutHearing\"")
                    .caseEventFieldLabel("The full fee of £${feeWithoutHearing} will be remitted. Click Continue to confirm the amount remitted and the amount left to pay are correct.")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getRemissionPartiallyApprovedForFeeWithHearingAdvice)
                    .fieldShowCondition("remissionDecision=\"partiallyApproved\" AND decisionHearingFeeOption=\"decisionWithHearing\"")
                    .caseEventFieldLabel("The full fee of £${feeWithHearing} will be partially remitted. Click Continue to confirm the amount remitted and the amount left to pay are correct.")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getRemissionPartiallyApprovedForFeeWithoutHearingAdvice)
                    .fieldShowCondition("remissionDecision=\"partiallyApproved\" AND decisionHearingFeeOption=\"decisionWithoutHearing\"")
                    .caseEventFieldLabel("The full fee of £${feeWithoutHearing} will be partially remitted. Click Continue to confirm the amount remitted and the amount left to pay are correct.")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getRemissionRejectedForFeeWithHearingAdvice)
                    .fieldShowCondition("remissionDecision=\"rejected\" AND decisionHearingFeeOption=\"decisionWithHearing\"")
                    .caseEventFieldLabel("The full fee of an appeal with hearing is £${feeWithHearing}.")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getRemissionRejectedForFeeWithoutHearingAdvice)
                    .fieldShowCondition("remissionDecision=\"rejected\" AND decisionHearingFeeOption=\"decisionWithoutHearing\"")
                    .caseEventFieldLabel("The full fee of an appeal without hearing is £${feeWithoutHearing}.")
                    .publish(false);
        fields.mandatory(CaseData::getAmountRemitted)
                    .fieldShowCondition("remissionDecision=\"approved\" OR remissionDecision=\"partiallyApproved\"")
                    .publish(false);
        fields.mandatory(CaseData::getAmountLeftToPay)
                    .fieldShowCondition("remissionDecision=\"approved\" OR remissionDecision=\"partiallyApproved\"")
                    .publish(false);
        fields.mandatory(CaseData::getRemissionDecisionReason)
                    .fieldShowCondition("remissionDecision=\"partiallyApproved\" OR remissionDecision=\"rejected\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getRemissionRejectedDatePlus14days)
                    .fieldShowCondition("remissionDecisionReason=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getAppellantInDetention)
                    .fieldShowCondition("remissionRejectedDatePlus14days=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
        fields.mandatoryNoSummary(CaseData::getIsNotificationTurnedOff)
                    .fieldShowCondition("remissionRejectedDatePlus14days=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
    }
}
