package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code detentionRemoval_appellantContactPreference} of event {@code removeDetainedStatus}.
 */
public final class RemoveDetainedStatusDetentionRemovalAppellantContactPreferencePage {
    private RemoveDetainedStatusDetentionRemovalAppellantContactPreferencePage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("detentionRemoval_appellantContactPreference");
        fields.pageLabel("The appellant's contact preference");
        fields.showCondition("isAdmin!=\"Yes\"");
        fields.readonlyNoSummary(CaseData::getAppellantContactPreferenceTitle)
                    .publish(false);
        fields.mandatory(CaseData::getContactPreference)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getEmailInfoText)
                    .fieldShowCondition("contactPreference=\"wantsEmail\"")
                    .publish(false);
        fields.mandatory(CaseData::getEmail)
                    .fieldShowCondition("contactPreference=\"wantsEmail\"")
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getEmailRetype)
                    .fieldShowCondition("contactPreference=\"wantsEmail\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getMobilePhoneNumberInfoText)
                    .fieldShowCondition("contactPreference=\"wantsSms\"")
                    .publish(false);
        fields.mandatory(CaseData::getMobileNumber)
                    .fieldShowCondition("contactPreference=\"wantsSms\"")
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getMobileNumberRetype)
                    .fieldShowCondition("contactPreference=\"wantsSms\"")
                    .publish(false);
    }
}
