package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code section17} of event {@code requestFeeRemission}.
 */
public final class RequestFeeRemissionSection17Page {
    private RequestFeeRemissionSection17Page() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("section17");
        fields.showCondition("remissionClaim=\"section17\"");
        fields.readonlyNoSummary(CaseData::getSection17Header)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getSection17Advice)
                    .publish(false);
        fields.mandatory(CaseData::getSection17Document)
                    .publish(false);
    }
}
