package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code autoHearingRequest} of event {@code reviewHearingRequirements}.
 */
public final class ReviewHearingRequirementsAutoHearingRequestPage {
    private ReviewHearingRequirementsAutoHearingRequestPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("autoHearingRequest");
        fields.showCondition("isIntegrated=\"Yes\" AND autoHearingRequestEnabled=\"Yes\" AND (isVulnerabilitiesAllowed=\"Granted\" OR isMultimediaAllowed=\"Granted\" OR isAdditionalAdjustmentsAllowed=\"Granted\")");
        fields.readonlyNoSummary(CaseData::getAutoRequestHearingGuide)
                    .publish(false);
        fields.mandatory(CaseData::getAutoRequestHearing)
                    .publish(false);
    }
}
