package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code adjustInCameraCourtRequirements} of event {@code reviewCmaRequirements}.
 */
public final class ReviewCmaRequirementsAdjustInCameraCourtRequirementsPage {
    private ReviewCmaRequirementsAdjustInCameraCourtRequirementsPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("adjustInCameraCourtRequirements");
        fields.readonlyNoSummary(CaseData::getInCameraCourtAdjustmentRequestTitle)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getInCameraCourt)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getInCameraCourtDescription)
                    .fieldShowCondition("inCameraCourt=\"Yes\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getInCameraCourtTribunalResponseTitle)
                    .fieldShowCondition("inCameraCourt=\"Yes\"")
                    .publish(false);
        fields.mandatory(CaseData::getInCameraCourtTribunalResponse)
                    .fieldShowCondition("inCameraCourt=\"Yes\"")
                    .publish(false);
    }
}
