package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code adjustSingleSexCourtRequirements} of event {@code reviewHearingRequirements}.
 */
public final class ReviewHearingRequirementsAdjustSingleSexCourtRequirementsPage {
    private ReviewHearingRequirementsAdjustSingleSexCourtRequirementsPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("adjustSingleSexCourtRequirements");
        fields.readonlyNoSummary(CaseData::getSingleSexCourtAdjustmentRequestTitle)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getSingleSexCourt)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getSingleSexCourtType)
                    .fieldShowCondition("singleSexCourt=\"Yes\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getSingleSexCourtTypeDescription)
                    .fieldShowCondition("singleSexCourt=\"Yes\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getSingleSexCourtTribunalResponseTitle)
                    .fieldShowCondition("singleSexCourt=\"Yes\"")
                    .publish(false);
        fields.mandatory(CaseData::getIsSingleSexCourtAllowed)
                    .fieldShowCondition("singleSexCourt=\"Yes\"")
                    .publish(false);
        fields.mandatory(CaseData::getSingleSexCourtTribunalResponse)
                    .fieldShowCondition("singleSexCourt=\"Yes\"")
                    .publish(false);
    }
}
