package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code adjustPersonalVulnerabilities} of event {@code reviewHearingRequirements}.
 */
public final class ReviewHearingRequirementsAdjustPersonalVulnerabilitiesPage {
    private ReviewHearingRequirementsAdjustPersonalVulnerabilitiesPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("adjustPersonalVulnerabilities");
        fields.readonlyNoSummary(CaseData::getReviewAdjustmentsTitle)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getAdditionalAdjustmentsDescription)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getVulnerabilitiesAdjustmentRequestTitle)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getPhysicalOrMentalHealthIssues)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getPhysicalOrMentalHealthIssuesDescription)
                    .fieldShowCondition("physicalOrMentalHealthIssues=\"Yes\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getVulnerabilitiesTribunalResponseTitle)
                    .fieldShowCondition("physicalOrMentalHealthIssues=\"Yes\"")
                    .publish(false);
        fields.mandatory(CaseData::getIsVulnerabilitiesAllowed)
                    .fieldShowCondition("physicalOrMentalHealthIssues=\"Yes\"")
                    .publish(false);
        fields.mandatory(CaseData::getVulnerabilitiesTribunalResponse)
                    .fieldShowCondition("physicalOrMentalHealthIssues=\"Yes\"")
                    .publish(false);
    }
}
