package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code sponsorName} of event {@code startAppeal}.
 */
public final class StartAppealSponsorNamePage {
    private StartAppealSponsorNamePage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("sponsorName");
        fields.pageLabel("What is the sponsor's name?");
        fields.showCondition("hasSponsor=\"Yes\"");
        fields.readonlyNoSummary(CaseData::getSponsorNameTitle)
                    .publish(false);
        fields.mandatory(CaseData::getSponsorGivenNames)
                    .publish(false);
        fields.mandatory(CaseData::getSponsorFamilyName)
                    .publish(false);
    }
}
