package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code oocAppellantAddress} of event {@code startAppeal}.
 */
public final class StartAppealOocAppellantAddressPage {
    private StartAppealOocAppellantAddressPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("oocAppellantAddress");
        fields.pageLabel("Appellant's address");
        fields.showCondition("isOutOfCountryEnabled=\"Yes\" AND appellantInUk=\"No\"");
        fields.readonlyNoSummary(CaseData::getAppellantCorrespAddressTitle)
                    .publish(false);
        fields.mandatory(CaseData::getHasCorrespondenceAddress)
                    .publish(false);
        fields.mandatory(CaseData::getAppellantOutOfCountryAddress)
                    .fieldShowCondition("hasCorrespondenceAddress=\"Yes\"")
                    .caseEventFieldLabel("Enter the address")
                    .publish(false);
    }
}
