package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code outOfCountryDecisionType} of event {@code startAppeal}.
 */
public final class StartAppealOutOfCountryDecisionTypePage {
    private StartAppealOutOfCountryDecisionTypePage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("outOfCountryDecisionType");
        fields.pageLabel("Out of country decision");
        fields.showCondition("isOutOfCountryEnabled=\"Yes\" AND appellantInUk=\"No\"");
        fields.readonlyNoSummary(CaseData::getOutOfCountryDecisionTypeTitle)
                    .publish(false);
        fields.mandatory(CaseData::getOutOfCountryDecisionType)
                    .caseEventFieldLabel("What type of decision are you appealing?")
                    .publish(false);
    }
}
