package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code appealReferenceNumber} of event {@code startAppeal}.
 */
public final class StartAppealAppealReferenceNumberPage {
    private StartAppealAppealReferenceNumberPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("appealReferenceNumber");
        fields.pageLabel("What is/was the ARIA appeal reference number?");
        fields.showCondition("sourceOfAppeal=\"rehydratedAppeal\" AND isAdmin=\"Yes\"");
        fields.mandatory(CaseData::getAppealReferenceNumber)
                    .caseEventFieldLabel("Please enter the ARIA reference in the following format: XX/00000/0000")
                    .publish(false);
    }
}
