package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code exceptionalCircumstancesRemission} of event {@code startAppeal}.
 */
public final class StartAppealExceptionalCircumstancesRemissionPage {
    private StartAppealExceptionalCircumstancesRemissionPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("exceptionalCircumstancesRemission");
        fields.pageLabel("Exceptional Circumstances");
        fields.showCondition("remissionType=\"exceptionalCircumstancesRemission\" AND appealType!=\"deprivation\" AND appealType!=\"revocationOfProtection\"");
        fields.readonlyNoSummary(CaseData::getExceptionalCircumstancesHeader)
                    .publish(false);
        fields.mandatory(CaseData::getExceptionalCircumstances)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getExceptionalCircumstancesSupportEvidenceAdvice)
                    .publish(false);
        fields.optional(CaseData::getRemissionEcEvidenceDocuments)
                    .publish(false);
    }
}
