package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code tribunalDecisionRule31} of event {@code updateTribunalDecision}.
 */
public final class UpdateTribunalDecisionTribunalDecisionRule31Page {
    private UpdateTribunalDecisionTribunalDecisionRule31Page() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("tribunalDecisionRule31");
        fields.showCondition("updateTribunalDecisionList=\"underRule31\"");
        fields.readonlyNoSummary(CaseData::getUpdateTribunalDynamicCurrentDecision)
                    .fieldShowCondition("updatedAppealDecision=\"*\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getOriginalTribunalDynamicCurrentDecision)
                    .fieldShowCondition("updatedAppealDecision!=\"*\"")
                    .publish(false);
        fields.mandatory(CaseData::getTypesOfUpdateTribunalDecision)
                    .publish(false);
    }
}
