package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code updateHearingAdjustments} of event {@code updateHearingAdjustments}.
 */
public final class UpdateHearingAdjustmentsUpdateHearingAdjustmentsPage {
    private UpdateHearingAdjustmentsUpdateHearingAdjustmentsPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("updateHearingAdjustments");
        fields.readonlyNoSummary(CaseData::getIsIntegrated)
                    .fieldShowCondition("reviewHearingRequirementsTitle=\"DUMMY_VALUE_TO_HIDE_FIELD\"");
        fields.readonlyNoSummary(CaseData::getReviewHearingRequirementsTitle);
        fields.readonlyNoSummary(CaseData::getAppealOutOfCountry)
                    .fieldShowCondition("reviewHearingRequirementsTitle=\"DUMMY_VALUE_TO_HIDE_FIELD\"");
        fields.readonlyNoSummary(CaseData::getIsOutOfCountryEnabled)
                    .fieldShowCondition("reviewHearingRequirementsTitle=\"DUMMY_VALUE_TO_HIDE_FIELD\"");
        fields.readonlyNoSummary(CaseData::getAppellantInterpreterLanguageCategory)
                    .fieldShowCondition("reviewHearingRequirementsTitle=\"DUMMY_VALUE_TO_HIDE_FIELD\"");
        fields.readonlyNoSummary(CaseData::getWitness1InterpreterLanguageCategory)
                    .fieldShowCondition("reviewHearingRequirementsTitle=\"DUMMY_VALUE_TO_HIDE_FIELD\"");
        fields.readonlyNoSummary(CaseData::getWitness2InterpreterLanguageCategory)
                    .fieldShowCondition("reviewHearingRequirementsTitle=\"DUMMY_VALUE_TO_HIDE_FIELD\"");
        fields.readonlyNoSummary(CaseData::getWitness3InterpreterLanguageCategory)
                    .fieldShowCondition("reviewHearingRequirementsTitle=\"DUMMY_VALUE_TO_HIDE_FIELD\"");
        fields.readonlyNoSummary(CaseData::getWitness4InterpreterLanguageCategory)
                    .fieldShowCondition("reviewHearingRequirementsTitle=\"DUMMY_VALUE_TO_HIDE_FIELD\"");
        fields.readonlyNoSummary(CaseData::getWitness5InterpreterLanguageCategory)
                    .fieldShowCondition("reviewHearingRequirementsTitle=\"DUMMY_VALUE_TO_HIDE_FIELD\"");
        fields.readonlyNoSummary(CaseData::getWitness6InterpreterLanguageCategory)
                    .fieldShowCondition("reviewHearingRequirementsTitle=\"DUMMY_VALUE_TO_HIDE_FIELD\"");
        fields.readonlyNoSummary(CaseData::getWitness7InterpreterLanguageCategory)
                    .fieldShowCondition("reviewHearingRequirementsTitle=\"DUMMY_VALUE_TO_HIDE_FIELD\"");
        fields.readonlyNoSummary(CaseData::getWitness8InterpreterLanguageCategory)
                    .fieldShowCondition("reviewHearingRequirementsTitle=\"DUMMY_VALUE_TO_HIDE_FIELD\"");
        fields.readonlyNoSummary(CaseData::getWitness9InterpreterLanguageCategory)
                    .fieldShowCondition("reviewHearingRequirementsTitle=\"DUMMY_VALUE_TO_HIDE_FIELD\"");
        fields.readonlyNoSummary(CaseData::getWitness10InterpreterLanguageCategory)
                    .fieldShowCondition("reviewHearingRequirementsTitle=\"DUMMY_VALUE_TO_HIDE_FIELD\"");
        fields.readonlyNoSummary(CaseData::getIsEvidenceFromOutsideUkOoc)
                    .fieldShowCondition("isOutOfCountryEnabled=\"Yes\" AND appealOutOfCountry=\"Yes\"");
        fields.readonlyNoSummary(CaseData::getIsAppellantAttendingTheHearing)
                    .fieldShowCondition("appealOutOfCountry!=\"Yes\"");
        fields.readonlyNoSummary(CaseData::getIsAppellantGivingOralEvidence)
                    .fieldShowCondition("appealOutOfCountry!=\"Yes\"");
        fields.readonlyNoSummary(CaseData::getIsWitnessesAttending);
        fields.readonlyNoSummary(CaseData::getWitnessDetailsReadonly)
                    .fieldShowCondition("isWitnessesAttending=\"Yes\"");
        fields.readonlyNoSummary(CaseData::getIsEvidenceFromOutsideUkInCountry)
                    .fieldShowCondition("appealOutOfCountry!=\"Yes\"");
        fields.readonlyNoSummary(CaseData::getIsInterpreterServicesNeeded);
        fields.readonlyNoSummary(CaseData::getInterpreterLanguageReadonly)
                    .fieldShowCondition("isInterpreterServicesNeeded=\"Yes\" AND appellantInterpreterSpokenLanguage=\"\" AND appellantInterpreterSignLanguage=\"\"");
        fields.readonlyNoSummary(CaseData::getAppellantInterpreterSpokenLanguage)
                    .fieldShowCondition("isInterpreterServicesNeeded=\"Yes\" AND appellantInterpreterLanguageCategoryCONTAINS\"spokenLanguageInterpreter\"");
        fields.readonlyNoSummary(CaseData::getAppellantInterpreterSignLanguage)
                    .fieldShowCondition("isInterpreterServicesNeeded=\"Yes\" AND appellantInterpreterLanguageCategoryCONTAINS\"signLanguageInterpreter\"");
        fields.readonlyNoSummary(CaseData::getIsAnyWitnessInterpreterRequired)
                    .fieldShowCondition("isWitnessesAttending=\"Yes\"");
        fields.readonlyNoSummary(CaseData::getWitness1InterpreterSpokenLanguage)
                    .fieldShowCondition("isAnyWitnessInterpreterRequired=\"Yes\" AND witness1InterpreterLanguageCategoryCONTAINS\"spokenLanguageInterpreter\"");
        fields.readonlyNoSummary(CaseData::getWitness1InterpreterSignLanguage)
                    .fieldShowCondition("isAnyWitnessInterpreterRequired=\"Yes\" AND witness1InterpreterLanguageCategoryCONTAINS\"signLanguageInterpreter\"");
        fields.readonlyNoSummary(CaseData::getWitness2InterpreterSpokenLanguage)
                    .fieldShowCondition("isAnyWitnessInterpreterRequired=\"Yes\" AND witness2InterpreterLanguageCategoryCONTAINS\"spokenLanguageInterpreter\"");
        fields.readonlyNoSummary(CaseData::getWitness2InterpreterSignLanguage)
                    .fieldShowCondition("isAnyWitnessInterpreterRequired=\"Yes\" AND witness2InterpreterLanguageCategoryCONTAINS\"signLanguageInterpreter\"");
        fields.readonlyNoSummary(CaseData::getWitness3InterpreterSpokenLanguage)
                    .fieldShowCondition("isAnyWitnessInterpreterRequired=\"Yes\" AND witness3InterpreterLanguageCategoryCONTAINS\"spokenLanguageInterpreter\"");
        fields.readonlyNoSummary(CaseData::getWitness3InterpreterSignLanguage)
                    .fieldShowCondition("isAnyWitnessInterpreterRequired=\"Yes\" AND witness3InterpreterLanguageCategoryCONTAINS\"signLanguageInterpreter\"");
        fields.readonlyNoSummary(CaseData::getWitness4InterpreterSpokenLanguage)
                    .fieldShowCondition("isAnyWitnessInterpreterRequired=\"Yes\" AND witness4InterpreterLanguageCategoryCONTAINS\"spokenLanguageInterpreter\"");
        fields.readonlyNoSummary(CaseData::getWitness4InterpreterSignLanguage)
                    .fieldShowCondition("isAnyWitnessInterpreterRequired=\"Yes\" AND witness4InterpreterLanguageCategoryCONTAINS\"signLanguageInterpreter\"");
        fields.readonlyNoSummary(CaseData::getWitness5InterpreterSpokenLanguage)
                    .fieldShowCondition("isAnyWitnessInterpreterRequired=\"Yes\" AND witness5InterpreterLanguageCategoryCONTAINS\"spokenLanguageInterpreter\"");
        fields.readonlyNoSummary(CaseData::getWitness5InterpreterSignLanguage)
                    .fieldShowCondition("isAnyWitnessInterpreterRequired=\"Yes\" AND witness5InterpreterLanguageCategoryCONTAINS\"signLanguageInterpreter\"");
        fields.readonlyNoSummary(CaseData::getWitness6InterpreterSpokenLanguage)
                    .fieldShowCondition("isAnyWitnessInterpreterRequired=\"Yes\" AND witness6InterpreterLanguageCategoryCONTAINS\"spokenLanguageInterpreter\"");
        fields.readonlyNoSummary(CaseData::getWitness6InterpreterSignLanguage)
                    .fieldShowCondition("isAnyWitnessInterpreterRequired=\"Yes\" AND witness6InterpreterLanguageCategoryCONTAINS\"signLanguageInterpreter\"");
        fields.readonlyNoSummary(CaseData::getWitness7InterpreterSpokenLanguage)
                    .fieldShowCondition("isAnyWitnessInterpreterRequired=\"Yes\" AND witness7InterpreterLanguageCategoryCONTAINS\"spokenLanguageInterpreter\"");
        fields.readonlyNoSummary(CaseData::getWitness7InterpreterSignLanguage)
                    .fieldShowCondition("isAnyWitnessInterpreterRequired=\"Yes\" AND witness7InterpreterLanguageCategoryCONTAINS\"signLanguageInterpreter\"");
        fields.readonlyNoSummary(CaseData::getWitness8InterpreterSpokenLanguage)
                    .fieldShowCondition("isAnyWitnessInterpreterRequired=\"Yes\" AND witness8InterpreterLanguageCategoryCONTAINS\"spokenLanguageInterpreter\"");
        fields.readonlyNoSummary(CaseData::getWitness8InterpreterSignLanguage)
                    .fieldShowCondition("isAnyWitnessInterpreterRequired=\"Yes\" AND witness8InterpreterLanguageCategoryCONTAINS\"signLanguageInterpreter\"");
        fields.readonlyNoSummary(CaseData::getWitness9InterpreterSpokenLanguage)
                    .fieldShowCondition("isAnyWitnessInterpreterRequired=\"Yes\" AND witness9InterpreterLanguageCategoryCONTAINS\"spokenLanguageInterpreter\"");
        fields.readonlyNoSummary(CaseData::getWitness9InterpreterSignLanguage)
                    .fieldShowCondition("isAnyWitnessInterpreterRequired=\"Yes\" AND witness9InterpreterLanguageCategoryCONTAINS\"signLanguageInterpreter\"");
        fields.readonlyNoSummary(CaseData::getWitness10InterpreterSpokenLanguage)
                    .fieldShowCondition("isAnyWitnessInterpreterRequired=\"Yes\" AND witness10InterpreterLanguageCategoryCONTAINS\"spokenLanguageInterpreter\"");
        fields.readonlyNoSummary(CaseData::getWitness10InterpreterSignLanguage)
                    .fieldShowCondition("isAnyWitnessInterpreterRequired=\"Yes\" AND witness10InterpreterLanguageCategoryCONTAINS\"signLanguageInterpreter\"");
        fields.readonlyNoSummary(CaseData::getIsHearingRoomNeeded);
        fields.readonlyNoSummary(CaseData::getIsHearingLoopNeeded);
        fields.readonlyNoSummary(CaseData::getHasNonLegalRep)
                    .fieldShowCondition("isHearingLoopNeeded=\"DUMMY_VALUE_TO_HIDE_FIELD\"");
        fields.readonlyNoSummary(CaseData::getNlrAttending)
                    .fieldShowCondition("hasNonLegalRep=\"Yes\"");
        fields.readonlyNoSummary(CaseData::getNlrAttendingOutsideUk)
                    .fieldShowCondition("hasNonLegalRep=\"Yes\"");
        fields.readonlyNoSummary(CaseData::getIsNlrInterpreterRequired)
                    .fieldShowCondition("hasNonLegalRep=\"Yes\" AND (nlrAttending=\"Yes\" OR nlrAttendingOutsideUk=\"Yes\")");
        fields.readonlyNoSummary(CaseData::getNlrInterpreterLanguageCategory)
                    .fieldShowCondition("hasNonLegalRep=\"Yes\" AND (nlrAttending=\"Yes\" OR nlrAttendingOutsideUk=\"Yes\") AND isNlrInterpreterRequired=\"Yes\"");
        fields.readonlyNoSummary(CaseData::getNlrInterpreterSpokenLanguage)
                    .fieldShowCondition("hasNonLegalRep=\"Yes\" AND (nlrAttending=\"Yes\" OR nlrAttendingOutsideUk=\"Yes\") AND isNlrInterpreterRequired=\"Yes\" AND nlrInterpreterLanguageCategoryCONTAINS\"spokenLanguageInterpreter\"");
        fields.readonlyNoSummary(CaseData::getNlrInterpreterSignLanguage)
                    .fieldShowCondition("hasNonLegalRep=\"Yes\" AND (nlrAttending=\"Yes\" OR nlrAttendingOutsideUk=\"Yes\") AND isNlrInterpreterRequired=\"Yes\" AND nlrInterpreterLanguageCategoryCONTAINS\"signLanguageInterpreter\"");
        fields.readonlyNoSummary(CaseData::getNlrNeedsStepFreeAccess)
                    .fieldShowCondition("hasNonLegalRep=\"Yes\" AND (nlrAttending=\"Yes\" OR nlrAttendingOutsideUk=\"Yes\")");
        fields.readonlyNoSummary(CaseData::getNlrNeedsHearingLoop)
                    .fieldShowCondition("hasNonLegalRep=\"Yes\" AND (nlrAttending=\"Yes\" OR nlrAttendingOutsideUk=\"Yes\")");
        fields.mandatory(CaseData::getListCaseHearingLength)
                    .fieldShowCondition("isIntegrated!=\"Yes\"");
        fields.mandatory(CaseData::getListingLength)
                    .fieldShowCondition("isIntegrated=\"Yes\"");
        fields.readonlyNoSummary(CaseData::getContinueToSeeAdditionalAdjustments);
    }
}
