package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code updateIrcName} of event {@code updateDetentionLocation}.
 */
public final class UpdateDetentionLocationUpdateIrcNamePage {
    private UpdateDetentionLocationUpdateIrcNamePage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("updateIrcName");
        fields.pageLabel("In which immigration removal centre is the appellant detained?");
        fields.showCondition("detentionFacility=\"immigrationRemovalCentre\"");
        fields.mandatory(CaseData::getIrcName)
                    .caseEventFieldLabel("Immigration removal centre name")
                    .publish(false);
    }
}
