package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code adjustRemoteHearing} of event {@code updateHearingAdjustments}.
 */
public final class UpdateHearingAdjustmentsAdjustRemoteHearingPage {
    private UpdateHearingAdjustmentsAdjustRemoteHearingPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("adjustRemoteHearing");
        fields.readonlyNoSummary(CaseData::getReviewAdjustmentsTitle);
        fields.readonlyNoSummary(CaseData::getAdditionalAdjustmentsDescription);
        fields.readonlyNoSummary(CaseData::getRemoteVideoCallAdjustmentRequestTitle);
        fields.readonlyNoSummary(CaseData::getRemoteVideoCall)
                    .caseEventFieldLabel("Is there anything you'd like the Tribunal to consider when deciding if a video call is suitable?");
        fields.readonlyNoSummary(CaseData::getRemoteVideoCallDescription)
                    .fieldShowCondition("remoteVideoCall=\"Yes\"");
        fields.readonlyNoSummary(CaseData::getRemoteVideoCallTribunalResponseTitle);
        fields.mandatory(CaseData::getIsRemoteHearingAllowed);
        fields.mandatory(CaseData::getRemoteVideoCallTribunalResponse);
    }
}
