package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.InterpreterSpokenLanguage;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code witness10InterpreterSpokenLanguage} of event {@code updateHearingRequirements}.
 */
public final class UpdateHearingRequirementsWitness10InterpreterSpokenLanguagePage {
    private UpdateHearingRequirementsWitness10InterpreterSpokenLanguagePage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("witness10InterpreterSpokenLanguage");
        fields.showCondition("witness10InterpreterLanguageCategoryCONTAINS\"spokenLanguageInterpreter\" AND isWitnessesAttending=\"Yes\" AND isAnyWitnessInterpreterRequired=\"Yes\" AND witness10.isWitnessDeleted!=\"Yes\"");
        fields.complex(CaseData::getWitness10InterpreterSpokenLanguage)
                    .mandatory(InterpreterSpokenLanguage::getLanguageRefData)
                    .optional(InterpreterSpokenLanguage::getLanguageManualEntry)
                    .mandatory(InterpreterSpokenLanguage::getLanguageManualEntryDescription).done()
                    .caseEventFieldLabel("Which spoken language interpreter is needed for ${witness10.witnessName} ${witness10.witnessFamilyName}?");
    }
}
