package uk.gov.hmcts.reform.iacaseapi.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Wizard page {@code homeOfficeAppealResponse} of event {@code uploadHomeOfficeAppealResponse}.
 */
public final class UploadHomeOfficeAppealResponseHomeOfficeAppealResponsePage {
    private UploadHomeOfficeAppealResponseHomeOfficeAppealResponsePage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("homeOfficeAppealResponse");
        fields.readonlyNoSummary(CaseData::getAddHomeOfficeAppealResponseTitle)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getUploadedHomeOfficeAppealResponseDocs)
                    .publish(false);
        fields.mandatory(CaseData::getHomeOfficeAppealResponseDocument)
                    .publish(false);
        fields.optional(CaseData::getHomeOfficeAppealResponseDescription)
                    .publish(false);
        fields.optional(CaseData::getHomeOfficeAppealResponseEvidence)
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getAppellantInDetention)
                    .fieldShowCondition("appealReviewDecisionTitle=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
        fields.mandatoryNoSummary(CaseData::getIsNotificationTurnedOff)
                    .fieldShowCondition("appealReviewDecisionTitle=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
        fields.mandatoryNoSummary(CaseData::getStf24wCurrentStatusAutoGenerated)
                    .fieldShowCondition("appealReviewDecisionTitle=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
        fields.mandatoryNoSummary(CaseData::getStf24wPreviousStatusWasYesAutoGenerated)
                    .fieldShowCondition("appealReviewDecisionTitle=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
    }
}
