package uk.gov.hmcts.reform.iacaseapi.domain.handlers.presubmit.statutorytimeframe24weeks;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.mockito.junit.jupiter.MockitoSettings;
import org.mockito.quality.Strictness;
import uk.gov.hmcts.reform.iacaseapi.domain.entities.AsylumCase;
import uk.gov.hmcts.reform.iacaseapi.domain.entities.StatutoryTimeframe24Weeks;
import uk.gov.hmcts.reform.iacaseapi.domain.entities.StatutoryTimeframe24WeeksHistory;
import uk.gov.hmcts.reform.iacaseapi.domain.entities.ccd.field.IdValue;
import uk.gov.hmcts.reform.iacaseapi.domain.entities.ccd.field.YesOrNo;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import static org.apache.commons.lang3.StringUtils.EMPTY;
import static org.apache.commons.lang3.StringUtils.SPACE;
import static org.mockito.Mockito.*;
import static uk.gov.hmcts.reform.iacaseapi.domain.entities.AsylumCaseFieldDefinition.APPEAL_SUBMISSION_DATE;
import static uk.gov.hmcts.reform.iacaseapi.domain.entities.AsylumCaseFieldDefinition.XUI_BANNER_TEXT;
import static uk.gov.hmcts.reform.iacaseapi.domain.entities.ccd.field.YesOrNo.NO;
import static uk.gov.hmcts.reform.iacaseapi.domain.entities.ccd.field.YesOrNo.YES;

@MockitoSettings(strictness = Strictness.LENIENT)
@ExtendWith(MockitoExtension.class)
class BannerTextServiceTest {
    private static final String PRE_EXISTING_BANNER_TEXT = "Some text";
    private static final String STF_24_W_BANNER_TEXT = "24 Week STF: case deadline 27 May 2026";
    private static final String APPEAL_SUBMISSION_DATE_STR = "2025-12-10";
    private static final int ONE = 1;

    List<IdValue<StatutoryTimeframe24WeeksHistory>> history = new ArrayList<>();
    private BannerTextService subject;
    @Mock
    private AsylumCase asylumCase;

    @BeforeEach
    public void setUp() {
        when(asylumCase.read(APPEAL_SUBMISSION_DATE)).thenReturn(Optional.of(APPEAL_SUBMISSION_DATE_STR));
        subject = new BannerTextService();
    }

    @Test
    void shouldAdd24wBannerTextIfNoCaseBannerTextExists() {
        subject.updateBannerText(asylumCase, buildSTF24WeeksWithStatus(YES));
        verifyBannerTextUpdateWith(STF_24_W_BANNER_TEXT);
    }

    @Test
    void shouldAppend24WBannerTextToExistingCaseBannerText() {
        when(asylumCase.read(XUI_BANNER_TEXT)).thenReturn(Optional.of(PRE_EXISTING_BANNER_TEXT));
        subject.updateBannerText(asylumCase, buildSTF24WeeksWithStatus(YES));
        verifyBannerTextUpdateWith(PRE_EXISTING_BANNER_TEXT + SPACE + STF_24_W_BANNER_TEXT);
    }

    @Test
    void shouldAdd24WBannerTextIfExistingCaseBannerText() {
        when(asylumCase.read(XUI_BANNER_TEXT)).thenReturn(Optional.of(EMPTY));
        subject.updateBannerText(asylumCase, buildSTF24WeeksWithStatus(YES));
        verifyBannerTextUpdateWith(STF_24_W_BANNER_TEXT);
    }

    @Test
    void shouldRemove24wBannerTextFromTheCaseBannerTextAndUpdateWithEmptyText() {
        when(asylumCase.read(XUI_BANNER_TEXT)).thenReturn(Optional.of(STF_24_W_BANNER_TEXT));
        subject.updateBannerText(asylumCase, buildSTF24WeeksWithStatus(NO));
        verifyBannerTextUpdateWith(EMPTY);
    }

    @Test
    void shouldRemove24wBannerTextFromTheCaseBannerTextHasSomeText() {
        when(asylumCase.read(XUI_BANNER_TEXT)).thenReturn(Optional.of(PRE_EXISTING_BANNER_TEXT + EMPTY + STF_24_W_BANNER_TEXT));
        subject.updateBannerText(asylumCase, buildSTF24WeeksWithStatus(NO));
        verifyBannerTextUpdateWith(PRE_EXISTING_BANNER_TEXT);
    }

    private void verifyBannerTextUpdateWith(String bannerTextWriteIntoDB) {
        verify(asylumCase, times(ONE)).write(XUI_BANNER_TEXT, bannerTextWriteIntoDB);
    }

    private StatutoryTimeframe24Weeks buildSTF24WeeksWithStatus(YesOrNo statusAutoGenerated) {
        return new StatutoryTimeframe24Weeks(statusAutoGenerated, EMPTY, this.history);
    }

}
