package uk.gov.hmcts.reform.iacaseapi.domain.handlers.presubmit.statutorytimeframe24weeks;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.mockito.junit.jupiter.MockitoSettings;
import org.mockito.quality.Strictness;
import uk.gov.hmcts.reform.iacaseapi.domain.entities.AsylumCase;
import uk.gov.hmcts.reform.iacaseapi.domain.entities.StatutoryTimeframe24Weeks;
import uk.gov.hmcts.reform.iacaseapi.domain.entities.ccd.field.YesOrNo;
import uk.gov.hmcts.reform.iacaseapi.domain.service.BannerTextService;

import java.util.ArrayList;
import java.util.Optional;

import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;
import static uk.gov.hmcts.reform.iacaseapi.domain.entities.AsylumCaseFieldDefinition.APPEAL_SUBMISSION_DATE;
import static uk.gov.hmcts.reform.iacaseapi.domain.entities.AsylumCaseFieldDefinition.STF_24W_CURRENT_STATUS_AUTO_GENERATED;
import static uk.gov.hmcts.reform.iacaseapi.domain.entities.AsylumCaseFieldDefinition.TRIBUNAL_RECEIVED_DATE;

@MockitoSettings(strictness = Strictness.LENIENT)
@ExtendWith(MockitoExtension.class)
class STF24WeeksBannerTextServiceTest {
    private static final String STF_24_W_BANNER_TEXT_TRIB_RECEIVED_DATE = "24 Week STF (27 May 2026)";
    private static final String STF_24_W_BANNER_TEXT_APPEAL_SUBMIT_DATE = "24 Week STF (28 May 2026)";
    private static final String APPEAL_SUBMISSION_DATE_STR = "2025-12-11";
    private static final String TRIBUNAL_RECEIVED_DATE_STR = "2025-12-10";
    private static final int ONE = 1;

    @Mock
    private BannerTextService bannerTextService;
    @Mock
    private AsylumCase asylumCase;

    private STF24WeeksBannerTextService subject;


    @BeforeEach
    public void setUp() {


        when(asylumCase.read(APPEAL_SUBMISSION_DATE)).thenReturn(Optional.of(APPEAL_SUBMISSION_DATE_STR));
        when(asylumCase.read(TRIBUNAL_RECEIVED_DATE)).thenReturn(Optional.of(TRIBUNAL_RECEIVED_DATE_STR));
        when(asylumCase.read(STF_24W_CURRENT_STATUS_AUTO_GENERATED, YesOrNo.class)).thenReturn(Optional.of(YesOrNo.YES));
        subject = new STF24WeeksBannerTextService(bannerTextService);
    }

    @Test
    void shouldAdd24wBannerTextIfNoCaseBannerTextExists() {
        subject.updateBannerText(asylumCase);
        verifyBannerTextUpdateWith(STF_24_W_BANNER_TEXT_TRIB_RECEIVED_DATE);
    }

    @Test
    void shouldAppend24WBannerTextToExistingCaseBannerText() {
        subject.updateBannerText(asylumCase);
        verifyBannerTextUpdateWith(STF_24_W_BANNER_TEXT_TRIB_RECEIVED_DATE);
    }

    @Test
    void shouldAppend24WBannerTextToExistingCaseBannerTextForAppealSubmitDate() {
        when(asylumCase.read(TRIBUNAL_RECEIVED_DATE)).thenReturn(Optional.empty());
        when(asylumCase.read(APPEAL_SUBMISSION_DATE)).thenReturn(Optional.of(APPEAL_SUBMISSION_DATE_STR));
        subject.updateBannerText(asylumCase);
        verifyBannerTextUpdateWith(STF_24_W_BANNER_TEXT_APPEAL_SUBMIT_DATE);
    }

    @Test
    void shouldAdd24WBannerTextIfExistingCaseBannerText() {
        subject.updateBannerText(asylumCase);
        verifyBannerTextUpdateWith(STF_24_W_BANNER_TEXT_TRIB_RECEIVED_DATE);
    }

    @Test
    void shouldRemove24wBannerTextFromTheCaseBannerTextAndUpdateWithEmptyText() {
        when(asylumCase.read(STF_24W_CURRENT_STATUS_AUTO_GENERATED, YesOrNo.class)).thenReturn(Optional.of(YesOrNo.NO));
        subject.updateBannerText(asylumCase);
        verifyBannerTextRemove(STF_24_W_BANNER_TEXT_TRIB_RECEIVED_DATE);
    }

    @Test
    void shouldRemove24wBannerTextFromTheCaseBannerTextHasSomeText() {
        when(asylumCase.read(STF_24W_CURRENT_STATUS_AUTO_GENERATED, YesOrNo.class)).thenReturn(Optional.of(YesOrNo.NO));
        subject.updateBannerText(asylumCase);
        verifyBannerTextRemove(STF_24_W_BANNER_TEXT_TRIB_RECEIVED_DATE);
    }

    private void verifyBannerTextUpdateWith(String bannerTextWriteIntoDB) {
        verify(bannerTextService, times(ONE)).addToBannerText(asylumCase, bannerTextWriteIntoDB);
    }

    private void verifyBannerTextRemove(String bannerTextWriteIntoDB) {
        verify(bannerTextService, times(ONE)).removeFromBannerText(asylumCase, bannerTextWriteIntoDB);
    }

    private StatutoryTimeframe24Weeks buildSTF24WeeksWithStatus(YesOrNo statusAutoGenerated) {
        return new StatutoryTimeframe24Weeks(new ArrayList<>());
    }

}

