package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import java.util.EnumSet;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code addStatutoryTimeframe24Weeks} for case type {@code Asylum}.
 */
@Component
public class AddStatutoryTimeframe24Weeks implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ADD_STATUTORY_TIMEFRAME24_WEEKS = "addStatutoryTimeframe24Weeks";

    /**
     * Registers event {@code addStatutoryTimeframe24Weeks}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(ADD_STATUTORY_TIMEFRAME24_WEEKS)
            .forStateTransition(EnumSet.of(State.pendingPayment, State.appealSubmitted, State.awaitingRespondentEvidence, State.awaitingClarifyingQuestionsAnswers, State.clarifyingQuestionsAnswersSubmitted), State.listing)
            .name("Add Statutory Timeframe")
            .description("Add Statutory Timeframe 24 Weeks")
            .displayOrder(124)
            .showCondition("stf24wCurrentStatusAutoGenerated!=\"Yes\" AND appellantInDetention!=\"Yes\" AND appealOutOfCountry!=\"Yes\"")
            .showSummary()
            .endButtonLabel("Submit")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_ADMOFFICER, UserRole.CASEWORKER_IA_CASEOFFICER, UserRole.CASEWORKER_IA_IACJUDGE, UserRole.CASEWORKER_IA_SYSTEM, UserRole.CASEWORKER_WA_TASK_CONFIGURATION)
            .fields();
        fields.page("addStatutoryTimeframe24Weeks");
        fields.mandatory(CaseData::getStf24wCurrentReasonAutoGenerated)
                    .publish(false);
    }
}
