package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code adjournHearingWithoutDate} for case type {@code Asylum}.
 */
@Component
public class AdjournHearingWithoutDate implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ADJOURN_HEARING_WITHOUT_DATE = "adjournHearingWithoutDate";

    /**
     * Registers event {@code adjournHearingWithoutDate}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(ADJOURN_HEARING_WITHOUT_DATE)
            .forStateTransition(EnumSet.of(State.preHearing, State.finalBundling, State.prepareForHearing, State.decision, State.respondentReview, State.awaitingRespondentEvidence, State.caseBuilding, State.caseUnderReview, State.submitHearingRequirements, State.awaitingReasonsForAppeal, State.reasonsForAppealSubmitted, State.clarifyingQuestionsAnswersSubmitted, State.awaitingClarifyingQuestionsAnswers), State.adjourned)
            .name("Adjourn hearing without a date")
            .displayOrder(47)
            .showSummary()
            .endButtonLabel("Adjourn")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_ADMOFFICER, UserRole.CASEWORKER_IA_CASEOFFICER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_IA_IACJUDGE)
            .fields();
        fields.page("adjournHearingPage1");
        fields.readonlyNoSummary(CaseData::getAdjournHearingWithoutDateReasonsTitle)
                    .publish(false);
        fields.readonly(CaseData::getIsIntegrated)
                    .fieldShowCondition("adjournHearingWithoutDateReasonsTitle=\"DO_NOT_SHOW_ON_UI\"")
                    .publish(false);
        fields.mandatory(CaseData::getAdjournHearingWithoutDateReasons)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getStateBeforeAdjournWithoutDate)
                    .fieldShowCondition("adjournHearingWithoutDateReasonsTitle=\"DUMMY_FIELD_TO_HIDE\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getDateBeforeAdjournWithoutDate)
                    .fieldShowCondition("adjournHearingWithoutDateReasonsTitle=\"DUMMY_FIELD_TO_HIDE\"")
                    .publish(false);
    }
}
