package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.ApplyForFTPAAppellantFtpaAppellantSubmissionOutOfTimePagePage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.ApplyForFTPAAppellantFtpaAppellantSubmissionPagePage;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code applyForFTPAAppellant} for case type {@code Asylum}.
 */
@Component
public class ApplyForFTPAAppellant implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String APPLY_FOR_FTPAAPPELLANT = "applyForFTPAAppellant";

    /**
     * Registers event {@code applyForFTPAAppellant}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(APPLY_FOR_FTPAAPPELLANT)
            .forStates(State.decided, State.ftpaSubmitted, State.ftpaDecided)
            .name("Apply for permission to appeal")
            .displayOrder(43)
            .showSummary()
            .endButtonLabel("Submit")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_ADMOFFICER, UserRole.CASEWORKER_IA_LEGALREP_SOLICITOR, UserRole.CITIZEN)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_IA_CASEOFFICER, UserRole.CASEWORKER_IA_IACJUDGE)
            .fields();
        ApplyForFTPAAppellantFtpaAppellantSubmissionOutOfTimePagePage.apply(fields);
        ApplyForFTPAAppellantFtpaAppellantSubmissionPagePage.apply(fields);
    }
}
