package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code ariaCreateCase} for case type {@code Asylum}.
 */
@Component
public class AriaCreateCase implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ARIA_CREATE_CASE = "ariaCreateCase";

    /**
     * Registers event {@code ariaCreateCase}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(ARIA_CREATE_CASE)
            .initialState(State.migrated)
            .name("Aria Create Case")
            .description("Aria migrate")
            .displayOrder(1)
            .showSummary()
            .endButtonLabel("Submit")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_SYSTEM)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_IA_ADMOFFICER, UserRole.CASEWORKER_IA_CASEOFFICER)
            .fields();
        fields.page("ariaCreateCasePage");
        fields.readonlyNoSummary(CaseData::getDummyEmptyLabel)
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getAriaMigrationTaskDueDays)
                    .fieldShowCondition("dummyEmptyLabel=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
        fields.mandatoryNoSummary(CaseData::getRemissionType)
                    .fieldShowCondition("dummyEmptyLabel=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
        fields.mandatoryNoSummary(CaseData::getRemissionDecision)
                    .fieldShowCondition("dummyEmptyLabel=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
        fields.mandatoryNoSummary(CaseData::getAppellantInDetention)
                    .fieldShowCondition("dummyEmptyLabel=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
        fields.mandatoryNoSummary(CaseData::getIsNotificationTurnedOff)
                    .fieldShowCondition("dummyEmptyLabel=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
    }
}
