package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code completeCaseReview} for case type {@code Asylum}.
 */
@Component
public class CompleteCaseReview implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String COMPLETE_CASE_REVIEW = "completeCaseReview";

    /**
     * Registers event {@code completeCaseReview}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(COMPLETE_CASE_REVIEW)
            .forStateTransition(State.appealSubmitted, State.listing)
            .name("Complete case review")
            .displayOrder(125)
            .showSummary(false)
            .endButtonLabel("Submit")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_CASEOFFICER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_IA_ADMOFFICER, UserRole.CASEWORKER_IA_IACJUDGE, UserRole.CITIZEN)
            .fields();
        fields.page("completeCaseReview");
        fields.readonlyNoSummary(CaseData::getCompleteCaseReviewStf24Title)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getStf24wCurrentStatusAutoGenerated)
                    .fieldShowCondition("completeCaseReviewStf24Title=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
        fields.readonlyNoSummary(CaseData::getStf24wPreviousStatusWasYesAutoGenerated)
                    .fieldShowCondition("completeCaseReviewStf24Title=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
    }
}
