package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code completeClarifyQuestions} for case type {@code Asylum}.
 */
@Component
public class CompleteClarifyQuestions implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String COMPLETE_CLARIFY_QUESTIONS = "completeClarifyQuestions";

    /**
     * Registers event {@code completeClarifyQuestions}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.event(COMPLETE_CLARIFY_QUESTIONS)
            .forState(State.awaitingClarifyingQuestionsAnswers)
            .name("Complete Clarifying Questions")
            .displayOrder(44)
            .showSummary(false)
            .endButtonLabel("Complete Clarifying Questions")
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_CASEOFFICER);
    }
}
