package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code createFlag} for case type {@code Asylum}.
 */
@Component
public class CreateFlag implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CREATE_FLAG = "createFlag";

    /**
     * Registers event {@code createFlag}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(CREATE_FLAG)
            .forStates(State.appealSubmitted, State.awaitingRespondentEvidence, State.caseBuilding, State.caseUnderReview, State.respondentReview, State.submitHearingRequirements, State.listing, State.prepareForHearing, State.finalBundling, State.preHearing, State.decision, State.decided, State.ended, State.appealTakenOffline, State.awaitingReasonsForAppeal, State.reasonsForAppealSubmitted, State.ftpaSubmitted, State.ftpaDecided, State.awaitingClarifyingQuestionsAnswers, State.clarifyingQuestionsAnswersSubmitted, State.awaitingCmaRequirements, State.cmaRequirementsSubmitted, State.cmaAdjustmentsAgreed, State.cmaListed, State.adjourned, State.pendingPayment, State.remitted)
            .name("Create Flag")
            .displayOrder(11)
            .showSummary()
            .endButtonLabel("Create Flag")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.IA_CASEFLAGS_PROFILE)
            .fields();
        fields.page("createFlag");
        fields.optional(CaseData::getCaseFlags)
                    .fieldShowCondition("flagLauncher=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .retainHiddenValue()
                    .publish(false);
        fields.optional(CaseData::getAppellantLevelFlags)
                    .fieldShowCondition("flagLauncher=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .retainHiddenValue()
                    .publish(false);
        fields.optional(CaseData::getWitnessLevelFlags)
                    .fieldShowCondition("flagLauncher=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .retainHiddenValue()
                    .publish(false);
        fields.optional(CaseData::getNlrLevelFlags)
                    .fieldShowCondition("flagLauncher=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .retainHiddenValue()
                    .publish(false);
        fields.optional(CaseData::getInterpreterLevelFlags)
                    .fieldShowCondition("flagLauncher=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .retainHiddenValue()
                    .publish(false);
        fields.mandatory(CaseData::getFlagLauncher)
                    .displayContextParameter("#ARGUMENT(CREATE)")
                    .publish(false);
    }
}
