package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code customiseHearingBundle} for case type {@code Asylum}.
 */
@Component
public class CustomiseHearingBundle implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CUSTOMISE_HEARING_BUNDLE = "customiseHearingBundle";

    /**
     * Registers event {@code customiseHearingBundle}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(CUSTOMISE_HEARING_BUNDLE)
            .forState(State.finalBundling)
            .name("Customise hearing bundle")
            .displayOrder(24)
            .showSummary(false)
            .endButtonLabel("Generate")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_CASEOFFICER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_IA_ADMOFFICER, UserRole.CASEWORKER_IA_IACJUDGE)
            .fields();
        fields.page("customiseBundle");
        fields.readonly(CaseData::getCaseFlagSetAsideReheardExists)
                    .fieldShowCondition("customHearingDocuments=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .publish(false);
        fields.readonly(CaseData::getSourceOfRemittal)
                    .fieldShowCondition("customHearingDocuments=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .publish(false);
        fields.optionalNoSummary(CaseData::getCustomHearingDocuments)
                    .fieldShowCondition("caseFlagSetAsideReheardExists!=\"Yes\"")
                    .publish(false);
        fields.optionalNoSummary(CaseData::getCustomLegalRepDocuments)
                    .fieldShowCondition("caseFlagSetAsideReheardExists!=\"Yes\"")
                    .publish(false);
        fields.optionalNoSummary(CaseData::getCustomAdditionalEvidenceDocuments)
                    .fieldShowCondition("caseFlagSetAsideReheardExists!=\"Yes\"")
                    .publish(false);
        fields.optionalNoSummary(CaseData::getCustomRespondentDocuments)
                    .fieldShowCondition("caseFlagSetAsideReheardExists!=\"Yes\"")
                    .publish(false);
        fields.optionalNoSummary(CaseData::getCustomTribunalDocuments)
                    .fieldShowCondition("caseFlagSetAsideReheardExists!=\"Yes\"")
                    .publish(false);
        fields.optionalNoSummary(CaseData::getAppellantAddendumEvidenceDocs)
                    .fieldShowCondition("customHearingDocuments=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .publish(false);
        fields.optionalNoSummary(CaseData::getRespondentAddendumEvidenceDocs)
                    .fieldShowCondition("customHearingDocuments=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .publish(false);
        fields.optionalNoSummary(CaseData::getAppAdditionalEvidenceDocs)
                    .fieldShowCondition("customHearingDocuments=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .publish(false);
        fields.optionalNoSummary(CaseData::getRespAdditionalEvidenceDocs)
                    .fieldShowCondition("customHearingDocuments=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .publish(false);
        fields.optional(CaseData::getCustomAppAdditionalEvidenceDocs)
                    .fieldShowCondition("caseFlagSetAsideReheardExists=\"Yes\" AND sourceOfRemittal!=\"*\"")
                    .publish(false);
        fields.optionalNoSummary(CaseData::getCustomRespAdditionalEvidenceDocs)
                    .fieldShowCondition("caseFlagSetAsideReheardExists=\"Yes\" AND sourceOfRemittal!=\"*\"")
                    .publish(false);
        fields.optionalNoSummary(CaseData::getCustomFtpaAppellantDocs)
                    .fieldShowCondition("caseFlagSetAsideReheardExists=\"Yes\"")
                    .publish(false);
        fields.optionalNoSummary(CaseData::getCustomFtpaRespondentDocs)
                    .fieldShowCondition("caseFlagSetAsideReheardExists=\"Yes\" AND sourceOfRemittal!=\"*\"")
                    .publish(false);
        fields.optionalNoSummary(CaseData::getCustomFinalDecisionAndReasonsDocs)
                    .fieldShowCondition("caseFlagSetAsideReheardExists=\"Yes\"")
                    .publish(false);
        fields.optionalNoSummary(CaseData::getCustomReheardHearingDocs)
                    .fieldShowCondition("caseFlagSetAsideReheardExists=\"Yes\"")
                    .publish(false);
        fields.optionalNoSummary(CaseData::getCustomAppAddendumEvidenceDocs)
                    .fieldShowCondition("caseFlagSetAsideReheardExists=\"Yes\"")
                    .publish(false);
        fields.optionalNoSummary(CaseData::getCustomRespAddendumEvidenceDocs)
                    .fieldShowCondition("caseFlagSetAsideReheardExists=\"Yes\"")
                    .publish(false);
        fields.optionalNoSummary(CaseData::getCustomLatestRemittalDocs)
                    .fieldShowCondition("caseFlagSetAsideReheardExists=\"Yes\" AND sourceOfRemittal=\"*\"")
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getAppellantInDetention)
                    .fieldShowCondition("customRespAddendumEvidenceDocs=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
        fields.mandatoryNoSummary(CaseData::getIsNotificationTurnedOff)
                    .fieldShowCondition("customRespAddendumEvidenceDocs=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
    }
}
