package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code decisionWithoutHearingListed} for case type {@code Asylum}.
 */
@Component
public class DecisionWithoutHearingListed implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String DECISION_WITHOUT_HEARING_LISTED = "decisionWithoutHearingListed";

    /**
     * Registers event {@code decisionWithoutHearingListed}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(DECISION_WITHOUT_HEARING_LISTED)
            .forAllStates()
            .name("Decision w/o hearing Listed")
            .description("System event to update case data when an on-papers hearing is listed")
            .displayOrder(105)
            .showSummary(false)
            .endButtonLabel("Decision without hearing Listed")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_SYSTEM)
            .fields();
        fields.page("decisionWithoutHearingListed");
        fields.mandatory(CaseData::getDecisionWithoutHearingListed)
                    .publish(false);
    }
}
