package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.DecideFtpaApplicationFtpaAppellantDecisionAndReasonsDocumentPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.DecideFtpaApplicationFtpaAppellantDecisionOutcomePage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.DecideFtpaApplicationFtpaAppellantDecisionReasonsNotesPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.DecideFtpaApplicationFtpaAppellantDecisionRemadeRule32Page;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.DecideFtpaApplicationFtpaAppellantFinalR35NoticePage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.DecideFtpaApplicationFtpaApplicantTypePage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.DecideFtpaApplicationFtpaDecisionLstInsPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.DecideFtpaApplicationFtpaRespondentDecisionAndReasonsDocumentPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.DecideFtpaApplicationFtpaRespondentDecisionOutcomePage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.DecideFtpaApplicationFtpaRespondentDecisionReasonsNotesPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.DecideFtpaApplicationFtpaRespondentDecisionRemadeRule32Page;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.DecideFtpaApplicationFtpaRespondentFinalR35NoticePage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.DecideFtpaApplicationIsFtpaAppellantNoticeOfDecisionSetAsidePage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.DecideFtpaApplicationIsFtpaRespondentNoticeOfDecisionSetAsidePage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.DecideFtpaApplicationRule35AppellantObjectionsPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.DecideFtpaApplicationRule35RespondentObjectionsPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code decideFtpaApplication} for case type {@code Asylum}.
 */
@Component
public class DecideFtpaApplication implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String DECIDE_FTPA_APPLICATION = "decideFtpaApplication";

    /**
     * Registers event {@code decideFtpaApplication}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(DECIDE_FTPA_APPLICATION)
            .forStateTransition(EnumSet.of(State.ftpaSubmitted, State.ftpaDecided), State.ftpaDecided)
            .name("Decide FTPA application")
            .displayOrder(46)
            .showSummary()
            .endButtonLabel("Submit")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_IACJUDGE)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_IA_ADMOFFICER, UserRole.CASEWORKER_IA_CASEOFFICER, UserRole.CITIZEN)
            .fields();
        DecideFtpaApplicationFtpaApplicantTypePage.apply(fields);
        DecideFtpaApplicationFtpaAppellantDecisionOutcomePage.apply(fields);
        DecideFtpaApplicationFtpaAppellantDecisionAndReasonsDocumentPage.apply(fields);
        DecideFtpaApplicationIsFtpaAppellantNoticeOfDecisionSetAsidePage.apply(fields);
        DecideFtpaApplicationRule35AppellantObjectionsPage.apply(fields);
        DecideFtpaApplicationFtpaAppellantFinalR35NoticePage.apply(fields);
        DecideFtpaApplicationFtpaAppellantDecisionReasonsNotesPage.apply(fields);
        DecideFtpaApplicationFtpaAppellantDecisionRemadeRule32Page.apply(fields);
        DecideFtpaApplicationFtpaRespondentDecisionOutcomePage.apply(fields);
        DecideFtpaApplicationFtpaRespondentDecisionAndReasonsDocumentPage.apply(fields);
        DecideFtpaApplicationIsFtpaRespondentNoticeOfDecisionSetAsidePage.apply(fields);
        DecideFtpaApplicationRule35RespondentObjectionsPage.apply(fields);
        DecideFtpaApplicationFtpaRespondentFinalR35NoticePage.apply(fields);
        DecideFtpaApplicationFtpaRespondentDecisionReasonsNotesPage.apply(fields);
        DecideFtpaApplicationFtpaRespondentDecisionRemadeRule32Page.apply(fields);
        DecideFtpaApplicationFtpaDecisionLstInsPage.apply(fields);
    }
}
