package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.DecideAnApplicationDecideAnApplicationPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.DecideAnApplicationRemove24WeekRefusalDecisionPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.DecideAnApplicationSelectMakeAnApplicationPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code decideAnApplication} for case type {@code Asylum}.
 */
@Component
public class DecideAnApplication implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String DECIDE_AN_APPLICATION = "decideAnApplication";

    /**
     * Registers event {@code decideAnApplication}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(DECIDE_AN_APPLICATION)
            .forStates(State.appealSubmitted, State.pendingPayment, State.awaitingRespondentEvidence, State.caseBuilding, State.caseUnderReview, State.respondentReview, State.submitHearingRequirements, State.listing, State.prepareForHearing, State.finalBundling, State.preHearing, State.decision, State.decided, State.adjourned, State.ftpaSubmitted, State.ftpaDecided, State.ended, State.awaitingReasonsForAppeal, State.reasonsForAppealSubmitted, State.awaitingClarifyingQuestionsAnswers, State.clarifyingQuestionsAnswersSubmitted, State.awaitingCmaRequirements, State.cmaRequirementsSubmitted, State.cmaAdjustmentsAgreed, State.cmaListed, State.remitted)
            .name("Decide an application")
            .displayOrder(60)
            .showSummary()
            .endButtonLabel("Record decision")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_CASEOFFICER, UserRole.CASEWORKER_IA_IACJUDGE)
            .grant(Set.of(Permission.R), UserRole.CITIZEN)
            .fields();
        DecideAnApplicationSelectMakeAnApplicationPage.apply(fields);
        DecideAnApplicationDecideAnApplicationPage.apply(fields);
        DecideAnApplicationRemove24WeekRefusalDecisionPage.apply(fields);
    }
}
