package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code decisionWithoutHearing} for case type {@code Asylum}.
 */
@Component
public class DecisionWithoutHearing implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String DECISION_WITHOUT_HEARING = "decisionWithoutHearing";

    /**
     * Registers event {@code decisionWithoutHearing}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.event(DECISION_WITHOUT_HEARING)
            .forStateTransition(EnumSet.of(State.adjourned, State.respondentReview, State.submitHearingRequirements, State.listing, State.decided), State.finalBundling)
            .name("Decision without a hearing")
            .displayOrder(49)
            .showSummary()
            .endButtonLabel("Decision")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_ADMOFFICER, UserRole.CASEWORKER_IA_CASEOFFICER, UserRole.CITIZEN)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_IA_IACJUDGE);
    }
}
