package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code editClarifyingQuestionAnswers} for case type {@code Asylum}.
 */
@Component
public class EditClarifyingQuestionAnswers implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String EDIT_CLARIFYING_QUESTION_ANSWERS = "editClarifyingQuestionAnswers";

    /**
     * Registers event {@code editClarifyingQuestionAnswers}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.event(EDIT_CLARIFYING_QUESTION_ANSWERS)
            .forState(State.awaitingClarifyingQuestionsAnswers)
            .name("Edit clarifying answers")
            .description("Edit clarifying question answers")
            .displayOrder(45)
            .showSummary()
            .endButtonLabel("Submit")
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CITIZEN);
    }
}
