package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.EditDocumentsEditDocs2Page;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.EditDocumentsEditDocsPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code editDocuments} for case type {@code Asylum}.
 */
@Component
public class EditDocuments implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String EDIT_DOCUMENTS = "editDocuments";

    /**
     * Registers event {@code editDocuments}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(EDIT_DOCUMENTS)
            .forStates(State.appealSubmitted, State.awaitingRespondentEvidence, State.caseBuilding, State.caseUnderReview, State.respondentReview, State.submitHearingRequirements, State.listing, State.prepareForHearing, State.finalBundling, State.preHearing, State.decision, State.decided, State.ended, State.awaitingReasonsForAppeal, State.reasonsForAppealSubmitted, State.ftpaSubmitted, State.ftpaDecided, State.awaitingClarifyingQuestionsAnswers, State.clarifyingQuestionsAnswersSubmitted, State.awaitingCmaRequirements, State.cmaRequirementsSubmitted, State.cmaAdjustmentsAgreed, State.cmaListed, State.adjourned, State.pendingPayment, State.remitted, State.migrated)
            .name("Edit documents")
            .displayOrder(46)
            .showSummary(false)
            .endButtonLabel("Submit")
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_ADMOFFICER, UserRole.CASEWORKER_IA_CASEOFFICER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_IA_IACJUDGE)
            .fields();
        EditDocumentsEditDocsPage.apply(fields);
        EditDocumentsEditDocs2Page.apply(fields);
    }
}
