package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.EditAppealAfterSubmitAdminJSponsorContactPreferencePage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.EditAppealAfterSubmitAppealWasNotSubmittedMyHmCtsPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.EditAppealAfterSubmitAppellantAddressAdminJPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.EditAppealAfterSubmitAppellantAddressPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.EditAppealAfterSubmitAppellantBasicDetailsPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.EditAppealAfterSubmitAppellantContactDetailsPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.EditAppealAfterSubmitAppellantContactPreferencePage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.EditAppealAfterSubmitAppellantNationalitiesPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.EditAppealAfterSubmitAppellantsRepresentationPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.EditAppealAfterSubmitChecklistPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.EditAppealAfterSubmitDepartureDateAdminJPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.EditAppealAfterSubmitDepartureDatePage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.EditAppealAfterSubmitDeportationOrderPagePage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.EditAppealAfterSubmitEntryClearanceDecisionLetterPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.EditAppealAfterSubmitHasOtherAppealsPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.EditAppealAfterSubmitHomeOfficeDecisionLetterPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.EditAppealAfterSubmitHomeOfficeReferenceNumberPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.EditAppealAfterSubmitInternalContactDetailsPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.EditAppealAfterSubmitLegalRepresentativeAddressPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.EditAppealAfterSubmitLegalRepresentativeDetailsPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.EditAppealAfterSubmitLegalRepresentativeDetailsPaperJPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.EditAppealAfterSubmitNewMattersPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.EditAppealAfterSubmitNlrDetailsPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.EditAppealAfterSubmitOocAppellantAddressPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.EditAppealAfterSubmitOocHomeOfficeReferenceNumberPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.EditAppealAfterSubmitOtherAppealsPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.EditAppealAfterSubmitOutOfCountryAppealAdminJPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.EditAppealAfterSubmitOutOfCountryDecisionTypePage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.EditAppealAfterSubmitOutOfCountryPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.EditAppealAfterSubmitRemovalDirectionsPagePage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.EditAppealAfterSubmitRpDcAppealHearingOptionPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.EditAppealAfterSubmitSourceOfAppealPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.EditAppealAfterSubmitSponsorAddressPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.EditAppealAfterSubmitSponsorAuthorisationPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.EditAppealAfterSubmitSponsorContactPreferencePage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.EditAppealAfterSubmitSponsorNamePage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.EditAppealAfterSubmitSponsorPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.EditAppealAfterSubmitSubmissionOutOfTimePagePage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.EditAppealAfterSubmitTribunalReceivedAppealPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.EditAppealAfterSubmitUploadTheNoticeOfDecisionPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code editAppealAfterSubmit} for case type {@code Asylum}.
 */
@Component
public class EditAppealAfterSubmit implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String EDIT_APPEAL_AFTER_SUBMIT = "editAppealAfterSubmit";

    /**
     * Registers event {@code editAppealAfterSubmit}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(EDIT_APPEAL_AFTER_SUBMIT)
            .forAllStates()
            .name("Edit appeal")
            .displayOrder(2)
            .showCondition("[STATE]!=\"appealStarted\" AND [STATE]!=\"appealStartedByAdmin\"")
            .showSummary()
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_ADMOFFICER, UserRole.CASEWORKER_IA_CASEOFFICER, UserRole.CASEWORKER_IA_IACJUDGE, UserRole.CITIZEN)
            .fields();
        EditAppealAfterSubmitChecklistPage.apply(fields);
        EditAppealAfterSubmitSourceOfAppealPage.apply(fields);
        EditAppealAfterSubmitTribunalReceivedAppealPage.apply(fields);
        EditAppealAfterSubmitAppellantsRepresentationPage.apply(fields);
        EditAppealAfterSubmitAppealWasNotSubmittedMyHmCtsPage.apply(fields);
        EditAppealAfterSubmitLegalRepresentativeDetailsPaperJPage.apply(fields);
        EditAppealAfterSubmitLegalRepresentativeAddressPage.apply(fields);
        EditAppealAfterSubmitOutOfCountryPage.apply(fields);
        EditAppealAfterSubmitOutOfCountryDecisionTypePage.apply(fields);
        EditAppealAfterSubmitOutOfCountryAppealAdminJPage.apply(fields);
        EditAppealAfterSubmitDepartureDateAdminJPage.apply(fields);
        EditAppealAfterSubmitDepartureDatePage.apply(fields);
        EditAppealAfterSubmitHomeOfficeReferenceNumberPage.apply(fields);
        EditAppealAfterSubmitOocHomeOfficeReferenceNumberPage.apply(fields);
        EditAppealAfterSubmitAppellantBasicDetailsPage.apply(fields);
        EditAppealAfterSubmitAppellantNationalitiesPage.apply(fields);
        EditAppealAfterSubmitAppellantAddressPage.apply(fields);
        EditAppealAfterSubmitOocAppellantAddressPage.apply(fields);
        EditAppealAfterSubmitAppellantAddressAdminJPage.apply(fields);
        EditAppealAfterSubmitAppellantContactPreferencePage.apply(fields);
        EditAppealAfterSubmitAppellantContactDetailsPage.apply(fields);
        EditAppealAfterSubmitInternalContactDetailsPage.apply(fields);
        EditAppealAfterSubmitHomeOfficeDecisionLetterPage.apply(fields);
        EditAppealAfterSubmitEntryClearanceDecisionLetterPage.apply(fields);
        EditAppealAfterSubmitUploadTheNoticeOfDecisionPage.apply(fields);
        EditAppealAfterSubmitSponsorPage.apply(fields);
        EditAppealAfterSubmitSponsorNamePage.apply(fields);
        EditAppealAfterSubmitSponsorAddressPage.apply(fields);
        EditAppealAfterSubmitSponsorContactPreferencePage.apply(fields);
        EditAppealAfterSubmitAdminJSponsorContactPreferencePage.apply(fields);
        EditAppealAfterSubmitSponsorAuthorisationPage.apply(fields);
        EditAppealAfterSubmitNlrDetailsPage.apply(fields);
        EditAppealAfterSubmitDeportationOrderPagePage.apply(fields);
        EditAppealAfterSubmitRemovalDirectionsPagePage.apply(fields);
        EditAppealAfterSubmitNewMattersPage.apply(fields);
        EditAppealAfterSubmitHasOtherAppealsPage.apply(fields);
        EditAppealAfterSubmitOtherAppealsPage.apply(fields);
        EditAppealAfterSubmitLegalRepresentativeDetailsPage.apply(fields);
        EditAppealAfterSubmitRpDcAppealHearingOptionPage.apply(fields);
        EditAppealAfterSubmitSubmissionOutOfTimePagePage.apply(fields);
    }
}
