package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code editCmaRequirements} for case type {@code Asylum}.
 */
@Component
public class EditCmaRequirements implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String EDIT_CMA_REQUIREMENTS = "editCmaRequirements";

    /**
     * Registers event {@code editCmaRequirements}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.event(EDIT_CMA_REQUIREMENTS)
            .forState(State.awaitingCmaRequirements)
            .name("edit CMA requirements")
            .description("Edit CMA requirements")
            .displayOrder(47)
            .showSummary()
            .endButtonLabel("Edit")
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_CASEOFFICER, UserRole.CITIZEN);
    }
}
