package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.FlagCaseFlagCase2Page;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.FlagCaseFlagCasePage;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code flagCase} for case type {@code Asylum}.
 */
@Component
public class FlagCase implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String FLAG_CASE = "flagCase";

    /**
     * Registers event {@code flagCase}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(FLAG_CASE)
            .forAllStates()
            .name("Flag the case")
            .displayOrder(45)
            .showSummary()
            .endButtonLabel("Flag case")
            .explicitGrants()
            .fields();
        FlagCaseFlagCasePage.apply(fields);
        FlagCaseFlagCase2Page.apply(fields);
    }
}
