package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import java.util.EnumSet;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.ForceFtpaDecidedStateFtpaAppellantDecisionOutcomePage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.ForceFtpaDecidedStateFtpaRespondentDecisionOutcomePage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.ForceFtpaDecidedStateMoveToFtpaDecidedApplicantPagePage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.ForceFtpaDecidedStateMoveToFtpaDecidedDatePagePage;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code forceFtpaDecidedState} for case type {@code Asylum}.
 */
@Component
public class ForceFtpaDecidedState implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String FORCE_FTPA_DECIDED_STATE = "forceFtpaDecidedState";

    /**
     * Registers event {@code forceFtpaDecidedState}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(FORCE_FTPA_DECIDED_STATE)
            .forStateTransition(EnumSet.allOf(State.class), State.ftpaDecided)
            .name("Force FTPA decided state")
            .description("Move the appeal to the appeal FTPA decided state")
            .displayOrder(125)
            .showCondition("[STATE]!=\"appealStarted\" AND [STATE]!=\"appealStartedByAdmin\" AND isRehydratedAppeal=\"Yes\" AND isAdmin=\"Yes\" AND hasBeenFtpaDecided!=\"Yes\"")
            .showSummary()
            .endButtonLabel("Force to FTPA decided")
            .explicitGrants()
            .fields();
        ForceFtpaDecidedStateMoveToFtpaDecidedDatePagePage.apply(fields);
        ForceFtpaDecidedStateMoveToFtpaDecidedApplicantPagePage.apply(fields);
        ForceFtpaDecidedStateFtpaAppellantDecisionOutcomePage.apply(fields);
        ForceFtpaDecidedStateFtpaRespondentDecisionOutcomePage.apply(fields);
    }
}
