package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code forceCaseToCaseUnderReview} for case type {@code Asylum}.
 */
@Component
public class ForceCaseToCaseUnderReview implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String FORCE_CASE_TO_CASE_UNDER_REVIEW = "forceCaseToCaseUnderReview";

    /**
     * Registers event {@code forceCaseToCaseUnderReview}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(FORCE_CASE_TO_CASE_UNDER_REVIEW)
            .forStateTransition(EnumSet.of(State.caseBuilding, State.awaitingReasonsForAppeal), State.caseUnderReview)
            .name("Force case - case under review")
            .description("Force case to case under review")
            .displayOrder(44)
            .showSummary()
            .endButtonLabel("Submit")
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_CASEOFFICER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_IA_ADMOFFICER, UserRole.CASEWORKER_IA_IACJUDGE)
            .fields();
        fields.page("forceCase");
        fields.readonlyNoSummary(CaseData::getForceCaseToCaseUnderReviewTitle);
        fields.mandatory(CaseData::getReasonToForceCaseToCaseUnderReview);
    }
}
