package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.GenerateDecisionAndReasonsAnonymityOrderPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.GenerateDecisionAndReasonsLegalRepresentativesPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code generateDecisionAndReasons} for case type {@code Asylum}.
 */
@Component
public class GenerateDecisionAndReasons implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String GENERATE_DECISION_AND_REASONS = "generateDecisionAndReasons";

    /**
     * Registers event {@code generateDecisionAndReasons}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(GENERATE_DECISION_AND_REASONS)
            .forState(State.decision)
            .name("Prepare Decision and Reasons")
            .displayOrder(25)
            .showSummary()
            .endButtonLabel("Generate")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_CASEOFFICER, UserRole.CASEWORKER_IA_IACJUDGE)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_IA_ADMOFFICER, UserRole.CITIZEN)
            .fields();
        GenerateDecisionAndReasonsAnonymityOrderPage.apply(fields);
        GenerateDecisionAndReasonsLegalRepresentativesPage.apply(fields);
    }
}
