package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code generateUpperTribunalBundle} for case type {@code Asylum}.
 */
@Component
public class GenerateUpperTribunalBundle implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String GENERATE_UPPER_TRIBUNAL_BUNDLE = "generateUpperTribunalBundle";

    /**
     * Registers event {@code generateUpperTribunalBundle}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.event(GENERATE_UPPER_TRIBUNAL_BUNDLE)
            .forState(State.ftpaDecided)
            .name("Generate Upper Tribunal bundle")
            .description("Generate upper tribunal bundle")
            .displayOrder(23)
            .showSummary(false)
            .endButtonLabel("Generate")
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_ADMOFFICER, UserRole.CASEWORKER_IA_IACJUDGE);
    }
}
