package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code generateUpdatedHearingBundle} for case type {@code Asylum}.
 */
@Component
public class GenerateUpdatedHearingBundle implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String GENERATE_UPDATED_HEARING_BUNDLE = "generateUpdatedHearingBundle";

    /**
     * Registers event {@code generateUpdatedHearingBundle}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(GENERATE_UPDATED_HEARING_BUNDLE)
            .forStates(State.preHearing, State.decision, State.adjourned, State.appealTakenOffline)
            .name("Update Hearing Bundle")
            .description("Create an updated hearing bundle")
            .displayOrder(25)
            .showSummary(false)
            .endButtonLabel("Generate")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_CASEOFFICER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_IA_ADMOFFICER, UserRole.CASEWORKER_IA_IACJUDGE)
            .fields();
        fields.page("customiseUpdatedBundle");
        fields.readonly(CaseData::getCaseFlagSetAsideReheardExists)
                    .fieldShowCondition("customHearingDocuments=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .publish(false);
        fields.optionalNoSummary(CaseData::getCustomHearingDocuments)
                    .fieldShowCondition("caseFlagSetAsideReheardExists!=\"Yes\"")
                    .publish(false);
        fields.optionalNoSummary(CaseData::getCustomLegalRepDocuments)
                    .fieldShowCondition("caseFlagSetAsideReheardExists!=\"Yes\"")
                    .publish(false);
        fields.optionalNoSummary(CaseData::getCustomAdditionalEvidenceDocuments)
                    .fieldShowCondition("caseFlagSetAsideReheardExists!=\"Yes\"")
                    .publish(false);
        fields.optionalNoSummary(CaseData::getCustomRespondentDocuments)
                    .fieldShowCondition("caseFlagSetAsideReheardExists!=\"Yes\"")
                    .publish(false);
        fields.optionalNoSummary(CaseData::getCustomTribunalDocuments)
                    .fieldShowCondition("caseFlagSetAsideReheardExists!=\"Yes\"")
                    .publish(false);
        fields.optionalNoSummary(CaseData::getAppellantAddendumEvidenceDocs)
                    .fieldShowCondition("customHearingDocuments=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .publish(false);
        fields.optionalNoSummary(CaseData::getRespondentAddendumEvidenceDocs)
                    .fieldShowCondition("customHearingDocuments=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .publish(false);
        fields.optionalNoSummary(CaseData::getAppAdditionalEvidenceDocs)
                    .fieldShowCondition("customHearingDocuments=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .publish(false);
        fields.optionalNoSummary(CaseData::getRespAdditionalEvidenceDocs)
                    .fieldShowCondition("customHearingDocuments=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .publish(false);
        fields.optionalNoSummary(CaseData::getCustomAppAdditionalEvidenceDocs)
                    .fieldShowCondition("caseFlagSetAsideReheardExists=\"Yes\"")
                    .publish(false);
        fields.optionalNoSummary(CaseData::getCustomRespAdditionalEvidenceDocs)
                    .fieldShowCondition("caseFlagSetAsideReheardExists=\"Yes\"")
                    .publish(false);
        fields.optionalNoSummary(CaseData::getCustomFtpaAppellantDocs)
                    .fieldShowCondition("caseFlagSetAsideReheardExists=\"Yes\"")
                    .publish(false);
        fields.optionalNoSummary(CaseData::getCustomFtpaRespondentDocs)
                    .fieldShowCondition("caseFlagSetAsideReheardExists=\"Yes\"")
                    .publish(false);
        fields.optionalNoSummary(CaseData::getCustomFinalDecisionAndReasonsDocs)
                    .fieldShowCondition("caseFlagSetAsideReheardExists=\"Yes\"")
                    .publish(false);
        fields.optionalNoSummary(CaseData::getCustomReheardHearingDocs)
                    .fieldShowCondition("caseFlagSetAsideReheardExists=\"Yes\"")
                    .publish(false);
        fields.optionalNoSummary(CaseData::getCustomAppAddendumEvidenceDocs)
                    .publish(false);
        fields.optionalNoSummary(CaseData::getCustomRespAddendumEvidenceDocs)
                    .publish(false);
    }
}
