package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code generateServiceRequest} for case type {@code Asylum}.
 */
@Component
public class GenerateServiceRequest implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String GENERATE_SERVICE_REQUEST = "generateServiceRequest";

    /**
     * Registers event {@code generateServiceRequest}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(GENERATE_SERVICE_REQUEST)
            .forStates(State.pendingPayment, State.appealSubmitted, State.awaitingRespondentEvidence, State.respondentReview, State.caseBuilding, State.caseUnderReview, State.submitHearingRequirements, State.listing, State.prepareForHearing, State.finalBundling, State.preHearing, State.decision, State.decided, State.awaitingReasonsForAppeal, State.reasonsForAppealSubmitted, State.awaitingClarifyingQuestionsAnswers, State.clarifyingQuestionsAnswersSubmitted, State.awaitingCmaRequirements, State.cmaRequirementsSubmitted, State.cmaAdjustmentsAgreed, State.cmaListed, State.adjourned)
            .name("Create a service request")
            .description("Create a new service request")
            .displayOrder(53)
            .showCondition("eaHuAppealTypePaymentOption!=\"payOffline\" AND isServiceRequestTabVisibleConsideringRemissions!=\"No\" AND remissionDecision!=\"approved\"")
            .showSummary(false)
            .endButtonLabel("Submit")
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_ADMOFFICER, UserRole.CASEWORKER_IA_LEGALREP_SOLICITOR)
            .fields();
        fields.page("createAServiceRequest");
        fields.pageLabel("Pay for this appeal");
        fields.readonlyNoSummary(CaseData::getAppealType)
                    .fieldShowCondition("remissionType=\"DO_NOT_SHOW_ON_UI\"");
        fields.readonlyNoSummary(CaseData::getRemissionType)
                    .fieldShowCondition("appealType=\"DO_NOT_SHOW_ON_UI\"");
        fields.readonlyNoSummary(CaseData::getLegalRepCreateServiceRequestHeader);
        fields.readonlyNoSummary(CaseData::getLegalRepCreateServiceRequestDescription);
        fields.readonlyNoSummary(CaseData::getLegalRepCreateServiceRequestFeeHeader);
        fields.readonlyNoSummary(CaseData::getFeeAmountGbp)
                    .fieldShowCondition("newFeeAmount!=\"*\"")
                    .caseEventFieldLabel(" ");
        fields.readonlyNoSummary(CaseData::getNewFeeAmount)
                    .caseEventFieldLabel(" ");
        fields.readonlyNoSummary(CaseData::getManageFeeRequestedAmount)
                    .fieldShowCondition("newFeeAmount=\"*\"");
    }
}
