package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code listCma} for case type {@code Asylum}.
 */
@Component
public class ListCma implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String LIST_CMA = "listCma";

    /**
     * Registers event {@code listCma}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(LIST_CMA)
            .forStateTransition(State.cmaAdjustmentsAgreed, State.cmaListed)
            .name("List the appointment")
            .description("List CMA")
            .displayOrder(50)
            .showSummary()
            .endButtonLabel("Submit")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_ADMOFFICER)
            .grant(Set.of(Permission.R), UserRole.CITIZEN)
            .fields();
        fields.page("listCmaHearing");
        fields.readonlyNoSummary(CaseData::getListCmaHearingTitle)
                    .publish(false);
        fields.mandatory(CaseData::getAriaListingReference)
                    .publish(false);
        fields.mandatory(CaseData::getListCaseHearingCentre)
                    .publish(false);
        fields.mandatory(CaseData::getListCaseHearingLength)
                    .publish(false);
        fields.mandatory(CaseData::getListCaseHearingDate)
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getIsNotificationTurnedOff)
                    .fieldShowCondition("ariaListingReference=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .publish(false);
    }
}
