package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.ListCaseWithoutHearingRequirementsAdditionalInstructionsPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.ListCaseWithoutHearingRequirementsAutoListHearingPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.ListCaseWithoutHearingRequirementsHearingChannelPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.ListCaseWithoutHearingRequirementsHearingLocationPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.ListCaseWithoutHearingRequirementsIsAppealSuitableToFloatPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.ListCaseWithoutHearingRequirementsIsHearingLinkedPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.ListCaseWithoutHearingRequirementsIsPanelRequiredPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.ListCaseWithoutHearingRequirementsListCaseWithoutHearingPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code listCaseWithoutHearingRequirements} for case type {@code Asylum}.
 */
@Component
public class ListCaseWithoutHearingRequirements implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String LIST_CASE_WITHOUT_HEARING_REQUIREMENTS = "listCaseWithoutHearingRequirements";

    /**
     * Registers event {@code listCaseWithoutHearingRequirements}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(LIST_CASE_WITHOUT_HEARING_REQUIREMENTS)
            .forState(State.submitHearingRequirements)
            .name("List without requirements")
            .displayOrder(20)
            .showSummary()
            .endButtonLabel("Submit")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_CASEOFFICER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_IA_ADMOFFICER, UserRole.CASEWORKER_IA_IACJUDGE)
            .fields();
        ListCaseWithoutHearingRequirementsListCaseWithoutHearingPage.apply(fields);
        ListCaseWithoutHearingRequirementsHearingChannelPage.apply(fields);
        ListCaseWithoutHearingRequirementsHearingLocationPage.apply(fields);
        ListCaseWithoutHearingRequirementsIsAppealSuitableToFloatPage.apply(fields);
        ListCaseWithoutHearingRequirementsIsHearingLinkedPage.apply(fields);
        ListCaseWithoutHearingRequirementsIsPanelRequiredPage.apply(fields);
        ListCaseWithoutHearingRequirementsAdditionalInstructionsPage.apply(fields);
        ListCaseWithoutHearingRequirementsAutoListHearingPage.apply(fields);
    }
}
