package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.MarkAppealAsRemittedCourtReferenceNumberPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.MarkAppealAsRemittedListingInstructionsPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.MarkAppealAsRemittedSourceOfRemittalPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.MarkAppealAsRemittedUploadOtherRemittalDocsPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.MarkAppealAsRemittedUploadRemittalDecisionPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code markAppealAsRemitted} for case type {@code Asylum}.
 */
@Component
public class MarkAppealAsRemitted implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String MARK_APPEAL_AS_REMITTED = "markAppealAsRemitted";

    /**
     * Registers event {@code markAppealAsRemitted}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(MARK_APPEAL_AS_REMITTED)
            .forStateTransition(State.ftpaDecided, State.remitted)
            .name("Mark appeal as remitted")
            .displayOrder(55)
            .showSummary()
            .endButtonLabel("Submit")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_ADMOFFICER)
            .grant(Set.of(Permission.R), UserRole.CITIZEN)
            .fields();
        MarkAppealAsRemittedSourceOfRemittalPage.apply(fields);
        MarkAppealAsRemittedCourtReferenceNumberPage.apply(fields);
        MarkAppealAsRemittedListingInstructionsPage.apply(fields);
        MarkAppealAsRemittedUploadRemittalDecisionPage.apply(fields);
        MarkAppealAsRemittedUploadOtherRemittalDocsPage.apply(fields);
    }
}
