package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code moveToPaymentPending} for case type {@code Asylum}.
 */
@Component
public class MoveToPaymentPending implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String MOVE_TO_PAYMENT_PENDING = "moveToPaymentPending";

    /**
     * Registers event {@code moveToPaymentPending}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.event(MOVE_TO_PAYMENT_PENDING)
            .forStateTransition(State.appealSubmitted, State.pendingPayment)
            .name("Mark appeal as not paid")
            .displayOrder(53)
            .showSummary()
            .endButtonLabel("Mark as not paid")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_SYSTEM);
    }
}
