package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.ccd.sdk.type.ChangeOrganisationRequest;
import uk.gov.hmcts.ccd.sdk.type.Organisation;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code nocRequest} for case type {@code Asylum}.
 */
@Component
public class NocRequest implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String NOC_REQUEST = "nocRequest";

    /**
     * Registers event {@code nocRequest}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(NOC_REQUEST)
            .forAllStates()
            .name("NoC Request")
            .description("Notice of Change Request")
            .displayOrder(71)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_CAA)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_IA_ADMOFFICER, UserRole.CASEWORKER_IA_CASEOFFICER)
            .fields();
        fields.page("SingleFormPageWithComplex");
        fields.pageLabel("Change Organisation Request");
        fields.complex(CaseData::getChangeOrganisationRequestField, false)
                    .complex(ChangeOrganisationRequest::getOrganisationToAdd)
                    .optional(Organisation::getOrganisationId).done()
                    .complex(ChangeOrganisationRequest::getOrganisationToAdd)
                    .optional(Organisation::getOrganisationName).done()
                    .complex(ChangeOrganisationRequest::getOrganisationToRemove)
                    .optional(Organisation::getOrganisationId).done()
                    .complex(ChangeOrganisationRequest::getOrganisationToRemove)
                    .optional(Organisation::getOrganisationName).done()
                    .optional(ChangeOrganisationRequest::getCaseRoleId)
                    .optional(ChangeOrganisationRequest::getRequestTimestamp)
                    .optional(ChangeOrganisationRequest::getApprovalStatus)
                    .defaultValue("1").done();
    }
}
