package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code payAndSubmitAppeal} for case type {@code Asylum}.
 */
@Component
public class PayAndSubmitAppeal implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String PAY_AND_SUBMIT_APPEAL = "payAndSubmitAppeal";

    /**
     * Registers event {@code payAndSubmitAppeal}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.event(PAY_AND_SUBMIT_APPEAL)
            .forAllStates()
            .name("Pay and submit")
            .description("Pay and submit - event added back in for legacy inflight cases support")
            .showSummary(false)
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CITIZEN);
    }
}
