package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.RecordAdjournmentDetailsAdditionalAdjournmentInfoPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.RecordAdjournmentDetailsHearingAdjournmentDatePage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.RecordAdjournmentDetailsHearingAdjournmentDecisionPartyPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.RecordAdjournmentDetailsHearingAdjournmentRequestingPartyPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.RecordAdjournmentDetailsHearingReasonToCancelPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.RecordAdjournmentDetailsHearingReasonToUpdatePage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.RecordAdjournmentDetailsNextHearingDatePage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.RecordAdjournmentDetailsNextHearingDurationPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.RecordAdjournmentDetailsNextHearingFormatPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.RecordAdjournmentDetailsNextHearingVenuePage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.RecordAdjournmentDetailsRelistCaseImmediatelyPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.RecordAdjournmentDetailsSelectHearingForAdjournmentDetailsPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.RecordAdjournmentDetailsShouldReserveOrExcludeJudgePage;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code recordAdjournmentDetails} for case type {@code Asylum}.
 */
@Component
public class RecordAdjournmentDetails implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String RECORD_ADJOURNMENT_DETAILS = "recordAdjournmentDetails";

    /**
     * Registers event {@code recordAdjournmentDetails}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(RECORD_ADJOURNMENT_DETAILS)
            .forStates(State.prepareForHearing, State.finalBundling, State.preHearing, State.decision, State.respondentReview, State.awaitingRespondentEvidence, State.caseBuilding, State.caseUnderReview, State.submitHearingRequirements, State.awaitingReasonsForAppeal, State.reasonsForAppealSubmitted, State.clarifyingQuestionsAnswersSubmitted, State.awaitingClarifyingQuestionsAnswers)
            .name("Record adjournment details")
            .showCondition("isIntegrated=\"Yes\"")
            .showSummary()
            .endButtonLabel("Submit")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_ADMOFFICER, UserRole.CASEWORKER_IA_CASEOFFICER, UserRole.CASEWORKER_IA_SYSTEM, UserRole.IA_SPECIFIC_ACCESS_CTSC_PROFILE)
            .grant(Set.of(Permission.R), UserRole.CITIZEN)
            .fields();
        RecordAdjournmentDetailsSelectHearingForAdjournmentDetailsPage.apply(fields);
        RecordAdjournmentDetailsHearingAdjournmentDatePage.apply(fields);
        RecordAdjournmentDetailsHearingAdjournmentDecisionPartyPage.apply(fields);
        RecordAdjournmentDetailsHearingAdjournmentRequestingPartyPage.apply(fields);
        RecordAdjournmentDetailsAdditionalAdjournmentInfoPage.apply(fields);
        RecordAdjournmentDetailsRelistCaseImmediatelyPage.apply(fields);
        RecordAdjournmentDetailsHearingReasonToCancelPage.apply(fields);
        RecordAdjournmentDetailsHearingReasonToUpdatePage.apply(fields);
        RecordAdjournmentDetailsNextHearingFormatPage.apply(fields);
        RecordAdjournmentDetailsNextHearingVenuePage.apply(fields);
        RecordAdjournmentDetailsNextHearingDurationPage.apply(fields);
        RecordAdjournmentDetailsNextHearingDatePage.apply(fields);
        RecordAdjournmentDetailsShouldReserveOrExcludeJudgePage.apply(fields);
    }
}
