package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code recordRemissionReminder} for case type {@code Asylum}.
 */
@Component
public class RecordRemissionReminder implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String RECORD_REMISSION_REMINDER = "recordRemissionReminder";

    /**
     * Registers event {@code recordRemissionReminder}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.event(RECORD_REMISSION_REMINDER)
            .forStates(State.pendingPayment, State.appealSubmitted, State.awaitingRespondentEvidence, State.caseBuilding, State.caseUnderReview, State.respondentReview, State.submitHearingRequirements, State.listing, State.prepareForHearing, State.finalBundling, State.preHearing, State.decision, State.decided, State.adjourned)
            .name("Record remission reminder")
            .displayOrder(71)
            .showSummary(false)
            .endButtonLabel("Record decision")
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_SYSTEM);
    }
}
