package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code recordAllocatedJudge} for case type {@code Asylum}.
 */
@Component
public class RecordAllocatedJudge implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String RECORD_ALLOCATED_JUDGE = "recordAllocatedJudge";

    /**
     * Registers event {@code recordAllocatedJudge}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(RECORD_ALLOCATED_JUDGE)
            .forState(State.ftpaSubmitted)
            .name("Record allocated Judge")
            .displayOrder(45)
            .showSummary()
            .endButtonLabel("Submit")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_ADMOFFICER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_IA_CASEOFFICER, UserRole.CASEWORKER_IA_IACJUDGE)
            .fields();
        fields.page("allocatedJudge");
        fields.readonlyNoSummary(CaseData::getAllocatedJudgeTitle)
                    .publish(false);
        fields.mandatory(CaseData::getAllocatedJudgeEdit)
                    .publish(false);
    }
}
