package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code recordApplication} for case type {@code Asylum}.
 */
@Component
public class RecordApplication implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String RECORD_APPLICATION = "recordApplication";

    /**
     * Registers event {@code recordApplication}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(RECORD_APPLICATION)
            .forStates(State.pendingPayment, State.appealSubmitted, State.awaitingRespondentEvidence, State.caseBuilding, State.caseUnderReview, State.respondentReview, State.submitHearingRequirements, State.listing, State.prepareForHearing, State.finalBundling, State.preHearing, State.decision, State.decided)
            .name("Record an application")
            .displayOrder(30)
            .showSummary()
            .endButtonLabel("Record application")
            .explicitGrants()
            .fields();
        fields.page("recordApplication");
        fields.readonlyNoSummary(CaseData::getApplicationsTitle);
        fields.readonlyNoSummary(CaseData::getApplicationsTitle2);
        fields.mandatory(CaseData::getApplicationDocuments);
        fields.mandatory(CaseData::getApplicationSupplier);
        fields.mandatory(CaseData::getApplicationType);
        fields.mandatory(CaseData::getApplicationReason);
        fields.mandatory(CaseData::getApplicationDate);
        fields.mandatory(CaseData::getApplicationDecision);
        fields.mandatory(CaseData::getApplicationDecisionReason);
    }
}
