package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code refundConfirmation} for case type {@code Asylum}.
 */
@Component
public class RefundConfirmation implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String REFUND_CONFIRMATION = "refundConfirmation";

    /**
     * Registers event {@code refundConfirmation}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.event(REFUND_CONFIRMATION)
            .forAllStates()
            .name("Refund confirmation")
            .displayOrder(76)
            .showCondition("decisionTypeChangedWithRefundFlag=\"Yes\"")
            .showSummary(false)
            .endButtonLabel("Continue")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_ADMOFFICER);
    }
}
