package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code removeStatutoryTimeframe24Weeks} for case type {@code Asylum}.
 */
@Component
public class RemoveStatutoryTimeframe24Weeks implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String REMOVE_STATUTORY_TIMEFRAME24_WEEKS = "removeStatutoryTimeframe24Weeks";

    /**
     * Registers event {@code removeStatutoryTimeframe24Weeks}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(REMOVE_STATUTORY_TIMEFRAME24_WEEKS)
            .forAllStates()
            .name("Remove Statutory Timeframe")
            .description("Remove Statutory Timeframe 24 Weeks")
            .displayOrder(124)
            .showCondition("stf24wCurrentStatusAutoGenerated=\"Yes\"")
            .showSummary()
            .endButtonLabel("Submit")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_ADMOFFICER, UserRole.CASEWORKER_IA_CASEOFFICER, UserRole.CASEWORKER_IA_IACJUDGE, UserRole.CASEWORKER_IA_SYSTEM, UserRole.CASEWORKER_WA_TASK_CONFIGURATION)
            .grant(Set.of(Permission.R), UserRole.CITIZEN)
            .fields();
        fields.page("removeStatutoryTimeframe24Weeks");
        fields.mandatory(CaseData::getRemovalOf24wDecisionReason)
                    .publish(false);
        fields.mandatory(CaseData::getRemovalOf24wDecisionDecisionMaker)
                    .publish(false);
    }
}
