package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.ccd.sdk.type.ChangeOrganisationRequest;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code removeRepresentation} for case type {@code Asylum}.
 */
@Component
public class RemoveRepresentation implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String REMOVE_REPRESENTATION = "removeRepresentation";

    /**
     * Registers event {@code removeRepresentation}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(REMOVE_REPRESENTATION)
            .forAllStates()
            .name("Stop representing a client")
            .displayOrder(73)
            .showSummary()
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_LEGALREP_SOLICITOR)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_IA_ADMOFFICER, UserRole.CASEWORKER_IA_CASEOFFICER, UserRole.CASEWORKER_IA_IACJUDGE)
            .fields();
        fields.page("SingleFormPageWithComplex");
        fields.pageLabel("Details");
        fields.complex(CaseData::getChangeOrganisationRequestField, false)
                    .mandatory(ChangeOrganisationRequest::getCaseRoleId).done()
                    .caseEventFieldLabel(" ");
        fields.readonlyNoSummary(CaseData::getAppellantNameForDisplay)
                    .caseEventFieldLabel("Client")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getRemoveRepresentationDescription)
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getAppellantInDetention)
                    .fieldShowCondition("changeOrganisationRequestField=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
        fields.mandatoryNoSummary(CaseData::getIsNotificationTurnedOff)
                    .fieldShowCondition("changeOrganisationRequestField=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
    }
}
