package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.Direction;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code requestReasonsForAppeal} for case type {@code Asylum}.
 */
@Component
public class RequestReasonsForAppeal implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String REQUEST_REASONS_FOR_APPEAL = "requestReasonsForAppeal";

    /**
     * Registers event {@code requestReasonsForAppeal}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(REQUEST_REASONS_FOR_APPEAL)
            .forStateTransition(State.awaitingRespondentEvidence, State.awaitingReasonsForAppeal)
            .name("AiP - Request Appeal Reasons")
            .description("Direct the appellant to submit their Appeal Reasons.")
            .displayOrder(10)
            .showSummary()
            .endButtonLabel("Submit")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_CASEOFFICER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_IA_ADMOFFICER, UserRole.CASEWORKER_IA_IACJUDGE)
            .fields();
        fields.page("requestReasonsForAppeal");
        fields.readonly(CaseData::getSendDirectionExplanation)
                    .publish(false);
        fields.readonly(CaseData::getSendDirectionParties)
                    .publish(false);
        fields.mandatory(CaseData::getSendDirectionDateDue)
                    .publish(false);
        fields.complex(CaseData::getLastModifiedDirection, false)
                    .optional(Direction::getExplanation)
                    .optional(Direction::getParties)
                    .optional(Direction::getDateDue)
                    .optional(Direction::getDateSent)
                    .optional(Direction::getTag)
                    .optional(Direction::getPreviousDates)
                    .optional(Direction::getUniqueId)
                    .optional(Direction::getDirectionType).done()
                    .fieldShowCondition("sendDirectionDateDue=\"DUMMY_FIELD_TO_HIDE\"");
        fields.mandatoryNoSummary(CaseData::getIsNotificationTurnedOff)
                    .fieldShowCondition("sendDirectionDateDue=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
    }
}
