package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code requestResponseReview} for case type {@code Asylum}.
 */
@Component
public class RequestResponseReview implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String REQUEST_RESPONSE_REVIEW = "requestResponseReview";

    /**
     * Registers event {@code requestResponseReview}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(REQUEST_RESPONSE_REVIEW)
            .forState(State.respondentReview)
            .name("Review Home Office response")
            .description("Review appeal response")
            .displayOrder(16)
            .showSummary()
            .endButtonLabel("Send direction")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_CASEOFFICER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_IA_ADMOFFICER, UserRole.CASEWORKER_IA_IACJUDGE, UserRole.CITIZEN)
            .fields();
        fields.page("requestResponseReview");
        fields.readonlyNoSummary(CaseData::getRequestResponseReviewTitle)
                    .publish(false);
        fields.mandatory(CaseData::getSendDirectionExplanation)
                    .publish(false);
        fields.readonly(CaseData::getSendDirectionParties)
                    .publish(false);
        fields.mandatory(CaseData::getSendDirectionDateDue)
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getIsAdmin)
                    .fieldShowCondition("sendDirectionDateDue=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
        fields.mandatoryNoSummary(CaseData::getIsNotificationTurnedOff)
                    .fieldShowCondition("sendDirectionDateDue=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
    }
}
