package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.RequestFeeRemissionExceptionalCircumstancesRemissionPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.RequestFeeRemissionHelpWithFeesPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.RequestFeeRemissionHomeOfficeWaiverPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.RequestFeeRemissionLegalAidPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.RequestFeeRemissionRemissionAsylumSupportPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.RequestFeeRemissionRemissionClaimPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.RequestFeeRemissionRemissionTypePage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.RequestFeeRemissionSection17Page;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.RequestFeeRemissionSection20Page;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code requestFeeRemission} for case type {@code Asylum}.
 */
@Component
public class RequestFeeRemission implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String REQUEST_FEE_REMISSION = "requestFeeRemission";

    /**
     * Registers event {@code requestFeeRemission}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(REQUEST_FEE_REMISSION)
            .forStates(State.pendingPayment, State.appealSubmitted, State.awaitingRespondentEvidence, State.caseBuilding, State.caseUnderReview, State.respondentReview, State.submitHearingRequirements, State.listing, State.prepareForHearing, State.finalBundling, State.preHearing, State.decision, State.decided, State.adjourned, State.awaitingReasonsForAppeal, State.remitted, State.ftpaSubmitted, State.ftpaDecided)
            .name("Request a fee remission")
            .displayOrder(80)
            .showSummary(false)
            .endButtonLabel("Submit")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_ADMOFFICER, UserRole.CASEWORKER_IA_LEGALREP_SOLICITOR, UserRole.CASEWORKER_IA_SYSTEM, UserRole.CITIZEN)
            .fields();
        RequestFeeRemissionRemissionTypePage.apply(fields);
        RequestFeeRemissionRemissionClaimPage.apply(fields);
        RequestFeeRemissionRemissionAsylumSupportPage.apply(fields);
        RequestFeeRemissionLegalAidPage.apply(fields);
        RequestFeeRemissionSection17Page.apply(fields);
        RequestFeeRemissionSection20Page.apply(fields);
        RequestFeeRemissionHomeOfficeWaiverPage.apply(fields);
        RequestFeeRemissionHelpWithFeesPage.apply(fields);
        RequestFeeRemissionExceptionalCircumstancesRemissionPage.apply(fields);
    }
}
