package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import java.util.EnumSet;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.Direction;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code requestCmaRequirements} for case type {@code Asylum}.
 */
@Component
public class RequestCmaRequirements implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String REQUEST_CMA_REQUIREMENTS = "requestCmaRequirements";

    /**
     * Registers event {@code requestCmaRequirements}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(REQUEST_CMA_REQUIREMENTS)
            .forStateTransition(EnumSet.of(State.pendingPayment, State.respondentReview, State.reasonsForAppealSubmitted), State.awaitingCmaRequirements)
            .name("Request CMA requirements")
            .displayOrder(46)
            .showSummary()
            .endButtonLabel("Send direction")
            .publishToCamunda()
            .explicitGrants()
            .fields();
        fields.page("requestCmaRequirements");
        fields.readonlyNoSummary(CaseData::getRequestCmaRequirementsTitle)
                    .publish(false);
        fields.mandatory(CaseData::getRequestCmaRequirementsReasons)
                    .publish(false);
        fields.mandatory(CaseData::getSendDirectionDateDue)
                    .publish(false);
        fields.complex(CaseData::getLastModifiedDirection, false)
                    .optional(Direction::getExplanation)
                    .publish(true)
                    .optional(Direction::getParties)
                    .publish(true)
                    .optional(Direction::getDateDue)
                    .publish(true)
                    .optional(Direction::getDateSent)
                    .publish(true)
                    .optional(Direction::getTag)
                    .publish(true)
                    .optional(Direction::getPreviousDates)
                    .publish(true)
                    .optional(Direction::getUniqueId)
                    .publish(true)
                    .optional(Direction::getDirectionType)
                    .publish(true).done()
                    .fieldShowCondition("sendDirectionDateDue=\"DUMMY_FIELD_TO_HIDE\"");
        fields.mandatoryNoSummary(CaseData::getIsNotificationTurnedOff)
                    .fieldShowCondition("sendDirectionDateDue=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
    }
}
