package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code requestHomeOfficeData} for case type {@code Asylum}.
 */
@Component
public class RequestHomeOfficeData implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String REQUEST_HOME_OFFICE_DATA = "requestHomeOfficeData";

    /**
     * Registers event {@code requestHomeOfficeData}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(REQUEST_HOME_OFFICE_DATA)
            .forStates(State.appealSubmitted, State.awaitingRespondentEvidence, State.listing)
            .name("Request Home Office data")
            .displayOrder(54)
            .showCondition("appealOutOfCountry=\"No\" AND hasBeenValidatedByNewHomeOfficeApi!=\"Yes\"")
            .showSummary()
            .endButtonLabel("Request Home Office data")
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_CASEOFFICER)
            .fields();
        fields.page("requestHomeOfficeData");
        fields.pageLabel("Match appellant details");
        fields.readonlyNoSummary(CaseData::getHoAppellantDetailsAdviceFlag);
        fields.readonlyNoSummary(CaseData::getMatchingAppellantDetailsFound)
                    .fieldShowCondition("hoAppellantDetailsAdviceFlag=\"DUMMY_VALUE_TO_HIDE_FIELD\"");
        fields.readonlyNoSummary(CaseData::getHoAppellantDetailsFoundAdvice)
                    .fieldShowCondition("matchingAppellantDetailsFound=\"Yes\"");
        fields.readonlyNoSummary(CaseData::getHomeOfficeSearchResponse)
                    .fieldShowCondition("matchingAppellantDetailsFound=\"DUMMY_VALUE_TO_HIDE_FIELD\"");
        fields.readonlyNoSummary(CaseData::getHoAppellantDetailsNotFoundAdvice)
                    .fieldShowCondition("matchingAppellantDetailsFound=\"No\"");
        fields.readonlyNoSummary(CaseData::getHomeOfficeApiError)
                    .fieldShowCondition("matchingAppellantDetailsFound!=\"No\" AND matchingAppellantDetailsFound!=\"Yes\"");
        fields.readonlyNoSummary(CaseData::getAppellantDetails);
        fields.readonlyNoSummary(CaseData::getAppellantFullName)
                    .caseEventFieldLabel("Name");
        fields.readonlyNoSummary(CaseData::getAppellantDateOfBirth);
        fields.mandatory(CaseData::getHomeOfficeAppellantsList);
    }
}
