package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code requestNewHearingRequirements} for case type {@code Asylum}.
 */
@Component
public class RequestNewHearingRequirements implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String REQUEST_NEW_HEARING_REQUIREMENTS = "requestNewHearingRequirements";

    /**
     * Registers event {@code requestNewHearingRequirements}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(REQUEST_NEW_HEARING_REQUIREMENTS)
            .forStateTransition(EnumSet.of(State.decided, State.ftpaDecided, State.remitted), State.submitHearingRequirements)
            .name("Request hearing requirements")
            .description("Request new hearing requirements")
            .displayOrder(16)
            .showSummary()
            .endButtonLabel("Send direction")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_CASEOFFICER, UserRole.CASEWORKER_IA_IACJUDGE)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_IA_ADMOFFICER)
            .fields();
        fields.page("requestNewHearingRequirements");
        fields.readonlyNoSummary(CaseData::getRequestNewHearingRequirementsTitle)
                    .publish(false);
        fields.mandatory(CaseData::getSendDirectionExplanation)
                    .publish(false);
        fields.readonly(CaseData::getSendDirectionParties)
                    .publish(false);
        fields.mandatory(CaseData::getSendDirectionDateDue)
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getIsAdmin)
                    .fieldShowCondition("requestNewHearingRequirementsTitle=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
        fields.mandatoryNoSummary(CaseData::getAppellantInDetention)
                    .fieldShowCondition("requestNewHearingRequirementsTitle=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
        fields.mandatoryNoSummary(CaseData::getIsNotificationTurnedOff)
                    .fieldShowCondition("requestNewHearingRequirementsTitle=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
    }
}
