package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code requestHearingRequirements} for case type {@code Asylum}.
 */
@Component
public class RequestHearingRequirements implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String REQUEST_HEARING_REQUIREMENTS = "requestHearingRequirements";

    /**
     * Registers event {@code requestHearingRequirements}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.event(REQUEST_HEARING_REQUIREMENTS)
            .forStateTransition(State.respondentReview, State.listing)
            .name("Request hearing requirements")
            .description("Request hearing requirements - DEPRECATED")
            .displayOrder(18)
            .showSummary(false)
            .endButtonLabel("Send direction")
            .publishToCamunda()
            .explicitGrants();
    }
}
