package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code residentJudgeFtpaDecision} for case type {@code Asylum}.
 */
@Component
public class ResidentJudgeFtpaDecision implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String RESIDENT_JUDGE_FTPA_DECISION = "residentJudgeFtpaDecision";

    /**
     * Registers event {@code residentJudgeFtpaDecision}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.event(RESIDENT_JUDGE_FTPA_DECISION)
            .forStateTransition(EnumSet.of(State.ftpaSubmitted, State.ftpaDecided), State.ftpaDecided)
            .name("Resident judge FTPA decision")
            .displayOrder(46)
            .showSummary()
            .endButtonLabel("Submit")
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_IA_ADMOFFICER, UserRole.CASEWORKER_IA_CASEOFFICER, UserRole.CASEWORKER_IA_IACJUDGE, UserRole.CITIZEN);
    }
}
