package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code restoreStateFromAdjourn} for case type {@code Asylum}.
 */
@Component
public class RestoreStateFromAdjourn implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String RESTORE_STATE_FROM_ADJOURN = "restoreStateFromAdjourn";

    /**
     * Registers event {@code restoreStateFromAdjourn}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(RESTORE_STATE_FROM_ADJOURN)
            .forState(State.adjourned)
            .name("Restore to previous state")
            .displayOrder(48)
            .showSummary(false)
            .endButtonLabel("Restore appeal")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_ADMOFFICER, UserRole.CASEWORKER_IA_CASEOFFICER, UserRole.IA_SPECIFIC_ACCESS_CTSC_PROFILE)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_IA_IACJUDGE)
            .fields();
        fields.page("isIntegratedrestoreStateFromAdjourn");
        fields.readonly(CaseData::getIsIntegrated);
        fields.mandatoryNoSummary(CaseData::getAppellantInDetention)
                    .fieldShowCondition("isIntegrated=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
        fields.mandatoryNoSummary(CaseData::getIsNotificationTurnedOff)
                    .fieldShowCondition("isIntegrated=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
    }
}
