package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code reTriggerWaBulkTasks} for case type {@code Asylum}.
 */
@Component
public class ReTriggerWaBulkTasks implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String RE_TRIGGER_WA_BULK_TASKS = "reTriggerWaBulkTasks";

    /**
     * Registers event {@code reTriggerWaBulkTasks}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(RE_TRIGGER_WA_BULK_TASKS)
            .forAllStates()
            .name("Re-trigger Task For Case IDs")
            .description("For starting the event to Re-triggering all necessary WA tasks")
            .displayOrder(103)
            .showSummary(false)
            .endButtonLabel("Submit")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_INTERNAL)
            .fields();
        fields.page("1.0");
        fields.mandatoryNoSummary(CaseData::getCaseIdList)
                    .publish(false);
    }
}
