package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.ReviewHearingRequirementsAdjustAdditionalInstructionsRequirementsPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.ReviewHearingRequirementsAdjustAdditionalRequirementsPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.ReviewHearingRequirementsAdjustInCameraCourtRequirementsPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.ReviewHearingRequirementsAdjustMultimediaRequirementsPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.ReviewHearingRequirementsAdjustPersonalVulnerabilitiesPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.ReviewHearingRequirementsAdjustRemoteHearingPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.ReviewHearingRequirementsAdjustSingleSexCourtRequirementsPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.ReviewHearingRequirementsAutoHearingRequestPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.ReviewHearingRequirementsAutoListHearingPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.ReviewHearingRequirementsHearingChannelPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.ReviewHearingRequirementsHearingLocationPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.ReviewHearingRequirementsIsAppealSuitableToFloatPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.ReviewHearingRequirementsIsHearingLinkedPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.ReviewHearingRequirementsIsPanelRequiredPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.ReviewHearingRequirementsReviewHearingRequirementsPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code reviewHearingRequirements} for case type {@code Asylum}.
 */
@Component
public class ReviewHearingRequirements implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String REVIEW_HEARING_REQUIREMENTS = "reviewHearingRequirements";

    /**
     * Registers event {@code reviewHearingRequirements}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(REVIEW_HEARING_REQUIREMENTS)
            .forStates(State.listing, State.respondentReview)
            .name("Review hearing requirements")
            .displayOrder(39)
            .showSummary()
            .endButtonLabel("Submit")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_CASEOFFICER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_IA_ADMOFFICER, UserRole.CASEWORKER_IA_IACJUDGE)
            .fields();
        ReviewHearingRequirementsReviewHearingRequirementsPage.apply(fields);
        ReviewHearingRequirementsAdjustRemoteHearingPage.apply(fields);
        ReviewHearingRequirementsAdjustPersonalVulnerabilitiesPage.apply(fields);
        ReviewHearingRequirementsAdjustMultimediaRequirementsPage.apply(fields);
        ReviewHearingRequirementsAdjustSingleSexCourtRequirementsPage.apply(fields);
        ReviewHearingRequirementsAdjustInCameraCourtRequirementsPage.apply(fields);
        ReviewHearingRequirementsAdjustAdditionalRequirementsPage.apply(fields);
        ReviewHearingRequirementsAutoHearingRequestPage.apply(fields);
        ReviewHearingRequirementsHearingChannelPage.apply(fields);
        ReviewHearingRequirementsHearingLocationPage.apply(fields);
        ReviewHearingRequirementsIsAppealSuitableToFloatPage.apply(fields);
        ReviewHearingRequirementsIsHearingLinkedPage.apply(fields);
        ReviewHearingRequirementsIsPanelRequiredPage.apply(fields);
        ReviewHearingRequirementsAdjustAdditionalInstructionsRequirementsPage.apply(fields);
        ReviewHearingRequirementsAutoListHearingPage.apply(fields);
    }
}
