package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.SendDecisionAndReasonsSendDecisionAndReasonsPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.SendDecisionAndReasonsUploadDecisionAndReasonsPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code sendDecisionAndReasons} for case type {@code Asylum}.
 */
@Component
public class SendDecisionAndReasons implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String SEND_DECISION_AND_REASONS = "sendDecisionAndReasons";

    /**
     * Registers event {@code sendDecisionAndReasons}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(SEND_DECISION_AND_REASONS)
            .forStateTransition(State.decision, State.decided)
            .name("Complete decision and reasons")
            .displayOrder(26)
            .showSummary()
            .endButtonLabel("Upload")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_ADMOFFICER, UserRole.CASEWORKER_IA_CASEOFFICER, UserRole.CASEWORKER_IA_IACJUDGE)
            .grant(Set.of(Permission.R), UserRole.CITIZEN)
            .fields();
        SendDecisionAndReasonsSendDecisionAndReasonsPage.apply(fields);
        SendDecisionAndReasonsUploadDecisionAndReasonsPage.apply(fields);
    }
}
