package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code sendToPreHearing} for case type {@code Asylum}.
 */
@Component
public class SendToPreHearing implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String SEND_TO_PRE_HEARING = "sendToPreHearing";

    /**
     * Registers event {@code sendToPreHearing}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(SEND_TO_PRE_HEARING)
            .forStateTransition(State.finalBundling, State.preHearing)
            .name("Send to pre hearing")
            .displayOrder(44)
            .showSummary(false)
            .endButtonLabel("Submit")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_CASEOFFICER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_IA_ADMOFFICER, UserRole.CASEWORKER_IA_IACJUDGE)
            .fields();
        fields.page("sendToPreHearing");
        fields.readonlyNoSummary(CaseData::getDummyEmptyLabel)
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getAppellantInDetention)
                    .fieldShowCondition("dummyEmptyLabel=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
        fields.mandatoryNoSummary(CaseData::getIsNotificationTurnedOff)
                    .fieldShowCondition("dummyEmptyLabel=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
    }
}
