package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code sendLateTimelineNotice} for case type {@code Asylum}.
 */
@Component
public class SendLateTimelineNotice implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String SEND_LATE_TIMELINE_NOTICE = "sendLateTimelineNotice";

    /**
     * Registers event {@code sendLateTimelineNotice}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.event(SEND_LATE_TIMELINE_NOTICE)
            .forStates(State.awaitingRespondentEvidence, State.awaitingClarifyingQuestionsAnswers, State.clarifyingQuestionsAnswersSubmitted, State.listing)
            .name("Send timetabling directions")
            .description("Send timetabling directions when the 24w flag has been added after case review has been completed")
            .displayOrder(127)
            .showCondition("stf24wCurrentStatusAutoGenerated = \"Yes\"")
            .showSummary(false)
            .endButtonLabel("Submit")
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_CASEOFFICER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_IA_ADMOFFICER, UserRole.CASEWORKER_IA_IACJUDGE);
    }
}
