package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.SubmitAppealDeclarationPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.SubmitAppealSubmissionOutOfTimePagePage;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code submitAppeal} for case type {@code Asylum}.
 */
@Component
public class SubmitAppeal implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String SUBMIT_APPEAL = "submitAppeal";

    /**
     * Registers event {@code submitAppeal}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(SUBMIT_APPEAL)
            .forStateTransition(EnumSet.of(State.appealStarted, State.appealStartedByAdmin), State.appealSubmitted)
            .name("Submit your appeal")
            .displayOrder(3)
            .showSummary(false)
            .endButtonLabel("Submit")
            .publishToCamunda()
            .ttlIncrement(36524)
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_ADMOFFICER, UserRole.CASEWORKER_IA_LEGALREP_SOLICITOR, UserRole.CITIZEN)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_IA_CASEOFFICER, UserRole.CASEWORKER_IA_IACJUDGE)
            .fields();
        SubmitAppealSubmissionOutOfTimePagePage.apply(fields);
        SubmitAppealDeclarationPage.apply(fields);
    }
}
