package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code triggerCmrUpdated} for case type {@code Asylum}.
 */
@Component
public class TriggerCmrUpdated implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String TRIGGER_CMR_UPDATED = "triggerCmrUpdated";

    /**
     * Registers event {@code triggerCmrUpdated}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.event(TRIGGER_CMR_UPDATED)
            .forAllStates()
            .name("Trigger CMR Updated")
            .description("Trigger CMR updated notification necessary for triggering WA task")
            .displayOrder(102)
            .showSummary(false)
            .endButtonLabel("Trigger CMR Updated")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_SYSTEM);
    }
}
