package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import java.util.EnumSet;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code updatePaymentStatus} for case type {@code Asylum}.
 */
@Component
public class UpdatePaymentStatus implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String UPDATE_PAYMENT_STATUS = "updatePaymentStatus";

    /**
     * Registers event {@code updatePaymentStatus}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(UPDATE_PAYMENT_STATUS)
            .forStateTransition(EnumSet.allOf(State.class), State.appealSubmitted)
            .name("Update payment status")
            .displayOrder(90)
            .showSummary()
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_SYSTEM)
            .fields();
        fields.page("updatePaymentStatus");
        fields.pageLabel("Update payment status");
        fields.showCondition("appealType=\"DO_NOT_SHOW_ON_UI\"");
        fields.readonlyNoSummary(CaseData::getAppealType)
                    .caseEventFieldLabel(" ");
        fields.mandatoryNoSummary(CaseData::getAppellantInDetention)
                    .fieldShowCondition("appealType=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
        fields.mandatoryNoSummary(CaseData::getIsNotificationTurnedOff)
                    .fieldShowCondition("appealType=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
    }
}
