package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.UpdateHearingAdjustmentsAdditionalInstructionsPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.UpdateHearingAdjustmentsAdjustAdditionalRequirementsPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.UpdateHearingAdjustmentsAdjustInCameraCourtRequirementsPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.UpdateHearingAdjustmentsAdjustMultimediaRequirementsPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.UpdateHearingAdjustmentsAdjustPersonalVulnerabilitiesPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.UpdateHearingAdjustmentsAdjustRemoteHearingPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.UpdateHearingAdjustmentsAdjustSingleSexCourtRequirementsPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.UpdateHearingAdjustmentsHearingChannelPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.UpdateHearingAdjustmentsIsAppealSuitableToFloatPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.event.page.UpdateHearingAdjustmentsUpdateHearingAdjustmentsPage;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code updateHearingAdjustments} for case type {@code Asylum}.
 */
@Component
public class UpdateHearingAdjustments implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String UPDATE_HEARING_ADJUSTMENTS = "updateHearingAdjustments";

    /**
     * Registers event {@code updateHearingAdjustments}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(UPDATE_HEARING_ADJUSTMENTS)
            .forStates(State.listing, State.prepareForHearing, State.finalBundling, State.preHearing, State.decision, State.adjourned, State.respondentReview)
            .name("Update hearing adjustments")
            .displayOrder(39)
            .showSummary()
            .endButtonLabel("Update")
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_CASEOFFICER, UserRole.CASEWORKER_IA_IACJUDGE)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_IA_ADMOFFICER)
            .fields();
        UpdateHearingAdjustmentsUpdateHearingAdjustmentsPage.apply(fields);
        UpdateHearingAdjustmentsAdjustRemoteHearingPage.apply(fields);
        UpdateHearingAdjustmentsAdjustPersonalVulnerabilitiesPage.apply(fields);
        UpdateHearingAdjustmentsAdjustMultimediaRequirementsPage.apply(fields);
        UpdateHearingAdjustmentsAdjustSingleSexCourtRequirementsPage.apply(fields);
        UpdateHearingAdjustmentsAdjustInCameraCourtRequirementsPage.apply(fields);
        UpdateHearingAdjustmentsAdjustAdditionalRequirementsPage.apply(fields);
        UpdateHearingAdjustmentsHearingChannelPage.apply(fields);
        UpdateHearingAdjustmentsIsAppealSuitableToFloatPage.apply(fields);
        UpdateHearingAdjustmentsAdditionalInstructionsPage.apply(fields);
    }
}
