package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code uploadAdditionalEvidenceHomeOffice} for case type {@code Asylum}.
 */
@Component
public class UploadAdditionalEvidenceHomeOffice implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String UPLOAD_ADDITIONAL_EVIDENCE_HOME_OFFICE = "uploadAdditionalEvidenceHomeOffice";

    /**
     * Registers event {@code uploadAdditionalEvidenceHomeOffice}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(UPLOAD_ADDITIONAL_EVIDENCE_HOME_OFFICE)
            .forStates(State.caseBuilding, State.caseUnderReview, State.respondentReview, State.submitHearingRequirements, State.listing, State.prepareForHearing, State.awaitingReasonsForAppeal, State.reasonsForAppealSubmitted, State.awaitingClarifyingQuestionsAnswers, State.clarifyingQuestionsAnswersSubmitted, State.remitted)
            .name("Upload additional evidence")
            .displayOrder(33)
            .showSummary()
            .endButtonLabel("Upload")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_HOMEOFFICEAPC, UserRole.CASEWORKER_IA_HOMEOFFICELART, UserRole.CASEWORKER_IA_HOMEOFFICEPOU, UserRole.CASEWORKER_IA_RESPONDENTOFFICER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_IA_ADMOFFICER, UserRole.CASEWORKER_IA_CASEOFFICER, UserRole.CASEWORKER_IA_IACJUDGE, UserRole.CITIZEN)
            .fields();
        fields.page("uploadAdditionalEvidenceHomeOffice");
        fields.readonlyNoSummary(CaseData::getAdditionalEvidenceHomeOfficeTitle)
                    .publish(false);
        fields.mandatory(CaseData::getAdditionalEvidenceHomeOffice)
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getIsAdmin)
                    .fieldShowCondition("additionalEvidenceHomeOfficeTitle=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
        fields.mandatoryNoSummary(CaseData::getAppellantInDetention)
                    .fieldShowCondition("additionalEvidenceHomeOfficeTitle=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
        fields.mandatoryNoSummary(CaseData::getIsNotificationTurnedOff)
                    .fieldShowCondition("additionalEvidenceHomeOfficeTitle=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
    }
}
