package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code uploadAddendumEvidenceLegalRep} for case type {@code Asylum}.
 */
@Component
public class UploadAddendumEvidenceLegalRep implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String UPLOAD_ADDENDUM_EVIDENCE_LEGAL_REP = "uploadAddendumEvidenceLegalRep";

    /**
     * Registers event {@code uploadAddendumEvidenceLegalRep}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(UPLOAD_ADDENDUM_EVIDENCE_LEGAL_REP)
            .forStates(State.preHearing, State.decision, State.decided, State.ftpaSubmitted, State.ftpaDecided)
            .name("Upload additional evidence")
            .displayOrder(34)
            .showSummary()
            .endButtonLabel("Upload")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_LEGALREP_SOLICITOR, UserRole.CITIZEN)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_IA_ADMOFFICER, UserRole.CASEWORKER_IA_CASEOFFICER, UserRole.CASEWORKER_IA_IACJUDGE)
            .fields();
        fields.page("uploadAddendumEvidenceLegalRep");
        fields.pageLabel("Upload your evidence");
        fields.readonlyNoSummary(CaseData::getAddendumEvidenceLegalRepPageTitle)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getAddendumEvidenceLegalRepPageTitle2)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getAddendumEvidenceTitle)
                    .publish(false);
        fields.mandatory(CaseData::getAddendumEvidence)
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getAppellantInDetention)
                    .fieldShowCondition("addendumEvidenceLegalRepPageTitle=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
        fields.mandatoryNoSummary(CaseData::getIsNotificationTurnedOff)
                    .fieldShowCondition("addendumEvidenceLegalRepPageTitle=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
    }
}
