package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code uploadHearingRecording} for case type {@code Asylum}.
 */
@Component
public class UploadHearingRecording implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String UPLOAD_HEARING_RECORDING = "uploadHearingRecording";

    /**
     * Registers event {@code uploadHearingRecording}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(UPLOAD_HEARING_RECORDING)
            .forStates(State.decision, State.decided)
            .name("Upload hearing recording")
            .displayOrder(43)
            .showSummary()
            .endButtonLabel("Upload")
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_ADMOFFICER, UserRole.CASEWORKER_IA_CASEOFFICER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_IA_IACJUDGE)
            .fields();
        fields.page("uploadHearingRecording");
        fields.readonlyNoSummary(CaseData::getUploadHearingRecordingTitle);
        fields.mandatory(CaseData::getHearingRecordingDocuments);
    }
}
