package uk.gov.hmcts.reform.iacaseapi.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.CaseData;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.State;
import uk.gov.hmcts.reform.iacaseapi.ccd.model.UserRole;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Event {@code uploadAddendumEvidenceHomeOffice} for case type {@code Asylum}.
 */
@Component
public class UploadAddendumEvidenceHomeOffice implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String UPLOAD_ADDENDUM_EVIDENCE_HOME_OFFICE = "uploadAddendumEvidenceHomeOffice";

    /**
     * Registers event {@code uploadAddendumEvidenceHomeOffice}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(UPLOAD_ADDENDUM_EVIDENCE_HOME_OFFICE)
            .forStates(State.preHearing, State.decision, State.decided)
            .name("Upload additional evidence")
            .displayOrder(35)
            .showSummary()
            .endButtonLabel("Upload")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_IA_HOMEOFFICEAPC, UserRole.CASEWORKER_IA_HOMEOFFICELART, UserRole.CASEWORKER_IA_HOMEOFFICEPOU, UserRole.CASEWORKER_IA_RESPONDENTOFFICER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_IA_ADMOFFICER, UserRole.CASEWORKER_IA_CASEOFFICER, UserRole.CASEWORKER_IA_IACJUDGE, UserRole.CITIZEN)
            .fields();
        fields.page("uploadAddendumEvidenceHomeOffice");
        fields.readonlyNoSummary(CaseData::getAddendumEvidenceHomeOfficePageTitle)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getAddendumEvidenceHomeOfficePageTitle2)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getAddendumEvidenceTitle)
                    .publish(false);
        fields.mandatory(CaseData::getAddendumEvidence)
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getIsAdmin)
                    .fieldShowCondition("addendumEvidenceHomeOfficePageTitle=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
        fields.mandatoryNoSummary(CaseData::getAppellantInDetention)
                    .fieldShowCondition("addendumEvidenceHomeOfficePageTitle=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
        fields.mandatoryNoSummary(CaseData::getIsNotificationTurnedOff)
                    .fieldShowCondition("addendumEvidenceHomeOfficePageTitle=\"DUMMY_FIELD_TO_HIDE\"")
                    .retainHiddenValue();
    }
}
